### ISSUE TITLE
Design Inception Workshop

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-cif#10]
Acceptance Criteria:
- [x] Establish clear goals for workshop
- [x] Establish physical outcomes for workshop (e.g., what specific pieces of information do we want to have by the end of the workshop)
- [x] Create workshop structure
- [x] Design icebreaker game
- [x] Design workshop segments
- [x] Send day of reminder email

**Comment by LindsayMacfarlane** [comment]
Excellent design of the inception workshop @jaimiebutton ! Very impressed with your ability to adapt on the fly and pivot your approach during the planning phase. And thank you for sharing your lessons learned with the team about being agile during planning :)
