### ISSUE TITLE
As a CIF user, I want to sort and filter the revision change log, so I can access information faster

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1000]
#### Description:

Sorting the revision table for a project
Design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=3068%3A2675

#### Acceptance Criteria:

Given there is a table with the project revision information
When I want to pare down the results
Then I can filter the results

Given there is a table with the project revision information
When I want to sort the results
Then I can sort each column of the table

Given there is a table with the project revision information
When there are a lot of revisions
Then the data is displayed in pages

Given there is a table with the project revision information
When I access this page first
Then the most recent revision is displayed on top

#### Development Checklist:

- [ ] Using FilterableTable and headers to sort and filter each column
- [ ] Pagination should be implemented
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
@nanyangpro I'm splitting the sorting / filtering functionality out of the #919 card

**Comment by nanyangpro** [comment]
Thanks for the note, @pbastia! Marked in Figma.
(Oooh, we hit the 1000th card.)

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1000?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by rdromey** [comment]
Covered by card #919
