### ISSUE TITLE
CIF Refactor: Json Schema Form - Database decoupling

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1002]
Epic aimed at decoupling the database tables from the json form schemas, which are currently a 1-1 mapping.

**Comment by LindsayMacfarlane** [comment]
Any objections to closing this EPIC @Dianadec? The last ticket is in the Accepted by PO/Dev column. Perhaps something to quickly discuss tomorrow during refinement - does the team prefer to wait until items are in PROD before closing the EPIC?

**Comment by LindsayMacfarlane** [comment]
EPIC completed - moving to closed :)
