### ISSUE TITLE
Task: Investigate what to do with the UI Schemas

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1005]
#### Describe the task

Investigate and report on what the options are for the Ui Schemas:
- in the database, in a column next to the json_form?
- in a separate table?
- as @matthieu-foucault says: "I think a front-end object with the form's slug as the attribute would work to store our uiSchemas"
- still hard-coded in the forms?
- ...

#### Acceptance Criteria

As a developer
When I refactor a form
I want to know where to store the UI schema

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by pbastia** [comment]
Given that there is (at least currently) no need for form versioning, and that we will be able to identify each form by their slug, there is no requirement to store them at this point.
Storing each in `app/data/uiSchema/<slug>.json` would be sufficient.

**Comment by matthieu-foucault** [comment]
UI schemas should be a rendering concern only and ideally don't need to be saved in the db, even when form versioning is considered

**Comment by rdromey** [comment]
UI schemas will remain on the front end.
