### ISSUE TITLE
As an Ops team member, I want to automatically generate quarterly reports and annual reports between the input dates, so that I don't have to create them all manually.

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1019]
#### Description:

The date inputs required for the report generation are as follows:

- Contract Start Date (Budgets) + TEIMP End Date (Emissions Performance) = **Quarterly Reports**
- Emissions Intensity Report Due Date (Emissions Performance) + Project Assets Life End Date (Budgets) = **Annual Reports**

The wireframes include all the possibilities including generating the reports, editing a date, the scenario when one date is missing or deleting generated reports. 

[Link to Figma wireframe](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=4026%3A6770)

#### Acceptance Criteria:

Given I am a CIF administrator
When I am creating or editing a project revision
And annual or quarterly reports have not been entered
Then I can see read-only fields for the reporting start date and end date

Given I am a CIF administrator
When I am creating or editing a project revision
And annual or quarterly reports have not been entered
Then I can click an "edit" button that enables editing of the start and end date

Given I am a CIF administrator
When I am creating or editing the annual or quarterly reports of a project revision
Then I can see a "Generate (annual|quarterly) reports" button

Given I am a CIF administrator
When I am creating or editing the annual or quarterly reports of a project revision
And I press the "Generate (annual|quarterly) reports" button
Then the reports are generated annually or quarterly

#### Development Checklist:

- [x] `generate_reports` custom mutation that can take in the report type
- [x] Check edge-cases
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

- Based on work done in #599

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1019?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by Sepehr-Sobhani** [comment]
Based on the [discussion](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ?node-id=4026:6770#271580842) with @nanyangpro , we will keep the date fields immutable.

**Comment by LindsayMacfarlane** [comment]
I think I might be doing something wrong while testing - I couldn't activate the 'generate quarterly' and 'generate annual report' buttons, until I filled in reporting dates under TEIMP. However, the acceptance criteria and design mentioned only requiring the contract start date and project assets life end date to be populated. Was this something that changed based on Nan's field mapping?  

Once I was able to select the auto-generation for new projects, it worked great :) But I couldn't see the generate button for existing projects.

@Sepehr-Sobhani @nanyangpro

**Comment by Sepehr-Sobhani** [comment]
@LindsayMacfarlane Thanks in advance for testing this feature. based on my understanding of acceptance criteria and mock-ups, we show `Generate Reports` section if there are no reports already in place (We can show it but that might be a bit risky since the user might generate reports that overlap existing reports). Also, we only enable generate report buttons when we have the following fields populated with date:

Contract Start Date (Budgets) + TEIMP End Date (Emissions Performance) = Quarterly Reports
Emissions Intensity Report Due Date (Emissions Performance) + Project Assets Life End Date (Budgets) = Annual Reports

**Comment by LindsayMacfarlane** [comment]
Ok - that's helpful @Sepehr-Sobhani 

@nanyangpro - it will be good to do some usability testing on this feature with CIF. It may just be me, but I found the flow confusing and maybe not intuitive (but perhaps it is to CIF?).

**Comment by nanyangpro** [comment]
Agreed, @LindsayMacfarlane. Looking forward to further testings with users and refine the workflows Suha had originally put together where fit.

**Comment by nanyangpro** [comment]
Agreed, @LindsayMacfarlane. Looking forward to further testings with users and refine the workflows Suha had originally put together where fit.

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - #1139 has been created addressing the usability testing for this feature, and is ready for the next sprint.
