### ISSUE TITLE
As a CIF Project Coordinator, I want to enter Contract Start Date and Projects Assets Life End Date, so that quarterly and annual reports can be generated.

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1020]
#### Description:

The 2 date inputs will later be utilized for generating Annual and Quarterly Reports. These input fields will be under Budgets, Expenses and Payments, and are relevant once there is a Funding Agreement.

Link to Figma [wireframe](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=3861%3A2836)

#### Acceptance Criteria:

Given I am on the Budgets, Expenses and Payments
When the project is funded
Then I can enter a Contract Start Date

Given I am on the Budgets, Expenses and Payments
When the project is funded
Then I can enter a Projects Assets Life End Date

#### Development Checklist:

- [x] New columns are added to the `funding_parameter` table for `contract_start_date` & `project_assets_life_end_date` (both timestamptz)
- [x] The front-end json_schema is updated to include these fields (app/data/jsonSchemaForm/fundingAgreementSchema.ts)
- [x] The back-end json_schema is updated to include these fields (schema/data/prod/json_schema/funding_agreement.json)
- [x] The fields appear on the funding agreement form as datepickers
- [x] The fields are required & properly display validation if not set

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

- Based on work captured in #598

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1020?planning-poker) with Zenhub @BCerki @matthieu-foucault @mikevespi @pbastia @Sepehr-Sobhani

**Comment by suhafa** [comment]
@pbastia good question! Quarterly and Annual reports aren't relevant unless and until the project has a FA. If there is a date missing in Quarterly or Annual reports however, I added in a **[workflow]**(https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=4026%3A4501) to showcase how this would appear in Figma.

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani ! I tested in dev by:

1) Confirming that existing projects now included contract start date and project assets life end date. 
2) Confirming that new projects can be created with contract start date and project assets life end date.
