### ISSUE TITLE
Co-Design landing page wireframe

### ISSUE THREAD

**Issue by rajpersram** [bcgov/cas-cif#103]
#### Checklist:

- [x] Identify GGIRCS team members who we'd like to participate
- [x] Plan co-design session(s)
- [x] Hold session(s)
- [x] Create wireframes
- [x] Review with GGIRCS and CIF team for revisions
- [x] Translate to Figma prototype and upload both designs to corresponding user story ticket 80.

**Comment by rajpersram** [comment]
Co-design session planned for Tue, Nov 30.

**Comment by rajpersram** [comment]
Wireframe upload to corresponding [User Story ticket 80](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/80)

**Comment by LindsayMacfarlane** [comment]
Thank you @rajpersram! As always, I'm really enjoying these co-design sessions. They are amazing for collaboration and getting the right feedback.
