### ISSUE TITLE
Budgets label is wrong in tasklist when viewing project [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1030]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in dev
- view a project that has a Project Funding Agreement
- note the task list item says "budget"

Screenshots:
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/2b811a6b-5e17-441b-a09e-d7d60336521d)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
@suhafa, what is the label meant to be? (Just "Budgets" capitalised, or something else?)

**Comment by suhafa** [comment]
@BCerki Thanks for the question Brianna! I would suggest it be 'Budgets overview'

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! Verified in dev environment that the label under Budgets, Expenses & Payments now says "Budgets overview".

Thanks for the quick work on this one.
