### ISSUE TITLE
Inconsistent task list statuses [7]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1032]
Describe the Bug:

Some of the tasklist statuses are inconsistent.

1. If a form is open but untouched, tasklist sometimes says `Not Started`, sometimes says `In Progress`. Here are the `In Progress` ones (or see Happo screenshots):
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/60f53967-b888-457d-8283-6e94e2004898)
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/3900fe4e-c41b-47bb-84cb-5589601f8cec)

2) Milestone doesn't have a status:
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/2a22ad56-c63d-44db-a260-079ce713c52d)

3) Are all the dropdowns meant to be expanded when there are `Attention Required` statuses, or only the dropdowns that have errors? All appear to expand (note managers and contacts don't have any errors but their section is expanded):
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/fbdb7f3c-8646-48af-8fac-201b8a964991)

Probability (how likely the bug is to happen, scored from 1-5): 5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
@nanyangpro , @suhafa , do you want to weigh on this ticket? I mostly noticed inconsistencies, not necessarily bugs

**Comment by suhafa** [comment]
Thanks for bringing this to our attention @BCerki! A few notes to address the inconsistencies - 
1. If a form hasn't been modified at all, then it is best to have it say `'Not started'` and `'In Progress'` status applies when it has been modified in any way.
2. Good eye for spotting this!
3. Any sub-form with `Attention Required` needs to be expanded as you rightly noted (this includes errors). If there is nothing noteworthy (like in the case of Contacts and Managers) then it should remain collapsed

**Comment by BCerki** [comment]
I can't reproduce #3 or #1 anymore.

**Comment by BCerki** [comment]
I can't reproduce #3 or #1 anymore, probably fixed in a refactor. #2 has more to it so I'm going to make a separate ticket
