### ISSUE TITLE
Milestones: "Professional Designation" is optional but doesn't have a blank option [7]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1037]
Describe the Bug:

"Professional Designation" is optional, but defaults to "Professional Engineer" and there's no way to unset this (no blank option)

Probability (how likely the bug is to happen, scored from 1-5): 5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Create a new milestone report

Screenshots:
https://www.loom.com/share/6a21a94870cf4d3bb00159212a4f09e1

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by gurjmatharu** [comment]
@nanyangpro @suhafa for this issue what is the expected behaviour.  Should an option be `None` or `N/A`?  Thoughts?

**Comment by nanyangpro** [comment]
Thanks for your question, @gurjmatharu!

In terms of design consistency, we can replicate the exact behaviour of the optional fields on the "Project Managers" form. However, I'm lacking context of this field, @Suha's input would be more appreciated.

**Comment by suhafa** [comment]
Thanks @gurjmatharu and @nanyangpro! We could go with your suggestion of `N/A` here. This field is almost always either the `Professional Engineer` or `CPA`. `N/A` makes more sense in case there is none assigned (yet).

**Comment by LindsayMacfarlane** [comment]
Thanks @gurjmatharu! 

A quick observation:
- The review form show's an error if submitting a project where the professional designation is NA. 
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/9d431e5b-bf45-4c01-8fee-5c07ab80c6a8)  
I confirmed that this error is not displayed when the other two professional designations are selected. 

Moving to approved, but if you could create a bug ticket that would be fantastic.

**Comment by LindsayMacfarlane** [comment]
Note: bug card #1352 has been created.
