### ISSUE TITLE
Milestones: "Remove" button is awkwardly placed [4]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1038]
Describe the Bug:

Milestones: "Remove" button is awkwardly placed near the description field, it's not clear what it applies to

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Open any milestone report or create a new one

Screenshots:

![Screen Shot 2022-08-29 at 5.18.57 PM.png](https://images.zenhubusercontent.com/6243a3ea8726850c1675becd/84cbecec-6cb5-48fd-ac56-bbb8e4a1f88b)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
This has been merged but not deployed to dev yet!

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani ! Button placement now has spacing and looks so much nicer - thank you :)

![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/3e03de72-dca3-4153-9b99-c96259728c80)
