### ISSUE TITLE
Project managers: can't clear an existing manager and then add another one in its place [6]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1040]
Describe the Bug:

can't clear an existing manager and then add another one in its place

Probability (how likely the bug is to happen, scored from 1-5):3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Go to an existing project that has a manager -> clear the existing manager -> add a new manager

Screenshots:
https://www.loom.com/share/9fb1df18f0044ba1a11cd6c84e73610f

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani! I followed the steps to recreate the bug and can no longer trigger that bug.
