### ISSUE TITLE
Milestones: Task List not showing "Attention Required" when navigating away [7]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1041]
Describe the Bug:

Task List status doesn't switch to "Attention Required" when navigating away from the form by using a Task List link, when there are validation errors present

Probability (how likely the bug is to happen, scored from 1-5): 4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Go to an existing project or create a new project -> add a new milestone report -> don't fill out the form -> navigate away from the milestone report section by clicking any other sections in the task list -> go back to the created milestone report (status is filled and form has multiple validation errors)

Screenshots:
https://www.loom.com/share/3cd517bd5f464d82bb49ef4a2c3cb7fe

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
Additionally, when there are no milestone reports added, the status is missing from the Tasklist: ![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/979bd325-c950-446f-ad53-3cb01f085113)

**Comment by mikevespi** [comment]
@Sepehr-Sobhani I can no longer reproduce this, can you confirm you aren't experiencing it anymore? If not, I'll go ahead and close this

**Comment by Sepehr-Sobhani** [comment]
Thanks @mikevespi! I can't reproduce it either. 👍

**Comment by Sepehr-Sobhani** [comment]
Can't be reproduced anymore! I'm going to take @BCerki comment to a new bug card and close this ticket!
