### ISSUE TITLE
Project Contacts: removing secondary contact will bring back removed primary contact [4]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1042]
Describe the Bug:

removing a primary contact, then adding a secondary contact, then removing that secondary contact adds the previously removed primary contact back in

Note: This is caused by calling undoFormChangeMutation when removing secondary contact (when we only have one secondary contact)

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Go to an existing project that already has a primary project contact -> go to the project contacts section -> clear primary contact -> add secondary contact -> remove secondary contact (primary contact is back again)

Screenshots:

https://www.loom.com/share/67b4aca0cb8d4ad196eec7fc944ace22

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by LindsayMacfarlane** [comment]
No longer able to recreate the bug. Thank you @Sepehr-Sobhani !
