### ISSUE TITLE
Budgets: removing a funding agreement shows nothing in the diff [6]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1043]
Describe the Bug:

removing a funding agreement (by setting Is this project funded to "No") shows nothing in the diff at the end.

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Go to an existing funded project -> go to Budgets section -> select No in response to `Is this a funded project?` and proceed -> go to project summary page (nothing is below `Project Funding Agreement` section)

Screenshots:

https://www.loom.com/share/836ba779105442b6a648f44972001449

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani. Tested in dev by following the above instructions. I can confirm that if a user removes funding, it is now displayed in the dif:
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/e6f601ba-f2f5-43a3-98c1-86699ee00621)
