### ISSUE TITLE
Check for SQL errors in revert and verify files [8]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1049]
###Description of the Tech Debt###

NOTE: If we decide to get rid of the `revert` and `verify` files, this issue is irrelevant.

We don't typically use/run the `revert` and `verify` files locally, so if there's an error in them, we may not know about it.

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |    2   |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |   1    |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |    2   |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |   2    |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |    1   |
| TOTAL SCORE:                                                                                                                  |       |   8    |

**Comment by BCerki** [comment]
@dleard, does your PR https://github.com/bcgov/cas-cif/pull/1190 fix this issue?

**Comment by dleard** [comment]
I think this card was about creating an automated check for revert/verify. I just manually checked for and fixed some errors that were introduced recently.

**Comment by mikevespi** [comment]
Dylan: We use revert in dev, but don't allow reverts past tags in production.

A discussion should be had on whether sqitch verify is actually helpful and worth maintaining.

**Comment by pbastia** [comment]
we've had a few instances where some code was hastily pushed to dev without being checked if it runs properly - having an automated action that reverts and verifies would help a little with this as an additional check

**Comment by dleard** [comment]
revert is more important than verify. This card has implemented the revert check. We can talk about verify again if we decide it is a useful check.
