### ISSUE TITLE
As a CIF User, I want to see a customized list of options for "Project Status" according to the funding stream

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1052]
#### Description:
The options for the "Project Status" field on the "Project Overview" page are slightly different for EP and IA. 

The statuses currently in the system (`cif.project_status` table) are for EP, however there are some inconsistencies between them and the list below. As per Nan's comment, the lists in this ticket are the most current lists of statuses, as confirmed by the CIF team, and our tables should reflect them.

**Ordered "Project Status" for EP**: 
- Proposal Submitted
- Under Technical Review
- Technical Review Complete
- Waitlisted
- Disqualified
- Withdrawn
- Not Funded
- Funding Agreement Pending
- Project in Progress
- Amendment Pending
- Project in TEIMP
- Emissions Intensity Report Complete
- Project in Annual Reporting
- Agreement Terminated
- Closed

**Ordered "Project Status" for IA**:
- Proposal Submitted
- Under Technical Review
- Technical Review Complete
- Waitlisted
- Disqualified
- Withdrawn
- Not Funded
- Funding Agreement Pending
- Project in Progress
- Amendment Pending
- Project Summary Report Complete
- Agreement Terminated
- Closed

#### Acceptance Criteria:

Given that I am a CIF user
When I am on the project form for an EP stream project
Then I only see the EP-appropriate statuses in the status dropdown (see list above for what to include and order)

Given that I am a CIF user
When I am on the project form for an IA stream project
Then I only see the IA-appropriate statuses in the status dropdown (see list above for what to include and order)

#### Development Checklist:

- [x] The hardcoded EP statuses in `project_status.sql` needs to be updated to match the list in the description of this card
- [x] The IA specific statuses need to be added to `project_status`
- [x] Create a join table with `funding_stream` on `project_status` and seed it with the valid combinations of stream and status based on the lists
- [x] Refactor `selectProjectStatusWidget` to query the new join table based on the projects funding stream (which can be determined through the `fundingStreamRfpId`)
- [x] Remove the no longer used `funding_stream_rfp_id_status` table (Ensure this will not break any entries in the database first)
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by BCerki** [comment]
@nanyangpro, when you say project status can only move forward--is that an FYI, or do we need to enforce that?

**Comment by nanyangpro** [comment]
Great question, @BCerki! - Just an FYI for now (we don't want to prevent the users doing so, because they may have made a mistake. But ideally, we should at least **warn** them if they want to change the status backwards). However, the display of all the project status should reflect the sequence.

**Comment by dleard** [comment]
Has potential side effect on #924 (as described in that card)

**Comment by nanyangpro** [comment]
Thanks for confirming, @mikevespi - The lists in the ticket description is the most up-to-date version of "Project Status" for both EP and IA, confirmed by the CIF team during the research phase of IA stream projects. Please refer to the description for implementation, since additional mapping work was completed based on the latest version as well.

**Comment by mikevespi** [comment]
Note: I'm removing `"Project Status" can only move forwards not backwards.` from the description,  as this is still being determined. From Jesse & Amanda, prior to an agreement being signed it is possible for status to move backwards, whereas after that point it is not. More research being done.

**Comment by nanyangpro** [comment]
Thanks for the note, @mikevespi! More details documented in #924.

**Comment by mikevespi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1052?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @pbastia @Sepehr-Sobhani

**Comment by Dianadec** [comment]
With this now estimated, does this card need further refining or can we remove that tag

**Comment by Sepehr-Sobhani** [comment]
@nanyangpro We have a project in PROD with the status of `Complete` which based on the AC of this card, it's going to be deprecated; I was wondering if the `Closed` status is going to replace the `Complete` status or if that is totally something different?!

**Comment by nanyangpro** [comment]
Thanks for your question, @Sepehr-Sobhani - They are the same. "Closed" is the latest wording we got confirmed by CIF.

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani ! Looks great and I can confirm that EP and IA project status now reflects the list provided in the description. Thank you for your work on this ticket.
