### ISSUE TITLE
As a CIF User, I want to see a customized Budgets page according to the funding stream

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1053]
#### Description:
The Budgets, Expenses & Payments page is slightly different for EP and IA.

- [Latest design for **EP**](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2898%3A2863)
- [Latest design for **IA**](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=6246%3A301&t=0GHib02jzGbLF4d9-1)

Changes for **IA** from "EP":
- Discard the "Performance Milestone Holdback Percentage" field.
- Under the "Expenses & Payments Tracker" section, only display "Total Payment Amount To Date".

#### Acceptance Criteria:

Given that I am on the IA Budgets, Expenses & Payments page
When view or edit the form
Then it appears the same as the EP budgets form (including the `Is this a funded project` initial question) except as described in the AC below:

Given that I am on the IA Budgets, Expenses & Payments page
When view or edit the form
Then there is no  "Performance Milestone Holdback Percentage" field.

Given that I am on the IA Budgets, Expenses & Payments page
When view or edit the form
Then there is only "Total Payment Amount To Date" field under the "Expenses & Payments Tracker" section

#### Development Checklist:

- [ ] have entirely separate forms to handle `Budgets, Expenses & Payments page` based on the project funding stream: `ProjectFundingAgreementEP` and `ProjectFundingAgreementIA`  (and their Summary equivalents)
- [ ] Tasklist is updated to link to the right form depending on the funding stream
- [ ] tests for separate forms
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by matthieu-foucault** [comment]
I would consider having a separate form altogether for the IA budget, rather than having customized behaviour for this single form

**Comment by BCerki** [comment]
@nanyangpro, does the IA form have the `Is this a funded project?` initial question like EP does?

**Comment by nanyangpro** [comment]
Good question, @BCerki - This page will eventually be gone (once we implement the relationship between "Project Status" and displaying/enabling forms). Yes, for now. :)

**Comment by mikevespi** [comment]
Nan will take a look at this and reach out to the developers. It's possible that some of this work has already been done.

**Comment by nanyangpro** [comment]
Hi developers - Based on the chat with Amanda, the ticket description has been updated with link to a quick mock-up for Budgets, Expenses & Payments (IA).
Please update the AC accordingly and feel free to let me know if you have further questions either here or at tmr's Dev/Design Sync. Thanks!

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1053?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @mikevespi @pbastia @sam-warren @Sepehr-Sobhani @tmastrom

**Comment by BCerki** [comment]
@nanyangpro, in this AC:

Given that I am on the IA Budgets, Expenses & Payments page
When view or edit the form
Then there is only "Total Payment Amount To Date" field under the "Expenses & Payments Tracker" section

What's the calculation for "Total Payment Amount To Date"?

**Comment by nanyangpro** [comment]
Good question, @BCerki 

For existing IA projects, there are 2 payments in total for each project:
- **Advanced Payment (80%)** at the beginning
- **Project Summary Report Payment (20%)** at the end. To receive this, IA projects must submit a complete Project Summary Report; it is anticipated that most IA projects will likely receive the full 20% at the end but may be paid less than the full amount if the submitted report is below satisfaction and they fail to follow further directions to improve their report.
- Back to your question, before the Project Summary Report Payment is released, "Total Payment Amount To Date" would simply equal to the Advanced Payment that was paid out at the beginning; once the Project Summary Report Payment is released, "Total Payment Amount To Date" would equal to the sum of both payments.

On another note, from the recent discussions with the CIF team, they are aiming at switching from the 80/20 payment structure to 100% up front going forward, but it's yet to be confirmed officially, so we may subject to changes.

**Comment by BCerki** [comment]
Added dependency on the Project Summary Report form page--we need the values from that form to do the calculation for "Total Payment Amount To Date". FYI @tmastrom

**Comment by BCerki** [comment]
Removed dependency by creating [#total calculated value](https://github.com/bcgov/cas-cif/issues/1419). Until #1419 is completed, you won't see a calculation, just the default message that we don't have enough information to do the calculation.

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! Confirmed in dev that "Performance Milestone Holdback Percentage" is not available on the Budgets page and that "Total Payment Amount to Date" is the only field displayed under the tracker. I also noted that calculation won't be tested as part of this ticket based on your comment above.
