### ISSUE TITLE
As a Clean Growth data user, I want to have access to an up-to-date version of metabase, so that I can use its latest features

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1063]
#### Description:

- update to 44.2
- use the default metabase container

#### Acceptance Criteria:

Given I am a Clean Growth user
When I visit https://cas-metabase.nrs.gov.bc.ca/
Then I want to see the latest version of metabase (0.44.2)

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by Dianadec** [comment]
Waiting for Metabase dev to be back up to check this one.

**Comment by LindsayMacfarlane** [comment]
Double checked - Metabase dev not backup yet. @pbastia - is there an existing ticket in the backlog to fix dev?

**Comment by pbastia** [comment]
@LindsayMacfarlane this will be fixed as part of #1064

**Comment by LindsayMacfarlane** [comment]
Thanks @pbastia! Verified and new version is now available:
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/e1ea4ad5-9e9d-4d00-9223-8976505e247b)
