### ISSUE TITLE
As a Clean Growth Developer, I want to use the nrs wildcard certificate, so that I don't have to maintain a separate certificate pipeline

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1064]
#### Description:

- scrap the nginx container (because we can stop using our own entrust cert, and use NRS wildcard instead)

This should be mostly removing code.
Check airflow to see if we need to remove some manual dags there

#### Acceptance Criteria:

Given I am a Clean Growth developer
When I visit https://cas-metabase.nrs.gov.bc.ca/
Then I want to see a wildcard certificate from nrs being used

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by matthieu-foucault** [comment]
@pbastia The first attempt to deploy to dev failed, because the deployment's selectors were updated. 
I managed to deploy by deleting the deployment first (causing an outage).
While the helm chart succeeded, metabase isn't currently accessible. I haven't had the time to investigate why.

**Comment by pbastia** [comment]
Thanks! I'll investigate @matthieu-foucault

**Comment by LindsayMacfarlane** [comment]
@pbastia - is there anything I need to do to test this one?

**Comment by pbastia** [comment]
Yes - once metabase is deployed to prod, we can go through it together. Next week!
