### ISSUE TITLE
Production backups should be tested regularly

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1065]
#### Describe the task

We have tested and written a runbook for our backup process. What we need now is an automated (semi-automated?) process to consistently test that our backups in production are valid (not corrupted).

#### Acceptance Criteria

- [ ] A cronjob that pulls our production backups & tests that we can successfully restore to a point in time with those backups.
- [ ] a DAG triggering that job
- [ ] a way of assessing whether the backup succeeded

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by dleard** [comment]
@matthieu-foucault @pbastia @LindsayMacfarlane We talked about this last week. This probably needs more details but didn't want to lose the conversation & need for this.

**Comment by pbastia** [comment]
Strategy:
- Create a `cif_private.full_backup_log` table
- Investigate if we can run a postgres command before pgbackrest executes the backup - or schedule this with a cronjob daily, a couple of hours before the backup itself
- Create a `prod-backup-test` helm chart with 
    - a postgres operator, configured to load the latest prod backup
    - a job that verifies that the `cif_private.full_backup_log` table contains the latest entry
- a DAG that deploys the helm chart to our cif-tools namespace, and uninstalls it when everything is complete
