### ISSUE TITLE
project_contact form_change records are never archived [8]

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1066]
Describe the Bug:

project_contact form change records are not archived, the contactId is just removed from the new_form_data. This is different from expected behaviour and could become a hard to track bug if we write something that depends on form_change records being archived as we expect them to.

This bug is related to #1068

Probability (how likely the bug is to happen, scored from 1-5): 4
Effect (how bad the bug is when it does happen, scored from 1-5): 4

Steps to reproduce the behaviour:

When editing a revision that has an existing contact, remove that contact in the UI.
Go look in the database. The form_change record is in operation 'update' (where we would expect it to be 'archive').
The change that was made was that the contactId was removed from the new_form_data rather than archiving the record.

**Comment by Dianadec** [comment]
Closing - was not a bug
