### ISSUE TITLE
Our custom update_form_change() sql mutation will not update archived records by default [8]

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1068]
Describe the Bug:

@Sepehr-Sobhani and I found this issue when looking at the fix for #1040.
When the update_form_change() mutation is passed an operation as part of the patch, then it will update the operation to 'update'. When not passed 'update' as the operation, the `coalesce` in the mutation defaults back to 'archive'.
Archived records are filtered out on the front-end, thus the bug in #1040.

Simply passing 'update' or defaulting the mutation to change it to 'update' is probably not what we want either, as that means that any form_change record with a 'create' operation will automatically be changed to 'update' (this is not the behaviour of the app currently, all form_change records from the first revision have 'create' as the operation).

A workaround has been put in place for now in #1062 where we are conditionally passing either 'create' or 'update' from the front-end depending on the `is_first_revision` column on `project_revision`.

This bug is related to #1066, as if we fix the project_contact form_changes to actually archive properly, then contacts will end up having the same issue as outlined in #1040.

This is only an issue for form_change records that can be archived and updated in the same revision (ie: ones that are derived from intersection tables like project_manager and project_contact...potentially additional_funding_source as well). 

Probability (how likely the bug is to happen, scored from 1-5): 4
Effect (how bad the bug is when it does happen, scored from 1-5): 4

Steps to reproduce the behaviour:

call update_form_change() on an archived form_change record without defining an operation.
because of our `coalesce` in the mutation, the operation will not change from 'archive' to ' update'.

**Comment by pbastia** [comment]
I can see the code handling the null case. Thanks @gurjmatharu !
