### ISSUE TITLE
As a project coordinator, I want to only submit amendments that are approved

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#1073]
#### Description:

This was an unanswered question in #999, which has now been answered in https://github.com/bcgov/cas-cif/issues/991#issuecomment-1233539315: we should only be able to submit amendments that are approved.

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro and @pbastia - is this ticket still required or has it been addressed in our other amendments/revisions tickets.

**Comment by nanyangpro** [comment]
Good question @LindsayMacfarlane - I wasn't aware of the creation of this ticket. Looking at it, I don't think the description properly reflect the work done in #991 (unless I missed some crucial conversations related).

The user should be able to create/submit an Amendment record and update the status of it later. However, until the status of the amendment is changed to "Approved", the changes to thedata shouldn't be applied to the database. cc: @pbastia

**Comment by LindsayMacfarlane** [comment]
@nanyangpro and @pbastia - circling back on this ticket. Given its age and where we are at in implementation, I don't think this is still relevant? Thoughts? If agreed, we can close.

**Comment by pbastia** [comment]
@LindsayMacfarlane With the new flow allowing routinely updated fields, general revisions and Amendments to be modified at the same time, this card isn't relevant anymore. Let's close it :)

**Comment by nanyangpro** [comment]
Agreed with @pbastia. Thanks for confirming, @LindsayMacfarlane.
