### ISSUE TITLE
Co-Design Operators UI

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#108]
#### Description
Design wireframes for ability to search, add and edit operator information.

#### Checklist
- [x] Create wireframe based on GGIRCS and CIF team input
- [x] Review with team and get feedback
- [x] Make any required updates (based on bullet above)
- [x] Create prototype and present for feedback
- [x] Add wireframe and prototype to applicable tickets (cas-cif#65, #66, 67)

**Comment by rajpersram** [comment]
See parent [ticket 67 for Operators wireframe](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/67)

**Comment by LindsayMacfarlane** [comment]
Thank you @rajpersram :)
