### ISSUE TITLE
Task: Investigate GCS costs increases

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1081]
@LindsayMacfarlane is reporting an increase of the GCS storage costs, in spite of the team's efforts to reduce image registry usage.
Investigate what is causing this

**Comment by pbastia** [comment]
@LindsayMacfarlane what is the priority for this?

**Comment by LindsayMacfarlane** [comment]
I agree with high priority @pbastia.

**Comment by pbastia** [comment]
One option: Only run the GGIRCS ETL if there is new data - right now it runs nightly no matter what
Another option: Switching away from postgres session (#1103)
Another option: don't use patroni and only use the PostgresOperator
Another option: Finish migrating our container registry to github and retire our GCS registry

**Comment by pbastia** [comment]
Recommendation is to not optimize at this point, as implementing all the  above options would amount to about a week's developer time.
@LindsayMacfarlane

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia and @Dianadec - agree with recommended approach. We can revisit in the future if the costs continue to increase.
