### ISSUE TITLE
As a CIF user, I want amendment and revision statuses properly set on create/commit

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1085]
#### Description:

Related to #919, #999 & #981.

In #919 there are 2 sets of statuses defined:
`In Discussion / Pending Province Approval / Pending Proponent Signature / Approved` (for Amendment)
`Draft / Applied` (for General Revision, Minor Revision)

**Shouldn't amendments also have a `Draft` status while they are being drafted?**

In #999 we added `In Discussion / Pending Province Approval / Pending Proponent Signature / Approved` to the `amendment_status` table.
In #919 we added `Draft / Applied` to the `amendment_status` table.

**Should the `amendment_status` table be renamed to `revision_status`? (An amendment is a type of revision)**
**Does this status table have overlap with our `change_status` table?**
('pending', 'staged', 'committed') --> pending/staged = Draft, committed = Applied

Regardless, these statuses need to be automatically set in some places.
On project create: set amendment_status to 'Draft'
On project_revision create: set amendment_status to 'Draft'
On revision commit (for General/Minor): set amendment_status to 'Applied' 
For the other amendment statuses they can be manually set by the user in the UI shown in #981

This will require a change to the migration file `project_revision_001_add_amendment_columns`. The amendment_status column should default to 'Draft'. We will need to set the proper status for all current revisions. (If the latest revision has a change_status of 'pending' or 'staged' then 'Draft' otherwise 'Applied') <-- note the overlap of status tables.

#### Acceptance Criteria:

Given I am a CIF user
When I create a new project
Then the initial project revision has status 'Draft'

Given I am a CIF user
When I edit a project (create a new revision)
Then the new project revision has status 'Draft'

Given I am a CIF user
When I submit a revision (General/Minor)
Then the revision has status 'Applied'

#### Development Checklist:

- [x] The migration that adds the column defaults it to 'Draft'
- [x] The migration that adds the column handles setting the status properly for existing records
- [x] commit_project_revision mutation sets the amendment_status to 'Applied' for General/Minor revisions

- [x] rename the table cif.amendment_status to cif.revision_status
- [x] add a `is_amendment_specific` boolean column
- [x] In `Discussion / Pending Province Approval / Pending Proponent Signature` are all amendment specific (note `Approved` is removed and replaced with Applied`
- [x] `Draft / Applied` are not amendment specific
- [x] `cif.project_revision` column `revision_status` is `not null default 'Draft'`

- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by nanyangpro** [comment]
Good questions, @dleard.

- For Amendments, I see all 3 statuses before "Approved" as in the "Draft" stage, and users can still make changes to the revision record (Amendment) itself without actually updating the database at those statuses.
- It's a dev question, but I second your suggestion of renaming "amendment_status" to "revision_status" for the table for the same reason you stated.

**Comment by gurjmatharu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1085?planning-poker) with Zenhub @pbastia @Sepehr-Sobhani

**Comment by gurjmatharu** [comment]
We need confirmation on this point.
> Should the amendment_status table be renamed to revision_status? (An amendment is a type of revision)
Does this status table have overlap with our change_status table?
('pending', 'staged', 'committed') --> pending/staged = Draft, committed = Applied

**Comment by pbastia** [comment]
solution after discussing with @dleard and @BCerki :
- rename the table `cif.amendment_status` to `cif.revision_status`
- add a `is_amendment_specific` boolean column
- `In Discussion / Pending Province Approval / Pending Proponent Signature` are all amendment specific 
- `Draft / Applied` are not amendment specific

The overlap between a revision's `revision_status` and a form change's `change_status` is not a problem, one is a business concern (revision) and the other is an implementation concern (whether a record has been written to the db)

**Comment by LindsayMacfarlane** [comment]
Hi @BCerki - I think I may be having a hard time testing this :) Here's what I have experienced:

- When I initially create a project (i.e., for the first time) > it is captured as a general revision with a status of applied
- When I went to make my first General Revision > effective date of pending, status draft. Given this is in draft, I can't seem to make any other revisions (I get a message saying "there is an existing revision". 
- When I went to make an Amendment revision (on a different project for testing purposes) > listed as pending, status as draft

Observation:
- after making a revision of any type, the "Amendments & Other Revisions" tab in the task list disappears and I have to exit the project, then re-find it in the project list to continue with updates or just to see the amendments list again and confirm that the changes were captured. There should be a ticket for this, but we should confirm.

**Comment by BCerki** [comment]
> * When I initially create a project (i.e., for the first time) > it is captured as a general revision with a status of applied
Applied status is new in this PR, yes.

> * When I went to make my first General Revision > effective date of pending, status draft. Given this is in draft, I can't seem to make any other revisions (I get a message saying "there is an existing revision".
As far as I understand, this is expected behaviour--if there's an existing revision, users shouldn't be able to make a new one. Instead, they should edit the existing one.

> * When I went to make an Amendment revision (on a different project for testing purposes) > listed as pending, status as draft
Also new in this PR
 
> * after making a revision of any type, the "Amendments & Other Revisions" tab in the task list disappears and I have to exit the project, then re-find it in the project list to continue with updates or just to see the amendments list again and confirm that the changes were captured. There should be a ticket for this, but we should confirm.

I don't see a ticket for this; I'll make one and add this link here when it's up.

@pbastia, do you want to comment on any of this? We worked on a lot of it together.

**Comment by LindsayMacfarlane** [comment]
Thank you for that clarification @BCerki! Moving to approved.
