### ISSUE TITLE
Task: create cif user upon login

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#109]
need to call the `createUserFromSession` mutation after the SSO login (if not exists)

Investigate how to do that from the server side

idea: an express middleware that triggers this mutation that we wire on the auth-callback route.

Todo
- write that middleware
- update the sso-express package to call next() in the `authCallbackController` (and make 100% sure we're not leaking tokens if something goes wrong)

**Comment by LindsayMacfarlane** [comment]
I don't believe there is anything I can/need to test for this ticket. @pbastia - does this still require another dev to review or can it be put in the accepted column.

While testing the other log in tickets, everything worked as expected.

**Comment by pbastia** [comment]
This is a prerequisite for the user's name showing up near the logout button (since that feature requires a record in the database to exist) - so it works as expected :)
We can move this to 'accepted'
