### ISSUE TITLE
Research & Design Knowledge Transfer and Preparations for it

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1090]
#### Describe the task
Knowledge and assets (design, documentation, Miro boards, etc.) transfer needs to be completed before the button contract end date (Friday, Sep 30).

#### Acceptance Criteria

- [x] Nan identifies and lists knowledge and assets needed from Suha
- [x] Suha identifies and lists knowledge and assets needed to be passed down to Nan
- [x] Schedule time in the week of 26th - 30th based on Suha's availability
- [x] Transfer knowledge and assets as listed
- [x] Make sure things can move forward smoothly

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by nanyangpro** [comment]
Things needed identified so far:
- Figma Files #1082
- Usability Test (Emissions Intensity Report) status and next-steps updates
- Documentation discovery updates

List to be expanded.

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane, this ticket can be closed unless you have additional comments/concerns (please see summary below).

Items discussed and confirmed with @suhafa:

- **Documentation/Recordings**: All research/design related documentation and recordings so far can be found in our MS Teams channels, thus no migration required.
- **Miro**: All CIF related Miro boards were created and hosted under "CAS-GGIRCS team", thus no ownership transfer required. The access permissions should remain the same.
- **Figma**: Only one Figma file requires ownership transfer. The transfer will take place in the scheduled session after the sprint review on Thursday, Sep 29. #1082
- **Usability test findings for Emissions Intensity Report** are compiled and synced with the team during the Dev/Design Sync on Wednesday, Sep 28 by @suhafa. She will enter the proposed and validated tickets in ZenHub as discussed. #917
- **Latest design updates** (Emissions Intensity Report, Report Auto Generation, etc.) have been provided to Nan by Suha.
- **Questions and suggestions for designs** (Task List, Emissions Intensity Report, Report Auto Generation, etc.) so far have been brought to Suha by Nan.
- **Suggested next steps for Nan in general**: Clean up and organize Figma pages. Identify and address inconsistencies between design and implementation.

**Comment by LindsayMacfarlane** [comment]
Thank you both @suhafa @nanyangpro! You have documented the knowledge transfer so well - I have no concerns.

This has been the first project where I have had the opportunity to work with two UX/UI Designers and it has been absolutely fantastic. Your collaboration and ability to work seamlessly together has been exemplary. Kudos to you both for what appears to be an incredibly coordinated and smooth knowledge transfer and transition.
