### ISSUE TITLE
Update technical leads in the registry, and other vendor account dependencies 

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1095]
- GH token used in the cas-pipeline values and env probably needs to be regenerated

**Comment by pbastia** [comment]
The current registry system is not working, here is some more information from RC:
> you can also remove their access to each namespace with oc adm policy remove-role-from-user admin <username>@github, and it is my understanding that you’d need to do this anyhow even after updating the details in the registry.

**Comment by Dianadec** [comment]
@pbastia let me know if you're free today to go over this one
