### ISSUE TITLE
As a user, I don't want to see a rank calculation until I've entered year and stream

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1097]
#### Description

NOTE: This may be irrelevant once we've made the stream/year immutable

Good question, @BCerki. - Just so that the users don't get confused by seeing the calculated ranking against the other projects not having a year or stream (which doesn't make much sense and is not indeed necessary), they shouldn't be allowed to enter a score without having selected a stream and year for a project. Hope it's helpful.

_Originally posted by @nanyangpro in https://github.com/bcgov/cas-cif/issues/934#issuecomment-1244267873_

#### Acceptance Criteria:

Given that the stream, year, or score on the project form are not filled
When a user encounters the rank widget
Then they should not see a calculated rank and should instead see a message that reads (?)

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

- Linked to tickets #1075 and #718?

**Comment by BCerki** [comment]
@nanyangpro, what message (?) should users see when there's no score, year, or stream entered? Can we use the same text no matter which combination of fields is/isn't filled?

**Comment by nanyangpro** [comment]
Good question, @BCerki. Stream and year are crucial, especially for customized display of forms/fields, thus they should have been selected (and immutable onwards) before user can proceed with other data entry for a project.

In terms of the case where no score has been entered, please see the message in #934's comment for more context.

**Comment by BCerki** [comment]
> @BCerki @nanyangpro @LindsayMacfarlane The work in #1075 and #934 will make this card irrelevant. I suggest closing it, unless I'm missing something?

I'm fine to close

**Comment by LindsayMacfarlane** [comment]
If addressed through the mentioned tickets we can close. @BCerki @dleard @nanyangpro

**Comment by nanyangpro** [comment]
Good call. Agreed, thanks @dleard!

**Comment by LindsayMacfarlane** [comment]
Closing ticket as it is a duplicate and will be addressed through other work.
