### ISSUE TITLE
As a CIF user, I want to see the Funding stream and RFP year as read-only on the project overview form

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1100]
#### Description:

Thanks to #1075, the users won't be allowed to modify the funding stream and RFP IDs (aka year) once the project is created.

This is mainly database work, creating triggers that protect these fields once created.

#### Acceptance Criteria:

Given I am a CIF administrator 
When I am creating or editing a project
And I am on the project form
Then I cannot edit the funding stream (the control is disabled)

Given I am a CIF administrator
When I am creating or editing a project
And I am on the project form
Then I cannot edit the Funding Stream RFP year (the control is disabled)

#### Development Checklist:

- [x] Make funding stream immutable once project created <- database trigger
- [ ] Make funding stream RFP (aka the funding year) immutable once project created <- database trigger
- [x] Make the fields disabled in the json schema form
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
@pbastia and @nanyangpro - this ticket covers not being able to change the funding stream and RFP ID, but would it also apply to the RFP year (or is that covered in a separate ticket)?

**Comment by Dianadec** [comment]
@LindsayMacfarlane is this still a high priority?

**Comment by LindsayMacfarlane** [comment]
@Dianadec - I'd be curious to get the team's perspective. I believe this user story can wait until we start to tackle building in functionality that supports the IA stream, which is a high priority , but not as high as some of our other EPICS. I believe IA was a stretch goal for this quarter....so, to answer your question....yes, but later ;)

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1100?planning-poker) with Zenhub @BCerki @gurjmatharu @pbastia @Sepehr-Sobhani

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1100?planning-poker) with Zenhub @BCerki @gurjmatharu @pbastia @Sepehr-Sobhani @mikevespi @sam-warren

**Comment by LindsayMacfarlane** [comment]
I think I'm trying to test before this feature has been released?

**Comment by mikevespi** [comment]
Oh! Yes, the deploy failed :( just saw it now. I'll move it back to review until it's ready. 

Sorry!

**Comment by mikevespi** [comment]
Happo flakiness shenanigans, all set now @LindsayMacfarlane

**Comment by LindsayMacfarlane** [comment]
Thank you @mikevespi! 

One observation: Let's say, as a user, I make a mistake entering the year and funding stream. I have a couple of options to update:
1. Hit the back button on the browser. I can now re-enter the funding year and stream. Not sure if using the browser's back button is the ideal option?
2. Jump to review and submit and select the discard project revision button (note: at first I thought I had to enter all the required information to get to this page...but it turns out I don't have too)
No changes required. Just random thoughts.

**Comment by mikevespi** [comment]
And good ones at that. I've added a trigger to the database to prevent it from being changed, but I will look into that behaviour next week. I think ideally if that happens it would be nice to be able to just click back, but the way that we limit people to having one new project in progress at a time might get in the way with it. Good catch @LindsayMacfarlane

**Comment by pbastia** [comment]
@LindsayMacfarlane @mikevespi we need to capture this behaviour in a bug, this is a way of bypassing our "only one project creation in progress at a time" - and makes it possible for one user to have multiple project creations on the go, that are only accessible via the URL

**Comment by LindsayMacfarlane** [comment]
@dleard - was this ticket part of the release v1.2.0?
