### ISSUE TITLE
Task: Update the ordering/grouping inconsistencies noticed between the wireframe and implementation

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1101]
#### Describe the task

This ticket is for updating the ordering/grouping of fieldsin the CIF app to reflect the latest design, and goes hand in hand with #1029 (suggested to be completed first so that we have the accurate labelling in the app) which addresses field/button labelling inconsistencies between the wireframe and implementation.

#### Acceptance Criteria

(Fully refined by @nanyangpro, reach out if having questions.)

**Budgets, Expenses & Payments**
- [x] Move the "Contract Start Date" and "Project Assets Life End Date" fields to the top, i.e. above "Maximum Funding Amount".
- [ ] ~Move the "Total Project Value" and "Anticipated/Actual Funding Amount" fields to the bottom, i.e. below "Additional Funding Sources".~ captured in #1129

**Emissions Intensity Report Form**
- [x] Group "GHG Emission Intensity Performance" and all the fields below with label "Upon Completion".

**Comment by Sepehr-Sobhani** [comment]
Based on yesterday's (Sep 22) discussion with @nanyangpro

**Comment by nanyangpro** [comment]
This ticket #1101 and #1029 (suggested done first) should go hand in hand. They are both fully refined addressing inconsistencies between design and implementation **across the app** instead of just for one form.

**Comment by pbastia** [comment]
The second item will require a similar refactor to the milestone form, and should probably be split up in a separate card

**Comment by LindsayMacfarlane** [comment]
Thank you @sam-warren! Verified in dev:
- Contract start date and project assets life end date now displayed at the top
-  GHG fields now captured within a 'upon completion' frame
