### ISSUE TITLE
PostgresOperator monitoring should monitor cif-prod

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1102]
#### Describe the task

crunchy-monitoring was setup before the first prod deployment. we need to extend that

#### Acceptance Criteria

- [ ] redeploy https://github.com/bcgov/cas-pipeline/tree/master/helm/crunchy-monitoring to our CIIP-tools namespace to include the -prod namespaces.
- [ ] the `.crunchy-values.yaml` file in the team's 1password needs to be updated and redeployed

**Comment by LindsayMacfarlane** [comment]
Hi @pbastia - what is your recommended priority for this issue? Should we be looking at tackling next sprint (October 31 - Nov 11)?

**Comment by pbastia** [comment]
If we can that would be great. This is likely low effort, as it's already done for -test and -dev
