### ISSUE TITLE
Projects without a primary manager will not show up in the projects list [6]

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1106]
Describe the Bug:

If a project is created without a primary manager, it will not show up in the project list (so it will be inaccessible to users). This is because of the `some` filter [here](https://github.com/bcgov/cas-cif/blob/develop/app/pages/cif/projects.tsx#L53).
The `some` filter asserts that "Some related ProjectManager matches the filter criteria", so if a project is created without a primary manager, then this filter always excludes that record.

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Create a project via the UI, but do not set a primary manager.
Navigate to the list of projects, see that the project is not in the list.

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki - I followed the steps to replicate the bug and could no longer reproduce. Projects without a project manager are now displayed in the project lists.
