### ISSUE TITLE
Hide amendments  behind growth book flag 

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1108]
#### Describe the task

Hide new amendment feature behind feature flag. 

#### Acceptance Criteria

- [x] Turn on feature flag in growth book
- [x] Put amendments and other revisions table behind the feature flag (on the Tasklist and its dedicated page)
- [x] Put amendments and other revisions create page behind the feature flag
- [x] Put amendments and other revisions view  page behind the feature flag
- [x] make sure the current create revision process is still working

#### Additional context

- Add any other context about the task here.
- Or here

keyword: growthbook, feature flag

**Comment by LindsayMacfarlane** [comment]
FYI @pbastia - I've created this ticket for hiding amendments behind a feature flag

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani!  

I always forget in growth book - when it is purple, that means it is visible in that environment correct? If so, are there any objections to have amendments visible in the test environment?
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/a3e48f41-4b24-4ab2-b755-0f25f5bbbe5c)

**Comment by Sepehr-Sobhani** [comment]
> Thank you @Sepehr-Sobhani!
> 
> I always forget in growth book - when it is purple, that means it is visible in that environment correct? If so, are there any objections to have amendments visible in the test environment? ![image.png](https://camo.githubusercontent.com/ed2628c31ef661fb00c8d82a99ed27679fa7232dc16cc8ad9f0cf1641a4a9cac/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630663964623038396533613338386661636465393664312f61336534386634312d346232342d346162322d623735352d306632356635626262653563)

@LindsayMacfarlane Yes you're right and there's no objection :) I'm gonna turn it on.

**Comment by LindsayMacfarlane** [comment]
Brilliant! Thank you @Sepehr-Sobhani!
