### ISSUE TITLE
Amendments & Revisions are displayed in the task list when creating a project [7]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1122]
Describe the Bug:

Amendments & Revisions are displayed in the task list when creating a project (before saving a project).

Probability (how likely the bug is to happen, scored from 1-5): 5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Login -> create new project -> click amendments and revisions on the task list

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani! The amendments and other revisions is no longer displayed in the task list when creating a new project.
