### ISSUE TITLE
Refactor `create_project_revision` to include `revision_type`

### ISSUE THREAD

**Issue by gurjmatharu** [bcgov/cas-cif#1128]
###Description of the Tech Debt###

Currently we have the `create_project_revision` mutation that creates a new project revision and it's corresponding forms.
However, we also need it to support `revision_type`.  Due to a restriction on postgres' create or replace function, we will need to drop and recreate the function.  This will require modifying sqitch and ensuring the function is backwards compatible.  Perhaps adding `revision_type` as an aoptional parameter.

> To replace the current definition of an existing function, use CREATE OR REPLACE FUNCTION. It is not possible to change the name or argument types of a function this way (if you tried, you would actually be creating a new, distinct function). Also, CREATE OR REPLACE FUNCTION will not let you change the return type of an existing function. To do that, you must drop and recreate the function. (When using OUT parameters, that means you cannot change the types of any OUT parameters except by dropping the function.)

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |  Low     | 1      |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |   Med    |    2   |
| System Fault Risk - Risk of system errors or application downtime                                                             |     Low  |  1     |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |   High    |   3    |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |   Low    |    1   |
| TOTAL SCORE:                                                                                                                  |       |   7    |

**Comment by LindsayMacfarlane** [comment]
Thank you @gurjmatharu! I don't think there is anything I need to test on this one?

**Comment by gurjmatharu** [comment]
@LindsayMacfarlane nope it was solved in #992
