### ISSUE TITLE
Task: Remove CIIP references in CIF realm login page config

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#113]
The CIF login prompt still has references to CIIP,
we should:
- Ensure non-IDIR login is only enable in `dev` as it is needed for cypress to run end-to-end tests
- create generic wording that supports all CAS applications, as the description is shared between CIIP, CIF, and the GGIRCS apps
 
Needs to be updated in
- [ ] dev
- [ ] test
- [ ] prod

![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/0a912ca0-6115-42cd-baac-8f0840aa7270)

**Comment by matthieu-foucault** [comment]
I think that this is configured for the whole realm, so we may want to find some generic wording that applies to all applications

**Comment by matthieu-foucault** [comment]
Also adding dev/test in the dev/test realm titles could be good

**Comment by matthieu-foucault** [comment]
@pbastia this may be superseded by #305. This screen doesn't have to be visible, we can redirect directly to the siteminder page

**Comment by LindsayMacfarlane** [comment]
Roadmap discussion (March 25, 2022): team indicated that this ticket is no longer required (also need note from above). Ticket is being closed.
