### ISSUE TITLE
Quarterly reports generated by new report auto-generate feature have timezone issue [8]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1136]
Describe the Bug:

Quarterly reports generated by the new report auto-generate feature are off by one day. we need to cast `due_date` field in the mutation SQL to make it a timestamptz and add an e2e test (as a regression test) to make sure we always have the right date in those reports.
Note that this issue doesn't happen in the local dev environment.
Quarterly Reports should be 5th of related months(Jan, Apr, Jul, Oct).

Probability (how likely the bug is to happen, scored from 1-5):5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Create new project -> fill in the required date inputs to generate a quarterly report reports -> generate reports -> quarterly reports are off by one day

Screenshots:

![Screen Shot 2022-10-13 at 2.12.01 PM.png](https://images.zenhubusercontent.com/6243a3ea8726850c1675becd/eed63f81-2066-4416-b783-3a72837e52b5)

![Screen Shot 2022-10-13 at 2.12.23 PM.png](https://images.zenhubusercontent.com/6243a3ea8726850c1675becd/3dc646df-ba08-455f-80a6-9cc61c6179b5)

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani ! Tested in dev and can confirm that quarterly reports are now generated/displayed as Jan 5, April 5, July 5.
