### ISSUE TITLE
Validate and/or refine the envisioned workflows for the Routinely Updated Fields

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1137]
#### Describe the task

Based on the internal discussions with the developers, the envisioned workflows for updating the Routinely Updated Fields (see below) have been prototyped as outcome of #960.

- [Generic example for fields with Dropdown as front-end component](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=4939%3A685&node-id=5089%3A1414&viewport=-484%2C320%2C0.14&scaling=scale-down&starting-point-node-id=5089%3A1414&show-proto-sidebar=1)
- [Generic example for fields with Date Picker or Text Input as front-end component](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=4939%3A685&node-id=4939%3A1324&viewport=-484%2C320%2C0.14&scaling=scale-down&starting-point-node-id=4939%3A1324&show-proto-sidebar=1)

They need to be validated with the CIF team and refined where fit.

#### Acceptance Criteria

- [x] Schedule walk-through and feedback gathering meeting with CIF Ops
- [x] Document suggestions/concerns to inform design update decisions
- [x] Sync and discuss findings and potential design updates with Devs
- [x] Refine the design and prototypes if needed
- [x] Draft user story tickets with design linked

**Comment by nanyangpro** [comment]
Hi Lindsay, this ticket is ready for you to review and can be closed with

- The envisioned workflows reviewed, refined, and validated by the CIF team
- Ticket #1158 created for implementation with details in its description

**Comment by LindsayMacfarlane** [comment]
Thank you so much @nanyangpro for walking me through the design and decisions that went into this ticket. Much appreciated.
