### ISSUE TITLE
Usability testing of Report Auto-Generation

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1139]
#### Describe the task

Usability testing of implementation for #1019.

#### Acceptance Criteria

- [x] Book sessions
- [x] Develop testing script/plan
- [x] Conduct sessions
- [x] Document findings
- [x] Report back to the team
- [x] Create/update ticket if necessary

#### Additional context

Definition of Ready
(Note: If any of the points are not applicable: delete or mark N/A)
- [x] Implementation is ready.
- [x] Script is ready.
- [x] Tasks are created.
- [x] Data is created (if necessary).
- [x] Users (participants) are identified.

Definition of Done
(Note: If any of the points are not applicable: delete or mark N/A)
- [x] Findings are documented (if necessary).
- [x] Follow-up tickets created (if necessary).

**Comment by Dianadec** [comment]
@nanyangpro I moved this to 'in progress' but let me know if there's another way you have been indicating the progress of these types of cards during the sprint.

**Comment by nanyangpro** [comment]
Good call, @Dianadec - When the work is started, I usually move it to "Design In Progress" instead of "Development In Progress". Thanks!

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket is ready for you to review and can be closed with

- [Observation and findings](https://miro.com/app/board/uXjVPKCDCAE=/?share_link_id=126637130204) documented, complied, and synced up with the team
- Tickets addressing the immediate next steps created: #1153 (nice-to-have), #1154 for generating Quarterly Reports, and #1155 for generating Annual Reports.

**Comment by LindsayMacfarlane** [comment]
As always @nanyangpro, your work is exemplary. I also really appreciated the miro board where you clearly identified what are priority enhancements, what are nice to have's and requests that can wait until later.
