### ISSUE TITLE
CIF user name and logout button

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#114]
#### Describe the task

Show the user `<lastname>, <firstname>` and email address (one above the other) and a logout button in the header

**Comment by pbastia** [comment]
something like that?
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/11507754/143494395-c521c6d9-fa65-481b-b734-8b31ff2e9782.png">

**Comment by matthieu-foucault** [comment]
yes!

**Comment by rajpersram** [comment]
Or the one illustrated in the prototypes uploaded, which looks like:

![cif header.jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/15d3dfc6-f2db-454f-aebf-c70c74a03aed)

**Comment by matthieu-foucault** [comment]
- We don't have a profile/preferences page yet, so I was more in favor of a simple button for now
- Users logging in with a different email has caused issues in the past, so I wanted to see emails up there
- We could probably figure out how to get the ministry info (`ENV`), but we haven't set that up yet

**Comment by rajpersram** [comment]
Ok, good to know. Thanks. Best to flag this info on the wireframes pages in Miro so I can account for them before prototyping. Perhaps the ministry title is unnecessary. I thought we'd be pulling that info from the GAL.

**Comment by LindsayMacfarlane** [comment]
Tested in dev environment - works as expected. I was able to log in, see my user name and email, and log out of the system.
