### ISSUE TITLE
Bug: Revision view happo screenshot displays a loading icon

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1141]
Describe the Bug:

The project revision view screenshot is taken too early and should wait for content to be displayed on the page before.
see latest revision on https://github.com/bcgov/cas-cif/pull/1134

Probability (how likely the bug is to happen, scored from 1-5): 5
Effect (how bad the bug is when it does happen, scored from 1-5): 1

**Comment by Sepehr-Sobhani** [comment]
Nothing to test at the user's end.
