### ISSUE TITLE
Bug: Amendments table tasklist item has an expand behaviour when there are no items

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1142]
Describe the Bug:

The tasklist link to 'Amendments and other revisions' now displays a caret if there are no sub-items, that shouldn't be the case

![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/2d5a4f42-2119-4acc-88fb-e2b8850e9bc2)

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani !
