### ISSUE TITLE
Milestone report's next report due link is not aligned with the correct report[7]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1151]
Describe the Bug:

Milestone report's next report due link is not aligned with the correct report. removing one report from the middle can cause the link to show the wrong number and anchor.

Probability (how likely the bug is to happen, scored from 1-5):3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
create multiple milestone reports → make the last report as the next report due → remove the last report → next report due link is still referring to that last report which does not exist anymore

Screenshots:
https://www.loom.com/share/b7dd8e1b496f49ea9d98d81213a6f988

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by LindsayMacfarlane** [comment]
Amazing instructions and video @Sepehr-Sobhani! Thank you for tackling the bug @gurjmatharu!  I could no longer reproduce the bug while following the steps outlined above.
