### ISSUE TITLE
As a user, I want to make sure that the Annual Reports are properly generated.

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1155]
#### Description:

- As a user, I want to see all the Annual Reports due on Jan 30th of the years covering the whole period between the **"Emissions Intensity Repot Due Date" and "Project Assets Life End Date"** after clicking the "Generate Annual Reports" button.
_For a project whose "Emissions Intensity Report Due Date" is in Year X, the first Annual Report should be due on Jan 30th, Year (X+2)._
_For a project whose "Project Assets Life End Date" is in Year X, the last Annual Report should be due on Jan 30th, Year (X+1)._

- As a user, I want to see the "Emissions Intensity Repot Due Date" and "Project Assets Life End Date" auto-updated when they are changed elsewhere.
_I believe this is how they behave now, but we just to make sure they stay up-to-date._

#### Acceptance Criteria:

Given I am a CIF administrator
When I am creating or editing a project revision
And annual reports have not been entered
Then I can see read-only "Emissions Intensity Repot Due Date" and "Project Assets Life End Date" fields on the annual report's form (If populated)

Given I am a CIF administrator
When I am creating or editing the annual reports of a project revision
Then I can see a "Generate annual reports" button enabled (if required fields populated otherwise disabled)

Given I am a CIF administrator
When I am creating or editing the annual reports of a project revision
And I press the "Generate annual reports" button
Then the reports are generated annually on **the 30th** of all years covering the whole period between the required dates

Given I am a CIF administrator
When I am creating or editing the annual reports of a project revision
Then I don't see a "Generate annual reports" button if there are existing annual reports

#### Development Checklist:

- [x] Refactor the generation function in the database to split the work into 2 separate functions to generate Annual and Quarterly reports- independently maintainable and testable
- [x] Separate report auto-generation feature tests (Quarterly and Annual)
- [x] Update mutation functions
- [x] Update tests to cover the new logic for annual reports (X+1 and X+2)
- [x] Always show required date fields even if reports are generated
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

- Note That we have a timezone issue for this feature which is addressed in [this](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1136) ticket.

**Comment by pbastia** [comment]
Before hard-coding such logic in the application, @nanyangpro to reach out and confirm the logic in this ticket with the business area, in a written format, for traceability.
cc @LindsayMacfarlane

**Comment by Sepehr-Sobhani** [comment]
Quick Note here, We need to change the end date of annual reports from 31 to 30. Currently, the logic is based on Jan 31st of each year.

**Comment by rdromey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1155?planning-poker) with Zenhub @pbastia @Sepehr-Sobhani

**Comment by rdromey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1155?planning-poker) with Zenhub @dleard @gurjmatharu

**Comment by nanyangpro** [comment]
Written confirmation on the details in the description above has been received from CIF Ops Amanda.
![image.png](https://images.zenhubusercontent.com/5e3b4990c0f4cb9e2c9b1b1e/d01b3aab-11be-4536-a351-dd71fe222702)

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro - thanks for the above. Is it possible to remove the copy of the email (i.e., email addresses and names) and just have the calculation/formula? I recognize that those are business emails, but we try not to include those in ZenHub. Thanks!

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani! Looks good :)

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani - during a quick first test, I couldn't generate an annual report. The button isn't greyed out, but when I click, nothing happens. I'll test again, but perhaps you can take a quick look as well?

**Comment by Sepehr-Sobhani** [comment]
Thanks, @LindsayMacfarlane! Would you please send me the dates you've tested with?

**Comment by LindsayMacfarlane** [comment]
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/87ca58d1-1b98-4034-8a9b-263daa6c8609)

**Comment by Sepehr-Sobhani** [comment]
That happened because `Emissions Intensity Report Due Date` is after the `Project Assets Life End Date`.

**Comment by LindsayMacfarlane** [comment]
Ok! Thank you :) I will retest. We could also consider adding (at a later date) an error message? (FYI @nanyangpro, @suhafa)

**Comment by LindsayMacfarlane** [comment]
@Sepehr-Sobhani - retested - looks great! Looks like it meets acceptance criteria. Thanks for all your work on this critical feature for CIF :)
