### ISSUE TITLE
As a CIF administrator, I want to see the parameters of the report generation after I generated reports, so that I still have context on how those reports were generated

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1157]
#### Description:

On both Annual and Quarterly reports, when the reports are generated, we hide the start and end dates used for the generation. This removes the context for the user, and 

#### Acceptance Criteria:

Given I am a CIF administrator
When I generate Annual or Quarterly reports
And I click 'Generate Reports'
Then I can still see the dates used for the generation

Given I am a CIF administrator
When I view the Quarterly or Annual reports that have been generated
Then the dates used for the generation are up-to-date with their source (the other forms)

#### Development Checklist:

- [x] Show the report generator component - without the generate button (maybe a read-only prop on it?)
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1157?planning-poker) with Zenhub @pbastia @Sepehr-Sobhani @gurjmatharu

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani - looks great and meets the acceptance criteria!
