### ISSUE TITLE
Draft/visualize high-level vision for design

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1159]
#### Describe the task

There are many design/research artifacts that were previously synced with the team, but are forgot / unaware of by the team. We need to organize them better to keep the designers and the developers on the same page in terms of the high-level design vision for the CIF app.

#### Acceptance Criteria

- [x] Archive outdated design artifacts (mock-ups, prototypes, comments, notes, etc.) in Figma
- [x] Organize research artifacts (scripts, recordings, etc.) in MS Teams
- [x] Draft/visualize high-level vision for CIF design with gaps identified
- [x] Communicate to / discuss with the team

#### Additional context

**Comment by suhafa** [comment]
To discuss if 'Draft/visualize high-level vision for CIF design with gaps identified' is a higher level task that needs to be split and refined on its own, after getting context from @nanyangpro

**Comment by nanyangpro** [comment]
Hi Lindsay - This ticket is ready for you to review and can be closed with
1. The research & design artifacts organized with changes communicated
2. The [Envisioned High-level User Workflow (Internal & External)](https://miro.com/app/board/uXjVP1NVDKE=/?share_link_id=532144421562) diagramed, demoed and discussed, and the input from the team documented.

**Comment by LindsayMacfarlane** [comment]
Thank you for all your effort on this @nanyangpro! It was great to visualize the future workflow for CIF and continued opportunities for improvement.
