### ISSUE TITLE
Design wireframes and prototypes for showing a list of attachments for a project.

### ISSUE THREAD

**Issue by rajpersram** [bcgov/cas-cif#116]
#### Checklist:

- [x] Create wireframes
- [x] Review with GGIRCS and CIF team for revisions
- [x] Translate to Figma prototype and upload both designs to corresponding user story ticket 75.

**Comment by rajpersram** [comment]
Wireframes for showing list of attachments and for uploading attachments has been sent to the associated user stories mentioned above ([72](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/72), [74](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/74), [75](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/75)).

**Comment by LindsayMacfarlane** [comment]
Thank you @rajpersram !
