### ISSUE TITLE
As a CIF administrator, I want to notify the individual(s) an amendment is waiting for, so I can get their attention

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1167]
#### Description:

This is part 2 of #982

[Prototype Example 1 (Notify Tech Team)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=3989%3A5985&node-id=3989%3A8493&viewport=-674%2C-451%2C0.24&scaling=scale-down&starting-point-node-id=3989%3A8493&show-proto-sidebar=1)
[Prototype Example 2 (Notify Director)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=3989%3A5985&node-id=3989%3A7927&viewport=-674%2C-451%2C0.24&scaling=scale-down&starting-point-node-id=3989%3A7927&show-proto-sidebar=1) 
[Prototype Example 3 (Notify Proponent)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=3989%3A5985&node-id=3989%3A7085&viewport=-674%2C-451%2C0.24&scaling=scale-down&starting-point-node-id=3989%3A7085&show-proto-sidebar=1)

When the user clicks the "Notify" button on an amendment view in the "pending actions from" control, a modal opens up, for the user to select which individuals to notify

#### Acceptance Criteria:

Given I am a CIF administrator
When I view an amendment from the revisions list
And I click on the "Notify" button from the "pending actions from" section
Then I can see a modal dialog allowing me to select who to notify, with a "Notify By Email" and "Cancel" buttons

Given I am a CIF administrator
And I view the pending actions modal
When I click the "Cancel" button
Then the modal closes and nothing else happens

Given I am a CIF administrator
When I am notifying people that an amendment requires their attention
And I am viewing the modal 
Then for each selected group, I can select the following contacts:
- Ops Team : Ops Team Primary and Secondary managers
- Tech Team: Tech Team Primary and Secondary managers
- Director: Program director
- Proponent: Project contacts

Given I am a CIF administrator
When I am notifying people that an amendment requires their attention
And I am viewing the modal 
And a Project Manager (Primary or secondary) or a Proponent contact is not defined
Then I can see a message telling me where to add it
And the associated checkbox is disabled

Given I am a CIF administrator
And I am viewing the notification modal
And I selected at least one 
When I click the "Notify by email" button
Then the app opens the default email program with:
- `To:` field populated with the selected emails
- `Subject:` field is: "Amendment pending your actions (CIF: << RFP Number >>)
-  Email body contains a link to the amendment view
And the modal closes

#### Development Checklist:

- [x] Program director contact cannot be hard-coded in the codebase - we will need to set it up as an environment variable, or a database entry somewhere. Maybe just a `PROGRAM_DIRECTOR_EMAIL` env variable initially?
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1167?planning-poker) with Zenhub @BCerki @gurjmatharu @mikevespi @pbastia @sam-warren @Sepehr-Sobhani @tmastrom

**Comment by BCerki** [comment]
I blocked this because the first time I read the AC, I thought this ticket included doing the work that's already covered in #1166 . Might be able to start (but not completed) this ticket while #1166 is in progress

**Comment by BCerki** [comment]
@nanyangpro, in the wireframe there are down arrows (sorry, don't know the design term) beside each category of contact. Are those meant to expand/collapse the list? If yes, can we address them in a separate ticket?

**Comment by BCerki** [comment]
@nanyangpro, another one--in the wireframe, is the checkbox supposed to be beside the individual's name? (vs beside the header)

**Comment by BCerki** [comment]
After discussion with @nanyangpro;
- collapsing/expanding will be handled in a separate ticket if needed (right now only secondary contacts can have more than person)
- checkboxes will be beside individual names

**Comment by nanyangpro** [comment]
Great questions, @BCerki! Thanks for confirming and appreciate your suggestions.

- Yes, disabled.
- Yes, cleared.

**Comment by BCerki** [comment]
After discussion with @nanyangpro (Nan, please weigh in here if I've remembered something incorrectly):
- selecting pending actions from is optional (and therefore `(optional)` will appear beside the label)
- in addition to the above AC, per the wireframe, there will be an `Update` button (to be consistent with https://github.com/bcgov/cas-cif/issues/1158). After making a recipient selection from the dropdown, the user will click update, and this will determine which names show up in the modal.

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! Looks good. A couple observations when creating project 2022-RFP-1-CUTE-666 (name Devils Club):

- I noticed that when I changed the 'pending actions from' after setting the status, the status would revert or change.

**Comment by BCerki** [comment]
@Sepehr-Sobhani , I'll look into this--I think it's related to the modal state

**Comment by BCerki** [comment]
@LindsayMacfarlane, @Sepehr-Sobhani, I think this is two bugs:
- rjsf state problem, addressed here: https://github.com/bcgov/cas-cif/issues/1167
- the pending actions from dropdown doesn't change to readonly until after refresh. I think this is unrelated to the modal, so I've made a bug ticket: https://github.com/bcgov/cas-cif/issues/1328
