### ISSUE TITLE
As a CIF developer, I want the Funding Agreement form to be refactored with a custom commit handler, so I have more flexibility in the form layout.

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1170]
#### Description:

Similarly to the milestone refaactor (#1007) 

#### Acceptance Criteria:

Given I am a CIF developer
When I commit a funding agreement form
Then a custom form commit handler is called
And both `funding_agreement` and `additional_funding_sources` tables are populated

Given I am a CIF developer
When I add, remove or reorder fields on the funding agreement page
Then there is only a single form to change

#### Development Checklist:
- [ ] write new, single json schema, using an array type for the additional funding sources
- [ ] don't forget to update the tasklist and mutation fragments to fetch the new data
- [ ] existing form_change records need to be migrated with:
    - [ ] a migration function that goes through every existing revision, grabs the milestone reporting requirements and creates a new form_change for each of these - and delete (archive) the form_changes for `reporting_requirement`, `payment` and `milestone` tables.
    - [ ] tests for that migration function
- [ ] add the funding_agreement form to the list of database form in the server side validation plugins
- [ ]
- [ ] fix dev data, potentially
- [ ] tests for  react form and summary components need to use the same json schema as is deployed to the database.
- [ ] `commit_form_change_internal` should use a custom handler for the funding agreement form
- [ ]  tests for `handle_funding_Agreement_form_change_commit`
- [ ] create_project_revision might need refactoring
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
@pbastia - is this the same as #1171?

**Comment by pbastia** [comment]
@LindsayMacfarlane yes! Thanks for catching that. Zenhub showed me an error "could not create the issue", and I clicked the create button again. I guess it worked anyways ;)
Closing this extra one.
