### ISSUE TITLE
As a CIF user, I want to see a relevant message when I log in and I don't have any roles assigned, so I know who to ask to get access

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1172]
#### Description:

The "guest" dashboard shows a blank page with no information, giving the user the impression that something went wrong. We should display a message a long the lines of "Guest access - ask your administrator to grant you access"

#### Finalized wireframe
[Figma Link](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=6391%3A302&t=LQhnU1Qn7tevySM4-1)

#### Acceptance Criteria:

Given I am a new CIF user
When I log in to the system
And I don't have any permissions granted to me
Then a message is displayed telling me what I need to do

#### Development Checklist:

- [x] Implement message
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

#### Definition of Ready (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

#### Definition of Done (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
@LindsayMacfarlane @nanyangpro we might need business area input for the wording?

**Comment by LindsayMacfarlane** [comment]
Thanks for flagging @pbastia. @nanyangpro - is there common messaging that other teams use for this scenario? Another question - can someone from the program area be given the role to assign access or does it need to come through the team?

**Comment by pbastia** [comment]
@LindsayMacfarlane right now it needs to come through the team - although I don't see why we couldn't grant this to someone from the business area and give them the little bit of training on how to do that

**Comment by nanyangpro** [comment]
Good call, @pbastia and @LindsayMacfarlane - I support involving the business area for suggesting the wording.
May I get a complete list of all current roles in the system? @pbastia

**Comment by pbastia** [comment]
we currently have the following roles: 
- cif_admin
- cif_internal
- cif_external
- cif_guest

we only use cif_admin and cif_internal at the moment

**Comment by suhafa** [comment]
[Wireframe here](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=6391%3A302&t=LQhnU1Qn7tevySM4-1)

**Comment by LindsayMacfarlane** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1172?planning-poker) with Zenhub @dleard @gurjmatharu @mikevespi @pbastia @Sepehr-Sobhani

**Comment by Sepehr-Sobhani** [comment]
This has been merged but not deployed to dev yet!

**Comment by dleard** [comment]
@Sepehr-Sobhani this has now been deployed to dev

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani! I tested in Dev and can confirm the message is displayed and that I was able to select the ggircs email address and successfully send an email.
