### ISSUE TITLE
Project Revision Discard is not working [7]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1186]
Describe the Bug:

When we have an in-progress revision we are not able to discard the revision and it raises an error. This is because now we have a custom mutation to delete project revisions rather than the postgraphile one so the input parameter has changed.

Probability (how likely the bug is to happen, scored from 1-5):4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
create a new project or edit an existing project -> go to submit changes page -> hit discard project revision button -> hit proceed -> Error is there :)

Screenshots:
```
{
    "errors": [
        {
            "message": "Variable \"$input\" got invalid value { id: \"WyJwcm9qZWN0X3JldmlzaW9ucyIsMjUxXQ==\" }; Field \"revisionId\" of required type \"Int!\" was not provided.",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ]
        },
        {
            "message": "Variable \"$input\" got invalid value { id: \"WyJwcm9qZWN0X3JldmlzaW9ucyIsMjUxXQ==\" }; Field \"id\" is not defined by type \"DeleteProjectRevisionInput\".",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ]
        }
    ]
}
```
![Screen Shot 2022-11-17 at 1.43.10 PM.png](https://images.zenhubusercontent.com/6243a3ea8726850c1675becd/2ff3c31f-9897-46f5-bed0-d0ae8691110d)

**Comment by pbastia** [comment]
This is a good first issue for relay things - it'll prompt questions that the team can answer

**Comment by LindsayMacfarlane** [comment]
Thank you @gurjmatharu. Tested this morning in dev and was able to recreate the error (see below):
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/ce73d00b-3e48-4001-9273-80f796e7b864)

**Comment by gurjmatharu** [comment]
This was fixed in with #980

**Comment by LindsayMacfarlane** [comment]
Hi @gurjmatharu - I'm still able to recreate the error:
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/975db982-4f23-4396-a059-51c86e60410e)

**Comment by LindsayMacfarlane** [comment]
Tested again and it works now :) Thank you @gurjmatharu!
