### ISSUE TITLE
Post Workshop Knowledge Capturing

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#12]
Following the CIF Inception Workshop on Sep.9, this ticket aims to ensure information captured in the workshop is categorized and saved in our organizational memory.

Acceptance Criteria:
- [x] Put results from [Menti](https://www.menti.com/vanjco7rhq) into [Inception Workshop - Sep 9](https://miro.com/app/board/o9J_lxg8ELA=/) Miro
- [x] Combine stakeholder section with [previous stakeholder map](https://miro.com/app/board/o9J_l6EhGNw=/?moveToWidget=3074457361645077182&cot=10) from Aug. 30, now all fully captured [here](https://miro.com/app/board/o9J_lFm_59I=/?moveToWidget=3074457364282614091&cot=14)!
- [x] Group ideas from Exorcise the Demons activity
- [x] Clean up Team Agreements to be able to revisit (& refine if desired) at later sessions
- [x] Save Green Team and Pink Team process maps in CIF Internal Users Teams channel

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton ! I always this part of the process where we can start to group, theme and identify potential problem statements.
