### ISSUE TITLE
Plan for Defining CIF OKRs

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#121]
Following the[ Research Metrics Facilitation ](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/24)ticket, we will work with CIF decision makers to iron out our objectives & key results.

Once we have our OKRs, we can identify what data points we can collect to measure these goals.

**Acceptance Criteria:**
- [x] Create plan of attack to build out OKRs with Taylor/Matt
- [x] Get feedback on plan from Taylor

**Comment by rajpersram** [comment]
Here are some ideas that come to mind around OKRs which will require ongoing measuring:

1. Decrease the amount of time spent onboarding new employees into the CIF Project management tools environment
2. Decrease the number of touchpoints for internal users to manage a project
3. Reduce the amount of time spent on client support (tickets, calls, etc). 
  a. increase transparency with client on project status

We should reference the Problems Identified frame in the Miro board, CIF User Story Mapping.
