### ISSUE TITLE
As a CIF user, I want to see calculated payment amounts on the Emissions Intensity Report

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1210]
#### Description:

[Formula with examples](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EcXm1DnetBZNgFOkakDR_IEB1RS8r51PTHqH2h4C5L6URw?e=RbiNV2) - Please open it with the Word app instead of browser for formatting and better readability.

Figma Design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=5872%3A434

Currently, we have "Holdback Payment Amount" and "Holdback Payment Amount (Adjusted)" fields on the Emissions Intensity Report form. They are not accurate enough, which was reported confusing during previous user tests. Instead, we should replace them with the following read-only calculated values:

- **Maximum Performance Milestone Amount**
![image.png](https://images.zenhubusercontent.com/5e3b4990c0f4cb9e2c9b1b1e/21b4cc26-d354-41d2-b43a-0ae4a9f9bcb3)
- **Actual Performance Milestone Amount**
![image.png](https://images.zenhubusercontent.com/5e3b4990c0f4cb9e2c9b1b1e/1a0ace3d-f9bb-41c5-8736-ffad88a2aeae)

In terms of the **Payment Percentage of Performance Milestone Amount (%)** field, we currently calculate it referring to the “Table 1: Lookup Table for Payment Percentage” in Schedule G. However, the CIF team has update it with the following formula:
![image.png](https://images.zenhubusercontent.com/5e3b4990c0f4cb9e2c9b1b1e/78db0519-808a-4c8f-ab0e-d3910eb3fb44)

#### Acceptance Criteria:

Given I am on the Emissions Intensity Page
When I am viewing the fields
Then I do not see Holdback Payment Amount or Holdback Payment Amount (adjusted) fields

Given I am on the Emissions Intensity Page
When I am viewing the fields
Then I can see a **Maximum Performance Milestone Amount** field
And the field shows the correct value using the calculation in this card

Given I am on the Emissions Intensity Page
When I am viewing the fields
Then I can see an **Actual Performance Milestone Amount** field
And the field shows the correct value using the calculation in this card

Given I am on the Emissions Intensity Page
When I am viewing the fields
Then I can see an **Payment Percentage of Performance Milestone Amount (%)** field
And the field value is derived from the calculation in this card, not the database table

#### Development Checklist:

- [x] Remove the holdback fields
- [x] Add a read-only field for **Maximum Performance Milestone Amount**. The computed_column `holdback_amount_to_date` will return the sum of all holdbacks.
- [x] Add a computed_column for **Payment Percentage of Performance Milestone Amount (%)** (form_change_payment_percentage) using the above calculation
- [x] Add a read-only field for **Payment Percentage of Performance Milestone Amount (%)** to the page using the computed_column
- [x] Add a read-only field for  **Actual Performance Milestone Amount**, this calculation can be done on the front-end using the other 2 fields and the calculation described above.
- [ ] Meets DoD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by dleard** [comment]
@nanyangpro We looked at this in refinement & were wondering why it had attn: developer/PO tags on it & if it was ready to be refined?

**Comment by dleard** [comment]
ready for refinement

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1210?planning-poker) with Zenhub @BCerki @gurjmatharu @mikevespi @pbastia @sam-warren @tmastrom

**Comment by tmastrom** [comment]
@nanyangpro What should the fields show if the user needs to add more information for these fields to be calculated? Right now it is just '0' but it could be good to have a message telling the user that not enough info is present.

**Comment by BCerki** [comment]
> @nanyangpro What should the fields show if the user needs to add more information for these fields to be calculated? Right now it is just '0' but it could be good to have a message telling the user that not enough info is present.

I set the default message for the `CalculatedValueWidget` to "This field cannot be calculated due to lack of information now." in another PR

**Comment by nanyangpro** [comment]
Great call, thanks @tmastrom! @BCerki and I had related discussions last week, and we agreed on displaying a generic message (as quoted above) in such scenarios for now. 

_Going forward, we may tailor messages for each field, so that users are informed what information is required for the calculation, but this is for sure a future enhancement with lower priority now. Hope it's helpful!_

**Comment by LindsayMacfarlane** [comment]
Thank you @gurjmatharu! Tested in Dev:
- Confirm that fields related to the holdback amount have been removed
- Fields related to payment %, max performance and actual have been added

**Comment by LindsayMacfarlane** [comment]
Thank you so much @gurjmatharu for walking me through the math :) We will want to make sure the program area tests this out multiple times.
