### ISSUE TITLE
Tech Debt: Update NextJS

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1222]
###Description of the Tech Debt###

NextJS's version is a bit behind and may be lacking some functionality that would help with some other bugs and tech debt (#1152, #751)

Todo:
Update NextJS to v13.0.5

**Comment by Sepehr-Sobhani** [comment]
I did a bit of exploration on this ticket; at this moment we can update the version to `13.1.1` but it requires react version 18 which changes so many other things subsequently (including unit tests)

**Comment by Sepehr-Sobhani** [comment]
@LindsayMacfarlane FYI, This has been merged but it's taking a bit of time to get deployed, so I'm keeping this here until the actual deploying is complete.

**Comment by Sepehr-Sobhani** [comment]
@LindsayMacfarlane this is deployed! nothing to test though as it was only bumping packages and changing the code base to work as it was working before.
