### ISSUE TITLE
Design workflow for enter immutable fields (Funding Stream & RFP Year)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1223]
#### Describe the task

**Funding Stream** and **RFP Year** are immutable once entered and saved.

Workflow need to be designed for entering them upon creation of a project.

#### Acceptance Criteria

- [x] Visualize envisioned workflow with design/prototype in Figma
- [x] Review and refine with the developers
- [x] Review and refine with the CIF team
- [x] Link the validated workflow in #1075

**Comment by nanyangpro** [comment]
This design ticket is created and pulled into the current sprint (Nov 28 - Dec 9, 2022) to unblock #1075 for upcoming sprints as discussed with @LindsayMacfarlane.

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket is ready for you to review and can be closed with:

-  Multiple options of envisioned workflows prototyped, discussed, and refined with the developers.
- The links to the prototypes of the validated and selected workflows for both [EP](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=5936%3A294&node-id=5936%3A1172&viewport=-589%2C1434%2C0.25&scaling=scale-down&starting-point-node-id=5936%3A1172&show-proto-sidebar=1) and [IA](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=5936%3A294&node-id=6008%3A2837&viewport=-589%2C1434%2C0.25&scaling=scale-down&starting-point-node-id=6008%3A3069&show-proto-sidebar=1) added in #1075 to unblock the implementation.

**Comment by LindsayMacfarlane** [comment]
Thank you so much for your quick work on this @nanyangpro ! I really appreciated your demo and being able to get a decision from the CIF team at our Sprint Review. Ultimately, the decision was to move forward with Option #2 based on:
- usability (e.g., the CIF team liked the simplicity of having only 1 confirm button to select)
- Ease of implementation (i.e., Dylan indicated that not displaying the task list would be simpler and less complicated to implement)
