### ISSUE TITLE
additional_funding_source form_change records persist after removing the funding agreement[5]

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1226]
Describe the Bug:

Additional funding sources are children of the funding agreement, so they should be removed if a funding agreement is archived or deleted. Currently they persist in the database after removal. This workflow is highly unlikely, but will cause some confusion in the data if done (how do we have additional funding sources for a non-funded project?).

To fix this we need to iterate over all the related additional_funding_source form_change records and archive/delete them in the `discard_funding_parameter` mutation.

Probability (how likely the bug is to happen, scored from 1-5): 1

Effect (how bad the bug is when it does happen, scored from 1-5): 4

Steps to reproduce the behaviour:

- create a project with a funding agreement & add additional funding sources
- remove the furnding agreement
- see in the database that the related additional_funding_source form_change records persist

**Comment by mikevespi** [comment]
This is an odd one to QA so I've written out what I think is the easiest way to verify:
- remove the funding agreement from a project with additional funding sources
- create a new amendment on that project, adding a funding agreement (but not manually adding additional funding sources!) 
- make sure that this newly added funding agreement does not show any additional funding sources.

(Previously, this process would end up with the "old" additional funding sources showing up on the  fresh funding agreement.)
- make  sure that additional funding sources don't get automatically populated

**Comment by LindsayMacfarlane** [comment]
Thanks @mikevespi, tried testing out and still encountered a bug. I added in funding source, then tried to remove, but couldn't submit the change. Probably user error, but happy to walk you through what I'm experiencing :)

**Comment by mikevespi** [comment]
Oh no! I'll pull it back in and see what's going on, thank you for the catch @LindsayMacfarlane !

**Comment by mikevespi** [comment]
@LindsayMacfarlane I can't seem to reproduce it, so on Monday let's hop on a call and you can walk me through it :)

**Comment by Dianadec** [comment]
Sprint planning notes: blocked by lindsay's review

**Comment by Dianadec** [comment]
note from Dylan: this will go away after the refactor

**Comment by LindsayMacfarlane** [comment]
No longer experience error I identified above. Based on that and the comment above, @mikevespi - is it safe to say this one is resolved and I can move to the accepted by PO column?

**Comment by mikevespi** [comment]
@LindsayMacfarlane it is! Thank you for double checking, moving the card now.
