### ISSUE TITLE
Can't select Revision Type in TEST Environment

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1228]
#### Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

#### Steps to reproduce the behaviour:
- Go to TEST
- Select an existing project and go to create a new revision 
- Try to select Revision Type > user can't select any of the radio buttons

#### Screenshots:
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/8048533b-1f85-4e98-bfe8-d770c363dd9c)
Additional information:

- Browser: Chrome
- Version: [e.g. 22]

#### Additional context:
- This bug doesn't exist in Dev

**Comment by mikevespi** [comment]
@LindsayMacfarlane I just tried this in test and the radio buttons work for me. I assume since it wasn't an issue in dev, that the fix just hadn't been released yet when this ticket was made. Can you please confirm you aren't still having the problem? If not, I'll close the ticket.

**Comment by mikevespi** [comment]
No problem!
Closing issue as it has been fixed in another PR.
