### ISSUE TITLE
Add in decimal to the total project value field on the "Budget, expenses and payments" form.[5]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1236]
###Description of the Tech Debt###

Based on this comment: https://github.com/bcgov/cas-cif/issues/942#issuecomment-1335615607

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |     1  |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |  1     |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |    1   |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |    1   |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |     1  |
| TOTAL SCORE:                                                                                                                  |       | 5      |

**Comment by LindsayMacfarlane** [comment]
Thank you @mikevespi! Tested and it looks good :)
