### ISSUE TITLE
Update docker/setup-buildx-action to v2

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1241]
We are getting warnings that `set-output` and `save-state` will be deprecated soon in our build-image steps. `docker/setup-buildx-action@v1` is what is throwing these warnings. It looks like updating to v2 should fix the issue. I saw a closed PR in https://github.com/docker/setup-buildx-action that removed them.

Deprecation notice: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by LindsayMacfarlane** [comment]
Thank you @gurjmatharu! I don't think there is anything I need to test in relation to this ticket, so moving to approved. Cheers :)
