### ISSUE TITLE
As a CIF administrator, I want to add decimal places to the province's share %, so that I can track a more accurate number

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1247]
#### Description:

The province's share percentage currently only accepts round numbers.

#### Acceptance Criteria:

Given I am a CIF administrator
When I create or edit a project's 'Budgets, Expenses and Payments' form
Then I can enter decimal places for the Province's Share Percentage field

#### Development Checklist:

- [ ] The `uiSchema` should have a `numberOfDecimalPlaces: 2` set for that field
- [ ] Meets the DOD

#### Notes:

- Received confirmation from JF (January 11) that the Province's Share % does need to allow for decimal values: "We don’t always have decimal places in the funding agreements, but do occasionally if required... We would need that to reflected in the system in order to make accurate payments."
- Email with FA examples can be found:
https://bcgov.sharepoint.com/:f:/t/00608-ScrumTeam/EsJfoJEPeHJAjfNw3LScBO8BufQRB7xzz10MrfWp5R827Q?e=WweaDR

#### Definition of Ready (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

#### Definition of Done (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

**Comment by LindsayMacfarlane** [comment]
Pulling this back into the backlog. I'd like us to revisit our notes and see what we had previously learned from the CIF team. Would also be good to quickly follow up with JF.

**Comment by LindsayMacfarlane** [comment]
@suhafa @nanyangpro - I went through our previous tickets and Figma file to see if we had earlier feedback from the CIF team regarding allowing decimal places (or not) for the Province's Share Percentage. Do either of you have additional notes that speak to this field? Once I hear back, I can reach out to the Ops Team to get additional clarification/feedback before we implement any changes. Thanks!

**Comment by suhafa** [comment]
@LindsayMacfarlane I've looked through our usability testing notes, no dice. @nanyangpro might be aware of this though!

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1247?planning-poker) with Zenhub @BCerki @gurjmatharu @mikevespi @pbastia @sam-warren @Sepehr-Sobhani @tmastrom @dleard

**Comment by LindsayMacfarlane** [comment]
Hi @sam-warren - double checking - is this ticket in progress?

**Comment by sam-warren** [comment]
@LindsayMacfarlane Not currently - must have self-assigned myself when I moved it into the current sprint. Will remove myself and leave it for anyone to pick up 👌

**Comment by LindsayMacfarlane** [comment]
Thank you @gurjmatharu and @Sepehr-Sobhani. Approved.
