### ISSUE TITLE
Create `contact` and `contact_project` table

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#125]
#### Describe the task

Create a table to house the contact data

#### Acceptance Criteria

- [ ] the `contact` table exists
- [ ] the `contact` table has a `given_name` column
- [ ] the `contact` table has a `family_name` column
- [ ] the `contact` table has a `email_address` column
- [ ] the `contact` table has a `phone_number` column
- [ ] the `contact` table has a `phone_number_ext` column
- [ ] the `contact` table has a `position` column
- [ ] the `contact` table has a `comments` column

- [ ] the `contact_project` table has two `project_id` and `contact_id` foreign keys

**Comment by matthieu-foucault** [comment]
To be revised following discussion with the CIF team. Contacts should be associated with an operator (or maybe multiple operators?)
