### ISSUE TITLE
Clarify and confirm Funding Agreement changes and potential impacts on us

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1253]
#### Describe the task

Jesse and Amanda advised that the Funding Agreement (FA) template has been updated for 2023 application intake. A changed decision was delivered to the team on Wednesday, Jan 11th, 2023: **the CIF team won't request for proposal this year (2023). Instead, they will allocate the funding they have to waitlisted applications from previous years.** However, the needs for us to clarify and confirm the scope and impacts of the potential FA changes remain valid. One of the major changes is the budgeting/payment structure.

This ticket is to further investigate and understand:

- What the FA changes are (besides the payment structure)
- What the CIF team's vision/solution in practicing the changes
- If and how will the changes be applied to funded projects from the waiting list
- What risks/opportunities the CIF team envision
- What support (enhanced/new features) is needed from us and how we plan to address them

#### Acceptance Criteria

- [x] Draft questions as guided by the goals above
- [x] Schedule discussion sessions with CIF to clarify unclearness and identify the next steps and timeline if required
- [x] Reach out to CIF for the new FA template (if it's ready)
- [x] Deliver and document findings with the team

**Comment by nanyangpro** [comment]
According to @LindsayMacfarlane's updates from the stand-up this morning, the CIF team won't request for proposal this year (2023). Instead, they will allocate the funding they have to waitlisted applications from previous years.
This ticket was originally created for "investigate impacts of the Funding Agreement changes for 2023 application intake". While the needs for us to clarify and confirm the scope and impacts of the potential FA changes remain valid, this ticket needs to be repurposed according to the decision update above. Detailed updates to be expected in the ticket description.

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket is ready for you to review and close with
- Organized notes documented in [Miro](https://miro.com/app/board/uXjVP1NVDKE=/?moveToWidget=3458764543531640088&cot=14)
- Findings summarized and communicated back to the team
- The new FA templates for both EP and IA uploaded to the CIF Internal Users channel in MS Teams with major changes highlighted in Miro
  - [FA_Template EP- 2022 Final.docx](https://bcgov.sharepoint.com/:w:/t/00608-CIFInternalUsers/EVklfwJCMJZCp4k_MRfrkQEBTZGqqw5quVkGJ5g0OEl2ow)
  - [FA_Template IA - 2022 Final.docx](https://bcgov.sharepoint.com/:w:/t/00608-CIFInternalUsers/EY9LHh9zLxVPi__O-bQK0OQBtADUDOJdobthgd-9_Jg0Cg)

**Comment by LindsayMacfarlane** [comment]
Thank you @nanyangpro - it was great to have that conversation with the Ops team and get additional clarification. Please note: I've removed the direct link to the Miro Board given they can be accessed publicly with a url.
