### ISSUE TITLE
Refine the workflows for updating Routinely Updated Fields as discussed in #1166

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1254]
#### Describe the task

To reflect the design decision as agreed upon with @pbastia from the discussion for #1166. 

- The envisioned workflow for updating Routinely Updated Fields needs to be refined for more intuitive user experience, i.e. we should provide visual cues such as text indicator for users so that they are aware that they need to click on the "Update" button to confirm their changes on those fields.
- The workflow for updating the "Pending actions from" field for each revision record should be consistent with the generic workflow for updating Routinely Updated Fields.

#### Acceptance Criteria

- [x] Update the prototypes in Figma
- [x] Sync up with the team
- [x] Address additional input if necessary

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket is ready for you to review and can be closed with

- The updated envisioned workflow for updating Routinely Updated Fields discussed with the team and further refined accordingly.
- The links to the updated prototypes being added in #1158's ticket description.
  - [Generic example 1: for Routinely Updated Fields with Dropdown as front-end component](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=4939%3A685&node-id=5089%3A1414&viewport=-484%2C320%2C0.14&scaling=scale-down&starting-point-node-id=5089%3A1414&show-proto-sidebar=1)
  - [Generic example 2: for Routinely Updated Fields with Date Picker or Text Input as front-end component](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=4939%3A685&node-id=4939%3A1324&viewport=-484%2C320%2C0.14&scaling=scale-down&starting-point-node-id=4939%3A1324&show-proto-sidebar=1)
- The [workflow for updating the "Pending actions from" field for each revision record](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=3989%3A5985&node-id=3989%3A7927&viewport=-674%2C-451%2C0.24&scaling=scale-down&starting-point-node-id=3989%3A7927&show-proto-sidebar=1) refined to be consistent with other Routinely Updated Fields.

**Comment by LindsayMacfarlane** [comment]
Thank you so much @nanyangpro - you always have our users at heart.
