### ISSUE TITLE
Identify and confirm the scope of the proponent-facing portal for 2023 application intake

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1260]
#### Describe the task

Shelby has indicated the need to have a proponent-facing portal/tool **before March 2023** for the CIF team to handle the 2023 application intake (and for the proponents to submit their application). Due to the urgency of it, the developers suggested to have a clearly defined scope of features for this MVP, so that we can plan the most effective solution to address the need.

#### Acceptance Criteria

- [x] Draft a list of required features based on previous discussions with Shelby, Jesse, and Amanda
- [ ] Review, refine, and finalize the feature list engaging the CIF team and us

#### Additional context

- Initial feedback from CIF team in relation to required fields/features for an MVP include: funding stream, funding year, legal name, and allowing for attachments
- Nice to have: auto generation of RFP number
- Question for devs: can we automate funding year for proponents submitting an application?

**Comment by suhafa** [comment]
Ticket #1263, #1265 and #1277 support this ticket's scope

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - According to your updates from the stand-up this morning, the CIF team won't request for proposal this year (2023). Instead, they will allocate the funding they have to _waitlisted_ applications from previous years. While the need for having an external industry-facing portal remains valid (#1253 needs repurposing, #1263, #1265, and #1277 as mentioned by @suhafa above), **the scope of this ticket is not relevant any more and up to you for closing it.** Thanks!

**Comment by LindsayMacfarlane** [comment]
Thank you @suhafa and @nanyangpro - it was great having the mockup to present to the CIF team at our sprint review for feedback and input.
