### ISSUE TITLE
Explore available tools/services/common components to support external user intake

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1262]
#### Describe the task

Existing resource for further exploration:
- CCBC code
- GC Forms
- CHEF

#### Acceptance Criteria

- [x] Meet with CCBC team for a demo
- [x] Review GC Forms
- [x] Review CHEFS
- [ ] Explore MUNI/LGIS (removed into its own ticket. This is low priority)
- [ ] Review and present options to scrum team for feedback

#### Additional context

- Note a meeting has been scheduled with CCBC on December 14th for a demo

**Comment by LindsayMacfarlane** [comment]
Met with CCBC team Product Owner on December 14, 2022 for a demo of their applicant intake portal. Some key takeaways:

- App was built in 5 months and leveraged CIIP/CIF code
- Currently the app has no validation on the front end as there wasn't a lot of fields where validation would be beneficial 
- There are several intake screens related to document upload for form templates (Note: proponents need to first download the templates from the website, complete them and then upload into the system)
- They have an area for contact information to be entered (note: CIF hasn't requested this feature, but could be valuable?)
- Biggest amount of work for our team could be related to the document upload/management. More user research/conversations with CIF team are needed to really understand the basic requirements.

cc @suhafa @pbastia - feel free to add your notes here from today's conversation.

**Comment by suhafa** [comment]
Met with GC Forms CDS team on 22 Dec. Their Github repo can be found [here](https://github.com/cds-snc/platform-forms-client) and you can demo [their sandbox](https://forms-staging.cdssandbox.xyz/). Provinces are not able to use it, and it is limited to Federal Government, so we may not be able leverage this as of now, but it will be good to have on our radar for future work.

**Comment by suhafa** [comment]
A few more CCBC notes to add to your points @LindsayMacfarlane 
- The CCBC team will reach out to the user to correct mistakes, as there is no validation. (I don't know if we would be happy with that outcome as it would create additional work for CIF. Might need to explore that)
- The CCBC app allows for a lot of flexibility: unvalidated fields can be submitted provided to you check a box that acknowledges that you as the user are submitting incomplete data, the user can edit and update the application even after submission until intake closes. After that they can view the submission
- Uploads are limited to not more than 100mb in size with specific file types predetermined, but can again be flexible if need be.

**Comment by LindsayMacfarlane** [comment]
Feedback from January 5, 2023 Sprint Review:

- MH: supports idea of using CHEFS if possible. Also, recently had a conversation with GC Forms regarding using a common repo for this type of functionality between Province and Federal Government.

**Comment by suhafa** [comment]
Scrum Team feedback on CHEFS:
- To decide on using CHEFS, we need to determine all the requirements of the application and validate with CIF first
- to use CHEFS then will be a binary choice, either we go ahead with it or we don't depending on the complexity of the platform
- If we go ahead with CHEFS, we will need to decide if we want to host it on our platform or theirs

**Comment by suhafa** [comment]
@LindsayMacfarlane adding CHES to the AC. Any suggestions for how we could reach out to Donna Coe from LGIS/MUNI?

**Comment by Dianadec** [comment]
Will this be worked on next sprint? @suhafa cc @LindsayMacfarlane

**Comment by LindsayMacfarlane** [comment]
I'm going to pull MUNI out of this ticket as it is a lower more exploratory ticket. I think this ticket can be wrapped up. Perhaps @mikevespi can comment on whether we would use CHEFS later on in development given how we are approaching the first slice? My thought, since we are trying to mirror/reuse what we've built in CIF so far, we probably won't utilize CHEFS at this point...but it is still an option to keep in the back of our minds.

**Comment by mikevespi** [comment]
I'm leaning away from using CHEFS. Since the information the proponents will be able to enter and see is information we already capture in the system, we already have the components we need built. Reusing our existing code has a number of benefits:
- Lower maintenance costs
- One less external dependency, and more control over the apps UI/UX
- Consistent look and feel to the site from both sides
- Since we've already done user research on our processes and designs, it means we're re-leveraging that work as well (I think this is easy to underestimate. Having already gone through iterations of these features means that we can move forward with this portion of the app at a faster pace with a relatively high degree of confidence)

The closer we mirror the internal side, the more value we get out of work already done.
