### ISSUE TITLE
External user journey map

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1263]
#### Describe the task

Create a Roadmap for the external user facing work. We need to uncover who within CIF would be our ally in doing external user engagement. Need to subsequently decide on communication plan, timeline etc

#### Acceptance Criteria

- [x] Ask CIF team if they have the external User Journey mapped out. 
- [x] If not, create one with them (Amanda would be a good point of contact for this) Reach out to the CIF Team to narrow down the scope of External User Portal and confirm the user flow
- [x] Prepare Miro board for workshop
- [x] Prepare Miro board for doing an async review of the workshop
- [x] Prepare meeting invites for a synced conversation on the workshop
- [x] Send out invites
- [x] Review and revise the [CIF Process](https://miro.com/app/board/o9J_lwRsVsQ=/) Miro Board
- [x] Share findings with team in dev/design Sync to brainstorm about the application implementation and high level design ideas (WILL BE DONE ON THURSDAY)
 

#### Additional context

- This ticket was made after closing #941 work
- Or here

**Comment by LindsayMacfarlane** [comment]
Feedback from January 5, 2023 Sprint Review:
- There is no existing user journey map

**Comment by suhafa** [comment]
External user journey mapping conducted with CIF team on Jan 16. It was a productive conversation. Some next action items include reaching out to Megan and the Tech team for their input on the journey map, after organizing the information uncovered during the first session.

**Comment by suhafa** [comment]
External user journey mapping conducted with CIF team on Jan 16. It was a productive conversation. Some next action items include reaching out to Megan and the Tech team for their input on the journey map, after organizing the information uncovered during the first session.

**Comment by suhafa** [comment]
External user journey mapping conducted with CIF team on Jan 16. It was a productive conversation. Some next action items include reaching out to Megan and the Tech team for their input on the journey map, after organizing the information uncovered during the first session.

**Comment by suhafa** [comment]
External user journey mapping conducted with CIF team on Jan 16. It was a productive conversation. Some next action items include reaching out to Megan and the Tech team for their input on the journey map, after organizing the information uncovered during the first session.

**Comment by suhafa** [comment]
External user journey mapping conducted with CIF team on Jan 16. It was a productive conversation. Some next action items include reaching out to Megan and the Tech team for their input on the journey map, after organizing the information uncovered during the first session.

**Comment by suhafa** [comment]
External user journey mapping conducted with CIF team on Jan 16. It was a productive conversation. Some next action items include reaching out to Megan and the Tech team for their input on the journey map, after organizing the information uncovered during the first session.

**Comment by suhafa** [comment]
[Miro board](https://miro.com/app/board/uXjVP0UonjU=/) updated and organized. From our discussion, features have been identified and listed in the board. Findings can be reported for the upcoming dev design sync. @LindsayMacfarlane after your review this issue is good to be closed! c:

**Comment by LindsayMacfarlane** [comment]
Thank you @suhafa ! I had to jump out of the dev/design sync session, so I'm assuming this was discussed? As a side note, I removed the link to the Miro Board above as we are trying not to link out to board that can be public.

**Comment by suhafa** [comment]
@LindsayMacfarlane we discussed the findings from both the sessions Nan and I had over the course of this week, but the Miro board itself was not reviewed by the team in detail since the higher level concerns were discussed already. I check off the last point. Feel free to close this ticket! c:
