### ISSUE TITLE
Outreach plan 

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1264]
#### Describe the task

This ticket is to cover planning of how we want to approach external users, when, and what formalities need to be considered before doing so. This may help us present a case for doing the research and speaking with external operators.

Feb. 9 update:
- Goal to do virtual 1:1's with operators before the CPI workshop.
- Need to coordinate with the CPI workshop planning (Jess K.) to ensure that we have a spot to engage with operators.
- At CPI, suggest to only have 30 mins with each operator if we are doing individual testing, or 1 hour if we do a group testing session.

#### Acceptance Criteria

- [x] acquire list of contacts we can speak to for Phase 2 of research plan and Phase 3 (see 'Miro: CIF External User Research' to view phases)
- [x] prepare 2 draft emails for 1:1's and CPI workshop 
- [x] Reach out to contacts for a 1:1 prior to CPI Workshop via email
- [x] Send out invites to contacts for CPI Workshop (if applicable)
- [x] Send out consent forms
- [x] Rework Prototypes for session
- [x] Rework Script for session
- [x] Update Observer Notes

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Dianadec** [comment]
@LindsayMacfarlane have there been previous tickets about related external user research that we could pull from to use info as acceptance criteria to be able to refine this card more? Are we waiting for more info before we can refine this card?

**Comment by Dianadec** [comment]
@LindsayMacfarlane I added some info to the description of this card based on our conversations about CIF ext research planning.

**Comment by nanyangpro** [comment]
Summarizing my responsibilities during the testing sessions below as discussed with @suhafa: 
- Observe user behaviours and  monitor the chat
- Take notes [here in Miro](https://miro.com/app/board/uXjVOlTUwNY=/?share_link_id=624655803966)
- Ensure we don't go over time for each section as we time-boxed [here](https://can01.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fbcgov.sharepoint.com%2F%3Aw%3A%2Fr%2Fteams%2F00608-CIFInternalUsers%2FShared%2520Documents%2FCIF%2520Internal%2520Users%2FExternal%2520App%2FUsability%2520Test%2520Script.docx%3Fd%3Dw2c87daa957184765a8e1dbb22672d9cf%26csf%3D1%26web%3D1%26e%3DS0QjeW&data=05%7C01%7CNan.1.Yang%40gov.bc.ca%7C69ef85a923b44022167508db44f5b3f6%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638179595405955123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xtG72P5MQDFrflpwJbzn6IQhAT2qDluj%2B2075IT7DCQ%3D&reserved=0)

**Comment by pbastia** [comment]
Outreach plan was completed...and executed! Thank you @suhafa @nanyangpro !
