### ISSUE TITLE
As a CIF developer, I want a smooth hotfix strategy to be clearly documented, so it isn't a lot of work to figure it out every time

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1269]
#### Description:

Deploying a hotfix directly to the main branch is a bit of a challenge when we try to deploy it, and causes a very large rewrite of history.
This card is about writing a playbook with simple steps on how to do this.

A process to explore could be:
1. make a hotfix branch off of main
1. bring -test to the -prod state (both db schema and data)
1. test the upgrade path
1. deploy hotfix to prod
1. rebase develop to include the hotfix (without a PR? Or merge main into a PR?) 
1. fix all the pending PRs (rebases, lots of commits will be there)

#### Acceptance Criteria:

Given I am a CIF developer
When I have an urgent patch to deploy to prod
Then I shouldn't have to halt feature merge to develop

Given I am a CIF developer
When I have an urgent patch to deploy to prod
Then I can deploy it directly to test

Given I am a CIF developer
When I have an urgent patch to deploy to prod
Then I can resume merging features to test (then to prod) without collisions

Given I am a CIF developer
When I have an urgent patch to deploy to prod
Then I can follow a clear process outlined in the dev documentation

#### Development Checklist:

- [x] Explore alternatives
- [ ] Try them out in a local mock git repo
- [ ] Make sure to pair on this one and gather feedback from the team 

#### Definition of Ready (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

#### Definition of Done (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

- This card should not be completed solo. Discussions amongst developers will be needed.
- No more than 2-3 days should be spent on this ticket

**Comment by pbastia** [comment]
@LindsayMacfarlane instead of estimating this card, I suggest limiting the effort spent to 3 or 5 points. what do you think? @dleard ?

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1269?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @mikevespi @sam-warren @Sepehr-Sobhani

**Comment by dleard** [comment]
We have a path for this (described in the ticket). It's just not a super smooth one and there may be better alternatives. I'm not against estimating this with points, but maybe it should be timeboxed to a couple of days?

**Comment by LindsayMacfarlane** [comment]
I support timeboxing.

**Comment by dleard** [comment]
A solution floated for #670 could be a part of this flow. Probably a good idea to do 670 first

**Comment by dleard** [comment]
@pbastia I moved this straight to accepted since there's nothing to test. Just tagging you in case you wanted to take a look at the documentation.

**Comment by pbastia** [comment]
Thank you! The documentation looks great, awesome work
