### ISSUE TITLE
Research and identify best practices for user messaging 

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1270]
#### Describe the task

CIF has complicated and non-standardized business concepts/terminologies, which is confusing and adds extra difficulties in onboarding new users. For these fields, besides labelling, we want to provide additional details/context to guide the users. Graphical UI elements have been brought up many times during previous user interviews, usability test, etc. However, the team has held mixed feelings towards such elements, mainly in concern of accessibility.

To support informed decision-making, research is required identifying the best practices for user messaging. For example, tooltips, text on screen, etc.

#### Acceptance Criteria
- [ ] Investigate UX/UI resources from the internet
- [ ] Reach out to other UX Designers to understand common practices in the BC Government and understand what/how other teams are implementing user messaging within their applications
- [ ] Propose decision based on the research outcome with reasoning documented and discussed with the team

#### Additional context

**Comment by nanyangpro** [comment]
Thank you for suggesting working on this ticket, @LindsayMacfarlane. FYI, I've removed the Backlog Refinement label from it since it's now refined with additional details. But feel free to take a look and improve the goal/AC of it as you see fit.

**Comment by suhafa** [comment]
@pbastia suggested reaching out to other teams like BC Parks, CCBC and the UX Guild to get some feedback on how they have tackled similar problems

**Comment by nanyangpro** [comment]
Closed as outdated (with re-usable tooltip component built).
