### ISSUE TITLE
Amendments disappear from Tasklist [5]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1272]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
"After making a revision of any type, the "Amendments & Other Revisions" tab in the task list disappears and I have to exit the project, then re-find it in the project list to continue with updates or just to see the amendments list again and confirm that the changes were captured."

Screenshots:
https://www.loom.com/share/942ac5996197424f88831dba7744205c

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
Based on these two tickets I think this is not a bug: 
https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1119
https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1122
Although this is not a clear flow to get to that page.

**Comment by BCerki** [comment]
Changed to a user story: https://github.com/bcgov/cas-cif/issues/1284
