### ISSUE TITLE
Applicant intake design

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1277]
#### Describe the task

Wireframe initial design related to applicant intake based on feedback from CIF team.

#### Acceptance Criteria

- [x] Create information architecture based on initial learning/feedback
- [x] Create a new Figma file
- [x] Conduct a workshop session to brainstorm with CIF and Scrum team to narrow down the scope of External User Portal
- [x] Create lo-fi wireframes 
- [x] Present to scrum team to iron out technicalities and feasibility of work
- [x] Map out what fields on internal side would need to be populated (being taken care of in #1159)
- [x] Update remaining wireframes
- [x] Present to Scrum Team in Dev/Design Team

#### Additional context

- Ticket might need to be split in three - workshops + design + iterations of design
- Or here

**Comment by LindsayMacfarlane** [comment]
FYI @suhafa - I've created this ticket to capture wireframe/design

**Comment by LindsayMacfarlane** [comment]
@suhafa created two quick low-fi mockups to present at the January 5, 2023 Sprint Review in order to get initial feedback from the CIF team and sprint review participants. Feedback included:

- JF preferred the design where there was an individual file upload per standard template.
- Would like to see validation (if possible), even if it as simple as ensuring there is a file uploaded per template
- JF: Recommends adding in a field for project name. A proponent can submit multiple applications, so having the project name would help differentiate which projects everything is associated to.
- Auto generation of RFP number continues to be a nice to have/lower priority. They can continue to use their excel form to generate the RFP number and manually input into the system for the time being, especially if this adds complexity.
- Depending on funding stream selected, the standard templates will change.
- Funding year - this can be pre-populated given a proponent can't submit for past or future funding years.
- There is no current external user journey map (*note: The CPI workshop may present a good opportunity to validate our assumptions on the user journey*)
- JF recommends we also look at the Local Government Information System (LGIS) through MUNI to see if there are opensource/reusable components and/or lessons learned we can leverage.

**Comment by LindsayMacfarlane** [comment]
@suhafa - I added into the acceptance criteria the need to map out what fields on the internal side should/would need to be populated based on a users submission. For example, my assumption would be that project status would automatically be 'proposal submitted', but that would be another question for the CIF team.

**Comment by suhafa** [comment]
@LindsayMacfarlane thank you for summing the notes up so well! As for mapping out fields that is a good suggestion. I had a question on similar lines for the devs as to how how might we pull data from external app into internal app? Is it an easy link, and therefore possible to have applications created as projects once finalized in the internal facing app (with pre-populated fields) This seems to be a great solution for reducing work of **collaboration** between the internal and external users however will need some dev input on feasibility and effort. Can we in the future enable more form uploads for selected projects who will need to upload milestone reports and others throughout the project life cycle? Tagging @pbastia for any initial insights he may have to add.

**Comment by suhafa** [comment]
@LindsayMacfarlane this ticket's work is completed! Next steps include creating epics and user stories as part of the first slice of work C:

**Comment by LindsayMacfarlane** [comment]
Thank you so much @suhafa! I'm excited for the next steps with creating epics and starting implementation. Also excited to refine based on taking a release planning approach :)
