### ISSUE TITLE
As a project coordinator, I want to select the operator when creating a project

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#128]
#### Description:
See #69 for wireframe

this includes creating the operator table and adding the search ui in the project creation page

#### Acceptance Criteria:
Given I am on the create/edit project page
When I select an operator from the dropdown
Then that operator is assigned to the project (as a pending change)

#### Development Checklist:
database
- [x] the `operator` table exists
- [x] the `operator` table has a `legal_name` column
- [x] the `operator` table has a `trade_name` column
- [x] the `operator` table has a `bc_registry_id` column
- [x] the `project` table has a foreign key to the `operator` table
front-end
- [x] a dropdown to select an operator exists
- [x] the dropdown pares down possible selections as the user types
- [x] on selecting an operator, the operator's legal name & bc registry id is shown in the dropdown and the trade name is shown below the dropdown.
- [x] on selecting an operator the record is saved as a 'pending' change in the form_change table (foreign key to operator on the project table).

#### Notes:
- The list of operators will likely be pre-populated from the swrs data, but that is for a later date. Some dev data should be added to the operator table to make this functional in dev.

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/128?planning-poker) with ZenHub @pbastia @AlexZorkin

**Comment by LindsayMacfarlane** [comment]
Thank you for the demo @dleard - I like that as I start typing an operator name the list gets more refined.
