### ISSUE TITLE
Design system and usability testing planning

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1283]
#### Describe the task

This captures the desire to plan out how the design team would like to tackle creating a design system and do some usability testing internally to improve our app's usability.

#### Acceptance Criteria

- [ ] Brainstorm on Miro, by mapping out our pain points, how we would like to organize this and how to share responsibility depending on capacity
- [ ] Identify key metrics we would like to measure usability on 

#### Additional context
Some resources 
- https://uxdesign.cc/usability-heuristic-frameworks-which-one-is-right-for-you-1962387b7cc
- https://www.usability.gov/how-to-and-tools/methods/usability-evaluation/index.html
- https://www.nngroup.com/articles/how-to-conduct-a-heuristic-evaluation/
- https://www.nngroup.com/articles/cognitive-walkthroughs/
- https://users.soe.ucsc.edu/~srikur/files/lect7.pdf
- https://uxdesign.cc/predicting-user-interfaces-the-klm-d25bb3a2f2d5
- https://www.researchgate.net/publication/253713707_Measuring_Cognitive_Load_to_Test_the_Usability_of_Web_Sites

**Comment by suhafa** [comment]
@nanyangpro hey Nan! The barebones of the ticket are here, feel free to go in and edit it as you deem fit

**Comment by nanyangpro** [comment]
Closed as outdated. Confirmed by @pbastia, the current priority is to wrap up CIF (internal app) design & development, and shift focus/capacity to OBPS.
