### ISSUE TITLE
As a cif user, I can assign a project status when I create a project

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#129]
#### Description:
We need to be able to set the project phase upon creation of the project, to any existing project phase within that rfp, to make data intake possible for any ongoing project.

See #69 for the wireframe

#### Acceptance Criteria:

Given I am on the project creation page
When I assign a funding stream to the project
Then I see a dropdown with the project statuses associated to that funding stream

Given I am on the project creation page
When I assign a funding stream to the project
Then the dropdown with the project statuses is set to the default phase

Given I am on the project creation page
When I commit the project
Then the project is associate with that project status

#### Development Checklist:

---Database
- [x] there is a project_state table with the following columns:
- id: int
- name: varchar(1000)
- description: varchar(1000)
- funding_stream_rfp_id - foreign key to the funding_stream_rfp table
- [ ] project_status table passes the style tests
- [ ] the `project` table has a `project_status_id` column

---Frontend
- [x] when the dropdown changes, the changes are persisted to the `form_changes` table
- [ ] when the project is committed, the `project_phase_id` value is set

<br> 

- [ ] meets the DOD

#### Personas:
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/129?planning-poker) with ZenHub @AlexZorkin @pbastia

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket
Operations Team - CIF Persona

Program Development Team - CIF Persona

**Comment by LindsayMacfarlane** [comment]
Proposed draft project status from CIF:

Proposal Submitted 
Technical Review
Review Complete
Waitlisted
Disqualified
Withdrawn
Funding Offered
Agreement Signed
Agreement Terminated
Advanced Milestone Complete
General Milestone 1 Complete
General Milestone 2 Complete
General Milestone 3 Complete
Reporting Milestone 1 Complete
Reporting Milestone 2 Complete
Reporting Milestone 3 Complete
TEIMP
Performance Milestone Complete
Summary Report Submitted
Annual Reporting
Complete
Under Review

**Comment by rajpersram** [comment]
@Peirist Can you clarify if these status' are in order, if that order is mandatory, and also if they're stream-specific or agnostic? Thanks.

**Comment by Peirist** [comment]
These statuses are in an order that maps roughly to the project cycle, so maintaining the order would be ideal. They're stream agnostic (though some statuses are only relevant to one stream).  I will note that the milestone statuses can be condensed, as per direction from the Operations team, so the list can read

...
Advanced Milestone Complete
Project Underway
TEIMP
...

**Comment by LindsayMacfarlane** [comment]
Thank you @AlexZorkin - I tested in Dev by:
- creating a new project and entering project data (including project status)
- project status was displayed correctly in the project list
