### ISSUE TITLE
Bug: Milestone holdback amount should have a dollar sign in the input field [6]

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1292]
Describe the Bug:

See @LindsayMacfarlane's comment [here](https://github.com/bcgov/cas-cif/issues/980#issuecomment-1347440443)
The 'Milestone holdback amount' field is missing a monetary sign to indicate which value is expected here

Probability (how likely the bug is to happen, scored from 1-5):3
Effect (how bad the bug is when it does happen, scored from 1-5):3

**Comment by gurjmatharu** [comment]
Closing - see: https://github.com/bcgov/cas-cif/issues/980
