### ISSUE TITLE
As a cif user, I can assign a funding stream when I create a project

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#130]
#### Description:
When a new project is created, the user needs to be able to select whether the funding stream is "IA" or "EF". This can be selected from a dropdown.

#### Acceptance Criteria:
Given that a user is on the project create screen, and they are determining the funding stream associated with this project
When they click the select funding stream dropdown
Then they can select the funding stream and their edit is saved in the database `form_changes` table

#### Development Checklist:
- [ ] Create a `funding_stream` table with id:int, name: varchar(1000), description: varchar(1000)
- [ ] pre-populate it "IA" and "EF", add using the sqitch change, IA is 1 EF is 2
- [ ] project table has a `funding_stream_id` foreign key
- [x] Create a dropdown selection for funding stream with the options from the `funding_stream` table
- [ ] When the value of this dropdown changes, it is persisted to the database `form_changes` table
- [ ] Meets the DOD

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/130?planning-poker) with ZenHub @AlexZorkin @pbastia

**Comment by LindsayMacfarlane** [comment]
Thanks @AlexZorkin! A couple of quick comments:

- For the funding stream: there is the funding stream ID (drop down) and then the description. Do we need both? Looking at the wireframe there is no description field.
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/350a6949-95d9-4bef-aa16-18f139328360)

- Can you please check-off the completed items in the development checklist.

**Comment by LindsayMacfarlane** [comment]
Thank you for the update @AlexZorkin .
