### ISSUE TITLE
Plan for CPI Workshop (User Engagement/Testing)

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1306]
#### Describe the task

The branch hosts a yearly workshop related to CleanBC Program for Industry initiatives (CIIP, CIF) for industry and interested stakeholders. This is a perfect opportunity for the team to design and conduct user engagement and user testing.

#### Acceptance Criteria
- [x] Create presentation draft
- [x] Configure Mentimeter
- [x] Share the presentation with Alana and team
- [x] Reach out to CIF
- [x] Send out invites for pre-workshop one-on-ones
- [x] Review and make updates if recommended by the reviewing team (if any)

#### Additional context

- Date of workshop to be confirmed (confirmed for the 9th and 10th of May) 
- Reach out to CIIP (if applicable). We might want to split CIIP and CIF components into different tickets/repos, but for now, I've lumped into one ticket)

**Comment by suhafa** [comment]
Hey @LindsayMacfarlane could you take another look at the AC. do you think we need to scope this out further or split it into two tickets?

**Comment by suhafa** [comment]
Reach out to Behzad (CIIP) and Jessica (CPR) if they would like anything users to be asked for their systems

**Comment by Dianadec** [comment]
@suhafa can this be pulled to in progress?

**Comment by suhafa** [comment]
@Dianadec pulled in progress and AC defined a little more to reflect next steps C:

**Comment by pbastia** [comment]
CPI presentation was submitted to the team for review. Great work @suhafa !
