### ISSUE TITLE
Status is missing from the Milestone report Tasklist [2]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1313]
Describe the Bug:

based on @BCerki comment on https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1041

when there are no milestone reports added, the status is missing from the Tasklist:
![image.png](https://images.zenhubusercontent.com/6243a3ea8726850c1675becd/63005358-a7eb-47b7-bccc-5eb1a18e9c4d)

@suhafa , this came up in https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1032; just to confirm, the general "Add Milestone Reports" should have a status even though most milestone things are for individual reports?

Probability (how likely the bug is to happen, scored from 1-5):1
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

**Comment by suhafa** [comment]
@Sepehr-Sobhani thanks for raising this issue! That is correct, to remain consistent with the rest of the task list, `Add Milestone Reports` should have `Not started` if there hasn't been any creating of milestones. It will display `In progress` if even one milestone has been created. And will display `Complete` if all mandatory information is present

**Comment by Sepehr-Sobhani** [comment]
Thank you @suhafa! just to confirm, this is the current implementation of having multiple milestone reports:
![Screenshot 2023-01-05 at 5 08 59 PM](https://user-images.githubusercontent.com/52381975/210909271-4ec8745d-55c8-4ab6-bcde-115a9ed4bbfe.png)

Is this the required behaviour when creating milestones?!

**Comment by suhafa** [comment]
@Sepehr-Sobhani yes, looks good to me!

**Comment by Sepehr-Sobhani** [comment]
Duplication of #803
