### ISSUE TITLE
As a cif user, I want to enter a unique project ID when I create a project

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#132]
#### Description:
Assigning a unique identifier to a project - no automatic generation for now.

[Project creation ticket 69 with prototype](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/69)

#### Acceptance Criteria:

Given I am a CIF user
When I create a project
Then I can enter a unique project ID for that project

Given I am creating a project
When I enter a unique project ID
Then I can only enter project IDs in the form `<Year>-RFP-<Stream Code>-<Rand Number>-<Operator code>` (ex: 2020-RFP-1-456-ABCD)

#### Development Checklist:
- [x] There is a text box to enter a unique project id 
- [x] There is client side validation of the unique project id
- [x] There is a `unique_project_id` column on the project table, with the `unique` constraint
- [x] Meets the DOD

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/132?planning-poker) with ZenHub @AlexZorkin @pbastia

**Comment by LindsayMacfarlane** [comment]
Hi @pbastia! I've tested this user story in Dev and have some feedback:

- As a 'new' user, I found it a bit challenging entering the RFP number into the system. There was great help text within the field, but once I started entering my unique ID, it was replaced with a more confusing guide (see screenshot). Is it possible to clean that up a bit? 
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/410d65e5-3b80-45c4-843d-1d2615f655cc)
- Once I had entered information into the two fields correctly, I was able to select the 'Commit Project Changes', but nothing happened. Should something have happened?

Looking good!

**Comment by pbastia** [comment]
@LindsayMacfarlane 
- The error handling is not something we tackled yet, we can probably ignore those for now. 
- There definitely should have been something happening, back to in progress!

**Comment by matthieu-foucault** [comment]
@pbastia it's not adding the project because of the not-null constraint on the funding_stream_id

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia 

I can now add an RFP number and the funny error message is no longer displayed. I did notice though, that if I enter an incorrect format, I don't get any error message (but I'm assuming tat is tackled in another ticket).

**Comment by matthieu-foucault** [comment]
Yes, form validation will be handler in #158
