### ISSUE TITLE
Amendment status change requires refresh to update pending actions from [5]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1328]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- navigate to the amendments page
- change the project status to something other than draft and click update
- pending actions from should be readonly but is still available
- navigate away and come back
- now pending actions from is correctly readonly

Screenshots:
https://www.loom.com/share/62a16898a5844017bce45939c47e1439

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani - I can no longer recreate the bug.

An observation: I can't seem to submit a revision that is an amendment - even when it says it is applied it is considered in progress.

**Comment by Sepehr-Sobhani** [comment]
Thank you @LindsayMacfarlane.

Submitting an amendment/revision based on the status is still in progress and captured in this ticket: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1293

For now, the only way to submit a revision is to follow below steps:
clicking on the `Resume Edition` button on any page/form -> clicking the `Submit Changes` header -> clicking the `Review and Submit Information` sub-header -> filling in the reason for changes box -> hitting `submit` button
