### ISSUE TITLE
As a cif user, I want to be able to assign more than one project manager to a project

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#133]
#### Description:
We want to be able to assign multiple users in the `cif_user` table to a single project. This will be done by adding records the the `project_manager` intersection table.

Managers have defined labels, "Tech Team Primary", "Tech Team Secondary", "Ops Team Primary", "Ops Team Secondary", but we still want to keep the implementation flexible in case those change and more managers are needed

#### Acceptance Criteria:
Given I am a CIF user
When I edit or create a project
Then I see one project manager field per manager label setup in the database

Given I am on the project create/edit page
When I select a user in the "Tech Team Primary" dropdown (or any project manager dropdown)
Then the corresponding project_manager form_change record is updated

Given I am on the project create/edit page
When I filled out all the project managers for the project
And I click submit
Then one record per project manager is saved to the `cif.project_manager` table

#### Development Checklist:
- [x] There is a `project_manager_label` table with an id (`integer primary key generated always as identity`) and a label (`varchar(1000)` with a unique index)
- [x] The `project_manager_label` is pre-populated with "Tech Team Primary", "Tech Team Secondary", "Ops Team Primary", "Ops Team Secondary"
- [x] Selecting a user from the dropdown adds a record to the `form_change` table as a pending change to the `project_manager` table
- [x] Clearing the project_manger marks the form_change as `deleted` 
- [x] Wireframe completed and linked to ticket
- [x] Meets DOD

#### Notes: 
- 

#### Personas:
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/133?planning-poker) with ZenHub @AlexZorkin @pbastia

**Comment by pbastia** [comment]
I think we wanted to get feedback from CIF, to see if we need to include this in the MVP or not. Maybe something we can mention at sprint review, to get the discussion started?

**Comment by rajpersram** [comment]
[Ticket 69](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/69) has the associated wireframe for creating a project and setting the Project Managers

**Comment by LindsayMacfarlane** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/133?planning-poker) with ZenHub @dleard @pbastia @AlexZorkin

**Comment by dleard** [comment]
@LindsayMacfarlane 
To test this go to the create project page
You should be able to set / remove 4 managers now (one for each manager label we have in the database)
Submitting a project without setting a manager should not show any validation errors since they are set as optional.

**Comment by LindsayMacfarlane** [comment]
Awesome! Thank you @dleard 

Works as expected based on the development checklist. 

One question (and apologies if we've previously discussed) - should the list of project managers show in the 'assigned to' column in the CIF Project table? If so, how do we make that UI nice - if we need to show multiple people?

@suhafa - another design question to loop you into :)

**Comment by dleard** [comment]
The 'assigned to' column is not currently implemented, so they won't show up there yet. It's hardcoded for now to be "J. Doeloremipsum, J. Doe". With 4 (or possibly more in the future) managers assigned to a project it could definitely use some thought about how and what to show there.

**Comment by LindsayMacfarlane** [comment]
Thanks @dleard - it doesn't look like we have a ticket for that?
