### ISSUE TITLE
Tech Debt: Remove dependency on Terraform Cloud and cas-shelf

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1333]
Following a call with Junmin, here's what we need to do:

- use Terraform (not cloud) in the bucket provisioning job 
- store the terraform state in GCS

Refactoring opportunities will pop up from there:
- the bucket provisioning job should live in its own helm chart so it can be reused across projects

AC: 
- [ ] Terraform state for CIFF created in GCS bucket
- [ ] Relavent Terraform modules in CIFF Helm charts with Terraform job
- [ ] Existing resources in Terraform Cloud state _moved_ to GCS bucket state

**Comment by pbastia** [comment]
@dleard @Sepehr-Sobhani @sam-warren :eyes:

**Comment by pbastia** [comment]
@mikevespi has experience with this :)

**Comment by Sepehr-Sobhani** [comment]
I'm interested to join if/when someone wants to tackle this :)

**Comment by joshgamache** [comment]
**Research**:	
- `cas-cif/chart/cas-cif/templates/bucket-provisioning-job.yaml` references `TFC`, which are variables for use with Terraform Cloud
   - This file provisions the GCP Storage containers, based on configuration from another repo: `cas-shelf/bcgov/`. That repo's folder contains terraform files, get applied from TFCloud.
   - This [Dockerfile](https://github.com/bcgov/cas-shelf/blob/master/docker/add-app/Dockerfile) is what gets run in the above helm template
	- Pulls in `cas-shelf/tfe-scripts/helpers` and `cas-shelf/tfe-scripts/tf-add-app-run.sh`
	- [tf-add-app-run.sh](https://github.com/bcgov/cas-shelf/blob/master/tfe-scripts/tf-add-app-run.sh) is the script that runs in the container
   - In `cas-shelf`, these commands might be needed [Package cas-shelf/cas-shelf-tfe-add-app (github.com)](https://github.com/bcgov/cas-shelf/pkgs/container/cas-shelf%2Fcas-shelf-tfe-add-app#other-commands) to recover existing TF Cloud state?
- `c53ff1` is the namespace prefix for CIF 

**Goals**:
- Establish Remote State in GCP buckets (ie. use our OpenShift's secret with the tfbackend, but locally).
- Configure Terraform scripts that will be run, *but do not run them*
- **Back up existing state!**
- Import existing Terraform *resources* from TF Cloud. See [this post for a potential solution](https://medium.com/@suman.maity112/migrate-terraform-resource-from-one-project-to-another-61d0c347419a).
	- Do we need to import existing state from TF Cloud? Probably not. We just want the resources under the our new state bucket's control!
		- ~~Should be able to accomplish this with the [TF Cloud GUI](app.terraform.io). Use the *variables* to identify the run for a particular namespace, then download the state from the run.~~
	- We can use [terraform state mv](https://developer.hashicorp.com/terraform/cli/commands/state/mv)
- Push update states to GCP buckets & Terraform Cloud (now without those resources)
- Upload remote state to GCP buckets
- Repeat for `-dev`, `-test`, `-prod`. 

**Pseudocode**:
```sh
# terraform state mv [options] SOURCE DESTINATION

TFC_STATE_FILE="This is the path to the file that we pulled the state from Terraform Cloud"
GCP_STATE_FILE="This is the path to the file that we pulled state from GCP"
OPTIONS="-state=${TFC_STATE_FILE} -state-out=${GCP_CLOUD_STATE_FILE}"

# We have our basic command, but now we need to know what resources to map to what. The resource naming *should* be consistent if we use the `main.tf` file (and `variables.tf`) from cas-shelf
SOURCE_RESOURCES=(A.list of.resources to.transfer)
DESTINATION_RESOURCES=(A.list of.resources to.transfer) # This will only be needed if the resources end up with different names.

# Run a loop, executing tf state mv $OPTIONS $SOURCE_RESOURCE[n] $DESTINATION_RESOURCE[n]
```
