### ISSUE TITLE
Consult with Tech Team and Meghan for user journey map

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1348]
#### Describe the task

After talking with the Ops team, we needed the Tech Team's input on some of the finer aspects of funding streams and how they would like to use the external applicant portal. Megan was also identified as a good source for understanding the user journey in the earlier stages of the projects.

#### Acceptance Criteria
- [x] Create meeting invites
- [x] Reach out to Tech Team and Meghan for meeting
- [x] Conduct session(s)
- [x] Organize and document insights

#### Additional context

- created after work done in #1263

**Comment by suhafa** [comment]
Session notes after meeting with Tech Team:
1) We got more insight into the different personas associated with the External Operators, namely Vendors (help operator pick the right tech for emissions reductions) and 'Consultant' or 3rd party subordinate (help optimize operator's efficiency)
2) We got additional insight as to what happens when a project is withdrawn or waitlisted. This could be a potential feature in the application - user can withdraw a project if waitlisted, and as an optional step specify why they are withdrawing and if they plan to try for funding again
3) We got a chance to review a few wireframes we've made with them as well, they suggested potentially adding BCGHGID as a field in Project overview. It may not be relevant moving forward

**Comment by suhafa** [comment]
Meeting with Meghan illuminated the awareness phase of CIF for the external operator. Added in potential features such as a funding stream eligibility checker, project concept form information being a form in the application and so on. @LindsayMacfarlane this ticket can be closed after your review!

**Comment by LindsayMacfarlane** [comment]
Thank you so much @suhafa. You facilitated a great session where you were able to get a lot of great information and insights from MG :)
