### ISSUE TITLE
Archived funding agreements show up in summary form [3]

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-cif#1355]
Describe the Bug:
~~After removing a funding agreement, it still shows up in the summary form with the archived values. The form seems to be getting archived, it doesn't show up in graphiql after removing it, and the frontend shows operation to be archive.~~ This part seems to have been fixed, possibly by #1339 or the funding form refactor

To add to the oddity, after submitting another revision on the same project (any form), the funding agreement will then show up as a "fresh" funding agreement, as if you added one but didn't fill it in.

Probability (how likely the bug is to happen, scored from 1-5): 1
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- remove the funding agreement from a project (click "no" under is this a funded project) and submit the revision
- go view the project you just revised, and check the funding agreement page
- you will still see the archived funding agreement

- now make another revision to the project, on any other form, and submit.
- go back in to view the funding agreement
- you will now see a "fresh" funding agreement (not the values you archived)
Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
Might be addressed in: https://github.com/bcgov/cas-cif/pull/1339

**Comment by pbastia** [comment]
This was fixed indeed!
