### ISSUE TITLE
Create project_phase table

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#136]
#### Describe the task

Create `project_phase` table

#### Acceptance Criteria

- [ ] there is a `project_phase` table with the following columns:
- id: int 
- name: varchar(1000)
- description: varchar(1000)
- funding_stream_rfp_id - foreign key to the `funding_stream_rfp` table

- [ ] table passes the style tests

**Comment by LindsayMacfarlane** [comment]
Hi @pbastia - double checking on the status of this ticket. Was it completed or was it merged with an existing ticket?

**Comment by pbastia** [comment]
@LindsayMacfarlane sorry I forgot to update the labels! this work is now part of #129

**Comment by LindsayMacfarlane** [comment]
Thanks for clarifying @pbastia - much appreciated :)
