### ISSUE TITLE
Fetch project funding agreement schemas from the database

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-cif#1360]
###Description of the Tech Debt###
Currently the `ProjectFundingAgreementForm` is getting the form schemas it needs from the frontend (from `app/data/jsonSchemaForm/`). We need to switch these to be fetching the schemas from the database so that we are only maintaining it in one place.

**This form uses two separate schemas: funding agreement, and additional funding sources.**
The following steps need to be taken for both, and all but the first and last steps here need to be done for both the form, and the form summary components.
- [x] ensure the schema in the database is up to date
- [x] remove anyOf / default from the database schema
- [x] add a query to the component fetching the `jsonSchema`s by their slugs, "funding_agreement" and "additional_funding_source"
- [x] switch the form to use the schema in the above query response
- [ ] switch the import in the components test to point to the schema in `schema/data/prod/json_schema/`. May need to use look into https://relay.dev/docs/guides/testing-relay-components/#mock-resolver-context for mocking queries that include more than one db-fetched schema
- [x] remove the schema from the frontend directory we were importing from before
- [x] remove the frontend schema import from `validationSchema` and add the new schema name to `app/server/middleware/graphql/databaseSchemaConfiguration.ts` so the validation plugin can find the correct schema

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring: 1 / 2  (the risk increases if we add/remove fields from, or start versioning the schema)

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| TOTAL SCORE:                                                                                                                  |       |       |

**Comment by BCerki** [comment]
To complete the refactor, we needed to use `rjsf` array types, which we haven't previously implemented. Create a couple tech debt issues to address that and keep this PR smaller:
- https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1535
- https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1536

**Comment by pbastia** [comment]
Thank you @BCerki ! The schemas are pulled from the database
