### ISSUE TITLE
As a CIF maintainer, I want to fetch the emission intensity schema from the database, so I can store changes to schemas and keep consistency across the codebase

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-cif#1361]
###Description of the Tech Debt###
Currently the `ProjectEmissionIntensiryForm` is getting the form schemas it needs from the frontend (from `app/data/jsonSchemaForm/`). We need to switch this to be fetching schemas from the database so that we are only maintaining them in one place.

This form uses more than one schema: `emissionIntensityReportSchema` and `emissionIntensityReportUiSchema`. The following steps need to be taken for both schemas, and where applicable for both the form and the form summary components.

- [x] ensure the schema in the database is up to date
- [x] remove anyOf / default from the database schema
- [x] add a query to the component fetching the `jsonSchema` by slug for `emissionIntensityReportSchema` and `emissionIntensityReportUiSchema`
- [x] switch the form to use the schema in the above query response
- [x] switch the import in the components test to point to the schema in `schema/data/prod/json_schema/`. May need to use look into https://relay.dev/docs/guides/testing-relay-components/#mock-resolver-context for mocking queries that include more than one db-fetched schema
- [x] remove the frontend schema
- [x] remove the frontend schema import from `validationSchema` and add the new schema name to `app/server/middleware/graphql/databaseSchemaConfiguration.ts` so the validation plugin can find the correct schema
- [x] deprecate existing form_change records and recreate a singular form_change that follows the new schema
- [ ] update any broken computed_columns that were referencing deprecated form_change records

See the milestone form handling for an example

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring: 1 / 2  (the risk increases if we add/remove fields from, or start versioning the schema)

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| TOTAL SCORE:                                                                                                                  |       |       |

**Comment by BCerki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1361?planning-poker) with Zenhub @dleard @gurjmatharu @JoshLarouche @pbastia @sam-warren @Sepehr-Sobhani @tmastrom

**Comment by dleard** [comment]
See #1691, there is a bug that may need handling during the work in this card

**Comment by pbastia** [comment]
@dleard are we OK to put this back in the tech debt column? I don't see any immediate benefits in working on this

**Comment by dleard** [comment]
I see it's both a user story and a tech debt? I think it's fine to put it off, but I wouldn't want to put the app in maintenance mode with the json schemas continuing to live in 2 different places

**Comment by pbastia** [comment]
Makes sense. Let's keep it in the backlog then

**Comment by Sepehr-Sobhani** [comment]
In this case, we need to bring [1357](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1357) and [1476](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1476) into backlog too!

**Comment by pbastia** [comment]
That's correct! Thanks @Sepehr-Sobhani

**Comment by Sepehr-Sobhani** [comment]
[This card](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1532) could also be related.

**Comment by pbastia** [comment]
Not much to test here. Thank you @BCerki , this was a ton of work!
