### ISSUE TITLE
Create a flow chart covering all possible states for creating a new revision record

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1365]
#### Describe the task

From the conversation with @BCerki, @gurjmatharu, and @Sepehr-Sobhani on refining #1284, Gurjeet indicated that there might be significant gaps between the business logic and the back-end technical logic around the workflow for creating/editing a revision record, which is causing shared confusions when it comes to development. He suggested putting together a flow chart diagram covering all possible states to reflect the business logic, and schedule a dedicated time with all the developers to come up with and agree on an approach to resolve the confusion and unblock associated development work.

#### Acceptance Criteria

- [x] Create a flow chart covering all possible states for creating/editing a new revision record
- [x] Schedule meeting(s) with all the developers to sync up the business and back-end logic using the diagram
- [x] Update the prototypes to reflect the refined workflows as discussed
- [x] Come up with and agree on solutions to proceed with

**Comment by LindsayMacfarlane** [comment]
@nanyangpro has reviewed the team's concerns and approach to creating a flow chart for the various revision states. I approve the approach, so have removed the attention PO label.

**Comment by Dianadec** [comment]
Feedback from refinement: might be helpful to include a dev when working on this card to provide input @dleard fyi @nanyangpro

**Comment by Dianadec** [comment]
Update from standup - @BCerki volunteered to work with @nanyangpro on this as needed

**Comment by BCerki** [comment]
From discussion with @nanyangpro re: editing open amendments, we don't have a prototype of the flow for this yet, but the plan is:

1. Click the `Amendments & Other Revisions` link in the tasklist and click `View/Edit`
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/16ce305e-c536-4ae5-95f8-70f1eed7d809)
2. Click the title of the form (in the Forms Updated section, not on the tasklist), which is a link
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/084f55fb-ffdf-4365-9275-f3192a28ef85)
3. The link leads to the form which will have some greyed-out fields (the fields that are updated using the routinely updated widget) but otherwise be the same as the forms when creating a project
https://markuphero.com/share/t6sGqzvhhHxKkjNEECbH

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket is ready for you to review and can be closed with:
1. The [flow chart for the front-end business workflow](https://miro.com/app/board/uXjVP1NVDKE=/?moveToWidget=3458764544793169232&cot=14) created and discussed with the team
2. The interactive prototypes refined as discussed to reflect the proposed workflows
- [View Revision Record (Updated)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF---Internal-User-Portal?page-id=2289%3A2663&node-id=3068%3A2675&viewport=-104%2C637%2C0.11&scaling=scale-down&starting-point-node-id=3068%3A2675&show-proto-sidebar=1)
- [New Revision Record (Updated)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF---Internal-User-Portal?page-id=2289%3A2663&node-id=3169%3A2715&viewport=-104%2C637%2C0.11&scaling=scale-down&starting-point-node-id=3169%3A2715&show-proto-sidebar=1)
- [Edit Revision Record (Updated)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF---Internal-User-Portal?page-id=2289%3A2663&node-id=7283%3A870&viewport=-104%2C637%2C0.11&scaling=scale-down&starting-point-node-id=7283%3A870&show-proto-sidebar=1)
3. New interactive prototype created as discussed to reflect the alternative workflows
- [Alternative Workflow](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF---Internal-User-Portal?page-id=2289%3A2663&node-id=7314%3A3733&viewport=-104%2C637%2C0.11&scaling=scale-down&starting-point-node-id=7314%3A3733&show-proto-sidebar=1)
4. #1422 created as the next step for gather input from CIF and make informed decisions

**Comment by LindsayMacfarlane** [comment]
Thank you for all your work on this @nanyangpro
