### ISSUE TITLE
Speaker Coaching 

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-cif#1366]
We have an opportunity to have a team speaker coaching session through A.H. at the Exchange Lab. The idea behind this came out our reflections about Sprint Review and how we can make our meetings even better, from a presentation/demo stand point. A.H. can provide us with helpful tips and tricks, answer any questions, and provide feedback.

This would be a 1-hour long session and we have a hold in the GGIRCS calendar for Wednesday, February 8th.
Feb. 13 Update: postponed until further notice. Coordinating a new date with AH.

**Comment by LindsayMacfarlane** [comment]
Note: due to scheduling conflicts, this session will be moved to a following sprint.

**Comment by LindsayMacfarlane** [comment]
This was quite insightful. My biggest take away is that to make a good presentation, you need to allocate a lot more time to its preparation. It was also highlighted how preparation is a "community" task > involve more people to gather more insights and perspectives into the content.
