### ISSUE TITLE
Security follow up

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1367]
#### Describe the task

Review feedback from MISO:

- have any objects been created that don't belong? 
- Any irregular entities that might allow inappropriate access (backdoors)
- Any routes/network policies that are suspect? 
- Any updates to images that should not have happened?
- Any changes to security tooling (attackers will typically turn these off, for sonar they might change scanned paths to give a false sense of confidence)

He also mentioned that he assumed your CI/CD tooling doesn't have permission to create accounts/grant access, but if it does, ensure no new accounts have been made as backups for the attacker.

Also, keep an eye out for any changes that would allow for persistence and/or exclusions for IPs.  

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by LindsayMacfarlane** [comment]
Note: I may have put this in the wrong repo. Feel free to update.

**Comment by pbastia** [comment]
@LindsayMacfarlane there was an email exchange with our MISO where we updated him on all actions taken.

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia !
