### ISSUE TITLE
removing and adding budgets, expenses and payments throws error [7]

### ISSUE THREAD

**Issue by gurjmatharu** [bcgov/cas-cif#1379]
Describe the Bug:
Remove budgets expenses and payments and then add it again - it will throw an error.

Probability: 5
Effect: 2

Steps to reproduce the behaviour:
1. Edit an existing project revision
2. Edit Budgets, Expenses and Payments (Resume Edition)
3. Click `No` to is this a funded project.
4. Click yes to discard
5. Click `Yes` to is this a funded project.

You will get the following error:
```
{
  "errors": [
    {
      "message": "more than one row returned by a subquery used as an expression",
      "locations": [
        {
          "line": 4,
          "column": 3
        }
      ],
      "path": [
        "createFormChange"
      ]
    }
  ],
  "data": {
    "createFormChange": null
  }
}
```

**Comment by BCerki** [comment]
@gurjmatharu, I can't reproduce this in dev

**Comment by mikevespi** [comment]
I am still getting this error in dev and local. Removed the Deletion Candidate tag.

**Comment by Sepehr-Sobhani** [comment]
I can't reproduce this, Can anyone else reproduce this?

**Comment by BCerki** [comment]
I can't reproduce it in the way the ticket describes, but there's still an error. If I remove a funding agreement and then re-add it and fill it, I don't see it in the diffs and all the newly entered info is gone when I commit: https://www.loom.com/share/1972fd120eda49e29e14654ffc95e28a

**Comment by Sepehr-Sobhani** [comment]
@BCerki True 💯 I think we can change this bug to the one you mentioned and since it's very unlikely to happen make its value less than 7.

**Comment by Sepehr-Sobhani** [comment]
Couldn't be reproduced but the issue @BCerki mentioned is captured in #1767
