### ISSUE TITLE
As a CIF developer, I can update any single field directly, without creating a revision first, so that I can support routine updates of fields (backend work)

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1380]
#### Description:

Split out from https://github.com/bcgov/cas-cif/issues/1158

Shortcut workflows for updating the Routinely Updated Fields have been designed and validated by the CIF team. With such, users can update the field with a few clicks without having to click on the "New Revision" button and follow the steps there on the Amendments & Other Revisions page.

This can be done by allowing users a shortcut to the fields below without following the "New Revision" workflow. In the backend, it would create a new revision of type 'minor revision', apply the change and commit it. This will preserve change history while allowing quick edits to certain fields.

The figma link "Example 1" shows an example where a routinely updated field can be updated directly from the 'view' page. There will be no reverting these changes with a revert button as the changes will be committed immediately. The field will save the data to a form_change record as data is entered and an 'update' button, when clicked will commit the revision.

This mutation will also need to update any other revision in flight on the project to preserve the change after the in flight revision is committed.

- [Detailed notes](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=4939%3A685)
- [Detailed grouping of fields](https://bcgov.sharepoint.com/:x:/t/00608-ScrumTeam/EbxB55A0pk9Kr-eCTocUvIkB1JM9mQs3kHz7PhBT07XSXQ?e=939BRq) on the "Fields" tab of this spreadsheet

Front-end work will be handled in another card, but here are the designs for context:
- [Generic example 1: for fields with Dropdown as front-end component](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=4939%3A685&node-id=5089%3A1414&viewport=-484%2C320%2C0.14&scaling=scale-down&starting-point-node-id=5089%3A1414&show-proto-sidebar=1)
- [Generic example 2: for fields with Date Picker or Text Input as front-end component](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=4939%3A685&node-id=4939%3A1324&viewport=-484%2C320%2C0.14&scaling=scale-down&starting-point-node-id=4939%3A1324&show-proto-sidebar=1)

#### Acceptance Criteria:

Given that I am a CIF developer
When I want to update a single field
Then there are mutations that allow me to do so

Given that I am a CIF developer
When I fire the mutation to update a single field
Then a new revision is created containing only that one field change, then committed
And I can see the revision as a "Minor Revision" in the revision table

Given that I am a CIF developer
When I fire the mutation to update a single field
And the project has other revisions in progress
Then those revisions also have the field updated

#### Development Checklist:

(confirm if we need new mutations/what they should contain)
- [ ] create a new mutation that saves the single field's data to a form_change record as data is entered
- [ ] create a new mutation that commits the single field's changes with type 'minor revision'
- [ ] no need for any revert mutations
- [ ] Exploration: there might be a way of inserting an already committed revision in the database and let the triggers do their thing. This way we would never have the database in a state where we have multiple pending revisions for a project
- [ ] Also update the field in any any other progress revisions on the project
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1380?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @mikevespi @sam-warren @Sepehr-Sobhani

**Comment by mikevespi** [comment]
Is the intent that if a revision is in flight when one of these fields are updated, the update mutation also changes the pending form change on the revision in progress?

**Comment by Dianadec** [comment]
Note that this needs to be added to an epic

**Comment by Dianadec** [comment]
Sprint planning update: May have implications based on the amendments meeting yesterday cc @mikevespi

**Comment by LindsayMacfarlane** [comment]
Note: Take a pause on this ticket to give team space to revisit our approach.

**Comment by pbastia** [comment]
The PR (https://github.com/bcgov/cas-cif/pull/1438) associated to this card will not be merged in as-is and will need to be picked apart after discussions on a more naive "Wild wild west" approach to amendments and revisions in general.

**Comment by mikevespi** [comment]
This work was completed but never merged, as the approach taken was changed. The work is now handled in other cards. 
Closing
