### ISSUE TITLE
As a CIF developer, I want to have a widget that allows me to update a Routinely Updated Field without going to the "Amendments & Other Revisions" page (frontend widget)

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1382]
#### Description:

This ticket is about creating a widget for Routinely Updated Fields and adding it to the Project Overview page for Project Status.

Context:

Shortcut workflows for updating the Routinely Updated Fields have been designed and validated by the CIF team. With such, users can update the field with a few clicks without having to click on the "New Revision" button and follow the steps there on the Amendments & Other Revisions page.

This can be done by allowing users a shortcut to the fields below without following the "New Revision" workflow. Backend logic for this handled in https://github.com/bcgov/cas-cif/issues/1380

The figma link "Example 1" shows an example where a routinely updated field can be updated directly from the 'view' page. There will be no reverting these changes with a revert button as the changes will be committed immediately.

- [Detailed notes](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=4939%3A685)
- [Detailed grouping of fields](https://bcgov.sharepoint.com/:x:/t/00608-ScrumTeam/EbxB55A0pk9Kr-eCTocUvIkB1JM9mQs3kHz7PhBT07XSXQ?e=939BRq) on the "Fields" tab of this spreadsheet
- [Generic example 1: for fields with Dropdown as front-end component](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=4939%3A685&node-id=5089%3A1414&viewport=-484%2C320%2C0.14&scaling=scale-down&starting-point-node-id=5089%3A1414&show-proto-sidebar=1)
- [Generic example 2: for fields with Date Picker or Text Input as front-end component](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=4939%3A685&node-id=4939%3A1324&viewport=-484%2C320%2C0.14&scaling=scale-down&starting-point-node-id=4939%3A1324&show-proto-sidebar=1)

#### Acceptance Criteria:

Given I am a CIF developer
When I transform a form field to be routinely updated
Then I have a widget to use that implements that functionality out of the box

#### Development Checklist:

- [x] Create a widget for routinely updated fields. The widget should use the original field's widget (pass as a prop) (?), ~update the database onChange~, and should have an update button that commits the revision (will use the mutations created in https://github.com/bcgov/cas-cif/issues/1380; for now, use mock function, see dev checklist bullet 3). There's a similar widget for amendment status that could perhaps be made more generic to work everywhere.
- [x] configuration of the widget can be either through a widget factory (that creates a widget with the proper form/arguments) or through some static values in the ui schema - there's a bit of exploration on how difficult it is to configure the mutation call
- [x] the widget calls a mock mutation function that just logs a message to the console when called

- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
This could be worked on and implemented without a mutation being called nor a flow being decided @BCerki

**Comment by BCerki** [comment]
You mean the `Update` button in the widget should do nothing in this ticket, and we hook it up to the mutation later?

Re the flow--if this ticket becomes just widget creation, I agree

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1382?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @mikevespi @sam-warren @Sepehr-Sobhani

**Comment by BCerki** [comment]
This will be the first of the forms to implement the routinely updated field workflow

**Comment by pbastia** [comment]
This might be an 8, to make sure it's well tested and that the form/widget configuration mechanics are usable and documented

**Comment by Sepehr-Sobhani** [comment]
@LindsayMacfarlane This is all code and nothing to test.

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani!
