### ISSUE TITLE
emission intensity performance calculation should be based off of the form_change values

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1383]
The calculation for emission intensity performance is currently deriving the values for the calculation from the emission_instensity_report table. This means that the calculated value from that function will not update until the project revision is submitted. The original work for this was done in the summer in card #766. I think sometime after this, we found a better way to do calculated values from form_change records as opposed to deriving them from the table and populating them on the front-end via the form_change_as_table computed columns.

This work is currently blocking #1210 as it needs to use the updated calculated values within another function.

What needs to be done:

- [x] deprecate the `emission_intensity_ei_performance_calculation` computed column
- [x] create a `form_change_ei_performance_calculation` computed column that uses the method described in #766, but derives the values needed for the calculation from the form_change record.
- [x] update `project_revision_teimp_payment_percentage` to use the new function in place of the old one
- [x] update the `ProjectEmissionIntensityReportForm` and the `ProjectEmissionIntensityReportFormSummary` components to use the new computed column (and remove the unnecessary asEmissionIntensityReport part of the fragment)
- [x] Write / update tests for the changes

**Comment by BCerki** [comment]
To test this one, you can go to the emissions form and enter in BEI, TEI, and PEI, and the GHG calculation should recalculate every time you change anything.

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! Tested as per your instructions above and can confirm that when I adjust BEI, TEI, PEI then then GHG Emission Intensity Performance auto calculates.
