### ISSUE TITLE
OpenShift 201 Lab exercises

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1390]
#### Describe the task

Completing OpenShift 201 lab exercises mentioned here: https://github.com/BCDevOps/devops-platform-workshops/tree/master/openshift-201

Based on the conversation with Lindsay, this is just a card to capture the work I need to do during this and next week.

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani! So happy that you were able to take the OpenShift course and finish up the course work. Don't forget to capture in your My Performance :)

**Comment by Sepehr-Sobhani** [comment]
@LindsayMacfarlane Of course. Thanks for supporting me during this course 🙏
Also, I like `your My Performance` :))
