### ISSUE TITLE
Team poster design

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1394]
#### Describe the task

The Service Transformation Branch is leading a poster design and printing for the ENV agile teams to post in the agile space at 525 Superior Street.

#### Acceptance Criteria

- [x] book session for team (interested folks)
- [x] brainstorm design ideas and content
- [x] Review with branch (?) 

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Dianadec** [comment]
Miro link: https://miro.com/app/board/uXjVPrzYAGg=/?share_link_id=26255177236

**Comment by Dianadec** [comment]
@LindsayMacfarlane my suggested next steps would be to meet with other designers on a team to fine-tune posters from a graphic design perspective. I would also think we would need to have some kind of approval of these by the branch or? Let me know.

**Comment by LindsayMacfarlane** [comment]
I would like to get buy-in from the branch - at least Adria and the directors. If we narrow down the design, I can review with them on Wednesday morning.

**Comment by Dianadec** [comment]
Added a comment to the miro board to determine next steps: 1 poster design or more?

**Comment by Dianadec** [comment]
I'll finalize these on Monday

**Comment by Dianadec** [comment]
Jpg files have been saved in scrum team > team posters. I have the larger file sizes for printing on my onedrive to send in for printing. https://bcgov.sharepoint.com/:f:/t/00608-ScrumTeam/Er4_bu0vc7tEgF750qDzmnwBCeE6cAh5EGvNSdChyLsN4w?e=hTRMG3

**Comment by LindsayMacfarlane** [comment]
Thank you so much for all your work on this @Dianadec! I'm so excited to see the final, printed copies :)
