### ISSUE TITLE
Review and cleanup of external user personas

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1395]
#### Describe the task

Review existing external user personas to see if we have captured key users.

#### Acceptance Criteria

- [x] review and polish existing personas
- [x] Add a 'Consultant' persona
- [x] review with CIF team. Confirm with them if the personas identified will be at the workshop
- [x] review with JK regarding stakeholder groups
- [x] update based on feedback
- [x] make into a usable artifact

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by LindsayMacfarlane** [comment]
@suhafa - created this ticket.

**Comment by suhafa** [comment]
@LindsayMacfarlane Thank you Lindsay! Should we scope in the Consultant persona within this ticket's AC or create a separate one? I am leaning towards the latter incase there is more to uncover there (especially from the External Operator's perspective)

**Comment by LindsayMacfarlane** [comment]
@suhafa - I would probably include as part of this one.

**Comment by suhafa** [comment]
@LindsayMacfarlane going to take a leap of faith here and consider the work of this ticket done. Ready for your review, unless you'd recommend we explore something else?

**Comment by LindsayMacfarlane** [comment]
Thanks @suhafa - how did we make it into a reusable artifact?

**Comment by suhafa** [comment]
@LindsayMacfarlane updated the 'CIF Discovery: Personas and Journey Maps' Miro board with new findings from our consultation with Meghan so far! Anything else you'd recommend as part of research prep work?
