### ISSUE TITLE
Collaborate with CPR team (JK) to see where our external user research overlaps

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1397]
#### Describe the task

A clear and concise description of what the task is.

#### Acceptance Criteria

- [x] Sync with Jaimie to discuss about CPR's current research work
- [x] Reach out to Jessica K. to schedule a meet up to dive into detail
- [x] Continue reaching out to JK for an idea on workshop format, who all can attend and any executive level concerns for outreach
- [x] Document learnings
- [x] Create action items

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
@LindsayMacfarlane created this ticket on the basis of our discussion for reaching out to the CPR team. Need your help here in making AC more specific to understand this task better :')

**Comment by pbastia** [comment]
Thanks @suhafa ! Marking this as complete. Would you mind sharing where those learnings were documented?

**Comment by suhafa** [comment]
Hi @pbastia! I refined the timeline on the 'CIF External User Research' Miro board with after we met with Jessica c:
