### ISSUE TITLE
Discovery Workshop Preparation

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#14]
The Discovery Workshop on Sep. 29 will kick off the discovery phase. This ticket outlines the work to be done in preparation for the workshop.

**The Workshop**
- [x] Prepare Territorial Acknowledgement
- [x] Explain what the Discovery phase will be
- [x] Build out persona activity
- [x] Build out journey mapping activity
- [x] Build out value mapping activity

**Communication**
- [x] Update Calendar inviation
- [x] Send participants a reminder email day prior to workshop

**Comment by LindsayMacfarlane** [comment]
Super fun workshop @jaimiebutton ! I learned so much more about CIF and the business process and look forward to digging into the issues in more detail. I also really enjoyed the team debrief where we were able to share our lessons learned.

**Comment by jaimiebutton** [comment]
Thanks for being so kind in your ticket closing messages!

╔═══════════════════════════════╗
╠═════════════════════▄█════════╣
╠══════════════════▄██░█════════╣
╠═══════════█═════██░░░█════════╣
╠══════════██════██░░░░█════════╣
╠══════════█░█══▄█░░░░░█════════╣
╠═════════██░░█═█░░░░░░█════════╣
╠════════▄█░░░███░░░░░██════════╣
╠════════█░░░░█░░░░░░██████████▀╣
╠════════█░░░░░░░░░░░██░░░░░░██═╣
╠════════█░░░░▄▄▄▄▄░░░░░░░░░░█══╣
╠════════█░░▄▀░░░░░▀▄░░░░░░░█═══╣
╠═▀███████░▐░░░░░░░░░▌░░░░░█════╣
╠═══█░░░░░░▌░░░▄▄▄▄▄▄█▄░░░██════╣
╠═══██░░░░▐░░▄██████████▄░█═════╣
╠════█░░░░▌▄███████▀▀▀▀█▀█▀═════╣
╠════██░░▄▄████████░░░░▌░██═════╣
╠═════█▐██████▌███▌░░░░▐░░██════╣
╠══════██▌████▐██▐░░░░░▐░░░░██══╣
╠═════█▐█▐▌█▀███▀▀░░░░░▐░░░░░██═╣
╠════█░░██▐█░░▄░░░▄█░░░▐░░░░░░██╣
╠═══█░░░▐▌█▌▀▀░░░█░█▌░░▐░░░░████╣
╠══█░░░░▐▀▀░░░░▄█░░█▌░░▌░░███═══╣
╠▄██░░░░░▌░░░▄██░▄██▌░▐░███═════╣
╠═══██░░░▐░░▀█▄░▄███▌░▐░░█══════╣
╠════███░░█░░░██▀▀░█░░▌░░░█═════╣
╠══════█░░░▌░░▐█████░▐░░░░██════╣
╠═════█░░░░▐░░░░▀▀▀░░▌░░░░░█════╣
╠═════█░░░░░▀▄▄░░░░░█░░░░░░██═══╣
╠════██░░░░░░░░▀▄▄▄▀░░████████▄═╣
╠════█░░░░░█░░░░░░░░░░█═════════╣
╠════█░█████░░░░░█░░░░█═════════╣
╠════██════██░░░░██░░░█═════════╣
╠════█══════█░░░█═███░░█════════╣
╠═══════════█░░░█═══██░█════════╣
╠═══════════█░░░█═════██════════╣
╠═══════════██░░█══════█════════╣
╠════════════█░░█═══════════════╣
╠═════════════█░█═══════════════╣
╠══════════════██═══════════════╣
╚═══════════════════════════════╝
