### ISSUE TITLE
Amendments/Revisions statuses

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1409]
#### Describe the task

This is to capture the changes needed for project Amendments/Revisions statuses and what statuses we need to show based on the revision type.

This is based on the discussion I had with @nanyangpro and @dleard about this topic and we decided to capture the issue in this card for further reference.

#### Acceptance Criteria

- [x] Discuss what to do with `Draft` status for `Amendments`
- [x] Final status for `Amendments` should be `Approved` and for `Revisions` should be `Applied`
- [x] Statuses should have the sequence(`In Discussion` / `Pending Province Approval` / `Pending Proponent Signature` / `Approved` => Amendment AND
`Draft` / `Applied` => General Revision, Minor Revision)
- [x] Only display "In Discussion / Pending Province Approval / Pending Proponent Signature / Approved" if Amendment
- [x] Only display "Draft / Applied" if General Revision or Minor Revision
- [x] tweak `create_project_revision` mutation to conditionally set the `revision_status` based on the `revision_type`
~- [ ] Write a one-time migration to update the `revision_status` of all amendments with `Draft` status to `In Discussion`~ -> this is not required since we don't have any `Amendment` in prod and don't have a way to create an amendment either so all revisions are `General Revisions` with `Draft` status which is correct.

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by nanyangpro** [comment]
Thanks @Sepehr-Sobhani! On an additional note, "Applied" and "Approved" could remain the same on the back-end (like what they are right now). In terms of being displayed to users, the wordings should be different.

**Comment by Sepehr-Sobhani** [comment]
@nanyangpro That's right. It could be just a rewording tweak on the front-end as we already unified them in the back-end.

**Comment by nanyangpro** [comment]
Perfect, thanks @Sepehr-Sobhani!

**Comment by nanyangpro** [comment]
@Sepehr-Sobhani & @dleard - In this ticket, can we add AC:
Only display relevant options for the "Status" field based on the type of the revision record? Currently it's a mixture of all possible statuses no matter what type of revision record it is, which could be confusing for users.
- Only display "In Discussion / Pending Province Approval / Pending Proponent Signature / Approved" if Amendment
- Only display "Draft / Applied" if General Revision or Minor Revision

**Comment by Sepehr-Sobhani** [comment]
@nanyangpro Thanks. I've added those to the AC.

**Comment by LindsayMacfarlane** [comment]
Backlog refinement (Feb 22, 2022): There are still a lot of outstanding questions to support moving forward with amendments and revisions. Taking a pause to do a more in-depth review/whiteboarding session before continuing with the implementation of this EPIC.

**Comment by pbastia** [comment]
@LindsayMacfarlane @Dianadec this a cleanup task for the mixup between statuses of amendments and revisions, and still needed

**Comment by pbastia** [comment]
I confirm the statuses in the right order for amendments and revisions. Thanks @Sepehr-Sobhani !
