### ISSUE TITLE
As an external proponent, I want a nice welcoming landing page, so that I can understand that I am applying and accessing the right funding program

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1411]
#### Description:

A landing page will be the first place Operators come to to log into the CIF web app and see their project information.

[Wireframe in Figma](https://www.figma.com/file/84BpebYIR1iYetxJThLsW6/CIF---External-User-Portal?node-id=213%3A554&t=pGNTtUF8ojCfNKxV-1)

#### Acceptance Criteria:

Given I am an Operator
When I come to cif.gov.bc.ca 
Then I see a nice landing page with a Welcome message
And a button for Administrator login that links me to the IDIR login page
And I DON'T see any login buttons in the header

Given I am an Operator
When I come to cif.gov.bc.ca 
Then I see a button for External Operator login 
And when I click it, it sends me to a placeholder home page after successfully logging in

#### Development Checklist:

- [x] add the welcome message from wireframe, including link, to the current welcome page
- [x] remove login button from header
- [x] add a login button to the welcome page for internal users, which links to the usual CIF internal login
- [x] add a placeholder home page for when external users successfully log in
- [x] add a login button for external users to the welcome page, with a callback url to the placeholder page
- [ ] Meets the DOD

#### Notes:

- Team discussed just reusing the existing landing page for this iteration

#### Definition of Ready (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

#### Definition of Done (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by BCerki** [comment]
Change here: ![image](https://user-images.githubusercontent.com/77306764/217344078-895b6338-5f0b-4f29-bad7-b09128c756b0.png)

**Comment by LindsayMacfarlane** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1411?planning-poker) with Zenhub @mikevespi @dleard @BCerki @gurjmatharu @sam-warren @Sepehr-Sobhani

**Comment by BCerki** [comment]
I don't think this one's ready for estimation--there are still questions in the AC. @mikevespi or @dleard , do you know more details on how we're going to do external login for this first slice? I don't think there's a separate card for it at this point

**Comment by mikevespi** [comment]
For the first slice, we can handle the login in a simple manner. We can do exactly the same thing we do with administrator login, and just give it a different callback URL. So when they log in as an admin we send them to `.../cif/`, whereas when they log in as an external user, they'll get sent to let's say `/cif-external/`. From here, we can hardcode an operator id into our queries and mutations for now so that everyone who tests and demos this can have the same experience. This helps us on our end since we can avoid surprise edge cases showing up in demos, and not being able to reproduce bugs that arise in testing. Once we have BCeId ready to go we can take a look at what the actual login process will look like. Any effort we put in to sing on before that point will likely be tossed for BCeID.

That's my view on it, I'm all ears if anyone has another take. Perhaps BCeId is closer than I thought?

**Comment by LindsayMacfarlane** [comment]
Thank you @mikevespi for volunteering to update the acceptance criteria.

**Comment by LindsayMacfarlane** [comment]
It looks so good! I was able to log in as an 'external user' using my IDIR (as expected in the first slice). Thank you @Sepehr-Sobhani!

**Comment by Sepehr-Sobhani** [comment]
> It looks so good! I was able to log in as an 'external user' using my IDIR (as expected in the first slice). Thank you @Sepehr-Sobhani!

Technically not an `external user` since we don't have that role in place yet (until we get BCeId stuff done) but happy that you liked it so far :)
