### ISSUE TITLE
As an Operator, I want to see a project list, so that I can view all of my projects in one place

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1412]
#### Description:

Dashboard that displays a table where an Operator can see high level information related to their project(s) information.

[Wireframe in Figma](https://www.figma.com/file/84BpebYIR1iYetxJThLsW6/CIF---External-User-Portal?node-id=136%3A798&t=0tjWsdMDBrr6AbMA-1)

#### Acceptance Criteria:

Given I am an Operator
When I am on my dashboard page
Then I see a table that displays my project information

Given I am an Operator
When I am on my dashboard page
Then I can see the status of my project

Given I am an Operator
When I am on my dashboard
And I want to review a specific project
Then I can select the 'view' button under the actions column

#### Development Checklist:

- [x] If #1431 is completed, use the external-specific `ExternalLayout.tsx` (that ticket has a bullet for what to do if this ticket is completed first)
- [x] Create a table with the following columns: Proposal Reference ID, Project Name, Status, Actions (where possible reuse code from `projects.tsx`, `ProjectTableRow.tsx`, and other project table components)
- [x] Status to pull from 'project status' table/field (reuse code from `StatusBadge.tsx)
- [ ] If ticket #1413 is completed, View button should link to an individual project view (that ticket has a bullet for what to do if this ticket is completed first)
- [ ] X

#### Notes:

-

#### Definition of Ready (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

#### Definition of Done (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

**Comment by LindsayMacfarlane** [comment]
@BCerki - is this ready for estimation?

**Comment by LindsayMacfarlane** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1412?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @mikevespi @sam-warren @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Please add your votes @mikevespi @gurjmatharu @sam-warren

**Comment by BCerki** [comment]
@suhafa, the existing project status component we have is grey and squarish: ![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/d02747bf-540c-4ddb-b33f-c93895b65132). We do have a colourful chip component for report statuses, but those statuses are different than the project ones so we can't reuse it as-is.

For the first slice, do you want to use the existing grey component, and then we can make a separate card to create the coloured chip component?

**Comment by BCerki** [comment]
This isn't hooked up to any buttons yet, so to test, visit https://dev.cif.gov.bc.ca/cif-external/externalProjects

**Comment by suhafa** [comment]
@BCerki Thanks for letting me know about this, I'll create a ticket about having colored statuses in detail. For now it should be okay to with the grey component

**Comment by BCerki** [comment]
Note: the statuses shown on this page are the project statuses that are assigned on the internal project overview form. Showing the external status instead will be handled in https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1468 (or I can remove the internal project status column from this PR if we don't want to see it at all)
