### ISSUE TITLE
As an Operator, I want to see a project overview, so that I can see all my project information at a glance

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1413]
#### Description:

Allows Operators to see high level information at a glance related to a specific project. 

[Wireframe in Figma](https://www.figma.com/file/84BpebYIR1iYetxJThLsW6/CIF---External-User-Portal?node-id=209%3A562&t=0tjWsdMDBrr6AbMA-1)

#### Acceptance Criteria:

Given I am an Operator
And I am on my dashboard
When I select the view button
Then my project overview information is displayed
And I see a next button (dead link)
And I see a changes indicator
And I see a return to dashboard link
And I see a tasklist that says "Project Overview" (rest of the tasklist handled outside of first slice)

#### Development Checklist:

- [x] use the external-specific default layout component from https://github.com/bcgov/cas-cif/issues/1431 if available. If not available, use the existing internal default layout component
- [ ] Display all information from the existing Project Overview form (use `ProjectFormSummary` component)
- [ ] Use the existing button, changes indicator, and link components
- [ ] Make a new component for the tasklist (can borrow styling and other pieces from internal tasklist, but functionality will be very different so needs to be a separate component)
- [ ] if not already completed by https://github.com/bcgov/cas-cif/issues/1412, add a link to the individual project pages from the project table view button
- [ ] Meets the DOD

#### Notes:
- As a first step, the team discussed simply showing what already exists in CIF project overview, with the understanding that once we have confirmation from the CIF team, we will hide/remove any information that shouldn't be made public

#### Definition of Ready (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

#### Definition of Done (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by BCerki** [comment]
@suhafa , can you please confirm dev checklist bullet 2 about what's part of the first slice?

**Comment by suhafa** [comment]
@BCerki Thanks Brianna! Ideally we should have all components. The tasklist (no links necessary for now, it just needs to say 'Project Overview') + changes saved function + button 'Next'(albeit greyed out) should be there. Additionally a 'Return to Dashboard' will also be helpful. I suggest this so that the MVP can give a good idea of some placeholder components. Anything you'd flag about this?

**Comment by BCerki** [comment]
> @BCerki Thanks Brianna! Ideally we should have all components. The tasklist (no links necessary for now, it just needs to say 'Project Overview') + changes saved function + button 'Next'(albeit greyed out) should be there. Additionally a 'Return to Dashboard' will also be helpful. I suggest this so that the MVP can give a good idea of some placeholder components. Anything you'd flag about this?

No flags, I added to the AC and dev checklist

**Comment by LindsayMacfarlane** [comment]
@BCerki - is this ready for estimation?

**Comment by LindsayMacfarlane** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1413?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @mikevespi @sam-warren @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Hi @mikevespi @gurjmatharu - please add your estimates

**Comment by LindsayMacfarlane** [comment]
Thank you @gurjmatharu! Looks good.

**Comment by LindsayMacfarlane** [comment]
@suhafa - FYI, some ideas for consideration:
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/3e451902-5183-4c1a-90fe-f659fe79a831)
