### ISSUE TITLE
As a user, I want to see calculated "Total Payment Amount To Date" on the IA funding form, so that I can avoid manual calculations

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1419]
#### Description:

This ticket is broken out from https://github.com/bcgov/cas-cif/issues/1053. To calculate "Total Payment Amount To Date":

For existing IA projects, there are 2 payments in total for each project:
- **Advanced Payment (80%)** at the beginning
- **Project Summary Report Payment (20%)** at the end. (To receive this, IA projects must submit a complete Project Summary Report; it is anticipated that most IA projects will likely receive the full 20% at the end but may be paid less than the full amount if the submitted report is below satisfaction and they fail to follow further directions to improve their report.)
- Before the Project Summary Report Payment is released, "Total Payment Amount To Date" would simply equal to the Advanced Payment that was paid out at the beginning; once the Project Summary Report Payment is released, "Total Payment Amount To Date" would equal to the sum of both payments.

#### Acceptance Criteria:

Given I am a user
When I am on the IA-specific funding form
Then I see a calculated value for "Total Payment Amount To Date" if enough information has been entered to do the calculation
And if not enough information has been entered, I see the default calculated value message provided by the calculated value widget

#### Development Checklist:

- [ ] Update `computed_columns/form_change_calculated_total_payment_amount_to_date` to include the correct calculation (this is already mostly done in https://github.com/bcgov/cas-cif/pull/1420)
- [ ] pgtap tests (also see https://github.com/bcgov/cas-cif/pull/1420)
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by BCerki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1419?planning-poker) with Zenhub @dleard @mikevespi @tmastrom @Sepehr-Sobhani @gurjmatharu @sam-warren

**Comment by pbastia** [comment]
Thank you @tmastrom ! I can see the working calculated field on the funding form of the IA project.
Question: Even if no advance milestone is in the system and paid out, we display that we paid 80% of the maximum funding amount. Is this correct?
