### ISSUE TITLE
Design Contact info view for a project

### ISSUE THREAD

**Issue by rajpersram** [bcgov/cas-cif#142]
#### Checklist:

- [x] Create wireframes
- [x] Review with GGIRCS and CIF team for revisions
- [x] Translate to Figma prototype and upload both designs to corresponding user story ticket 71.

**Comment by rajpersram** [comment]
Designs added to blocked ticket 71.

**Comment by LindsayMacfarlane** [comment]
This ticket looks complete? Unclear as to why it was moved from PO column back into sprint backlog?

**Comment by LindsayMacfarlane** [comment]
Designs complete and uploaded to related user story.
