### ISSUE TITLE
create a functional decomposition diagram (focusing on amendments)

### ISSUE THREAD

**Issue by gurjmatharu** [bcgov/cas-cif#1429]
#### Describe the task

Creating a functional decomposition diagram will allow us to:

> Break down large, complex processes and functions into simpler components. - Help individuals such as stakeholders understand processes better. - Decrease the amount of mistakes made through increased recognition of requirements. 

#### Acceptance Criteria

- [ ] Use a tool of choice to create a a functional decomposition diagram
- [ ] Have key stakeholders approve the diagram
- [ ] Version it and link further amendment issues to it

### Resources
- https://www.figma.com/templates/functional-decomposition-diagram/
- https://www.lucidchart.com/pages/templates/functional-decomposition-example

**Comment by nanyangpro** [comment]
Thanks for confirming, @pbastia! Yes, this has been taken care of and can be closed (unless @gurjeet thinks otherwise. :)

**Comment by gurjeet** [comment]
@nanyangpro , looks like you tagged the wrong Gurjeet.
