### ISSUE TITLE
Design phase and stream definition view

### ISSUE THREAD

**Issue by rajpersram** [bcgov/cas-cif#143]
#### Checklist:

- [x] Create wireframes
- [x] Review with GGIRCS and CIF team for revisions
- [x] Translate to Figma prototype and upload both designs to corresponding user story ticket 62.

**Comment by rajpersram** [comment]
@Peirist Can you confirm the nomenclature of the project steps (Phase, or Status, etc)? Thanks.

**Comment by Peirist** [comment]
Status

**Comment by rajpersram** [comment]
Designs sent to blocked [ticket 62](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/62)

**Comment by LindsayMacfarlane** [comment]
This ticket looks complete? Unclear why it was moved from PO review column into Sprint Backlog?
