### ISSUE TITLE
Determine how to smoothly transition to fields being immutable based on revision_type

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1430]
When we transition to only certain fields can be updated based on revision_type, we will change the possible fields to update for in-progress edits. If CIF has edits in progress with changes that fall under both general and amendment types then some of those fields will all of a sudden be immutable.

We've already had some discussion on this & an idea proposed is to identify this as a risk, write a script that will determine whether there are any revisions in flight that have changes that could be considered amendments & handle that if necessary. If the script determines that all in-flight edits are General Revisions, then no action will be necessary. Otherwise, we may need a migration to split those into their respective types (amendment/general revision) based on the fields changed.

**Comment by LindsayMacfarlane** [comment]
Backlog refinement (Feb 22, 2022): There are still a lot of outstanding questions to support moving forward with amendments and revisions. Taking a pause to do a more in-depth review/whiteboarding session before continuing with the implementation of this EPIC. 

- I have left this ticket in our sprint backlog; however, it could potentially be pulled out and back into the backlog.

**Comment by dleard** [comment]
@LindsayMacfarlane @pbastia This ticket is likely not needed as it was an issue with the pre-defined field splitting based on revision type, which we are not doing anymore. Once we've confirmed a way forward this can be closed

**Comment by dleard** [comment]
closing this as we have decided on a non-locking solution for amendments & revisions where no fields will be immutable based on type
