### ISSUE TITLE
As a developer, I want an external applicant-specific layout component, so that I can use on all external applicant pages

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1431]
#### Description:

The existing `DefaultLayout` component contains internal-specific elements. This card is about creating a default layout component specific to the external operator.

Wireframe: https://www.figma.com/file/84BpebYIR1iYetxJThLsW6/CIF---External-User-Portal?node-id=209%3A562&t=YNq955131rxLiI2K-0

#### Acceptance Criteria:

Given I am a developer
When I work on external operator cards
Then I have access to an external operator default layout component

Given I am using the external operator default layout component
When I view the component on the front-end
Then I see the same header as the internal operator layout
And a subheader with the links from the wireframe 
And a footer with the links from the wireframe

#### Development Checklist:

- [ ] Create a file containing the footer links (look at `data/dashboardLinks/footerLinks` for an example). For any unconfirmed links, just make a dead link (see below for link list)
- [ ] Create a file for the subheader links (look at `data/dashboardLinks/subHeaderLinks`). For unconfirmed links, dead link
- [ ] Create an external-specific default layout component (look at `DefaultLayout.tsx`). When using Subheader and Footer components, use the links objects created above as props
- [ ] If necessary, create an external-specific `Navigation` component (the existing one might have enough props to customize it for external operators)
- [ ] If any of the other first slice tickets are completed before this one, replace their `DefaultLayout` component with the external-specific one.
- [ ] Meets the DOD

#### Links Checklist (for the link locations of the sub-header and footer):

_**Sub-header**_
- [x] _Home_ - Leads to project list/dashboard
- [x] _Email Us_ - For now, let's have it point to a mailto function that opens up their Outlook, pointing to this email (will need to confirm this with program area): [CleanBCIndustryFund@gov.bc.ca](mailto:CleanBCIndustryFund@gov.bc.ca)
- [x] _Contact Information_ - For now this will have to be an empty link, meaning it appears as a link but doesn't do anything when you click on it.

_**Footer**_
- [x] _Program Details_ - https://alpha.gov.bc.ca/gov/content/environment/climate-change/industry/cleanbc-industry-fund (will need to confirm with program area if they prefer it to link to this page or something else)
- [x] _Disclaimer_ - https://www2.gov.bc.ca/gov/content/home/disclaimer
- [x] _Privacy_ - https://www2.gov.bc.ca/gov/content/home/privacy
- [x] _Accessibility_ - https://www2.gov.bc.ca/gov/content/home/accessible-government
- [x] _Copyright_ - https://www2.gov.bc.ca/gov/content/home/copyright

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by BCerki** [comment]
@suhafa, do we already know where all the header/footer links will lead? If yes, it's quick to put them in as part of this ticket. If no, we can just have them not work yet

**Comment by suhafa** [comment]
@BCerki HI Brianna, I updated the description to include a check list of the URLs and those that will have a link later.
As for the second question - yes! That works.

**Comment by gurjmatharu** [comment]
@LindsayMacfarlane nothing to really test here until the external pages are built.  This is just to enable them.

**Comment by LindsayMacfarlane** [comment]
Awesome! Thank you for tackling this ticket @gurjmatharu !
