### ISSUE TITLE
Dev data "IA" projects are actually EP projects

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1435]
###Description of the Tech Debt###

In `new_form_data`, `'fundingStreamRfpId'` is the `id` in the `funding_stream_rfp` table, NOT the `funding_stream` table. This means that a `fundingStreamRfpId` of 2 isn't an IA project; it's a particular EP year.

To fix:
- in `004` dev data, change the `fundingStreamRfpId` to one of the IA ids
- in `006` dev data, update the funding agreement where clause to filter by the new `fundingStreamRfpId`

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| TOTAL SCORE:                                                                                                                  |       |       |

**Comment by BCerki** [comment]
Lindsay, I think you can test this in dev by clicking on one of the dev data IA projects and confirming it has the right funding stream

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! Tested in dev:
- reviewed existing IA projects 
- created new 2022 IA project and confirmed it has the correct funding stream 
Projects appear to be displayed correctly.
