### ISSUE TITLE
Plan out second slice for external operator application

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1439]
#### Describe the task

We've scoped out the first slice of work for the MVP. This ticket is to plan out the scope for the second slice, update design if needed and create tickets

#### Acceptance Criteria

- [x] Meeting to discuss second slice features
- [x] Create tickets
- [x] Refine AC of tickets 
- [x] Update Designs

#### Additional context

- None yet

**Comment by suhafa** [comment]
Hi @Dianadec & @LindsayMacfarlane - created this ticket for mapping out the second slice!

**Comment by suhafa** [comment]
Feb 23:
- Team met up to scope out second slice, which is for the user to be able to submit high level project information and related documentation. 
- By June 2023, Lindsay hopes to allow users the ability to view applications and upload documents
- Design wise, minor updates will be needed depending on how tickets are scoped. Need to verify Program Details URL with CIF
- Research wise, explore RFP generation, clarify fields that will be displayed from Internal App (#1406)
- Bug discussed: The inactivity dialog box opens up despite the user being active in the session in the internal app @mikevespi 
- Dev wise, need to explore feature flag for submission, needs 1 or?

@LindsayMacfarlane to create starter tickets.

**Comment by LindsayMacfarlane** [comment]
Thank you @suhafa! I'm really enjoying the 'slice' approach to this work so that we are really focusing on the right things in a more iterative way.
