### ISSUE TITLE
As a CIF user, I want to delete attachments uploaded to a project, so that I can remove unneeded or duplicate attachments

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1441]
#### Description:

There is currently no way to remove attachments once they are uploaded to a project. A delete button should be implemented to allow users to delete attachments.

#### Acceptance Criteria:

Given I am viewing the attachments page
When I want to remove an attachment
Then I see a delete button for each attachment

Given I have uploaded an attachment
When I click the delete button for that attachment
Then the attachment is removed from the project

#### Development Checklist:

- [x] Add a delete button to the AttachmentTableRow component
- [x] On click, it should update the corresponding attachment in the database to be 'archived'
- [x] The graphql query on the attachments page should filter out archived records
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1441?planning-poker) with Zenhub @BCerki @gurjmatharu @mikevespi @sam-warren @tmastrom

**Comment by LindsayMacfarlane** [comment]
@mikevespi - awaiting your estimate on this one :)

**Comment by LindsayMacfarlane** [comment]
Thank you @sam-warren! Tested in dev and I was able to upload and delete a file related to a project. Thank you for your work on this one :)
