### ISSUE TITLE
As a user, I want the calculated field on the Budgets, Expenses & Payments form to update dynamically, so that I can see what effect my data entry has on calculations immediately

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1448]
#### Description:

On the Budgets, Expenses & Payments form, when Additional Funding Source(s) and Amount(s) are added, it impacts the calculated value of the following fields:
- Total Project Value
- Proponent's Share Percentage

However, the changes in value of the above fields are only reflected on the front-end after the revision is submitted. We want to display the changes immediately to the users before they submit the revision.

#### Acceptance Criteria:

Given I am a user filling out the **Budgets, Expenses & Payments** form
When I update any of the values used to calculate the **Total Project Value** field and the **Proponent's Share Percentage** field
Then the calculation updates immediately

#### Development Checklist:

- [ ] The computed column should take a `form_change` as an argument (not a project revision or a record from any other table). If the computed column is on something other than `form_change`, deprecate it and make a new computed column called `form_change_[computed column name]`. 
- [ ] Update/rewrite the calculation so that it calculates the value based on the most recent form change
- [ ] Update the graphql query and form on the front-end to use the new computed column (skip this step if the column is just revised, not new)
- [ ] Example of a computed column that correctly uses `form_change`: computed_columns/form_change_calculated_net_amount_this_milestone.sql
- [ ] Example of a PR that converts a computed column on project_revision into one that takes `form_change`: https://github.com/bcgov/cas-cif/pull/1389/files#diff-2aa18f386b9662410b092bb8ff4c196167e59099c55fa48036bb99c69d21502f
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

**Comment by nanyangpro** [comment]
Thanks for open the issue, @BCerki! - I've added in details to both ticket title and description with previous discussions in Teams and Miro copied over below.

@LindsayMacfarlane's comment: We should probably have a standard approach to this. It would be good to get dev perspective on this one. My assumption would be that nothing should auto calculate until submitted.

@nanyangpro's comment: I strongly agree with Lindsay on having a standard approach, but have the opposite assumption in terms of displaying updates for the calculated fields. I'm open to either approach which makes the most sense, your perspectives would be appreciated.

@BCerki's comment: I believe we decided to go with immediate autocalculation because otherwise we end up with bugs related to out-of-date information.

**Comment by nanyangpro** [comment]
Hi @BCerki - I re-tested the issue as described in the ticket after the debrief session (Mon, Feb 27) with @LindsayMacfarlane, and realized that the **Total Project Value** and **Proponent's Share Percentage** fields are auto-updated based on the Additional Funding Status. I'll close this ticket confirming there's no correction needed here.

On another note, I noticed that the updates for the impacted fields aren't showing up on the diff page, only the ones that are mannually updated by users are there. Are we intentionally doing so? If yes, why? If no, should we create a ticket addressing it? @BCerki, @dleard
