### ISSUE TITLE
Explore RFP Generation Design

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1452]
#### Describe the task

RFP generation feature needs to be scoped, designed and validated by CIF Team. 

#### Acceptance Criteria

- [x] Identify RFP generation pattern by CIF
- [x] Document potential constraints
- [x] Brainstorm with devs how we can best incorporate this feature in External (and Internal?) facing app 
- [x] Brainstorm with devs the new format for RFP, and constraints
- [x] Confirm RFP patterns with CIF
- [x] Suggest an alternative to the current format of RFPs
- [x] Document the decisions taken
- [x] Create necessary tickets

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
In discussion with the CIF Ops and Tech team on Apr 18, we agreed to assign a temporary ID called 'Submission ID', which will later get overridden with the RFP ID after the CIF team reviews the application and manually enters the numbers. Some outstanding questions:
- how should the 'Submission ID' be visible to the Internal team?
- what should the temporary 'Submission ID' look like?

**Comment by pbastia** [comment]
Thank you @suhafa ! Work completed as expected
