### ISSUE TITLE
As an External Operator, I want to create an application, so that I can be successful in getting my project funded

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1453]
#### Description:

Providing a feature that allows proponents to create and submit new applications/projects for consideration of CIF funding. 

[Wireframe of workflow in Figma](https://www.figma.com/file/84BpebYIR1iYetxJThLsW6/CIF---External-User-Portal?node-id=141%3A620&t=7NI0JkoHbRTs761L-1)

#### Acceptance Criteria:

Given I am a Proponent
When I am on my dashboard
Then I can see a button that allows me to create an application

Given I am a Proponent
When I select the button to create an application
Then I am brought to the application overview page

Given I am a Proponent
When I am on the application overview form
Then I can see a "return to dashboard link"

Given I am a Proponent
When I am on the application overview page
Then I can enter information related to funding Funding Stream, Project Name and Legal (company) Name (facility name not to be included in this ticket)

Given I am a Proponent
When I am on the application overview form
Then the Funding Year field is prepopulated with the current application funding year

Given I am a Proponent
When I make changes to the application overview form
Those changes are saved in real time
and I see the changes saved indicator

~~Given I am a Proponent
When I click the "Save and continue" button on the application overview form,
Then I am brought to the attachments page for that application~~ (postponed until next slice)

#### Development Checklist:

- [x] Create application overview page. The form schema can be added to `cif.form` via a file in `schema/data/dev`, or can live in the front end for now while it goes through the first wave of changes.
- [x] Add create button to dashboard, onClick ~~creates a new application in `cif.application` creates a new project in the projects table (sets any required fields that aren't part of the application for to `null` (?))~~ creates records in the `form_change` table
- [x] ~~UpdateApplication debounced mutation~~
- [x] Funding year - to be auto generated 
- [x] Funding stream - two options: EP and IA
- [x] Save Button
- [x] return to dashboard link may already be included in stepper/tasklist file, but if not, add
- [ ] Meets the DOD

#### Notes:

- We can consider splitting some of these acceptance criteria into multiple tickets.
- Note there are some mandatory fields on the internal side that need to be scoped and/or determined whether we can have proponents complete (e.g., project description, sector, total funding request).  (ADDRESSED)

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by mikevespi** [comment]
@LindsayMacfarlane I hadn't thought about this, but given what we've heard about the amount of contact required with the proponent during the application phase, is the intention for CIF Administrators to be able to see applications that have not been submitted yet? And if so, do they have the ability to edit them?

**Comment by suhafa** [comment]
@mikevespi That is a good question, I'll ask this in our upcoming session today

**Comment by BCerki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1453?planning-poker) with Zenhub @pbastia @dleard @sam-warren @gurjmatharu @Sepehr-Sobhani @mikevespi @tmastrom

**Comment by Dianadec** [comment]
@tmastrom @sam-warren - reminder to add your estimates please

**Comment by BCerki** [comment]
A couple notes:
- funding stream needs to be immutable so as discussed, external project creation will go through the same initial workflow as internal (pick stream then redirect to rest of form)
- attachment workflow has been moved to next slice so for now, the "Save"/"Submit Application Overview" button is dead (changes are still being saved per the changes indicator)

**Comment by pbastia** [comment]
Thanks for the excellent work @BCerki !
Just one comment - the pre-populated year selector doesn't seem to work and prevents me from going to the next page when creating an application, there might be something I'm doing wrong.
Do you mind going through that together when you have time?

**Comment by Sepehr-Sobhani** [comment]
Excuse me for interrupting your conversation, but that issue is not related to this card and we have a PR ready to merge for fixing that issue. @pbastia 
https://github.com/bcgov/cas-cif/pull/1615

**Comment by pbastia** [comment]
Thanks @Sepehr-Sobhani ! I'll wait until that card is finished and merged, since the issue prevents from testing this card.

**Comment by pbastia** [comment]
Thank you @BCerki and @Sepehr-Sobhani ! I was able to test this feature.
There is one unintended effect, probably linked to the fact that we mock project data? I filed a bug for it: #1651

**Comment by Sepehr-Sobhani** [comment]
Oooh, that's not good, Thanks for capturing that. @pbastia
