### ISSUE TITLE
As a External Operator, I want to be able to review my application information before I submit, so that I can confirm that all my information is correct

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1454]
#### Description:

NOTE: check the status of https://github.com/bcgov/cas-cif/pull/1558/files before implementing this because it includes creation of the `formStructure`

Ability for proponents to review their application before submitting so that they can double check and confirm that everything is correct.

#### Acceptance Criteria:

Given I am an external user
When I click the "Review" link in the stepper (stepper created in https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1413)
Then I am taken to a summary page

Given I am an external user
When I view the review page
I see a top section (see wireframe) that contains a "Review" header and text

Given I am an external user
When I view the review page
I see an application overview section (see wireframe) that contains a "Application Overview" header and a summary of the filled-in information
and this section is collapsible

Given I am an external user
When I view the review page
I see a "Save and continue" button
and when I click it my project is submitted

Wireframe elements not included in this ticket
- attachment summary (in https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1470)
- conditional alert about submitting empty form

#### Development Checklist:

- [x] create the summary page (cas-cif/app/pages/cif-external/project-revision/[projectRevision]/index.tsx)
- [x] create the top section using existing components if possible
- [ ] replace our `ProjectOverviewSummary` component with CCBC's to match the design (includes collapsibility
- [x] on submit,  commit project to project table and save attachments (commit function handled in https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1515, just need to wire it up)
- [x] if the application overview form doesn't already automatically link to this summary page, wire it up
- [ ] Meets the DOD

#### Notes:

-

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by mikevespi** [comment]
@LindsayMacfarlane  @suhafa  for this, are you envisioning something along the lines of our "Summary" page that we currently send users to before the finally create a project? 

Remember there won't be any "diffs", as every field at this point is being added, not changed. So the summary page would essentially be a nicely laid out "view only" version of the form they just filled in. No issues with it, just want to make sure we're aligned.

**Comment by LindsayMacfarlane** [comment]
@mikevespi - yes, view only for this slice. Thanks for checking :)

**Comment by BCerki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1454?planning-poker) with Zenhub @dleard @gurjmatharu @mikevespi @pbastia @sam-warren @Sepehr-Sobhani @tmastrom

**Comment by LindsayMacfarlane** [comment]
Hi @sam-warren and @tmastrom - please add your vote.

**Comment by pbastia** [comment]
Thank you @gurjmatharu ! This works as intended
