### ISSUE TITLE
As a CIF Administrator, I want to be able to add relevant documentation via an attachment form before I submit a project, so that I can have a better user experience

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1462]
#### Description:

Feedback from CIF: "wondering if we can look at having attachments added as an 8th tab (ex. "8. Attachments") instead of having it appear after the project has been submitted?" 

Currently, the attachments feature is only displayed after a project is created.

Since https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1515 was implemented, attachments are now handled by form changes.

Note: diffs will be handled in https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1680

#### Acceptance Criteria:

Given I am a CIF administrator
When I create or edit a project revision (i.e., the tasklist is in edit mode)
Then on the tasklist I see an eighth tab called `8. Project Attachments`
And when I click on it, it expands and shows a link called "Project Attachments" that leads to the editable project attachments form (editable project attachments "form"=the existing attachments table, `app/pages/cif/project-revision/[projectRevision]/attachments.tsx`)

Given I am a CIF administrator
When I view a project revision (i.e., the tasklist is in view mode)
Then on the tasklist I see an eighth tab called `8. Project Attachments`
And when I click on it, it expands and shows a link called "Project Attachments" that leads to the view-only project attachments form (view-only project attachments "form"=the existing attachments table, `app/pages/cif/project-revision/[projectRevision]/attachments.tsx`, with the upload button removed)

Given I am a CIF administrator
When I submit a project or approve/apply a project revision
Then the project attachment form changes are committed

Given I am a CIF administrator
When I am creating a project with attachments and I reach the review page (`app/pages/cif/project-revision/[projectRevision]/index.tsx`
Then I see a list of the attachments I added

#### Development Checklist:

- [x] Since [#1515](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1515), attachments are form_changes
- [x] Add attachments section to the tasklist
- [x] Make upload button show conditionally

- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
This would be quite easy, development wise. An easy win, especially if it makes it easier to adopt

**Comment by pbastia** [comment]
This would be quite easy, development wise. An easy win, especially if it makes it easier to adopt

**Comment by mikevespi** [comment]
To clarify, attachment uploads would still not belong to a specific project revision correct? This is just a matter of exposing the page during the creation process?

**Comment by pbastia** [comment]
Correct @mikevespi

**Comment by BCerki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1462?planning-poker) with Zenhub @dleard @gurjmatharu @JoshLarouche @pbastia @sam-warren @Sepehr-Sobhani @tmastrom

**Comment by BCerki** [comment]
In addition to the AC, I removed the "Delete" attachment button on the view-only pages so that they truly are view-only

**Comment by pbastia** [comment]
@BCerki excellent work! The last AC doesn't work for IA projects unfortunately
> Given I am a CIF administrator
When I am creating a project with attachments and I reach the review page (app/pages/cif/project-revision/[projectRevision]/index.tsx
Then I see a list of the attachments I added
