### ISSUE TITLE
As a CIF Administrator, I want to be able to track waste as a sector category, so that I can accurately capture and report out on sector related projects

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1463]
#### Description:

Feedback from CIF: Can we look at adding "Waste" to the sector drop down list under the project overview tab? One of the 2020 projects (for ex. 2020-RFP-1-VANC-193) has "waste" listed as their sector and Im not able to complete this section (sector is a mandatory field). Or if it makes sense, what about making the sector field "optional" like the Project Type field above it?

#### Acceptance Criteria:

Given I am an admin user
When I am on the project overview form and select the sector dropdown
Then I have "Waste" as an option

~~Given I am an admin user
When I am on the project overview form 
Then I filling out the sector dropdown is optional and does not prevent form submission~~

#### Development Checklist:

- [ ] Add "Waste" to the `cif.sector` table using a 001 file (see `report_type`/`report_type_001` for an example)
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by BCerki** [comment]
@nanyangpro / @suhafa, do you know if/why sector is mandatory?

**Comment by suhafa** [comment]
From a past ticket (#645): _"Tech team wants to know the sector the projects are in. They like to filter projects by sector for when they receive requests for information by sector. Currently the sector is an open field in the spreadsheet, the sectors are not official sectors such as NAICS--just a list of sectors the team uses."_ 
It helps the Tech team filter out projects so that may be one reason why.

**Comment by BCerki** [comment]
Based on @suhafa 's comment above, I'm going to write this ticket with sector remaining mandatory

**Comment by BCerki** [comment]
This should be done by https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1718
