### ISSUE TITLE
As a CIF administrator, I want to see the "Payment Percentage of Performance Milestone Amount" between 0 and 100%, so that the number makes sense from a payment perspective

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1478]
#### Description
On the Emissions Intensity Report page, the "Payment Percentage of Performance Milestone Amount" field is a percentage between 0% and 100%. The proponent gets the full/reduced payment or nothing.

If the calculated value goes over 100%, display 100%. If the calculated value goes negative, display 0%.

#### Acceptance Criteria

Given I am a CIF administrator
When I edit the TEIMP report
Then the "Payment Percentage of Performance Milestone Amount" field is clamped between 0 and 100%

Given I am a CIF administrator
When I edit the TEIMP report
Then the "Actual Performance Milestone Amount" field is calculated based on the clamped payment percentage value

Dev checklist

- [x] update postgraphile computed columns to reflect that logic
- [x] make sure tests cover negative and very large calculated payment percentage values

#### Additional context

![image.png](https://images.zenhubusercontent.com/5e3b4990c0f4cb9e2c9b1b1e/18a75be6-957f-4160-b48d-1c2403536664)

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1478?planning-poker) with Zenhub @pbastia @dleard @tmastrom @Sepehr-Sobhani @BCerki

**Comment by Dianadec** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1478?planning-poker) with Zenhub @sam-warren

**Comment by LindsayMacfarlane** [comment]
Thank you @sam-warren. Tested in Dev and it appears correct; however, this will be one we want the program area to review.
