### ISSUE TITLE
Correct display of the Gross/Net/Holdback Payment Amounts This Milestone

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1480]
#### Describe the task

Currently for each Milestone Report, as long as the "Maximum Amount This Milestone" field is filled out, the system calculates and displays the "Gross/Net/Holdback Payment Amounts This Milestone" fields. However, this isn't the accurate behaviour and could mislead the users.

For **Reporting Milestone**:
- No expenses, no payments, nothing needs to be corrected.

For **Advanced Milestone**:
- Discard the "Total Eligible Expenses" field
- Calculate and display the "Gross/Net/Holdback Payment Amounts This Milestone" only after the "Report Received Date" field is filled out. Otherwise, display _"This field cannot be calculated due to lack of information now."_.

For **General Milestone**:
- Calculate and display the "Gross/Net/Holdback Payment Amounts This Milestone" only after the "Total Eligible Expenses" and "Report Received Date" fields are filled out. Otherwise, display _"This field cannot be calculated due to lack of information now."_.

![image.png](https://images.zenhubusercontent.com/5e3b4990c0f4cb9e2c9b1b1e/3c9c3ea7-358c-4304-b024-fd2b3d679842)
#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by LindsayMacfarlane** [comment]
Note: I removed this ticket from the 'milestone' epic. A new epic for user feedback will be created to start capturing improvements from the recent usability testing and general use of the app.

**Comment by nanyangpro** [comment]
That's way more accurate. Thanks @LindsayMacfarlane!

**Comment by Dianadec** [comment]
@pbastia and @LindsayMacfarlane can this card be closed since it was split into two? 1513 and 1514

**Comment by pbastia** [comment]
Yes! Closing
