### ISSUE TITLE
External Intake database prework

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-cif#1495]
#### Describe the task

Database work to support the external intake process.

Since the requirements for external intake are still being discovered, and the feature will be hidden behind a Growthbook flag for the foreseeable future, we would like to keep our DB work out of the `sqitch.plan` to avoid some sqitch immutability headaches. For now, we will do our application specific db work in `schema/dev`.

- [ ] application table: 
   - id pk not null
   - funding_stream_rfp_id int
   - legal_name varchar(1000)
   - facility_name varchar(1000)
   - project_name varchar(1000)
   - upsert the timestamp columns (`select cif_private.upsert_timestamp_columns('cif', 'application');`

- [ ] application_attachment table:
id integer primary key generated always as identity,
   - id pk not null
   - file uuid,
   - description varchar(10000),
   - file_name varchar(1000),
   - file_type varchar(100),
   - file_size varchar(100),
   - application_id integer not null references cif.attachment(id),
   - uploaded_at timeztamptz, (with a trigger to set to now() on create)

**Comment by BCerki** [comment]
Design in dev/design sync: applications will go into the project table

**Comment by dleard** [comment]
@pbastia @LindsayMacfarlane I am closing this ticket because we have decided not to use an 'application' table
