### ISSUE TITLE
Project contact form errors if there are no contacts in the system [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1496]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 1
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- clear all the contacts from the database
- try to add a contact to a project
- receive error

Screenshots:
https://www.loom.com/share/833d5d31f7c548489b31a27f82b52951

Additional information:
- in `ProjectContactForm`, `filteredProjectContactFormChanges` and `allForms` don't handle empty arrays properly

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by pbastia** [comment]
@sam-warren thank you! There is no real way of testing this in -dev so I'll mark this as approved.

**Comment by pbastia** [comment]
@sam-warren thank you! There is no real way of testing this in -dev so I'll mark this as approved.
