### ISSUE TITLE
revise tasklist to include external cif needs as well 

### ISSUE THREAD

**Issue by gurjmatharu** [bcgov/cas-cif#1506]
#### Describe the task

Currently our task has been designed for internal use.  We need to extend this design to allow for external cif use as well. This will allow us to ensure we keep things DRY.
  Some points to consider:
- the top level elements are links with underlines for external facing
- there is no caret dropdown (yet?)
- the top level elements act as links

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by pbastia** [comment]
Tagging @suhafa - are we looking at 2 different versions of the task list?

**Comment by suhafa** [comment]
@pbastia We decided to have our current task list but very simplified, i.e. without the subtasks or progress statuses for the MVP. We could later borrow CCBC's design for the stepper. The idea is to keep it easy enough for external users to use without the complexity on the internal side. As for the top header, it doesn't need to be there. The copy of the task list is different as well on the internal side.

**Comment by pbastia** [comment]
In terms of development, we might want to look at a separate component to cut down on customization effort. The current implementation of the internal task list is already quite large, with all the relay fragments

**Comment by pbastia** [comment]
The external portal being different enough in terms of design, trying to add one more use case in an already complex internal component is a lot of effort for little value. Closing
