### ISSUE TITLE
As a External Operator, I want to submit an application without all the fields entered, so that I can have that flexibility

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1512]
#### Description:

This ticket includes allowing the user the ability to submit an application without putting in all the form details. It also includes showing an alert to let the user know they have incomplete fields, as well as a checkbox that allows them to acknowledge the incomplete fields before submission. 

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

?**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

- Ticket made after conversation  on #1454

**Comment by pbastia** [comment]
@suhafa which fields are currently mandatory that we would want to make optional?

**Comment by suhafa** [comment]
@pbastia we've not had a conversation on that with the CIF team just yet, I can confirm this and get back to you Pierre

**Comment by suhafa** [comment]
Workflow Suggestion: 

We could consider a workflow similar to what we have on the Admin side, where the user first selects a Funding Stream and the input is locked down before they get to any other fields. This way, the attachments for that Funding Stream can remain in place. If they want to change the Funding Stream again, they can create a new application.

**Comment by pbastia** [comment]
I think that makes sense

**Comment by pbastia** [comment]
This is already done with the current designs. @nanyangpro I suggest closing this

**Comment by nanyangpro** [comment]
Agreed, @pbastia. I'll close it.
