### ISSUE TITLE
As a CIF maintainer, I want the database structure to be refactored, so that I can support current attachments handling

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1515]
#### Describe the task

Supporting attachment upload for external users requires changing the way attachments are currently handled in the db. Previously, the attachment table had information about what project and status an attachment was related now. Now, the attachment table will just hold file information, and join tables for each type of attachment (external, reporting, etc.) will hold more info. We need to do this because we don't have project_id until projects are committed, but external applications need to upload attachments during project creation when the project is still a draft.

See the ERD for more details.

 

- [x] Create a new `project_attachment` table:
   - id
   - project_id (fkey ref to project table)
- [x] Add `project_attachment` into the form table 
- [x] Migration to add existing attachment files to the `project_attachment` table

- [x] In the existing attachment table:
   - remove project_id column
   - remove project_status_id column

- [x] Update the current upload mutation to use this new table and create form changes for attachments
- [x] Update archive mutation

- [x] All the new tables, migrations, and values described above exist
- [x] tests

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by pbastia** [comment]
This is a substantial amount of work - I suggest either estimating this task or making it a story @LindsayMacfarlane @Dianadec

**Comment by pbastia** [comment]
@BCerki to point #7 I think the default commit should work, we're not looking at splitting one schema to multiple tables (the upload mutation will take care of creating entries in the attachment table)

**Comment by Dianadec** [comment]
Once this card has been split, we can look at potentially pulling them into the sprint (Mar 13- 31)

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1515?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @sam-warren @Sepehr-Sobhani @tmastrom

**Comment by pbastia** [comment]
Not much to test here - this is prework for future attachment features. Thank you @Sepehr-Sobhani !
