### ISSUE TITLE
Prepare user testing script for external portal

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1520]
#### Describe the task

Based on the scope identified, prepare a script for conducting usability tests for the external portal MVP

#### Acceptance Criteria

- [x] Prepare draft script
- [x] Look out for good usability testing tools
- [x] Test to see if testing session falls under 45 minutes
- [x] Prepare note-taking document
- [x] Loop in LM/NY/Dev for input and role assigning 

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
Currently looking at Calendly and Self-Booking tool by Microsoft for scheduling
Also experimenting with Blossom, Maze and Loom for recording + time stamping purposes

**Comment by suhafa** [comment]
Materials for usability testing prepared. Research goals, Testing script and Observer's notes have been created.

**Comment by suhafa** [comment]
Material prepared and shared with the team for review. It is ready to be adapted to any format the testing will happen in (async, during workshop or one-on-one remotely). Note that we need some clarification on how the user will access the test format, and the user will need to be sent credentials as well as attachments for the smooth running of the testing c:

**Comment by LindsayMacfarlane** [comment]
Hi @suhafa! Thank you for all your work on preparing this usability script. I've added in some comments/edits (in particular around privacy), but overall, this is great. It looks like this document is stored in our Scrum Channel files - I wonder if we should move it to the CIF Internal Users channel for transparency and feedback with the CIF team?  

I've also provided a link to our signed external user engagement PIA. In this document includes a standard participant consent form that all external participants will need to complete. https://bcgov.sharepoint.com/:b:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/Privacy%20security/External%20User%20Engagement/ENV22010%20-%20PINT-344%20-%20External%20User%20Engagement%20-%20PCT%20Signed_ADM%20Signed.pdf?csf=1&web=1&e=JyJhsg
