### ISSUE TITLE
Improve the diff section design to provide clearer context of the changes and alert to users

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1523]
#### Describe the task

Following the technical design solution as discussed and agreed with @pbastia and @dleard on Wed, Mar 8, we need to improve the design of the diff section for an Amendment or General Revision to provide clearer context of the changes and alert the users when needed.

In summary,
- Only 1 open Amendment and/or 1 open General Revision at a time
- Before a revision record is applied/approved, under the diff section, for a changed field, instead of showing `{field name}: {initial value when the record was created} -> {updated value}`, we will show `{field name}: {latest committed value} -> {updated value}`

For the improved design, we need to address the following scenarios:
1. Display fields that are changed by the user, and **alert the user if the fields have been changed by other users after the current revision record was created and before it is applied/approved**
2. Display auto-calculated/populated fields impacted by the user's changes

#### Acceptance Criteria

- [x] Update the design with rapid prototypes
- [x] Validate the usability/accessibility of the improved design with CIF and the developers
- [x] Iterate/improve design based on the input
- [x] Create user stories for implementation

**Comment by nanyangpro** [comment]
@dleard's comment: 
> 1523 is necessary before implementing the very permissive editing flow. They will need to see what has changed since they started their revision/amendment and be able to decide which change to accept.

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket is ready for you to review and can be closed with:
- Design of the diff section refined and reviewed with both CIF and the developers
[- Design: Sequential Scenario 1](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF---Internal-User-Portal?node-id=7633%3A4258&t=9ZUtWsS7W7FVvhtv-1)
[- Design: Sequential Scenario 2](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF---Internal-User-Portal?node-id=7636%3A403&t=9ZUtWsS7W7FVvhtv-1)
[- Design: Sequential Scenario 3](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF---Internal-User-Portal?node-id=7636%3A669&t=9ZUtWsS7W7FVvhtv-1)
[- Design: Cleaner Version preferred by users, nice-to-have, out of scope of this ticket (Sequential Scenario 2)](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF---Internal-User-Portal?node-id=7647%3A912&t=9ZUtWsS7W7FVvhtv-1)
- #1569 created for dev refinement and implementation
- #1573 created for the cleaner version as preferred by users, which is labelled as a "nice-to-have"

**Comment by LindsayMacfarlane** [comment]
Thank you @nanyangpro for all your work on this design task!
