### ISSUE TITLE
As a CIF administrator, I want to see the most recent data in the summary of a revision/amendment, so that I know what I am about to override

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1528]
#### Description:

This is about pulling the data needed for #1523 when the designs have been finalised.

Context:
The summary of an amendment/revision needs to display, for each field impacted by that revision:
- the data when the revision was started
- the latest data in the system, that might have been updated by other revisions
- the data that has been changed by this revision, and that will override all previous changes.

This is about pulling the data from graphql, and crudely displaying it on the summary. Refined UX will be provided by #1523 and implemented in a separate ticket.

#### Acceptance Criteria:

Given I am about to commit a revision or amendment
When I look at the changes about to be written
And some changes have been made to fields this revision impacts, since this revision was started 
Then I can see the values about to be overridden

#### Development Checklist:

- [ ] Graphql query to pull the latest state of the system
- [ ] Crude frontend printout of that value
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

?**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1528?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @mikevespi @sam-warren @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
@dleard @gurjmatharu @sam-warren please add your estimate

**Comment by Dianadec** [comment]
Need to clarify whether this is a first step.

**Comment by pbastia** [comment]
I confirm that the summary page pulls, in addition from the diff, the latest committed data from the system. Thank you @BCerki !
