### ISSUE TITLE
CIF Business Value Matrix 

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#153]
#### Description:
Create a business value matrix in collaboration with CIF to help identify highest value items for development.

#### Checklist:
- [x] Meet with MZ and TP to discuss value and goal of exercise
- [x] Work with TP to define business values
- [x] Review with Matt for feedback

#### Notes:
- Split ticket into cas-cif#322

**Comment by LindsayMacfarlane** [comment]
Hi @Peirist - I've created this ticket to help capture the work related to the business value.

**Comment by LindsayMacfarlane** [comment]
Hi @Peirist @jaimiebutton @Sriram-pc 

I had a quick conversation with Matt last Friday about the business values and our upcoming conversation on Friday Jan 14. In preparation, Matt has recommended that we pick a user story as an example to demo the concept and how it works in practice. Is there a user story you think would best highlight how BV works?

**Comment by Sriram-pc** [comment]
@LindsayMacfarlane #69 (Create Project) looks like a good user story to explain the Business Value.
