### ISSUE TITLE
Map out what other fields can be displayed to proponent from the Reports on the internal side

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1530]
#### Describe the task

We mapped out with the Ops team what they would like to see on the external app from the Project overview on the internal side (#1406). This ticket is for mapping out how to display report information (Milestones, Quarterly and Annual Reports) on the external app from the internal side

#### Acceptance Criteria

- [x] map out/document all fields in application pertaining to reports
- [x] review with CIF team to determine what fields can be made viewable to proponents
- [x] update map/document with feedback from CIF team
- [x] update our team

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
@LindsayMacfarlane created this ticket for mapping out fields on the internal side pertaining to reports!

**Comment by pbastia** [comment]
Thanks @suhafa ! This was discussed, and the team was informed.
