### ISSUE TITLE
Scope out Fourth Release of work for external portal

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1531]
#### Describe the task

We've scoped out the third slice of work for the MVP. This ticket is to plan out the scope for the third slice, update design if needed and create tickets.

#### Acceptance Criteria

- [x] Meeting to discuss fourth slice features 
- [ ] Create tickets
- [ ] Write up a summary of tickets created and work scoped
- [ ] Refine AC of tickets 
- [ ] Add wireframe links to tickets

#### Additional context

-

**Comment by LindsayMacfarlane** [comment]
Hi @suhafa - this ticket still requires acceptance criteria/checklist. Can you please add that in.

**Comment by suhafa** [comment]
@LindsayMacfarlane updated and also scoped in some work to make tracking tickets easier!

**Comment by suhafa** [comment]
**Some takeaways from an initial scoping session held on the 29th of March:**
 	
- The team went over RFP Generation, and how we could potentially change the format of the RFP ID to be simpler. Need some clarification on CIF about their current RFP ID patterns, Operator Code being procured from SWRS and how that could fit in the application (dropdown?). Generating a temporary RFP code was also considered as an option
- It was agreed that the 'Upcoming Reports Widget' would be in the fourth slice, but not linked to any application yet.
- 'Uploading templates to the right area' -> we agreed it makes more sense to link to CIF's RFP website where users can download all templates and upload them to the right place themselves, rather than each file upload area carry the correct template. which could result in linking to an outdated template. 	
- Concerning #1529 (Security of files) it was decided it will remain in the next slice
- The next set of designs will focus on UI for the application after approval or review, due report file upload	
- Research work would be around getting clarification on RFP IDs and what CIF would like to see from the internal side related to due reports on the external side
	
Overall, we may need another follow up session after the new designs are ready, and block some time for brainstorming on RFPs following feedback from CIF, sometime mid-sprint.

**Comment by nanyangpro** [comment]
Hi @pbastia & @Dianadec - Since the CIF external isn't a priority any more, shall we close this ticket? Seeing it's still in progress, but not carried forward by anyone at this point. Thanks!

**Comment by pbastia** [comment]
I'm in favour of closing!
