### ISSUE TITLE
Can't submit changes when updating Emission Intensity Report and not providing `Report Due Date` [8]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1532]
Describe the Bug:

When updating `Emission Intensity Report`, if the we don't provide the `Report Due Date`, we can't submit the revision (submit button is disabled) since we have a validation error on this form. This is probably because we have the `reportDueDate` as required in the `emission_intensity_report.json` file.

Probability (how likely the bug is to happen, scored from 1-5):4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Update an existing emission intensity report form and don't fill out the report due date field. hit submit and try to submit the revision. (You can't :) cause the button is disabled)

**Comment by BCerki** [comment]
Fixed, closing
