### ISSUE TITLE
Emissions Intensity Form Doesn't Display 'Attention' Required when there are fields that need populating[6]

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1534]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5):5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- create a project
- go to emissions intensity report
- don't fill in all information
- select submit
- notice that the task list says 'filled' instead of action required

Screenshots:
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/4e4eb69f-62ae-4e86-a5e4-ce9de1454ca6)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
This might be solved by https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1361

**Comment by Sepehr-Sobhani** [comment]
Still a bug (July 4)

**Comment by BCerki** [comment]
Fixed by the emission intensity report refactor
