### ISSUE TITLE
Create a user story map for external portal

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1540]
#### Describe the task
As we dive deeper into the work done for the user portal, creating an [User Story mapping](https://www.nngroup.com/articles/user-story-mapping/) artefact can help the team stay on the same page when it comes to the bigger picture of the features we plan to have in the app.

* may make sense to create a Product Roadmap as well

#### Acceptance Criteria

- [x] Review current Miro 'Slices' board
- [x] Replicate the current slices work in the User Story Mapping format
- [x] Add future features to the map
- [x] Review with team

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
@LindsayMacfarlane this ticket is ready to be closed!
- Current design work has been mapped out in the user story mapping in Miro, along with some TBD features mentioned as draft
- Shared with the team in Dev/Design Sync Session
- Will keep updating it as we move further along in our progress of the app

**Comment by LindsayMacfarlane** [comment]
Thank you for this @suhafa! It is great to see the steps that a user could take through the application.
