### ISSUE TITLE
Explore ability to machine read PDFs

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#1560]
#### Describe the task

What level of effort is required to implement machine readable tech in order to parse data out of proponent submitted PDF documents? Is this a valuable feature?

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Initial feedback from Dylan: As far as I know, PDF parsing is a bit of a quagmire. PDFs are totally unstructured, so it's hard to consistently and accurately get a machine to transform PDF data to machine readable data. It's something we could research and see if there have been any advancements in this area, or tools we could leverage. But my initial thought is the effort to do this is high. It's easier (thought probably still not easy) if the PDF is consistently structured the same way. But I imagine they will be uploading all sorts of PDFs

**Comment by dleard** [comment]
@pbastia can we close this ticket as a wontfix? I don't think PDF reading is something we want to do

**Comment by pbastia** [comment]
Yes, let's close it. Thanks!
