### ISSUE TITLE
Project Table Filter Field Inconsistencies

### ISSUE THREAD

**Issue by tmastrom** [bcgov/cas-cif#1562]
Describe the Bug:

In the Projects table on the Projects page, the Primary Project Managers filter is missing the arrow indicating the field is a dropdown. The dropdown should look like the status dropdown (see screenshots 1 and 2).

Placeholder text in dropdown filters is serif font whereas other filters use a sans serif font (see screenshot 3).

Probability: 5

Effect: 2 (UX is slightly unclear)

Steps to reproduce the behaviour:
Go to the Projects page

Screenshots:

![Screenshot 2023-03-21 at 9.54.49 AM.jpg](https://images.zenhubusercontent.com/62f2b9c7cb78a05765516ca0/5a83bd11-083a-42ae-ba76-be9d68315c5d)

![Screenshot 2023-03-21 at 9.54.34 AM.jpg](https://images.zenhubusercontent.com/62f2b9c7cb78a05765516ca0/151b58db-c7ac-4e01-b6d5-0990748d2e7b)

![Screenshot 2023-03-21 at 9.57.56 AM.jpg](https://images.zenhubusercontent.com/62f2b9c7cb78a05765516ca0/7664236a-6db9-458c-aabb-6f3f43409f99)

Additional information:

- OS: MacOS Ventura
- Browser: chrome

**Comment by pbastia** [comment]
Thanks @sam-warren ! The font looks good, did we decide not to implement the sorting arrows on that field?

**Comment by pbastia** [comment]
I see. Thank you @sam-warren !
