### ISSUE TITLE
As a CIF user, I want the project form to be validated on the client and server, so that I submit information in the correct format

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#158]
#### Description:
This card is to implement form validation on the project create/edit form, and to specify the interaction and rules for when to execute validation. Displaying errors is covered in #200

Validation *must* be performed on the server side to ensure that validation cannot be bypassed. To validate the data on the server, we can create a postgraphile plugin ([example here](https://github.com/scotti2scotti/postgrahile-json-validation-plugin)) that will, for every mutation on the `form_change`, validate using the corresponding schema based on the value of a new `json_schema_name` column, and add a list of validation errors in the `form_change` record (`validation_errors` column to be added). The `ajv` library can be used for validation on the server-side.
This validation can happen every time data is saved, as long as validation errors are not displayed until submission happens.

#### Acceptance Criteria:

Given I am a CIF user
When a project revision's form data is saved on the server
Then it is validated and validation errors, if any, are saved in the database

Given I am a CIF user
When I submit a project revision
Then each field of the form is validated on the client side
And any validation error prevents the form from being submitted

Given I am a CIF user
When I submit a project revision and client-side validation succeeds 
And any form_change contained in the revision has a validation error
Then the submission fails

#### Development Checklist:
- [x] JSON schemas are stored in shared JavaScript file(s), indexed by an unique name
- [x] `form_change` table has a `json_schema_name` column
- [x] `form_change` table has a `validation_errors` column (`jsonb` type)
- [x] Dynamic json schema elements (e.g. `anyOf` properties) are injected by the client
- [x] Client form validate on form submit 
- [x] Server form validate on form save (i.e. on type)
- [x] Revision commit function ensures that all forms are valid

#### Personas:
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by rajpersram** [comment]
The wireframe and prototype for this will be on [ticket 69](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/69)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/158?planning-poker) with ZenHub @AlexZorkin @dleard @pbastia

**Comment by LindsayMacfarlane** [comment]
@Sriram-pc - this issue looks ready? Can we remove the backlog refinement label or does the team still need to review/discuss anything related to this ticket?

**Comment by matthieu-foucault** [comment]
It's good now, was just waiting for estimates

**Comment by Sriram-pc** [comment]
@LindsayMacfarlane

**Comment by LindsayMacfarlane** [comment]
Thanks @pbastia!

Tested in Dev by:
- attempted to create a new project with no project information and received a list of errors, plus errors listed under each applicable field. Was unable to submit project with errors.
- added in some required fields: error list and errors displayed under affected fields was updated accordingly. Could not save project as expected.
