### ISSUE TITLE
As a user, I want to see a Preview Revision page (no more Review and Submit page), so that I can use the new committing workflow

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1582]
#### Description:

Currently, when users finish creating a revision, then they are directed to a "Review and Submit" page (`app/pages/cif/project-revision/[projectRevision]/index.tsx`) where they can see their diffed changes and click "Submit." This is an old workflow. To facilitate the new workflow, users should see a "Preview Revision" page (`app/pages/cif/project-revision/[projectRevision]/view.tsx`) before creating a revision and commit projects via a status dropdown and update button.

- Design: [Preview Revision (the last step of creating a new revision)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF---Internal-User-Portal?page-id=2289%3A2663&node-id=3811-3067&viewport=-470%2C1174%2C0.2&scaling=scale-down&starting-point-node-id=3169%3A2715&show-proto-sidebar=1)
- Design : [View Revision (after a revision is created, editable unless the status is changed to "Approved" / "Applied")](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF---Internal-User-Portal?page-id=2289%3A2663&node-id=7283-630&viewport=-470%2C1174%2C0.2&scaling=scale-down&starting-point-node-id=3169%3A2715&show-proto-sidebar=1)

#### Acceptance Criteria:

Given I am a user
When I finish editing a form (I click "Submit XX Form" button at the end of any form page)
Then I am directed to the project revision page (the one with the radio boxes for amendment, pending actions from, forms updated, `app/pages/cif/project-revision/[projectRevision]/view.tsx`)
and I do not see a "Submit" button

Given I am a user
When I am on the project revision page
Then I can see a "Discard Amendment" or "Discard General Revision" (as applicable) button
And when I click it, I see a confirmation message

Given I am a user
When I view the tasklist
Then I should not see a "Submit Changes" section

Given I am a user
When I view the tasklist
Then I should see an Amendments & Revisions section
and a subsection with the text "New Revision (Preview)"

#### Development Checklist:

- [x] Make the individual form submit button link to the project revision page
- [x] Add the discard button from `app/pages/cif/project-revision/[projectRevision]/index.tsx` to the project revision page
- [x] Remove the yellow/green diff styling from `CustomDiffFields` (only using the strikeout/red styling from now on)
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by nanyangpro** [comment]
Thanks @BCerki! As discussed, I've updated the design and dropped the associated links with additional context in the description. Please feel free to update refine the AC accordingly.

**Comment by BCerki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1582?planning-poker) with Zenhub @dleard @gurjmatharu @JoshLarouche @pbastia @sam-warren @Sepehr-Sobhani @tmastrom

**Comment by pbastia** [comment]
Discard button will reflect the type of revision we're discarding: "Discard amendment" or "Discard general revision"

**Comment by nanyangpro** [comment]
Thanks @pbastia! The "Discard Amendment" / "Discard General Revision" button is added at the bottom of the project revision page on all the appropriate screens in the interactive prototypes above in the ticket description now.

**Comment by BCerki** [comment]
Some clarifications to the tasklist after discussion with @nanyangpro:
- on the project pages and changelog page, there should be nothing under the "Amendments and Other Revisions" section
- when viewing a submitted revision, there should be "View revision ##" under the "Amendments and Other Revisions"  section. Clicking it should bring the user to the view version of the page with the project status, red-black diffs, etc.
- when editing a revision, we should see "Edit revision ##" under the "Amendments and Other Revisions" section. Clicking it should bring the user to the edit version of the page with the project status, red-black diffs, etc.
- when creating a revision, we should see "New Revision" under  the "Amendments and Other Revisions" section and it should not be a link (clicking the current link wipes the form)

**Comment by nanyangpro** [comment]
Thanks @BCerki! As discussed, some enhancement for future considerations will be addressed in the following tickets, thus not in the scope of the current one:
- #1663 – No "Revision Type" section 
- #1665 – Alert users when breaking New Revision process 
- #1666 – Contextual text for when Amendment / General Revision is disabled during creation

**Comment by pbastia** [comment]
Stellar work @BCerki ! A couple of comments about the AC:

For this one, the button says says "Discard Project Revision" :
>Given I am a user
When I am on the project revision page
Then I can see a "Discard Amendment" or "Discard General Revision" (as applicable) button
And when I click it, I see a confirmation message

For this one, the tasklist says "Edit General Revision X" instead:
> Given I am a user
When I view the tasklist
Then I should see an Amendments & Revisions section
and a subsection with the text "New Revision (Preview)"

**Comment by BCerki** [comment]
> Stellar work @BCerki ! A couple of comments about the AC:
> 
> For this one, the button says says "Discard Project Revision" :
> 
> > Given I am a user
> > When I am on the project revision page
> > Then I can see a "Discard Amendment" or "Discard General Revision" (as applicable) button
> > And when I click it, I see a confirmation message
> 
> For this one, the tasklist says "Edit General Revision X" instead:
> 
> > Given I am a user
> > When I view the tasklist
> > Then I should see an Amendments & Revisions section
> > and a subsection with the text "New Revision (Preview)"

After discussion with @nanyangpro, instead of seeing "New Revision (Preview)" we'll see "Edit [name and number of revision]" (in comments but didn't update the AC, sorry). The other one I'll fix Monday

**Comment by pbastia** [comment]
Thank you @BCerki ! I can see everything working!
