### ISSUE TITLE
Design application screens during review and  after approval

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1585]
#### Describe the task

We've designed screens for the 'Create an application' workflow. Now we need to design what it looks like when an application is in review, and after approval. of an application. 

**Guiding questions for design work:** What will the UI look like after the application is approved? How will the fields for Milestone, Quarterly, Emissions Intensity and Project Summary reports be displayed on the external app? What will file uploads for reports after project approval look like?

#### Acceptance Criteria

- [x] Confirm what fields CIF team flags as good to display in the app from the internal side
- [x] Design screens for 'In Review' status
- [x] Design screens for 'Waitlisted' / 'Disqualified' status
- [x] Design screens for 'Reports' display after approval
- [x] Design screens for due report file upload 

#### Additional context

-

**Comment by suhafa** [comment]
Hi @pbastia! This ticket is ready for your review. Design screens were created in Figma for the post-application submission workflow.

**Comment by pbastia** [comment]
Thank you @suhafa , nice work!
