### ISSUE TITLE
Offsets: Explore documentation on private offsets data

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1587]
#### Checklist:
- [x] Read documentation provided by IHS on the data not available via the public API
- [x] start looking at common keys with swrs data
- [x] document insights/questions gathered during this phase of exploration (e.g., data warehousing miro board)

#### Notes:
- Documentation located here: Scrum Team>CPR>BC Carbon Registry and Offsets>BCCR API Documentation

**Comment by dleard** [comment]
@pbastia I've gone over the private schema & added a bunch of notes to the data warehousing miro. Let me know if you want to go over these together in order to move this to closed

**Comment by pbastia** [comment]
For sure, let's go over it when you have some time. Thanks @dleard

**Comment by pbastia** [comment]
We went over these together. Thank you @dleard !
