### ISSUE TITLE
CIF App Demo (internal) Preparation

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-cif#1588]
#### Describe the task

We have scheduled a demo for the CIF Internal users on April 12 from 10:30am - 11:30am. The goal is to show the CIF team how to use the app, so that they actually start using it more.

To prepare we need to think about how to best provide an overview for them. Lindsay suggested Pierre could provide the demonstration, and perhaps Nan can be there to assist and answer questions. Up for team input.

#### Acceptance Criteria

- [x] Schedule team prep meeting 
- [x] Create a shared document to plan what we will demo
- [x] Practice the demo with a team member and fine-tune according to feedback.
- [x] determine next steps for supporting the CIF team. Eg: Would office hours be helpful? Or simply a regular time each week for 30 mins to help them with anything?
- [ ] Optional: Compile a list of resources or links that might be helpful for the CIF team (do we have documentation stored in cas-home that we could link to? do we have user guides anywhere?)

#### Additional context

This is the second part following a CIF team onboarding session provided on April 5, more about agile ways of working and collaboration across teams.

**Comment by Dianadec** [comment]
@nanyangpro and @pbastia I have added some AC to this card, but let me know if you need more info to get organized for the demo.

**Comment by nanyangpro** [comment]
Thanks @Dianadec! Just dropping a few thoughts here which is related to the next steps in the AC: One of the goals we may be able to achieve from this is to understand what are the main reasons currently blocking the CIF team from fully adopting the CIF app. What is still missing? What is still confusing? What can we do to support the shift from spreadsheets? etc.

**Comment by Dianadec** [comment]
Yes, @nanyangpro great points. I wonder if it would be possible for someone on our team to take down notes/observations about the questions they ask during the demo. We can also reach out to the in advance of the demo to ask if they have specific areas they want to make sure we cover.

**Comment by nanyangpro** [comment]
Hi @Dianadec & @pbastia - Here's the [draft internal planning doc](https://bcgov.sharepoint.com/:w:/r/teams/00608-ScrumTeam/_layouts/15/doc2.aspx?sourcedoc=%7B47C82967-9ADA-4129-8DD6-F519528387D2%7D&file=CIF%20Admin%20App%20Demo%20Planning.docx&action=default&mobileredirect=true&cid=84c74f5b-d66c-4749-8363-b2580091d85b) as we discussed. If the detailed meeting invite looks good, feel free to update it for CIF or let me know, I can send it no problem too.

**Comment by nanyangpro** [comment]
Hi @pbastia - This ticket is ready for you to review and can be closed with:

- #1601, #1602, #1603 created as requested for future enhancements
- Next steps summarized and followed up by @Dianadec: 
    - Ensuring all CIF team members have access to CIF test and prod
    - Planning a Metabase training session in a CIF-related context in May
    - Open communication in CIF Internal Users channel across teams for feedback, questions, and reporting bugs

Thank you for your time and effort on this, it was a pleasure!

**Comment by pbastia** [comment]
thanks @nanyangpro !
