### ISSUE TITLE
Add a `ReviewTheme` with support for an accordion

### ISSUE THREAD

**Issue by gurjmatharu** [bcgov/cas-cif#1596]
#### Describe the task

To support an Accordion style review page as found here: https://www.figma.com/file/84BpebYIR1iYetxJThLsW6/CIF---External-User-Portal?node-id=144-472&t=7fTSBfcY7FLIzYj6-0

Some design decisions need to be made.  To adapt from CCBC we will need to approximately implement the following:

- Create a new `ReviewTheme`
- Create a custom `SectionField` and `ReviewField`
- Create review components
- Create Accordion component
- Implement a custom `ui:before` field to render stylized table elements (`<tr>`)

Perhaps a discussion on the requirements of having a table like interface.
Sharing components across the repo's is difficult with current implementation.

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by pbastia** [comment]
I don't think a new RJSF theme is in the scope of CIF at this point. Closing, we can always decide to add an accordion component to our current theme if needed
