### ISSUE TITLE
Selecting IA funding stream when creating a new project[8]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1597]
Describe the Bug:

When selecting the IA funding stream during the project creation step, the dropdown changes the selected funding stream to EP. This happens only for the first time.

Probability (how likely the bug is to happen, scored from 1-5):5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
create a new project -> Try to select the Innovation Accelerator as the funding stream

Screenshots:
https://www.loom.com/share/de0838d0d7504ce7b236c8770938b3ec

**Comment by BCerki** [comment]
I think this showed up in this PR: https://github.com/bcgov/cas-cif/pull/1558/files (the cypress test has to select the funding steam twice to pass). It might have something to do with the `useState` hook

**Comment by pbastia** [comment]
Thank you @tmastrom ! The bug appears resolved.
