### ISSUE TITLE
Rename "Project Type" to "Emissions Reduction Pathway"

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1603]
#### Describe the task

This was a feature request raised by Eric S. during the CIF (Internal) App Demo on Apr 13, 2023. May require further validation.

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by pbastia** [comment]
@nanyangpro  I'm tagging this 'UX research', but this card is probably not needed, granted the proper training is given to the team

**Comment by pbastia** [comment]
This hasn't been brought up again, and was the opinion of one person surveyed. Closing.
