### ISSUE TITLE
Preparation for the CPI Workshop Presentation

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1611]
#### Describe the task

This ticket captures work needed for preparing to present the presentation between Suha & Nan

#### Acceptance Criteria
- [x] Reach out to Patricia and Jaimie for feedback on Menti questions
- [x] Update Menti questions 
- [x] Split presentation work
- [x] Do a dry-run of the presentation on the 3rd of May

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
@nanyangpro @Dianadec created this ticket for upcoming planning for the CPI workshop

**Comment by nanyangpro** [comment]
Thanks @suhafa! A test run of the CPI workshop has been schedule on next Wed, May 3 for the whole branch. Shall we have a prep meeting together next Tue, May 2 to go through the deck and plan together for our team's session?

**Comment by nanyangpro** [comment]
As outcome of the Test Run (Wed, May 3):
- [CPI Workshop May 2023 presentation](https://bcgov.sharepoint.com/:p:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/CIF/Events,%20Workshops%20%26%20Meetings/CPI%20Workshop%20May%202023.pptx?d=w1168d07b1efb4b3fbfaebbb17477a6d6&csf=1&web=1&e=V1L9w8) deck has been refined with the updated version sent to Alana C. to be incorporated in the master slide deck for the workshop

**Comment by suhafa** [comment]
Hi @pbastia! This task is completed and ready for your review:
- We reached out to program area and refined engagement questions on Menti
- Nan & I split the work for the presentation
- We completed the dry-run prep as well

**Comment by pbastia** [comment]
Thank you! Fantastic job at the presentation :)
