### ISSUE TITLE
As a CIF user, I want to see the differences on budgets calculated fields since the last revision, so that I can focus on what did change

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1614]
#### Description:

Calculated fields are handled by computed columns, which our current diff logic can't display. For example, diff for calculated gross, net and holdback amounts for a milestone isn't shown on the summary page (page with red/black strikeout). This is likely because the calculated values are not actually part of the schema. 

This card is about implementing diffs for the budgets form. The calculated values on the budgets form are:
- Proponent's Share Percentage
- Anticipated Funding Amount Per Fiscal Year
- Total Project Value
- Total Net Payment Amount to Date
- Total Gross Payment Amount to Date
- Total Holdback Amount to Date
- Total Eligible Expenses to Date
- Total Payment Amount to Date (IA)

#### Acceptance Criteria:

Given I have added enough values to complete the calculation for the first time
When I view the summary page
Then the diff displays the newly calculated value

Given I have changed values that affect the calculated value
When I view the summary page
Then the diff displays changed values properly for calculated values

Given I have removed enough values to prevent the calculation
When I view the summary page
Then the diff displays removed calculated values properly

#### Development Checklist:
- [x] Any front-end calculated values are refactored into computed_columns:
    - [x] calculatedProponentsSharePercentage
- [x] Refactor calculations that calculate values based on info in `project_revision` to calculate based on `form_change` instead (this will also make the calculation dynamic)
    - [x] project_revision_anticipated_funding_amount_per_fiscal_year
    - [ ] ~project_revision_gross_payment_amount~
    - [ ] ~project_revision_net_payment_amount~
    - [x] project_revision_total_project_value
- [x] Query the previously calculated values under `formChangeByPreviousFormChangeId`
- [x] Pass the previously calculated value to `CustomDiffFields` via `formContext.oldData`
- [x] Query the latest committed calculated value under `latestCommittedFormChangesFor`
- [x] Pass the latest committed value to `CustomDiffFields` via `formContext.latestCommittedData`
- [x] Pass the current calculated value to `CustomDiffFields` via `getSchemaAndDataIncludingCalculatedValues` 
- [x] update summary form tests
- [x] update any other mutations or tests as necessary
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
    - [na] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by BCerki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1614?planning-poker) with Zenhub @dleard @gurjmatharu @JoshLarouche @mikevespi @pbastia @sam-warren @Sepehr-Sobhani @tmastrom

**Comment by nanyangpro** [comment]
Backlog refinement Apr 25: This one should be estimated considering that #1231 should already be completed.

**Comment by BCerki** [comment]
`project_revision_gross_payment_amount` is actually on milestones, not budgets, so will be handled here instead: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1616

**Comment by BCerki** [comment]
Anticipated Funding by Fiscal Year is a "string" field type but is actually an array (we made it string rather than array to accommodate the design). We'll need a case to address array diffs in `CustomDiffFields.tsx`'s `StringDiff`.

**Comment by BCerki** [comment]
The easiest way to show the diffs for anticipated funding per fiscal year was to change them to an array field so they work the same as additional funding sources. Everything looks the same on the editable pages, but for view/read-only, I used the generic `ReadOnlyArrayField` template so these anticipated funding per fiscal year looks slightly different than before. I can make a custom readonly array field template for anticipated funding per fiscal year if desired.

**Comment by pbastia** [comment]
I can see all the diffs! Thank you @BCerki !
