### ISSUE TITLE
Plan Metabase CIF training

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1618]
#### Describe the task

the CIF team needs a run through Metabase 101

#### Acceptance Criteria

- [x] Gather a few example questions from business area (NM) (may need to confirm in CIF internal users channel)
- [x] Update training questions with relevant CIF context
- [x] Schedule date for training, end of May: Scheduled May 31!

#### Additional context

- Word doc for internal planning (copied from November session - needs updating, but we can build from this: (Scrum Team > Metabase Training) https://bcgov.sharepoint.com/:w:/r/teams/00608-ScrumTeam/_layouts/15/doc2.aspx?action=edit&sourcedoc=%7Be2cc916c-8618-4c55-a8b4-b977fbf201ca%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1

**Comment by pbastia** [comment]
@dleard  looping you into this one

**Comment by Dianadec** [comment]
Hold sent out to CIF and DST - May 31 from 10-12

**Comment by Dianadec** [comment]
I added training topic ideas from Nicole M to the planning doc linked in the card description.
