### ISSUE TITLE
As a CIF user, I want to see the differences on Emission Intensity Report calculated fields since the last revision, so that I can focus on what did change

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1619]
#### Description:

Calculated fields are handled by computed columns, which our current diff logic can't display. For example, diff for calculated gross, net and holdback amounts for a milestone isn't shown on the summary page (page with red/black strikeout). This is likely because the calculated values are not actually part of the schema. 

This card is about implementing diffs for the Emission Intensity Report form. The calculated values on the Emission Intensity Report form are:
- `Calculated EI Performance`
- `Holdback Amount To Date` (Used to calculate `Maximum Performance Milestone Amount`)
- `Actual Performance Milestone Amount`
-  `Payment Percentage Of Performance Milestone Amount` (this is using `form_change_payment_percentage.sql`)

Note: this Issue is about showing the difference between the values a user has just typed into a form and the values in the previous form change.

#### Acceptance Criteria:

Given I have added enough values to complete the calculation for the first time
When I view the summary page
Then the diff displays the newly calculated value

Given I have changed values that affect the calculated value
When I view the summary page
Then the diff displays changed values properly for calculated values

Given I have removed enough values to prevent the calculation
When I view the summary page
Then the diff displays removed calculated values properly

#### Development Checklist:
(see `app/components/Form/ProjectFormSummary.tsx` for an example)
- [x] Any front-end calculated values are refactored into computed_columns:
- - [x] `actualPerformanceMilestoneAmount`
-  [x] Refactor calculations that calculate values based on info in `project_revision` to calculate based on `form_change` instead (this will also make the calculation dynamic)
- - [x] `project_revision_calculated_ei_performance`
- - [x] `project_revision_holdback_amount_to_date`
- - [x] `project_revision_payment_percentage`
- [x] Query the previously calculated values under `formChangeByPreviousFormChangeId`
- [x] Pass the previously calculated value to `CustomDiffFields` via `formContext.oldData`
- [x] Query the latest committed calculated value under `latestCommittedFormChangesFor`
- [x] Pass the latest committed value to `CustomDiffFields` via `formContext.latestCommittedData`
- [x] update summary form tests
- [x] update any other mutations or tests as necessary
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [na] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by Sepehr-Sobhani** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1619?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @JoshLarouche @mikevespi @pbastia @sam-warren @tmastrom

**Comment by nanyangpro** [comment]
Backlog refinement Apr 25: This one should be estimated considering that #1231 should already be completed.

**Comment by pbastia** [comment]
Thank you @Sepehr-Sobhani ! I can see the values added, changeed and removed
