### ISSUE TITLE
Compile findings from usability testing with industry operators

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1621]
#### Describe the task

After usability sessions conducted between 25th April - 5th of May, the insights collected need to be synthesized and shared with teams. 

#### Acceptance Criteria

- [x] Compile feedback
- [x] Sort notes in themes
- [x] Update User Journey Map
- [x] Prepare Miro board for presentation

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
Usability Test findings have been compiled in the CIF Usability Testing Miro Board, and presented in the Sprint Review. Recommendations have been added for addressing those findings. A suggestion for if and when we have capacity, it would be great if we could maintain timestamps of key points from our usability sessions for future easier reference.

@pbastia this ticket is good to be closed after your review!

**Comment by pbastia** [comment]
Thank you so much @suhafa for documenting all of this! Fantastic work!
