### ISSUE TITLE
Milestone calculations not getting updated with existing data and when changing milestone type[8]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1628]
Describe the Bug:

Pierre captured this bug as part of the card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1514
related comment: https://github.com/bcgov/cas-cif/issues/1514#issuecomment-1526182933

Changing the milestone type doesn't trigger the milestone calculations mentioned in the above card. Also, we don't get those calculations if we have existing data.

Probability (how likely the bug is to happen, scored from 1-5):3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):5
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- For an existing milestone that has Net/Gross/Holdback calculations, try to change the milestone type and see that those calculations don't get updated.
- Look at an existing milestone report with `Report Received Date` and `Total Eligible Expenses` filled out, calculations are not triggered.

**Comment by pbastia** [comment]
I can see the calculations are triggered now. Thank you @Sepehr-Sobhani !
