### ISSUE TITLE
As a CIF developer, I want the Emission Intensity Report form to be refactored with a custom commit handler, so I have more flexibility in the form layout

### ISSUE THREAD

**Issue by tmastrom** [bcgov/cas-cif#1637]
### Description of the Tech Debt 
Similar to funding agreement (#1171) and milestone (#1007) refactor. See exploratory work in this [issue](https://github.com/bcgov/cas-cif/issues/1564).

Given I am a CIF developer
When I commit an emission intensity report form
Then a custom form commit handler is called
And both `reporting_requirement` and `emisson_intensity_report` tables are populated

Given I am a CIF developer
When I add, remove or reorder fields on the emission intensity page
Then there is only a single form to change

##### Dev Checklist: 
- [ ] write new, single json schema
- [ ] don't forget to update the tasklist and mutation fragments to fetch the new data
- [ ] existing form_change records need to be migrated with:
    - [ ] a migration function that goes through every existing revision, grabs the milestone reporting requirements and creates a new form_change for each of these - and delete (archive) the form_changes for `reporting_requirement`, `payment` and `milestone` tables.
    - [ ] tests for that migration function
- [ ] add the new json schema to the list of database forms in the server side validation plugins
- [ ] fix dev data, potentially
- [ ] tests for  react form and summary components need to use the same json schema as is deployed to the database.
- [ ] `commit_form_change_internal` should use a custom handler for the form
- [ ]  tests for the new custom commit handler
- [ ] create_project_revision might need refactoring

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |   1    |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |   1    |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |   1    |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |   1    |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |    1   |
| TOTAL SCORE:                                                                                                                  |       |       |

**Comment by BCerki** [comment]
This was done in https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1361

**Comment by pbastia** [comment]
Thank you @BCerki ! Closing
