### ISSUE TITLE
Document External App Design/Research Efforts

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#1642]
#### Describe the task

Based on our conversation on May 4, it was decided to cap external app efforts at submitting an application with uploading documents. We need to document the design and research so far for future implementation. Suha will be preparing a document for hand-off 

#### Acceptance Criteria

- [x] Clean up External User Process Board
- [x] Clean up External User Research board
- [x] Prepare document for capturing work

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
Documentation prepared. It can be found in the **Scrum Team Channel < Files < CIF < External Application < Suha's External App Documentation** @pbastia ready for your review!

**Comment by pbastia** [comment]
I read through the file, thanks so much for documenting everything in such a detailed and complete way @suhafa !
