### ISSUE TITLE
As a CIF user, I want to access the login page from the login-redirect page, so that I am not stuck

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1644]
#### Description:

The login-redirect page doesn't have a link to the login page / a login button
This causes the users to be stuck on a page where they can't login even though the system tells them to login.

Add a "log in" button or link to the page that redirects the user back to the page they initially tried to access.

example:
https://dev.cif.gov.bc.ca/login-redirect?redirectTo=%2Fcif%2Fprojects

#### Acceptance Criteria:

Given I am a CIF user
When I am not logged into the system
And I try accessing a page that is not the root URL (e.g. cif.giv.bc.ca/cif/projects)
Then there is a button that navigates to the login page.

Given I am a CIF user
When I click the button on the login-redirect page
And I successfully log in
Then I am redirected back to the page I was trying to get to.

#### Development Checklist:

- [x] Add a login button / link to the login redirect page that
- [x] Provide the button with a redirect url of the url the user entered to  get to the login-redirect page in the first place
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
@nanyangpro @suhafa just flagging this for your advice - would it be better to add a "return to home page" button? Or directly the login buttons on that redirect page?
(clicking the clean growth logo also doesn't solve the issue)

**Comment by suhafa** [comment]
Thanks for raising this questions @pbastia!  A "Return to Home Page" button would certainly be required for this page. Since it is a redirect page, I would recommend "Return to Home Page" over the "Login" buttons. Additionally we should also allow the Clean Growth logo to return the user to the home page (or dashboard if they are logged in)

**Comment by nanyangpro** [comment]
Thanks @pbastia! - Would the login-redirect page show the CIF banner on the top?

If so, we can
- Add the login button to the right most of the banner, and display the copy "You need to log in to the CIF app to view the page" on the main page, **this way we can provide a little more context to users and save them a click**

Or

- Add the copy with the Return to Home Page link "To view the page, [return to the home page](url) to log in"

Either way, I second @suhafa that the Clean Gworth logo should always bring users back to the home page (or dashboard if logged in)

**Comment by pbastia** [comment]
I'd be for having the login button in the banner, when the user is not logged in, this way it's less work, and already matches the "Please Log In" text

**Comment by nanyangpro** [comment]
Sounds great to me, thanks @pbastia!

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1644?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @JoshLarouche @sam-warren @Sepehr-Sobhani @mikevespi

**Comment by JoshLarouche** [comment]
After discussion it was decided that adding a redirect button in the banner and having the clean growth logo redirect to the homepage is in the scope of this ticket.

**Comment by JoshLarouche** [comment]
After discussion with @nanyangpro, it was decided to keep both login buttons in the right side of the header on the login-redirect page

**Comment by JoshLarouche** [comment]
After discussion with @nanyangpro it was decided to keep both login buttons in the header of the login redirect page

**Comment by pbastia** [comment]
Nice work @JoshLarouche ! It even works with our feature flag!
