### ISSUE TITLE
"Missing" Emissions info[6]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1647]
Describe the Bug:

Based on the bug Lindsey Pulham mentioned in the CIF Internal Users' Teams channel.

```
I've noticed with multiple projects that when you try to review the info under the Emissions Intensity Report tab that it wont display what has been entered unless you click the "Edit" button. Selecting "undo changes" or resubmitting the info doesnt work either
```

Probability (how likely the bug is to happen, scored from 1-5):3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the bug:

Make a new revision on an existing emission intensity form (with data) and don't change anything, then submit the revision.
go back to the same project and try to view the emission intensity info using the tasklist (view mode), you will see `Emission Intensity Report not updated`.

**Comment by pbastia** [comment]
I see the missing emission report! Thanks @Sepehr-Sobhani
