### ISSUE TITLE
"False" late Milestones?[6]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1648]
Describe the Bug:

Based on the bug Lindsey Pulham mentioned in the CIF Internal Users' Teams channel.

```
Several projects on the dashboard are showing "Late" under the Milestone column when in fact they are not late, some are on track or even complete.
```

Probability (how likely the bug is to happen, scored from 1-5):3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

**Comment by pbastia** [comment]
Looks like there is no documentation on how to replicate the bug - I'll mark it as approved. @mikevespi if there is a way let me know!
