### ISSUE TITLE
Missing Emissions Intensity form

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-cif#1649]
Describe the Bug:
This bug was reported in the CIF Internal channel:
Hi there, I'm seeking some assistance with the app. I've noticed with multiple projects that when you try to review the info under the Emissions Intensity Report tab that it wont display what has been entered unless you click the "Edit" button. Selecting "undo changes" or resubmitting the info doesnt work either...is there a way around this? Appreciate any insight you can offer. Thanks!

The issue is in `ProjectEmissionIntensityReportFormSummary`. There are a few places where `isPristine` is being used to determine whether the form displays or not. The issue is that `isPristine` represents whether a form change has any changes from its' parent form change. So if the TEIMP form on a committed revision wasn't changed in the last revision, `isPristine` will be true and the form doesn't show. 

If I remember right, `isPristine` was put in here because there were cases where a full empty form would render despite a TEIMP not existing, but it wasn't me who implemented it so I could be off. 

Probability (how likely the bug is to happen, scored from 1-5): 5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- create a project and give it a TEIMP report
- create a new project revision on that project, and change anything BUT the TEIMP form, and commit the revision
- view the TEIMP page of the project
If this doesn't work, create one more project revision where you don't change the TEIMP. The idea is to get `isPristine` to be true on a committed revision, with a TEIMP form filled in.

Screenshots:
There are screenshots on the original post, but they were taken in prod so not copied here.

**Comment by Sepehr-Sobhani** [comment]
@pbastia I believe so!

**Comment by pbastia** [comment]
Amazing. Closing.
