### ISSUE TITLE
Default layout navigation bar

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#165]
#### Describe the task

Add a navigation bar as shown in the UI designs

**Comment by LindsayMacfarlane** [comment]
Looks good @matthieu-foucault ! I did notice that projects and operators are reversed in comparison to the UI Design, but that makes sense as projects will be used more often.

**Comment by rajpersram** [comment]
@LindsayMacfarlane Doesn't _really_ matter to me if it's a hassle to change, but the navbar was intentionally laid out to go from general to specific (Dashboard, Operators, Projects, Contacts) and then Admin bookended as the last.
