### ISSUE TITLE
As a CIF administrator, I don't want to see the read-only "Revision Type" section on the view or edit page of a revision, so that I don't see redundant information on the page

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1663]
#### Description:

Currently, when view/edit an Amendment or a General Revision, there's a "Revision Type" section on the top, we should remove it with reasons below:
- It's a duplication. Users can already tell the revision type from the page title and the tasklist
- The revision type is immutable once the Amendment / General Revision is created
- It makes the form longer with redundant information on the top 

#### Acceptance Criteria

Given I am a CIF administrator
When I view an Amendment or a General Revision
Then I should not see `Revision Type` section on top of the Amendment and General Revision pages since it's redundant 

Given I am a CIF administrator
When I want to edit an Amendment or a General Revision
Then I should not see `Revision Type` section on top of the Amendment and General Revision pages since it's redundant 

#### Development Checklist:

- [x] remove `revisionType` from `viewProjectRevisionSchema` and its dependencies
- [x] update `buildProjectRevisionSchema` based on the above change
- [x] we probably don't need `createProjectRevisionUISchema` any longer
- [x] update `edit.tsx` file based on the change on `buildProjectRevisionSchema`
- [x] update tests
- [x] amendment type is a dependency of revision type in the json schema, so ensure that removing revision type doesn't accidentally additionally remove amendment type

**Comment by BCerki** [comment]
Amendment type is a dependency of revision type in the form schema, so have to make sure we don't lose amendment type when implementing this

**Comment by nanyangpro** [comment]
Good call, thanks @BCerki! To clarify, this ticket is solely for front-end display.

**Comment by BCerki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1663?planning-poker) with Zenhub @dleard @gurjmatharu @JoshLarouche @sam-warren @Sepehr-Sobhani

**Comment by BCerki** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1663?planning-poker) with Zenhub @mikevespi

**Comment by pbastia** [comment]
Thank you @Sepehr-Sobhani ! The read only section is gone.
