### ISSUE TITLE
As a CIF Administrator, I want to see contextual text next to the disabled revision type when creating a new revision record, so that I know why it's disabled

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1666]
#### Description:

Currently when creating a new revision record, 
- the "Amendment" option is disabled for the "Revision Type" selection if there's an open Amendment in place
- the "General Revision" option is disabled for the "Revision Type" selection if there's an open General Revision in place

However, (newer) users aren't indicated why, thus contextual text is needed to avoid confusion.

#### Acceptance Criteria:

Given I'm a CIF indicator,
When I see "Amendment" or "General Revision" is disabled when creating a new revision record
Then I see contextual text when hovering over the tooltip icon next to it

> "You cannot create a new Amendment before the in-progress Amendment is approved."

for an Amendment.

> "You cannot create a new General Revision before the in-progress General Revision is applied."

for a General Revision.

#### Development Checklist:

- [x] Add `ui:tooltip` object to the `projectRevisionUISchema` in the `create.tsx` page and pass the appropriate text message to the tooltip object based on the disabled revision type
- [x] Add tests and make sure the tooltip has no accessibility issue (via axe)
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by nanyangpro** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1666?planning-poker) with Zenhub @andrea-williams

**Comment by BCerki** [comment]
Per discussion with @nanyangpro, the tooltip will be beside the `Revision Type` label

**Comment by nanyangpro** [comment]
For detailed reference:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUZnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1b5c597a089e906da6a50a51997e4edb074cb4c8/image.png)
