### ISSUE TITLE
Investigate if `teimpPaymentPercentage` and `teimpPaymentAmount` calculated fields are still required[5]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1675]
###Description of the Tech Debt###

These two calculated fields are on the TEIMP form but we don't show them on the form. Investigate if we still need these two fields on this form.

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |     1  |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |   1    |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |     1  |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |    1   |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |    1   |
| TOTAL SCORE:                                                                                                                  |       |    5   |

**Comment by BCerki** [comment]
Discussion with @nanyangpro and @Sepehr-Sobhani determined these calculations are no longer necessary

**Comment by pbastia** [comment]
There is nothing for the PO to test :)
Thanks @BCerki !
