### ISSUE TITLE
Error on committing a project revision when one of the forms have error[7]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1676]
Describe the Bug:

When updating the status of an amendment/revision to applied or approved, we get an error when committing the revision if one of the forms has an error.
We need to prevent users from marking the revision status as applied or approved when there's an error in any of the forms. (Might even need a designer decision, like showing an error or simply disabling the update button)

Probability (how likely the bug is to happen, scored from 1-5):4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

On an open revision/amendment, try to raise the error on any of the forms (like not filling one of the required fields) and go to the Project Revision Page and try to change the status to Approved/Applied.

Screenshots:
https://www.loom.com/share/eba6d31fbd1c451a948c6d5a21e63c2d

Additional context: In the old project review page, We used to prevent users from committing a project revision if a form has an error by simply disabling the submit button if below code returns true:

```js
  const hasValidationErrors = useMemo(
    () =>
      query.projectRevision?.formChangesByProjectRevisionId.edges.some(
        (edge) => edge.node.validationErrors.length > 0
      ),
    [query.projectRevision?.formChangesByProjectRevisionId.edges]
  );
```

Based on a discussion with @nanyangpro, if there's an error on any of the forms when the user tries to change the status to either Approved or Applied (based on the revision type) we need to disable the `Update` button and change the text next to it to `You can't commit this revision/amendment. Please see "Attention Required".`

**Comment by pbastia** [comment]
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/c2765401-9f34-44eb-adaa-816a4a572f42)
Amazing user feedback! Thanks @nanyangpro and @Sepehr-Sobhani
