### ISSUE TITLE
Pages paths refactor

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#168]
#### Describe the task

The pages should have the following paths:
`/cif/projects`
`/cif/project/new`
`/cif/project/[projectId]` : the "Overview tab
`/cif/project/[projectId]/attachments`
`/cif/project/[projectId]/revisions`
`/cif/operators`
`/cif/contacts`

A `pagesRoutes.ts` file should be implemented to define these routes. See CIIP's `routes.ts` file

**Comment by dleard** [comment]
should `/cif/project/new` be `/cif/project/[revisionId]` since starting a new project would create a revision? This route would also be used later for editing a project

**Comment by matthieu-foucault** [comment]
`/cif/project/new` should actually be `/cif/project-revision/[revisionId]/edit`

**Comment by LindsayMacfarlane** [comment]
Thank you @matthieu-foucault! That fixes the issue I was experiencing during testing yesterday. While reviewing this task, I noticed that the upload attachments is no longer available: ![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/1da32e07-0f1f-4e0b-90c3-5065cbfcf777)

**Comment by matthieu-foucault** [comment]
The uploads code is still there, but is just a test page for now, so I didn't want to leave links to it. Links to access an attachments page will be added in #74
