### ISSUE TITLE
As a CIF administrator, I'd like to see a metabase view of upcoming action items, so I know what needs my attention

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1686]
#### Description:

A list of upcoming milestones/reports due etc
>  Widget Feature: similar to what was proposed for external users, we’d like to have this feature offered internally that will show at the side/top of screen what’s outstanding, and upcoming

#### Acceptance Criteria:

Given I am a CIF admin user
When I access metabase
Then I have access to a view that shows me all outstanding reports
and I can see the report name, company name, due date, and how many days overdue a report is
and these reports are in order of what is the most late

Given I am a CIF admin user
When I access metabase
Then I have access to a view that shows me all upcoming reports
and I can see the report name, company name, due date, and how many days are left until the report is due
and then are ordered by what due date is the closest

#### Development Checklist:

- [x] Create two separate views in metabase. They need to include all reports: Quarterly, Annual, TEIMP, Milestones, and Project Summary
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
@dleard This could be the topic of the hands-on metabase training we were talking about today.
Building a view of reporting requirements, with conditional formatting, sorted by due date, something like that?

**Comment by pbastia** [comment]
I think this can be 2 metabase views:
- what's outstanding, in order of what is the most late
- what is upcoming sorted by what due date is the closest

It needs to include everything: Quarterly, Annual, TEIMP, Milestones, and Project Summary reports

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1686?planning-poker) with Zenhub @andrea-williams @BCerki @dleard @sam-warren @JoshLarouche

**Comment by pbastia** [comment]
Fantastic @Sepehr-Sobhani !
