### ISSUE TITLE
As a CIF administrator, I want to add general comments to a project, so I can communicate with team members

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1689]
#### Description:

> **General comments:** can this be added e.g., a general comments tab that would show a history of comments/general updates when we’ve last spoke to a proponent (kind of like a ‘know your customer’ section), what docs we’re waiting for, etc., similar to how a comment is added for an amendment but would be more general to overall project status (if this is completely out of scope/not a realistic feature that okay, this is a ‘nice to have’)

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by nanyangpro** [comment]
This could be a deletion candidate as discussed with Nicole last time? We have "General Comments" field for the stated purpose on the Project Overview form.

**Comment by pbastia** [comment]
Business area:
> It's just too bad that it's buried in a tab
> But it's totally fine, and I think this is the most appropriate place
