### ISSUE TITLE
As a CIF Administrator, I want to see help text of form fields, so that I understand what it is and how it's calulated

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1692]
#### Description:

The rules for some calculated fields are getting too complex even for someone familiar with the CIF program. Tooltips are prepared for fields on the forms below to provide more clarity to users.

- Budgets, Expenses, & Payments
- Milestone Reports
- Emissions Intensity Report 

#### Acceptance Criteria:

Given I am a CIF administrator
When I hover over the tooltip icon next to a field listed in the [Tooltips for Calculated Fields](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EfLRtSfmMwxJl5B8DGj2I2cBgFyPnX_bxFF8SZiIoZ30yA?e=e7z0T3) document
Then I see contextual help text for the field

#### Development Checklist:

- [x] Add `ui:tooltip` object to the UISchema of each of these forms and pass the related context to it
- [x] Add tests
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by Sepehr-Sobhani** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1692?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @JoshLarouche @mikevespi @sam-warren

**Comment by BCerki** [comment]
For the fields that have multiple bullet points, does all the text go in one tooltip?

**Comment by Sepehr-Sobhani** [comment]
@BCerki With the current tooltip implementation we only have one tooltip per field, So I'm assuming we can use an HTML list tag to display multiple bullet points.

**Comment by nanyangpro** [comment]
Great question, @BCerki! Yes.

Thanks @Sepehr-Sobhani for making it possible. :)

**Comment by Sepehr-Sobhani** [comment]
@pbastia This one is already in test.
