### ISSUE TITLE
External User Engagement Privacy Impact Assessment (PIA)

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#17]
Acceptance Criteria:
- [x] Generalize PIA for all Clean Growth initiatives
- [x] Draft PIA for external user research
- [x] Submit to NRM Privacy Group for initial review 
- [x] Review with Matt and Adria for input
- [x] Submit to NRM Privacy Group for final review 
- [x] Get ED's signature on PIA
- [x] Get other required signatures

Notes:
- Ideally want to draft a PIA that can be leveraged by Branch for all external user engagement.

**Comment by LindsayMacfarlane** [comment]
Emailed NRM Privacy group for early input on PIA template to ensure we are using the correct format.

**Comment by LindsayMacfarlane** [comment]
Emailed NRM Privacy group for feedback on draft prior to circulating to Directors and ED.

**Comment by LindsayMacfarlane** [comment]
Made updates based on feedback provided by NRM Privacy Officer. Have sent back for additional feedback and input.

**Comment by LindsayMacfarlane** [comment]
Sent draft email to AF, MZ and CF for feedback.

**Comment by LindsayMacfarlane** [comment]
Submitted latest version of PIA and participant consent form to NRM Privacy Group.

**Comment by LindsayMacfarlane** [comment]
Followed up on status of PIA, March 23, 2022.

**Comment by matthieu-foucault** [comment]
@LindsayMacfarlane You mentioned this week that the PIA was completed. Should this be closed?

**Comment by LindsayMacfarlane** [comment]
@matthieu-foucault - this PIA is related to external user engagement. I've closed the PIA related to the CIF app.

**Comment by LindsayMacfarlane** [comment]
Finally completed!!!
