### ISSUE TITLE
Can't delete a BC registry id [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1701]
Describe the Bug:

If you try to delete a bc registry for a committed operator, it deletes on the form but continues to show in view mode, the operators table, and dropdown on the project form.

Probability (how likely the bug is to happen, scored from 1-5): 1
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:
https://www.loom.com/share/78a5df748520499cbef8faa85ea1047d
Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
The same happens to the contacts form

**Comment by BCerki** [comment]
> The same happens to the contacts form

Right, there's already a card for that: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1026

**Comment by BCerki** [comment]
https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1702 should fix this

**Comment by pbastia** [comment]
That's great news! Closing
