### ISSUE TITLE
`handle_default_form_change_commit` function doesn't handle removing fields[8]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1702]
Describe the Bug:

`handle_default_form_change_commit` function is used to parse form_change data into table data when the status of the form_change record is set to `committed` but currently it has an issue with removing value from optional fields. when a user removes an optional field from any of the forms, this function doesn't remove it from the related table data.

Probability (how likely the bug is to happen, scored from 1-5):3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):5
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- on any forms, remove an optional field
- commit this change
- check the value of that changed field in the corresponding table data and you should see the existing data

**Comment by Sepehr-Sobhani** [comment]
That's a great point, Thanks @pbastia .
I have a PR ready here: https://github.com/bcgov/cas-cif/pull/1705 I would appreciate it if you can take a look if you have time. This change only affects optional fields when we are updating the form and should affect required fields.

**Comment by Sepehr-Sobhani** [comment]
Update based on the discussion with Dylan and his proposed solution: We need to go through each JSON schema file and identify the fields that are not required. For these fields, we should change their type to a list containing null (for example, `"type": "string"` will become `"type": ["null", "string"]`). Additionally, we need to add default: null to each of those objects.

After completing these modifications, we must update the JSON schemas in production. To achieve this, we need to write a migration similar to the `insert_json_schema_form_data` file. However, we should exercise caution during this migration, as we need to consider existing changes. Therefore, we must review each of the existing files to identify any modifications.

Please note that some forms do not utilize a database-backed JSON schema, such as the emission intensity, project, and contact forms. Hence, we need to update their schemas in the respective schema files.

It would be prudent to test this idea by selecting one database-backed and one front-end-backed schema form to assess its viability.

**Comment by Sepehr-Sobhani** [comment]
@pbastia This is all backend stuff but if you want to ensure that the logic is functioning properly, you can examine an optional field (such as the score in the project overview form) and remove it from the form. Then, verify that the field has actually been removed from the project table by checking it in Metabase.

**Comment by pbastia** [comment]
This works! Thank you @Sepehr-Sobhani
