### ISSUE TITLE
As a CIF admin user, I want to hard delete attachments, so that I'm not keeping files I don't need

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1703]
#### Description:

In #1462, we created an attachment form. When a user is creating a project for the first time and deletes an attachment, the attachment should be hard deleted. #1462 hard deletes the form_change record. This ticket is about hard deleting the actual attachment from google storage. (Once a project has been committed, we only soft delete so we can keep a change log.)

#### Acceptance Criteria:

Given I am a CIF admin user
When I am creating a project and I delete an attachment ~or discard my entire revision~
Then my attachments are deleted from google storage

#### Development Checklist:

- [x] Hard delete from google storage (check out CIIP's deleteRouter and hard delete functionality for an example)
- [ ] e2e test cleans up uploaded test files:
- - [x] Add assertions. Can use something like this if you like:
```  cy.get("input[type=file]").selectFile("./cypress/fixtures/1dummy.pdf");
    cy.findByText("1dummy.pdf").should("be.visible");
```
- - [ ] give CI the env variables necessary for upload (at least the storage dev json, maybe more)
- - [x] delete the uploaded test file (1dummy.pdf) from google storage after the test
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by BCerki** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1703?planning-poker) with Zenhub @dleard @gurjmatharu @JoshLarouche @mikevespi @sam-warren @Sepehr-Sobhani

**Comment by BCerki** [comment]
@patriciarussellCAS, to test this, create a new project, go straight to the attachment form, add an attachment, and then delete it. If it works, the attachment has been hard deleted (if you'd like me to show you the file disappearing from the google bucket, I can screenshare with you as you test).

**Comment by patriciarussellCAS** [comment]
Thanks @BCerki - it looks like I could use some help on this one as well. I can't seem to be able to delete the attachment from the project (soft delete).

**Comment by BCerki** [comment]
@patriciarussellCAS , this should work now
