### ISSUE TITLE
Bug: the chart to test backups is using obsolete images for PGO

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1707]
Describe the Bug:

The daily DAG to make sure our backups work is failing, so we don't have the certainty that our backups succeeded anymore.

The images in our main CIF helm chart's postgres template have the correct images that should be used in the backup-test chart.

Probability (how likely the bug is to happen, scored from 1-5): 5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
Just some changes in the code, but nothing to test for the PO.
