### ISSUE TITLE
As a CIF user, I want to have updated Sectors and Project Type lists on the project overview, so that I can accurately identify projects

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1718]
#### Description:

from the business area:
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/2913a0a2-db85-41d9-b8cb-95b365b01b2e)

#### Acceptance Criteria:

Given that I'm on the project overview page
When I'm creating or editing a project
Then I can see `Energy Efficiency` as one of the options in the project type drop down

Given that I'm on the project overview page
When I'm creating or editing a project
Then I can see `Waste` and `Manufacturing` as one of the options in the sectors drop down

#### Development Checklist:

- [x] Create `project_type_002.sql` and add `Energy Efficiency` as a new entry in the project_type table
- [x] Create `sector_001.sql` and add `Waste` and `Manufacturing` as new entries in the sector table
- [x] Update tests
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by Dianadec** [comment]
Add this to the epic for CIF enhancements @pbastia

**Comment by Sepehr-Sobhani** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1718?planning-poker) with Zenhub @dleard @andrea-williams @BCerki @gurjmatharu @sam-warren @JoshLarouche

**Comment by Sepehr-Sobhani** [comment]
Adding Methane Capture already addressed in https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1421

**Comment by andrea-williams** [comment]
for the second AC, should the `Waste` and `Manufacturing` options be in the Sector dropdown, not project type? (Based on the attached screenshot table). (Sorry, I've never even seen the CIF app so I'm operating blind here)

**Comment by Sepehr-Sobhani** [comment]
You are absolutely right, It was copy/paste issue, my bad! Thank you @andrea-williams

**Comment by pbastia** [comment]
Nice work @sam-warren ! I can see the updates in both dropdowns.
