### ISSUE TITLE
As a Developer, I want to use a tool to catch emails, so that I can test email features in dev and test

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1723]
#### Description:

Card about deploying MailHog or [maildev](https://github.com/maildev/maildev) to the cluster in -dev and -test, so that we don't email people accidentally while testing the email service.

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] helm chart item
- [ ] smtp configuration
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
...If we use CHES, is this still needed @dleard  ?

**Comment by Dianadec** [comment]
Meeting set for next week to see how the dev/test environment works for ches. May not need this card.

**Comment by pbastia** [comment]
ches wouldn't support this. deleting
