### ISSUE TITLE
As a CIF administrator, I want to have a "Pending Emission Report Submission" status for my projects, so I can filter by that status

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1734]
#### Description:

CIF admins would like a "Pending Emission Report Submission" status

#### Acceptance Criteria:

Given I am a CIF administrator,
When I am editing a project (revision or amendment)
And I am on the project overview form
Then I can set the Project Status to "Pending Emission Report Submission"

Given I am a CIF administrator,
When I am editing a project (revision or amendment)
And I am on the project overview form
Then I can set the Project Status to "Emissions Intensity Report Pending"
And I can't set the Project Status to "Emissions Intensity Report Complete" (the status has been renamed)

#### Development Checklist:

- [x] A new entry in the status table in the database
- [x] The "Emissions Intensity Report Complete" entry has just been renamed to "Emissions Intensity Report Pending"
- [x] A test
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by andrea-williams** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1734?planning-poker) with Zenhub @dleard @BCerki @Sepehr-Sobhani @sam-warren @gurjmatharu @JoshLarouche
