### ISSUE TITLE
verify testing strategy for custom diff fields

### ISSUE THREAD

**Issue by gurjmatharu** [bcgov/cas-cif#1737]
###Description of the Tech Debt###
Currently there is old, latestcommitted and new data that are needed to render diffs.  Each can be a string type or a number type.  With numerous edge cases around number of decimals, money, percentage, contacts/managers, etc.  The test coverage of this is quite large.  Currently strings, numbers, and zero's have been tested.

The purpose of this tech debt is to evaluate what tests are missing, required and to implement them.

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |    1   |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |   3    |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |  1     |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |    1   |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |    1   |
| TOTAL SCORE:                                                                                                                  |       |   7    |

**Comment by gurjmatharu** [comment]
This isn't really required now, with our new tooltips.  We can reevaluate tests as we go.

**Comment by pbastia** [comment]
Thanks @gurjmatharu . closing.
