### ISSUE TITLE
Forms with multiple form_change items can get stuck in Attention Required state [5]

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1743]
Describe the Bug:

It's possible to get form pages stuck in Attention Required state for forms that contain multiple items (quarterly, annual, milestone). If a user deletes a required field from a report and then archives that report, the report becomes invisible to them but still has validation errors. This will cause the whole form to show an Attention Required state and block the project from being committed.

A couple of potential fixes:

- In the get_form_status() function, consider any archived forms as 'Filled'
- Do not allow archiving a form if it is missing required information

Probability (how likely the bug is to happen, scored from 1-5): 1

Effect (how bad the bug is when it does happen, scored from 1-5): 4

Steps to reproduce the behaviour:

Create a project with a quarterly report
Submit the project
Create a new revision
Remove the report due date from the quarterly report
Archive the quarterly report
Add new quarterly reports with all necessary information filled out
The status of the form page will be 'Attention Required'
If you look in the database at all quarterly report form_change records for that revision, you can see that the archived one (which cannot be seen in the UI) has validation errors.

**Comment by pbastia** [comment]
I can confirm I can remove reports with missing required fields without issues. thank you @dleard !
