### ISSUE TITLE
Archiving a report form_change record removes the Generate Reports button[5]

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1744]
Describe the Bug:

The readonly prop [defined here](https://github.com/bcgov/cas-cif/blob/develop/app/components/Form/ProjectQuarterlyReportForm.tsx#L200) is determined by the length of the set of edges for Quarterly/Annual reports (maybe other places?) being equal to 0. This means that if a report is archived, the component will think it is readonly because the archived report(s) are counted in the set. The readonly prop is used to determine whether or not to show the Generate Reports button, so archiving a report hides that button and all reports from here on must be created manually.

This bug could have other side effects that have not been diagnosed.

This needs some investigation to see if there is a better way to define the readonly prop & if there are other side effects of how this prop is being set.

If it's determined that checking the size of the edges is still the best way to set the readonly prop, then that size check needs to ignore archived reports.

Probability (how likely the bug is to happen, scored from 1-5): 2

Effect (how bad the bug is when it does happen, scored from 1-5): 3

Steps to reproduce the behaviour:

Create a project
See that there is a Generate Reports button on the quarterly/annual report form page
Add a quarterly or annual report
Submit the project
Create a revision
Archive the quarterly/annual report
See that despite there being no reports, the Generate button is still gone
If the readonly prop is logged, you can see that it is set to "true" despite being in edit mode

**Comment by Sepehr-Sobhani** [comment]
I think we can have a `sql` function to determine if we have any other non-archived Quarterly reports for this revision but I feel like that would be an overkill and we can just simply filter out archived form changes.

**Comment by Sepehr-Sobhani** [comment]
@dleard suggested renaming the `readonly` prop to something more meaningful.
