### ISSUE TITLE
Bug: Inactivity modal shows up even when the user is active.[7]

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1749]
Describe the Bug:

When a user is in the app, the inactivity modal will show up even if the user has been active.
We need to make sure to appropriately reset the timer.

Probability (how likely the bug is to happen, scored from 1-5): 5
Effect (how bad the bug is when it does happen, scored from 1-5): 2

Steps to reproduce the behaviour:
Stay on the app for 30 minutes

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
Would it be a possible solution to pass `mousedown` event to `extendSessionOnEvents` to extend the session?!

**Comment by dleard** [comment]
First thing to check: Is CIF using the latest version of the sso packages?
