### ISSUE TITLE
Bug: Milestone Due column in project table can display erroneous information [7]

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1755]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 4
Effect (how bad the bug is when it does happen, scored from 1-5): 3

Steps to reproduce the behaviour:

Unclear - Project 144 in our prod data is impacted

This is likely due to our `project_next_milestone_due_date` also taking into account in deleted reports

**Comment by Sepehr-Sobhani** [comment]
I see `project_next_milestone_due_date` only takes care of milestone reports while Lindsey mentioned `Summary Reports` in the team's channel post which is a different report type. should we change the logic of this function and consider `summary reports` too?!

**Comment by pbastia** [comment]
For the "milestone" column of the projects table, I think we only need to take milestones into account, so I'd say no

**Comment by pbastia** [comment]
The title was misleading, it's not happening only when the project has non-milestone reporting requirements

**Comment by pbastia** [comment]
@Sepehr-Sobhani  it's unclear what I need to test here - is it something you can confirm is in dev?

**Comment by Sepehr-Sobhani** [comment]
In this ticket, we excluded archived reports from `project_next_milestone_due_date` so we can have an accurate due date. This is now in PROD.
