### ISSUE TITLE
Bug: form_change record only gets saved on a single status value

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#176]
Describe the Bug:
If any new row that with the `triggers_commit` set to `true` gets added to the `cif.change_status` table, it won't trigger a commit of the row.

https://github.com/bcgov/cas-cif/blob/de33df7f31a82559fcf22653e9c4b47e9bfebfcb/schema/deploy/tables/form_change.sql#L21

Probability (1-5):
1-2

Effect (1-5):
5

**Dev info**
Subqueries cannot be added in the `when` clause of a trigger, but function calls are allowed.
We can probably create a computed column or a function `cif.triggers_commit(cif.change_status)` that returns a boolean
and then call it something like 
```sql
create trigger ...
when (cif.triggers_commit(new)) 
```

**Comment by matthieu-foucault** [comment]
I'm missing some context here. Which `change_status` value other than `committed` would trigger a commit?

**Comment by pbastia** [comment]
Right now, none, but we've stored the various

**Comment by pbastia** [comment]
This can be closed for now since it's been inactive - and not really a bug anyways. We'll reopen it if needed
