### ISSUE TITLE
Removing and re-adding budgets, expenses and payments doesn't show the diffs[5]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1767]
Describe the Bug:
creating this bug to address a comment in card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1379

If I remove a funding agreement and then re-add it and fill it, I don't see it in the diffs and all the newly entered info is gone when I commit.

Probability (how likely the bug is to happen, scored from 1-5):3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- Edit an existing project revision
- Edit Budgets, Expenses and Payments
- Click No to is this a funded project.
- Click yes to discard
- Click Yes to is this a funded project.
- fill out the Budgets, Expenses and Payments form
- Go to Amendments & Other Revisions page to see the diff (it's only showing the removed form)

Screenshots:
[Loom Video](https://www.loom.com/share/1972fd120eda49e29e14654ffc95e28a)

**Comment by BCerki** [comment]
The extraneous arrows are covered by this bug ticket: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1822

**Comment by patriciarussellCAS** [comment]
I was able to recreate this and it appears to be fixed. Thanks!
