### ISSUE TITLE
Cypress/e2e test for the emissions form

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1772]
###Description of the Tech Debt###

Our e2e tests don't fully test the Emissions Intensity form (not part the edit test, possibly excluded from other tests too). This ticket is about adding assertions for that form (look at one of the other forms, e.g. project summary report, for an example of what should be covered).

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| TOTAL SCORE:                                                                                                                  |       |       |

**Comment by Sepehr-Sobhani** [comment]
@BCerki Is this ticket about covering the below TODO in `index.cy.js` file?
`//TODO: TEIMP Agreement, when fixture is added`

**Comment by BCerki** [comment]
> //TODO: TEIMP Agreement, when fixture is added

Yes, and also about adding TEIMP to the edit test

**Comment by Sepehr-Sobhani** [comment]
By edit did you mean `edit-project-revision` file? if so, seems like we already have tests for it (line 153 to 176)

**Comment by BCerki** [comment]
Yes, `edit-project-revision`. That test currently adds a new emission report, which is the same thing the create test does. I was thinking `edit` should instead edit a field that was put in by an emission intensity fixture
