### ISSUE TITLE
Calculated and adjusted calculated values are mixed up when viewing a project [8]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1773]
Describe the Bug:

When viewing a project that has adjusted values, the adjusted label doesn't show up, and the adjusted value shows up for the non-adjusted label:
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/4ded35fd-7038-4e5c-88af-e21e3638d2e9)
 (these are the values for those fields in the form: ![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/3179ab1d-fa2b-419e-bb26-ea3b94d45244)

A starting point might be `app/lib/theme/widgets/ReadOnlyAdjustableCalculatedValueWidget.tsx` or the other adjustable calculated value widgets. Field labels are normally handled by `app/lib/theme/widgets/FieldLabel.tsx`, but since these widgets show two values, they need to get a second label somehow, and I think that's the problem. Could also consider refactoring these widgets because the second label is causing display and accessibility issues too.

Probability (how likely the bug is to happen, scored from 1-5): 5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context
)

**Comment by Sepehr-Sobhani** [comment]
Is this only on the milestone report?
