### ISSUE TITLE
Calculated fields don't show in diffs if nothing else on the form has changed [6]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1788]
Describe the Bug:

When a calculated value on one form is calculated entirely from values on another form, the check for `formNotAddedOrUpdated` comes out as true and no diffs are shown. This makes it look like calculated values were deleted.

It probably affects these budgets fields:

- Total Eligible Expenses To Date: 
- Total Gross Payment Amount To Date: 
- Total Holdback Payment Amount To Date: 
- Total Net Payment Amount To Date
- anticipated funding amount per fiscal year?
- 
And these emissions intensity fields:
- Payment Percentage of Performance Milestone Amount (%)
- Actual Performance Milestone Amount
- Maximum Performance Milestone Amount

Milestones should be okay because the calculations are in newFormData

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 4 (looks like data has been lost)
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- start a revision
- change total eligible expenses on the milestone form
- do not touch the budgets form
- go to diffs page
- you won't see the budgets calculation (total net payment amount to date) diffs
- (this is one example, other fields do this too)

Screenshots:
When only the milestone form is touched:
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/617d2a20-3367-46ff-ac8d-ced557e47a21)

When something on the budgets form is changed (contract start date in this screenshot) then the calculated diffs show up:
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/68ca3d1c-8473-49d7-820b-fa29ca8804f2)

Considerations:
- could check if there are relevant milestone diffs showing and conditionally show the budgets form
- check if there have been changes to any of the calculated values in the milestone form (repetitive of the CustomDiffFields logic)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by patriciarussellCAS** [comment]
@BCerki I wasn't able to get this to work properly. Can you take a look? Thanks!

**Comment by BCerki** [comment]
@patriciarussellCAS , I think the emission form diffs are working correctly. (They're difficult to test, though, which is why we couldn't trigger them this morning.) Here is a path that should help you test them:
screenshare video: https://www.loom.com/share/b84af0ec250f4b61b0113db3cef3c3b3
steps:
- create a new EP project
- fill out the required information on the project overview (key-smash is fine, it doesn't matter what the data is)
- fill out the required info on the emissions form (key-smash is fine)
- submit the project
- create a General Revision for that new project
- add a milestone and fill out the required info
- don't touch anything on the emissions form
- navigate to the "Edit General Revision" page
- you should see diffs under both the milestone and emissions form sections
