### ISSUE TITLE
adjustedHoldbackAmount has wrong capitalization in the milestone schema [8]

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1794]
Describe the Bug:

Somewhere along the way a bad capitalization of `adjustedHold**B**ackAmount made it into the milestone schema. This caused any functions that were looking for the correct key in the json (adjustedHold**b**ackAmount) to come up with null. This is throwing off the totalHoldbackAmount calculation shown on the budgets-expenses-payments form.  When no calculatedHoldbackAmount value is present, it is coalescing to 0 because it can't find the adjusted value due to the capitalized key mismatch in the form data.

Probability (how likely the bug is to happen, scored from 1-5): 4

Effect (how bad the bug is when it does happen, scored from 1-5): 4

**Comment by pbastia** [comment]
The bug is fixed :) thanks @dleard !
