### ISSUE TITLE
Post Tech + Ops Session Knowledge Capture

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#18]
Following the Tech + Ops Team session on Sep. 16, this ticket will help pull out knowledge learned to be able to combine it with past and future meetings.

**Acceptance Criteria**
- [x] Create process map from verbal information
- [x] List main stages identified
- [x] Track where both teams fit in process

**Reference Materials:**
[Notes from meeting](https://teams.microsoft.com/l/file/B5572C26-6FDB-4BC2-A6DF-2CE5A6407643?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F00608-ScrumTeam%2FShared%20Documents%2FScrum%20Team%2FCIF%2FEvents%2C%20Workshops%20%26%20Meetings%2FTech%20%2B%20Ops%20Inception%20Conversation%20-%20Sep%2016.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F00608-ScrumTeam&serviceName=teams&threadId=19:57fe54e9af5e4fefbf34e89fc3936e1f@thread.tacv2&groupId=29821293-3244-455d-beae-e01d27762cfe)

**Comment by LindsayMacfarlane** [comment]
Great work @jaimiebutton ! I really enjoyed the workshop with the Tech and Ops team - we got so much valuable information. I also really enjoyed the collaborative team afternoon drafting the CIF process map - it was both fun and insightful. When you have a moment, could you please add a link to the relevant Miro boards for the process map. Thanks!

**Comment by jaimiebutton** [comment]
Updated, thanks!
