### ISSUE TITLE
Inconsistency in Project Summary Report Revisions: Previous Changes Not Visible in Subsequent Revisions (only IA projects)[9]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1802]
Describe the Bug:

If the user makes changes to the project summary report and commits them in a new revision, the previous changes will not be visible in the following revision.

To check: after two revisions, we correctly see the info on the summary page.

Probability (how likely the bug is to happen, scored from 1-5):5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- Create a new IA project
- Fill out the project summary report form
- commit changes
- create a new revision
- change data in the project summary report
- commit changes
- create another revision
- go to the project summary report
- changes are not updated!!!

Screenshots:
https://www.loom.com/share/b7b2295e9c9f42e78454afbdc312435d?sid=3b8a0eb2-c715-402a-984f-86fdb65be790

**Comment by pbastia** [comment]
@Sepehr-Sobhani has a feeling this could be related to the `union` sql we use when creating the revision

**Comment by pbastia** [comment]
IA projects represent about 10% of the projects

**Comment by BCerki** [comment]
New bug card related: https://github.com/bcgov/cas-cif/issues/1844
