### ISSUE TITLE
QA focus

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1803]
#### Describe the task

Focus on QA, as a team
form TBD

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BCerki** [comment]
Bug fixes in test:

- UI Glitch had overlapping text on the project summary report--fixed
- Milestone Calculated/Adjusted values were displaying erroneous labels on the revision summary page-fixed
- Secondary contacts were not showing under certain circumstances--fixed
- Professional designation was blank when the user selected 'N/A'--This fix wasn't working for me:https://www.loom.com/share/3eb126a500e44e94832f89fa4f2d1de6
- Removing a field from a form was not removing it from the data properly under certain circumstances--fixed, but note: In most forms, if something is removed, the key stays in `new_form_data` and the value goes to null. In the EI and Project Summary report form, the key seems to entirely disappear. In budgets, the only optional fields are within an array and if you remove a whole source the field goes to [], or if you remove a partial source the key disappears. Not sure if the inconsistency will cause problems later

**Comment by rdromey** [comment]
Placeholder for QA, CIF Team has checked the bugs and we should be good to go.
