### ISSUE TITLE
Project Contact Summary page doesn't show secondary contacts[7]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1808]
Describe the Bug:

The project contact summary form does not display secondary contacts despite their existence.

Probability (how likely the bug is to happen, scored from 1-5): 4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- Add secondary contacts to a revision
- Commit that revision
- create another revision
- change a random field in the project overview form
- commit the revision
- go to project contact form view page
- secondary contacts are not there 😱

**Comment by pbastia** [comment]
Nice work @Sepehr-Sobhani ! The secondary contacts are working :)
