### ISSUE TITLE
Project creation form styles should match prototype

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#181]

**Comment by matthieu-foucault** [comment]
This is to get us closer to the prototype/wireframe. I don't know if we'll have a perfect match. Having a separate identity vs background section while keeping the data structure flat is one of these things that is a bit tricky to do in terms of code, so I don't know if we'll get around to that

**Comment by LindsayMacfarlane** [comment]
Thank you for the clarification :) Perhaps this is something that can be discussed at the design session this week.
