### ISSUE TITLE
Logout button is not displayed for unauthorized users

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#187]
Describe the Bug:

Probability (1-5):

Effect (1-5):

Steps to reproduce the behaviour:
log in with the cypress reporter account, you should get redirected to a page saying you're not authorized.
The log out button is not rendering, so you can't log into a different account

**Comment by LindsayMacfarlane** [comment]
Tested in Dev using above account. I got the un-authorized message and logout button appeared as expected. Thank you @matthieu-foucault !
