### ISSUE TITLE
Deleted records prevent approval of amendment [7]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#1870]
Describe the Bug:

Deleted records cannot be modified, so if an amendment contains a deleted (archived?) form, the amendment cannot be approved. The error is "Deleted records cannot be modified". I think the problem is either the project attachments form or the reporting milestone.

See the Teams chat for a list of projects. To find the form changes associated with a project in metabase: `select * from cif.form_change where project_revision_id in (select id from cif.project_revision where project_id=[go get from teams]) and operation='archive';`

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Dianadec** [comment]
@BCerki no worries! I moved it to the cas-cif repo. This is done by opening the issue in github and using Transfer Issue on the right side.

**Comment by Sepehr-Sobhani** [comment]
@patriciarussellCAS To ensure this fix is working properly, try these steps:
1. Create a milestone related to expenses and submit the revision.
2. Change the milestone to a non-expense type in another revision and submit it.
3. In a third revision, remove the milestone and submit without encountering any errors.

**Comment by patriciarussellCAS** [comment]
Thanks @Sepehr-Sobhani & @BCerki - I believe I was able to test this properly and it appears to be working. I will move to Approved by PO. Would either of you be able to deploy this to Test for me?

**Comment by Sepehr-Sobhani** [comment]
@patriciarussellCAS It's deployed to test. Now we have CIF v1.15.0 which contains the most recent bug fix.
