### ISSUE TITLE
As a CIF project coordinator, I want parts of the project long id to be generated, so that I can ensure consistency on all the related forms and documents

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#189]
#### Description:
The project RFP should not be a free-form field, but a complex widget that populates automatically depending on the selected RFP year, stream, and operator. Only the three-digit part should be editable directly

The long id format is `<year>-RFP-<stream_id>-<random_digits>-<operator_code>`

To allow CIF users to input existing projects in the system, the random_digits part should be editable (later, an option should be added to generate those digits). The other parts should be read-only and depend on the selected RFP year, stream, and operator

#### Acceptance Criteria:
Given I am logged in as a CIF user
When I create a new project
Then the year, stream_id and operator_code parts of the long id should be automatically generated

#### Development Checklist:
- [x] The year is derived from the funding_stream_rfp table
- [x] The stream_id is derived from the the funding_stream_rfp table
- [x] The operator_code is derived from the operator table
- [x] The generated portions of the long ID are shown in the form as read-only
- [x] The random_digits part of the long ID is editable by the cif user
- [x] The database column has a unique constraint

#### Notes:
-
#### Personas:

- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/189?planning-poker) with ZenHub @AlexZorkin @matthieu-foucault @pbastia

**Comment by LindsayMacfarlane** [comment]
Thanks @dleard! Works as expected.
