### ISSUE TITLE
Fix project diffs in frontend

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-cif#1898]
###Description of the Tech Debt###

The diffs in the project revision summart page are not accurately reflecting all of the changes being made in the revision. To make it more clear what the project revision being submitted is going to change, the diffs are to be simplified to show exactly that: the differences between the project revision being submitted, and the projects current state. This means removing one of the form data objects being taken in by the diffs, and updating each of the summary pages to provide the correct values.

- [x] Form summary pages for pending project revisions all show the diffs between latest committed data, and data in that project revision
- [x] Deleting an attachment now shows up in the diffs
- [x] Tests have been updated to handle the new diffs layout

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| TOTAL SCORE:                                                                                                                  |       |       |

**Comment by pbastia** [comment]
@mikevespi I saw some comments related to this in the Teams chat, do you think we should try and get this done too before going to prod with the whole thing? Or could this wait?
