### ISSUE TITLE
Bug: CIF - Sentry doesn't work

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1902]
Describe the Bug:

Frontend errors don't send a stack trace to Sentry

Probability (how likely the bug is to happen, scored from 1-5): 5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by pbastia** [comment]
@patriciarussellCAS  I think this is essential especially since we're in maintenance mode

**Comment by patriciarussellCAS** [comment]
As part of this ticket we should double check that it's not an issue with other apps.

**Comment by pbastia** [comment]
@patriciarussellCAS let's bring this into the sprint backlog, @mikevespi and I will look at it on Monday

**Comment by pbastia** [comment]
It turns out Sentry works just fine. The issue is ad blockers and browser privacy extensions that prevent us from getting adequate stack traces. Maybe something we can investigate at a later point!
