### ISSUE TITLE
CIF: Bug: Operation column is confusing and shows archived records on the project attachment view page 

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1922]
Describe the Bug:

A confusing "Operation" column shows for attachments, where "Archive" operations are also shown in the attachments table when viewing a project.
I suggest removing that column altogether @dleard @patriciarussellCAS @Sepehr-Sobhani @BCerki 

Probability (how likely the bug is to happen, scored from 1-5): 5
Effect (how bad the bug is when it does happen, scored from 1-5): 2

Steps to reproduce the behaviour:
View the attachments page for a project where attachments were just added and removed as part of the latest revision/amendment

Screenshots:

<img width="864" alt="image" src="https://github.com/user-attachments/assets/47f1bc9c-cad4-4957-adad-21428a7b93e1">

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by dleard** [comment]
I found the [PR where this was added](https://github.com/bcgov/cas-cif/pull/1910/files#diff-0ff8aa46281608a06815f0f8426ebd6ff12f8a0b4e5ece2d0433dac471d85748) and it was an intentional change. Are we sure we want to remove it?

**Comment by pbastia** [comment]
@dleard  I think in this particular spot (the actual attachment table) this causes confusion when looking at the current attachments for a project.
The feature will stay active and useful for the diff before a user submits a revision, it's using the same component.

**Comment by patriciarussellCAS** [comment]
Thanks for taking this on guys! Do we need to assign someone to the ticket, or at this point does it matter? @pbastia

**Comment by patriciarussellCAS** [comment]
Is someone able to point to a specific project in the Test enviro where I could see this fix? Every project I click on has zero attachments! 

And just to confirm - the intended outcome here is that we should no longer see "archive" files in the list, correct? 
Also have we clarified for them what the difference between "create" and "update" is under the operation column? That isn't clear. 
@pbastia & @Sepehr-Sobhani

**Comment by patriciarussellCAS** [comment]
I was able to recreate this and confirmed that deleted attachments are no longer visible in the list. 

@pbastia - not sure if this is a separate issue but wondered why the file "type" for my word doc attachment looks like this? 


![Image](https://github.com/user-attachments/assets/e7dff6d6-a136-4472-8587-6a19e2c5f22b)

**Comment by pbastia** [comment]
@patriciarussellCAS this is the mime-type that the system reports, it's actually correct. If we want a better readout we would need to build that in

**Comment by patriciarussellCAS** [comment]
Next step: deploy to test - let CIF internal team know  - have them test it, then if it's good, push to Prod.

**Comment by patriciarussellCAS** [comment]
Deployed to Prod
