### ISSUE TITLE
Ensure that CleanBC logo is loaded with the page

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#198]
#### Describe the task

When loading the page, there is a flash of content without the CleanBC logo. It should come with the page, but does not for some reason. 
~This is probably what is causing the logo to not appear in the Happo screenshots~ Apparently that didn't fix the happo screenshot rendering, see https://github.com/happo/happo.io/issues/223

#### Acceptance Criteria

- [x] CleanBC logo is rendered without flashing
- [x] CleanBC logo is visible in the Happo screenshots: fixed by updating happo: https://github.com/bcgov/cas-cif/pull/228

**Comment by LindsayMacfarlane** [comment]
Thank you @matthieu-foucault ! The CleanBC logo is displayed as expected and I see no flashing.
