### ISSUE TITLE
As a CIF user, I want to be able to see at a glance the total funding request related to a project , so that I can easily see how much funding a particular project has been allocated 

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#204]
#### Description:
As a project coordinator I want to be able to see how much funding has been allocated to a given project. 

#### Acceptance Criteria:
Given I am a project coordinator
When I am on the create project view
Then I am able to enter the total funding request related to the project

#### Development Checklist:
- [x] `Total Funding Request` input is added to project creation form.
- [x] `Total Funding Request` is a numeric input that only allows two decimals and uses commas for thousands separator
- [ ] The project table show the total funding request
- [ ] Meets the DOD

#### Notes:
- 

#### Personas:
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)
- [Tech Team ](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/204?planning-poker) with ZenHub @AlexZorkin @dleard @pbastia

**Comment by LindsayMacfarlane** [comment]
@Sriram-pc can you add the link to the wireframe?

**Comment by Sriram-pc** [comment]
Attaching [#69](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/69). Bottom of this ticket has funding request total.

**Comment by Sriram-pc** [comment]
![image.png](https://images.zenhubusercontent.com/6149103e0c14630f5a9c158a/e2e501f0-8824-40f3-983a-a0ff4092419a)

**Comment by LindsayMacfarlane** [comment]
Thanks @dleard ! I tested in Dev and it works as expected. A couple of comments for consideration:

- I feel that the total funding request shouldn't be place between the Project name and project Summary. I'm assuming we will update its location when we update the design and layout?
- Field does not allow for text (as expected)
- Probably a usability question - I like that as a user I wouldn't have to enter the $, but I wonder if that is behaviour CIF would be expecting?  
- The project list table accurately displays the funding value entered

Thanks Dylan - looks great!
