### ISSUE TITLE
As a Tech Team user, I want to be able to enter the project evaluation score, so that I can easily see how a given project ranked

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#205]
#### Description:
Tech team users would like to be able to enter and view the project evaluation score related to an individual project. This is the overall project score result from the blind scoring that will be done outside of the scope of the app.

#### Acceptance Criteria:

Given I am a Tech team user
When I edit a project
Then there is a field where I can enter a project score.

Given I am a CIF user
When I am on the project list page
Then I can see the project score at a glance

Given I am a CIF user
When I am on the project list page
I can search and sort the list of projects by the project score

#### Development Checklist:
- [ ] The project_revision database table has a `score` column
- [ ] The edit project UI has a form field for the project score
- [ ] Entering the score creates a form_change record for the project_revision table
- [ ] Removing the score when no score previously existed deletes the form_change record
- [ ] Removing the score when a score previously existed creates an update form_change record
- [ ] The project list table displays the project score
- [ ] The project list table can be sorted and filtered by the project score

#### Notes:
- Question for the program area: does this field need to be included on the 'create project' page - or would this information typically be entered at a later stage? Perhaps this can be added once editing capabilities are created?

#### Personas:
[Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)

[Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

[Tech Team ](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by LindsayMacfarlane** [comment]
Sprint stand-up (January 10, 2022): TP indicates this field does not need to be prioritized for the mvp/first release as the score is not used for anything other than ranking and it doesn't need to be retained in the project information.

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro - this is complete through another ticket, correct?

**Comment by nanyangpro** [comment]
You are right, @LindsayMacfarlane. It's taken care of by #934, thus can be closed.

**Comment by LindsayMacfarlane** [comment]
Ticket is a duplicate and has already been implemented as per Nan's comment above. Closing.
