### ISSUE TITLE
CIF App Privacy Impact Assessment

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#207]
#### Describe the task

Draft Privacy Impact Assessment for the CIF application.

#### Acceptance Criteria

- [x] draft
- [x] review with PO and program area
- [x] submit to NRM privacy group
- [x] get signed off

#### Notes

- Required before launching Version 1 (MVP)

**Comment by Sriram-pc** [comment]
@pbastia @matthieu-foucault Tagging for the "CIF Flow Diagram" for STRA.
![image.png](https://images.zenhubusercontent.com/6149103e0c14630f5a9c158a/7061d52b-21a4-4fd5-930f-1d7917ae4466)

**Comment by Sriram-pc** [comment]
https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/ERTew6jGjxZIioOOwEk4UXIBPJLEpuBOku3-d9rc2S9KOA?e=pkT8gF

https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EQzd6K3RjMVBjer30tSAtAoBJSHIOVElHp5Cvq5PiIrAcg?e=cheemZ
