### ISSUE TITLE
Plan for usability testing

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#208]
This ticket captures the work to prepare for usability testing.

- [x] Identify where in development cycle we would like to usability test
- [x] Identify which user stories we would like to test
- [x] Write script
- [x] Determine who in CIF should be involved in usability testing
- [x] Design testing session(s)

Once this ticket is ready, we can schedule usability testing sessions with internal users.

**Comment by LindsayMacfarlane** [comment]
Thank you for creating this ticket @jaimiebutton. I added in a bullet for identifying who in CIF we need to test with. Based on the checklist criteria, my assumption is that several usability testing sessions may be needed/designed depending on the outcomes we are trying to achieve.

**Comment by LindsayMacfarlane** [comment]
Hi @elliottSlee @jaimiebutton - based on the checklist, do we feel this ticket has been accomplished?
