### ISSUE TITLE
Document value of CIF project

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#209]
As we develop the CIF digital solution, we will want to be able to share the value we are creating with the work we are doing. This compilation can act as a living document and be updated as we continue to explore the work.

- [x] [Create a place to store this information](https://bcgov.sharepoint.com/:w:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/Value%20of%20the%20CIF%20Project.docx?d=w39ecea4ad9ff41cb81f44e75c639f401&csf=1&web=1&e=TcRvIk)
- [x] Add in values identified in Business Value matrix
- [x] Refer back to CAS Digital Strategy
- [x] Refer back to Ministry's Digital Strategy
- [x] Brainstorm other ways we are adding value and win-wins

**Comment by LindsayMacfarlane** [comment]
I like this @jaimiebutton :) I believe Ram has started a Miro page to help document the BV. Perhaps we can leverage that page for this task (if appropriate). Would we also want to use this for the OKRs?

**Comment by jaimiebutton** [comment]
Fantastic, good to combine work! We could likely have the OKRs feed back into this after identifying them.

**Comment by LindsayMacfarlane** [comment]
Love it. Thanks @jaimiebutton !
