### ISSUE TITLE
Research Plan Outline

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#21]
Creation of [research plan outline ](https://bcgov.sharepoint.com/:w:/t/00608/Ef4jI2CiyjxAqBvL_7ghnOkBLJEyWw6Ze6cIhOJcCfTATw?e=fi6aLs)to pass through Matt and Taylor.

- [x] Outline goals of research
- [x] Write out specific areas of focus
- [x] Briefly explain proposed research methods
- [x] Pass to Lindsay for feedback
- [x] Pass to Taylor for feedback
- [x] Pass to Matt for feedback

**Comment by rajpersram** [comment]
Depends on ticket 35
