### ISSUE TITLE
Goals for External User Research

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#210]
To prepare for external user research (when we have capacity & approved PIA), this ticket documents outlining our goals for the research to set expectations.

- [ ] Ideate potential areas of focus
- [ ] Ideate potential methods of research & testing
- [ ] Outline high-level goals for completing external user research
- [ ] Document this in the Scrum Team channel for future reference

**Comment by elliottSlee** [comment]
Duplicate of #211
