### ISSUE TITLE
Discovery Workshop Follow-Up

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#22]
Acceptance Criteria:
- [x] Send follow-up email
- [x] Add slides to CIF Internal Users channel
- [x] Edit session recording
- [x] Add session recording to CIF Internal Users channel

Ask Ram if he'd be comfortable doing recordings in the future!

**Comment by LindsayMacfarlane** [comment]
As always, thank you for all your effort and dedication building our relationship with the CIF team and keeping our inception/discovery workshops inclusive and transparent.
