### ISSUE TITLE
As a CIF developer, I want to collect errors and metrics through Sentry

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#223]
add Sentry to CIF, [example](https://github.com/bcgov/cas-ciip-portal/blob/7c6d4f21230ed703bdd2fdd38334b6e5c64212b4/app/pages/_app.tsx#L67) from CIIP

Dev checklist:
- [ ] create project in Sentry interface
- [ ] env vars for cif instance 
- [ ] add the sentry boundary to `_app`

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/223?planning-poker) with ZenHub @AlexZorkin @dleard @pbastia

**Comment by LindsayMacfarlane** [comment]
Thanks @pbastia ! How would I test this one?
