### ISSUE TITLE
As a project coordinator, I want to see a summary of my answers before submitting a project revision, so that I can review the changes

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#226]
#### Description:
Before submitting a project revision, best practices recommended to show a list of changes being applied to the new/edited project. An example can be found [here](https://design-system.service.gov.uk/patterns/check-answers/).

For this iteration of the page, we only show the contents of the `form_change` records for the `project_revision`. 
Rendering of the differences since the previous revisions (#397) and rendering of errors (#396) will be handled in separate user stories.

Rendering of the form data in a read-only version can be done via a custom react-jsonschema-form theme, which would render a [`<dl>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl) instead of a `<form>`, `<dt>` instead of `<label>`, and a `<dd>` instead of an `<input>`. 

#### Acceptance Criteria:

Given that I filled the project overview, project managers, and/or project contacts forms
When I visit the  `/cif/project-revision/<id>` page
Then I see the values I entered in the page

Given that I did not add any project manager or contact
When I visit the  `/cif/project-revision/<id>` page
Then a message indicates that the project manager or contacts were not added.

#### Development Checklist:

- [ ] A custom `react-jsonschema-form` theme is used to display the form data
- [ ] Meets the DOD

#### Design:

![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/32157d4a-4674-4019-8e65-cd940c76c8c9)

#### Personas:

[Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/226?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @pbastia

**Comment by matthieu-foucault** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/226?planning-poker) with ZenHub @mikevespi

**Comment by BCerki** [comment]
@suhafa, @matthieu-foucault, what information do you want shown when the project contact or manager has been added?

**Comment by matthieu-foucault** [comment]
We can start with:
- For managers, something like `**<manager label>** <full name>` 
- For contacts, `**Primary Contact** <full name>` and then a list for the secondary contacts

**Comment by BCerki** [comment]
@matthieu-foucault, should I match the wireframe exactly or include all the all project information?

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki ! Tested in dev by: Updating an existing projecting (updated project name, project summary, project status, Ops team secondary project manager. Worked as expected.
