### ISSUE TITLE
Document gaps in UX/UI

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#232]
While we secure a UX/UI designer, we will naturally have gaps and assumptions in our designs. Documenting these gaps will help us know what to research when we have capacity and can point future UX/UI resources in the right direction of what to evaluate within our existing designs.

Acceptance criteria:

- [x] Create 'Design Patterns & Assumptions' Miro board to capture known gaps in CIF app's UX/UI design 
- [x] Document gaps known so far
- [x] Share board with GGIRCS team to add additional gaps

**Comment by Sriram-pc** [comment]
Attaching Raj's Hand off document. Might be helpful
https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EQrPC22TYjtDoxiTiIS4IfIBoj-fvcRHIUim1k9AVbwFAw?e=S3ji3p
