### ISSUE TITLE
Source-of-truth for Design Patterns

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#233]
This ticket captures the creation of a source-of-truth guide for design patterns for the CIF app. This guide can be used to ensure consistency across development, to minimize guesswork and avoid ad-hoc research.

- [x] Create 'Design Patterns & Assumptions' Miro board for guide
- [x] Create a framework of types of patterns
- [x] Fill in framework with hypotheses of what the patterns should be (if confident)
- [x] Pass Miro board to the GGIRCS team for shared ownership & feedback
Design Patterns & Assumptions Miro Board

**Comment by Sriram-pc** [comment]
Useful Design Links that Matthieu posted in the Scrum channel
https://www.nngroup.com/articles/errors-forms-design-guidelines/
https://xd.adobe.com/ideas/principles/web-design/best-practices-form-design/
https://design-system.service.gov.uk/patterns/validation/
https://www.nngroup.com/articles/error-message-guidelines/

**Comment by LindsayMacfarlane** [comment]
Thanks so much for getting this started @jaimiebutton ! I've added in a few links from design/writing guides that were created for the Water Team products - there may be some information that is applicable to our CAS applications. As we formalize this a bit more, it might be nice to present this at a Sprint Review (I have a feeling users don't recognize how much thought goes into considering design and accessibility).
