### ISSUE TITLE
As a CIF User, I want to not see a blank loading page when data is loading, so that I have a better experience

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#239]
#### Description:

Currently, the screen flashes blank when loading.
We should use the previous component in the `fallback` to show the previous page until the new page is loaded.
Will involve a relay-nextjs update.

#### Acceptance Criteria:

Given I am loogged into the cif app
When I perform an action that loads data
Then the screen does not flash

#### Development Checklist:

- [ ] Screen does not flash when loading
- [ ] Meets the DOD

**Comment by matthieu-foucault** [comment]
Relevant discussion: https://github.com/RevereCRE/relay-nextjs/issues/43

**Comment by dleard** [comment]
This is now also an issue in cas-ggircs since we started using relay-nextjs

**Comment by LindsayMacfarlane** [comment]
I didn't notice any flashing blank pages :)
