### ISSUE TITLE
Research Metrics Facilitation

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#24]
Metrics & Key Performance Indicators (KPIs) help us measure success against a set of targets, objectives, or industry peers. They also allow us to continually reflect on progress.

Metrics ideation will be captured in the CIF Metrics Miro board.

**Acceptance Criteria:**
- [x] Connect with Ram
- [x] Reach out to BC Gov Service Design Team (GDX) on their KPI work
- [x] Ram & Jaimie to do some learning from online resources
- [x] Ram & Jaimie [to share their learning in a document](https://bcgov.sharepoint.com/:w:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/CIF/Metrics/Suggested%20Metrics%20CIF.docx?d=w73c79b5e75a742cca48cd3670a343d08&csf=1&web=1)!
- [x] Raj to talk to developers about what KPIs we have (our could have) for CIIP that we can learn from
- [x] Take a look at [GWELLS past work](https://teams.microsoft.com/_#/files/Scrum%20Team?threadId=19%3A57fe54e9af5e4fefbf34e89fc3936e1f%40thread.tacv2&ctx=channel&context=GWELLS%2520Metrics%2520Work&rootfolder=%252Fteams%252F00608-ScrumTeam%252FShared%2520Documents%252FScrum%2520Team%252FCIF%252FMetrics%252FGWELLS%2520Metrics%2520Work)
- [x] Take a look at GDX Service Design team's past work

**Comment by jaimiebutton** [comment]
KPIs can be from the perspective of:
- Financial/Internal User Time
- User Satisfaction
- Process-Focused

**Comment by LindsayMacfarlane** [comment]
Some good reading/resource materials:
- Radical Focus, Achieving Your Most Important Goals with Objectives and Key Results.

**Comment by rajpersram** [comment]
The SUS has been sent out to establish a benchmark on ease-of-use of the current system (Excel, LAN, etc) and once we determine a milestone for the CIF web application, we can send the same survey to establish a quantitative comparison and from that, calculate a ROI estimate.
