### ISSUE TITLE
CPI Workshop User Research

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#242]
There will be a CleanBC Program for Industry workshop for Operators. We have an opportunity to conduct some user research for our digital systems. Workshop is being planned for Feb 23/24, 2022. 

Acceptance Criteria:
- [x] Reach out to planning team to see if there is an opportunity for us during two day workshop
- [x] Determine needs of GGIRCS team, CIF (CleanBC Implementation), and CIIP (ICU)
- [x] Determine mechanism (e.g., survey)
- [x] Determine tools/software that we can use
- [x] identify users we are targeting

Notes:
- Spoke to Tammie on Jan 25 about possible approach. Agenda is fairly well planned; however Behzad and Meghan are presenting for their respective program areas - we could get them to make a plug for the survey. 
- Is there anything for Public Reporting we can do here too?

**Comment by jaimiebutton** [comment]
Another ticket ([#293](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/293)) has been added to capture work for a future CIF survey.

**Comment by LindsayMacfarlane** [comment]
Great work team! @elliottSlee and @jaimiebutton - do we have a ticket in the backlog to capture the wrap-up and analysis of the feedback that was received from the survey?

**Comment by jaimiebutton** [comment]
See follow-up[ ticket #321 ](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/321)for survey analysis
