### ISSUE TITLE
User UUID should use IDIR guid instead of JWT sub

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#260]
The JWT subject is an id that is specific to the keycloak realm. 
Using IDIR guid instead to identify users would:
 - make an eventual transition to a different keycloak realm, or away from keycloak, easier
 - allow us to restore prod data in a test environment for QA purposes without having to deal with users with different UUIDs but duplicate emails

**Comment by matthieu-foucault** [comment]
![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/b5af66d5-d5ae-4f44-945b-8894e0fdbedb)

**Comment by dleard** [comment]
@matthieu-foucault @pbastia How will this affect authentication for external (non-government) users? Will we have to continue to use `sub` for them?

**Comment by pbastia** [comment]
I'm wondering if we could use the BCeID as an alternative, that siteminder supports? I've been recently made aware that anyone can get a basic one instantly https://www.bceid.ca/aboutbceid/ even if they're not a BC resident

**Comment by matthieu-foucault** [comment]
Usage of BCeID for CIF applications will need to be discussed. The use case for the basic BCeID is "when accessing a service in a personal capacity", which does not seem to be not the case here. A business BCeID might be needed instead.

For the scope of this issue, the user UUID should probably be coalesced to `sub`, to ensure that there is always a UUID (will be required when using our test accounts in development)
