### ISSUE TITLE
CIF internal usability testing with Ops Team

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#262]
#### Describe the task
Complete first round of usability testing with at least one user to better understand if functionality to date meets user needs.

#### Acceptance Criteria

- [x] make sure the testing environment has data
- [x] print script
- [x] prepare data collection tool (spreadsheet)
- [x] disseminate data collection tool to attendees

#### Additional context

- Ideally test once app deployed into TEST environment

**Comment by LindsayMacfarlane** [comment]
Hi @elliottSlee - what are your thoughts/capacity on pulling this ticket into this upcoming sprint (March 7 - 18)? Ideally, I'd like to see this started :)

**Comment by LindsayMacfarlane** [comment]
@elliottSlee - thank you and kudos for all the awesome work and analysis that went into this task. I really appreciate the insights gleamed and the relationship building that resulted from this work. A huge thank you to @suhafa for using this opportunity to get feedback on initial designs related to reports.
