### ISSUE TITLE
As a project coordinator, I want to enter reporting requirements for a project, so that I can track a project's reports

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#263]
#### Description:

Brief description of the work involved, including any user research context or key decisions.

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

#### Notes:

-

**Comment by dleard** [comment]
Old issue. Closed in favor of more specific reporting cards (#456 / #458)
