### ISSUE TITLE
As a CIF user, I want to see an error page with explanations, so that I understand what to do

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#264]
TODO: Prior to implementation, check in with Suha regarding phrasing of 500 page

#### Description:

This is about having nice 404 and 500 pages

#### Acceptance Criteria:

Given I am a CIF user
When I try to access a cif URL that doesn't exist
Then I can see a 404 page that informs me that the URL doesn't exist
And I can see a link to the main landing page

Given I am a CIF user
When the server encounters an issue
Then I am notified that the server returned an error
And I am prompted to email the team
And I can see a link to the main landing page

Given I am a CIF user
When I try to either access a page that doesn't exist or when the server encounters an error
Then I can see a CIF-styled error page with the CIF header and footer
And the presented text is identical to the CIIP pages

#### Development Checklist:

- [ ] a `pages/404.tsx`, and a `pages/500.tsx` page for the implementation (see [ciip 404](https://github.com/bcgov/cas-ciip-portal/blob/develop/app/pages/404.tsx) and [ciip 500](https://github.com/bcgov/cas-ciip-portal/blob/develop/app/pages/500.tsx) for an example)
- [ ] Meets the DOD

#### Notes:

- [Next documentation](https://nextjs.org/docs/advanced-features/custom-error-page) on error pages

**Comment by pbastia** [comment]
CIIP:
404
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/77cc3a05-38b6-46f2-935e-6b243bfa4eb3)

500
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/cd86633d-4d1a-4630-82f7-9127fa5c9dc4)

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/264?planning-poker) with ZenHub @dleard @matthieu-foucault @BCerki @gurjmatharu

**Comment by suhafa** [comment]
![image.png](https://images.zenhubusercontent.com/6201b10c9827341d8d5cbe9c/aac63d0e-85be-4d76-ac48-1c8516d91040)

**Text:** 
- Heading: Sorry, something went wrong
- Description: An unexpected error occurred. Contact us at **ggircs@gov.bc.ca** and tell us what happened. Meanwhile you can <u>refresh this page</u> or try again later.

**Notes**

- As a user, I want to click on the email address displayed with the error, and have it activate the default mail client on my computer for ease in reporting the error  {mailto:ggircs@gov.bc.ca + subject:Reporting an error}
- 'refresh this page' to reload the page when clicked for ease.

**Comment by matthieu-foucault** [comment]
@BCerki I think no button might be better here. There is probably be a way to get that information to display somehow, but I don't think it's worth the effort.

**Comment by suhafa** [comment]
@BCerki - Is it possible to change the description text to '**An unexpected error occurred. If this error persists, contact us at ggircs@gov.bc.ca and tell us what happened. Meanwhile you can refresh this page or try again later.**' - to avoid emails influx

**Comment by LindsayMacfarlane** [comment]
Thanks @BCerki - what's the best way for me to test this ticket?

**Comment by BCerki** [comment]
> Thanks @BCerki - what's the best way for me to test this ticket?

Head to the home page and add /404 or /500 to the URL and you should be able to see the error pages. The buttons and links on both pages should send you to the correct place

**Comment by LindsayMacfarlane** [comment]
Awesome! Thank you @BCerki - looks great!
