### ISSUE TITLE
CIF v1.0.0 release

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#271]
#### Describe the task

Once user testing in the `test` environment has been conducted and all critical bugs and improvements are done, we can release to the prod environment.
Cutting a prod release will require some checks to be enabled to ensure that the database migrations that are already deployed to prod are immutable. 
Following the CIIP release process, we can rely on standard-version to generate a changelog and increase version numbers appropriately.

#### Acceptance Criteria

- [ ] a github action ensures that sqitch changes before a tag are immutable
- [ ] a github action ensures that the sqitch plan ends with a tag on the `main` branch
- [ ] a `values-prod.yaml` file exists in the helm chart

**Comment by LindsayMacfarlane** [comment]
Well done everyone! This was a big milestone and it is so exciting to have the CIF app in PROD.
