### ISSUE TITLE
Form controls should have consistent styling

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#272]
#### Describe the task

`SelectParentWidget`, `SearchDropdownWidget`, `MoneyWidget` and `PhoneNumberWidget`, used in the project and creation forms, have inconsistent styling compared to other inputs.

#### Acceptance Criteria

- [x] `SelectParentWidget` and `SearchDropdownWidget` should have a line-height matching the `TextWidget` input
- [x] `SearchDropdownWidget`, `MoneyWidget` and `PhoneNumberWidget` should have an outline on focus matching the  `TextWidget`
- [ ] `SearchDropdownWidget` should no have a different style on hover
- [x] `SelectParentWidget` margins should be consistent with the other inputs
- [ ] `SearchDropdownWidget` should have down-arrow icon consistent with the [dropdown](https://button-inc.github.io/service-development-toolkit/@button-inc/bcgov-theme/index.html?path=/docs/components-dropdown--default) component
- [x] `SelectParentWidget` "empty" option should have a color consistent with other inputs placeholder value

#### Additional context

The list above is not exhaustive, and other syling items may need to be updated.

**Comment by gurjmatharu** [comment]
Sub-Task: `SearchDropdownWidget` should no have a different style on hover.
- Needs clarification.  Styles seem to be the same.

Sub-Task: SearchDropdownWidget should have down-arrow icon consistent with the dropdown component 

This should be the other way around - dropdown component needs to have consistent styling with the SearchDropDownWidget.  However, the dropdown widget doesn't use Icons.  Can we please create a new issue for this sub task.

**Comment by LindsayMacfarlane** [comment]
Thanks @gurjmatharu!

I took a look in dev. I'm not sure if the following observations are 100% related to this ticket.

1) Project Overview
- it looks like there are still discrepancies: funding stream, RFP year and project status don't match the other drop downs
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/dbd5c446-c123-483a-83c2-4c9b7d88dfd1)
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/2e3ba02b-c062-43c5-a28b-f9924f72779f)

2) Contacts
3) Operators
4) Other Observations:
- For accessibility, should text be lower case? For example: Short project name vs Short Project Name? 

FYI @suhafa - for consideration and future input.
