### ISSUE TITLE
Prod URL and SSL certificate

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#273]
#### Describe the task

A production URL for the CIF application, e.g. `cas-cif.nrs.gov.bc.ca`, should be ordered via the NRM service desk. 

If required, an Entrust certificate will need to be ordered (first, an attempt to issue the certificate needs to be made, leading to a failed deployment, payment must be done via the NRM service desk, and once the request is approved, the application can finally be deployed). 
Alternatively, a Let's Encrypt SSL cert could be used, offering a free and fully-automated process

#### Checklist:
- [x] Determine if we can use Let's Encrypt
- [x] Seek budget approval for Entrust if we can't use Let's Encrypt
- [x] Budget approved
- [x] Get input from program area on what url type should be secured (vanity vs nrs)
- [x] Submit required Domain name request & web property application form in order to secure cif.gov.bc.ca 
- [x] Submit SSL Certificate request

**Comment by LindsayMacfarlane** [comment]
Emailed program area (March 1, 2022) to get input on whether we should secure a vanity or nrs url for the CIF app.

**Comment by LindsayMacfarlane** [comment]
Program area would like to proceed with the vanity url.

**Comment by matthieu-foucault** [comment]
1) secure the vanity URL
2) configure the DNS
3) deploy to prod
4) order the certificate

**Comment by LindsayMacfarlane** [comment]
Steps to secure vanity url: https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/Vanity+URL%27s

**Comment by LindsayMacfarlane** [comment]
Submitted domain name request form and web property application form to CITZ GDX.

**Comment by matthieu-foucault** [comment]
The DNS was setup, so `cif.gov.bc.ca`, `dev.cif.gov.bc.ca` and `test.cif.gov.bc.ca` all point to the silver cluster. Developers now need to configure the app (helm chart) to use the hosts above. Given that SSL certificates are only issued on installation of the app with our current script, the easiest path in dev and test is probably to uninstall and then re-install the application with the new hosts

**Comment by matthieu-foucault** [comment]
@LindsayMacfarlane Entrust certificate request was issued. An email was sent to the GGIRCS inbox on Thursday April 14. The tracking ID in that email will have to be submitted as part ot the iStore request to approve the certificate.

**Comment by LindsayMacfarlane** [comment]
Request for SSL certificate has been submitted to the NRM Business Service Desk.

**Comment by LindsayMacfarlane** [comment]
Have followed up to see status of request on:
- April 29
- May 3

**Comment by LindsayMacfarlane** [comment]
Certificate order appears to be complete. See GGIRCS inbox for email.

**Comment by matthieu-foucault** [comment]
![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/a722c9e4-732d-4351-bdf4-62b8a3dd2ba1)

**Comment by matthieu-foucault** [comment]
@LindsayMacfarlane certificate was issued, backed up to 1Password, and the prod cif application was turned down to 0 pods, as it's not ready to be online yet
