### ISSUE TITLE
CIF page layout width should adapt to content

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#274]
#### Describe the task

The page layout, defined in `DefaultLayout`, is currently using the entire width of the page. On wide screens and on pages with little content, this does not provide a great user experience.

The page layout should use `auto` margins to center the contents horizontally. 

#### Additional context

- Mobile screen size support is not a requirement, but if we can have something that is responsive, that's a bonus
- If needed, we can add a prop to `DefaultLayout` to have narrow vs wide layouts. Some pages, e.g. rendering tables will need fairly wide layouts
- I could not find recommendations for the layout in the BC Design system. [Here](https://design-system.service.gov.uk/styles/layout/) is the UK design system equivalent.

**Comment by LindsayMacfarlane** [comment]
Thanks @gurjmatharu ! Tested in dev by playing with screen size on the following pages. It was unclear if only the heading was part of this ticket or the entire pages. Notes from my testing:

- dashboard: page adjusted as expected, did notice at a certain scale the 'CleanBC Industry Fund' disappeared in the heading
- project list table: the table didn't adjust. I wonder if there is value in having a sliding bar so users can more easily scroll? We could confirm need/value during usability testing
- Project overview: the two column layout got squished together at a certain scale. Two columns is not great design and will probably be updated anyways. 
- Operator table: table appears to be responsive
- Contact table: table appears to be responsive

**Comment by gurjmatharu** [comment]
Hi @LindsayMacfarlane,

I think we need to define screen sizes that we want to support.  A lot of our designs breakdown after a certain screen size.  This issue, was meant to to make it responsive for larger screen sizes (laptop +).

Project list table - agreed we should look into a sliding bar.  

Project overview - another one we definitely need to address, the two column layout isn't great.

Should we create a new issue to address the above and close this one out?

**Comment by LindsayMacfarlane** [comment]
Thank you for the update @gurjmatharu 

Let's close the ticket and pass this feedback onto @elliottSlee and @suhafa for consideration in usability testing and UI Design. If needed, we can then create tickets to address in future development.
