### ISSUE TITLE
Project form fields should follow logical order

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#276]
#### Describe the task

The Project creation form should have its fields ordered in a way that doesn't require the user to go up and down the page.

The form fields should be ordered as follows:

1. Funding Stream/RFP Year
2. Operator
3. RFP Number
4. Project Name
5. Summary
6. Total Funding request
7. Project status

This order can be enforced using the [`uiSchema["ui:order"]` property](https://react-jsonschema-form.readthedocs.io/en/latest/usage/objects/#specifying-property-order) in the `ProjectForm` component (`app/components/Form/ProjectForm.tsx`).

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki ! The project page follows a much more logical order now.

Some observations when testing:
- The heading for RFP year says "Funding Stream RFP". I wonder if there is opportunity to streamline that heading...or at least add 'Year' to the heading.
- Drop down menus have different fonts (size, colour, type). They should be all consistent
- Drop down menus contain field help text within the drop down (sorry - this probably isn't the correct terminology!); I'm wondering if this is best usability practice? I feel like best practice is to have help text coded beneath the field so it is always there as reference?
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/92645ff9-27aa-4585-8b14-444ffceff7e9)
- The RFP Number field has become really squished (squishiness stays the same regardless of screen size)
- Project status seems to be tied to funding stream RFP year. For example, if I don't select funding stream year, then no options are displayed in the project status. 
- After these changes, project view doesn't follow the same format. 

FYI @suhafa - above for consideration in future design/dev work.
