### ISSUE TITLE
As a CIF user, I want the history of swrs-imported operators to be initialized on import, so that I can have access to the full set of changes in the audit tables

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#286]
#### Description:

Currently, the operators created by SWRS don't have an audit trail for their creation or updates in the `cif.form_change` table. This breaks our architecture conventions, and breaks patterns that rely on an existing form_change to initialize the next.

#### Acceptance Criteria:

Given the operator import script from SWRS is running
When an operator with a `swrs_operator_id` is inserted 
And that `swrs_operator_id` doesnt exist in the system
Then a `form_change` record is also created, with the `create` type and the reason "Imported from SWRS"

Given the operator import script from SWRS is running
When an operator with a `swrs_operator_id` is upserted 
And that `swrs_operator_id` already exists in the system
Then a `form_change` record is also created, with the `edit` type and the reason "Updated from SWRS"

#### Development Checklist:

- [ ] a `cif_private.create_form_change_for_swrs_operator` function that generates the appropriate `form_change` record from an operator record
- [ ] This can probably be done with temporary triggers `on insert` and `on update` - or potentially create the form_change with `committed` status and let the existing triggers do the work?
- [ ] Meets the DOD

#### Notes:

-
#### Personas:
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)
- [Tech Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by LindsayMacfarlane** [comment]
Hi @pbastia - can you give me some hints on how I can test this one?

**Comment by LindsayMacfarlane** [comment]
Hi @pbastia - is this something I can test? Or is it more backend specific?

**Comment by LindsayMacfarlane** [comment]
Note: until there is a UI, that shows the form changes, I can't really test. 

Thank you @pbastia for walking me through this ticket.
