### ISSUE TITLE
Identify Internal Champions

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#29]
Acceptance Criteria:
- [x] Identify who we think internal champions are
- [x] Get feedback from Matt
- [x] Draft email
- [x] Send email to key players notifying them of their key player status & asking if there's anyone we missed
- [x] Notifying of upcoming Key Player meetings (both for Personas and Process mapping)

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton, MZ has provided some names as primary contacts/Champions for the team:
- Main point of contact: Taylor
- External User Engagement: Meghan
- Tech Team: Shelby
- Development Team: Taylor (same as primary contact)
- Operations Team: Amanda

I'm sure others will emerge, but this is a good start :)
