### ISSUE TITLE
How can we collectively remember our Common Goal?

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#291]
The GGIRCS team will be meeting with the CIF team on Feb. 25 to discuss our realignment of development priorities. Once we have outcomes from our discussion(s), how can we 'hold up' our common goals to ensure we all know what we're working towards?

- [x] Receive priority document from TP
- [x] Ideate how to make our common goal visible to all (with more of a business/plain language focus than development focus)
- [x] Set up time to coordinate with TP

**Comment by Sriram-pc** [comment]
Product Roadmap is one of the option. We can update for version 2 release, once we have an idea about the priorities

**Comment by LindsayMacfarlane** [comment]
Is our common goal the same or different from our vision?

This is important. I think it has been hard to communicate that we share the same goal/vision throughout the project as we don't have final mockups to show what it will all look like. Could this help? Really low-wifi mock-ups that would show CIF their journey through the app?

I like Ram's suggestion on the roadmap, but that also hasn't resonated with CIF as we would expect.

**Comment by jaimiebutton** [comment]
@LindsayMacfarlane Very cool idea - and that would be a separate but related ticket to build out a very simple user journey of pages linked together.

In addition to that, something like @Sriram-pc's idea of the product roadmap in a more accessible format. (Something super simple & clear)

**Comment by jaimiebutton** [comment]
Moved back into Backlog (will bring back once we receive the priority document from Taylor)
