### ISSUE TITLE
Development data should include form_change records

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#301]
#### Describe the task

We are creating a number of entities in our development data to avoid having to recreate contacts, operators, projects, etc every time. Those records were however directly added to the `contact`, `operator` and `project` tables, respectively, which does not match how our application will create database records: `form_change` records should be created and their status updated to `committed`. For projects, `project_revision` records should be used.

Not having `form_change` records means that when editing one of these generated entities, the forms do not get initialized properly

**Comment by LindsayMacfarlane** [comment]
Thanks @gurjmatharu! I'm assuming that there is nothing for me to test on this one?

**Comment by gurjmatharu** [comment]
> Thanks @gurjmatharu! I'm assuming that there is nothing for me to test on this one?  

Just the projects are listed, editable, and have connected contacts. That's about it!
