### ISSUE TITLE
As a Logged out user, I want to see the IDIR login form when I click the login button, so that I don't have to click two buttons

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#305]
#### Description:

One can use the `kc_idp_hint=idir` parameter to get keycloak to redirect the user directly to Siteminder.
This will require updating the [`sso-express` library](https://github.com/bcgov/cas-template-app/blob/develop/packages/sso-express/src/controllers.ts) to support adding arbitrary URL parameters in the authorization url (see the `loginController`)

This should be the default behaviour of the application. To show the keycloak screen, a boolean `SHOW_KC_LOGIN` env/`--show-kc-login` arg can be used. 
Until we have test IDIR accounts, `SHOW_KC_LOGIN` should be set to 'true' in the `dev` openshift environment, and when running end-to-end tests

#### Acceptance Criteria:

Given that I am logged out
When I click the "Log In" button
Then I am redirected to the siteminder site, where I can enter my IDIR username and password

Given that the application was started with the `SHOW_KC_LOGIN` flag and I am logged out
When I click the "Log In" button
Then I am redirected to the keycloak site, where I can enter chose my identity provider (keycloak username/password, or IDIR)

#### Development Checklist:

- [x] Release a minor update of the `@bcgov-cas/sso-express` package
- [x] Meets the DOD

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/305?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @pbastia

**Comment by mikevespi** [comment]
@matthieu-foucault the [method](https://github.com/bcgov/cas-template-app/blob/develop/packages/sso-express/src/controllers.ts#L99) generating the auth url comes straight from `openid-client` , so should we just add a param for URL params to `SSOExpressOptions`?

**Comment by matthieu-foucault** [comment]
Yes, adding an option for extra authorization url parameters would work

**Comment by LindsayMacfarlane** [comment]
Thank you for your work on this one @mikevespi . Just to confirm this ticket, when I test in dev I still get multiple steps for logging on:
1) Select login button on CIF app
2) Go to "Authenticate with" page - select IDIR
3) Then get redirected to site minder page where I can enter my login credentials.

I feel these are the same steps I was doing before?

**Comment by mikevespi** [comment]
This was intended behaviour on dev. At the moment, the step that is skipped is only skipped in test and prod. If we would like this changed for the dev namespace it's a simple change.

**Comment by LindsayMacfarlane** [comment]
Thanks @mikevespi - I think it would be good to have dev and test the same where/if possible for consistency. Should that be a new ticket to capture implementing this within the dev environment?

**Comment by mikevespi** [comment]
@LindsayMacfarlane It is in dev, it just doesn't affect it. It was intentional since skipping the login page in dev would mean everyone using it would require a working IDIR.
