### ISSUE TITLE
Audit check should not be required, and ignored by Shipit

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#306]
#### Describe the task

The audit check should not block merging PRs to develop, or block continuous deployment in shipit.
The audit check has been removed in our branch protection as a required status, but shipit is still blocked on CD.

An example of how to ignore a specific check is [here in the CIIP repo](https://github.com/bcgov/cas-ciip-portal/blob/develop/shipit.yml#L10)

This example is using circle ci checks, where CIF uses GH Actions. Instead of `hide` we want `allow_failures`.
It may be necessary to add some yaml to our GH Actions in order to expose those contexts.
Documentation on how to do this is [here](https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log)

#### Acceptance Criteria

- [x] audit is not required to merge to develop
- [x] shipit allows CD when audit is failing

**Comment by dleard** [comment]
This didn't require any extra context work, but needed a different syntax than we used in circleCI.
Instead of "ci/circleci: yarn-audit" it just needed to be "yarn-audit"
