### ISSUE TITLE
As a CIF user, I want to request another user's review on a pending amendment, so that I can get their explicit approval

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#308]
#### Description:

Brief description of the work involved, including any user research context or key decisions.

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
@nanyangpro @suhafa - is this user story captured with the recent notification work or is this something different? Wondering if we still need this?

**Comment by nanyangpro** [comment]
Thanks for confirming, @LindsayMacfarlane - Yes, this ticket can be closed with the initial intention covered by the notification work.

**Comment by LindsayMacfarlane** [comment]
Thank you for confirming @nanyangpro! Closing this ticket as a duplicate.
