### ISSUE TITLE
As a CIF User, I want to see an error on screen when a request fails, so that I know what happened

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#309]
#### Description:

When a GraphQL query, mutation, or a network request fails, an [alert](https://button-inc.github.io/service-development-toolkit/@button-inc/bcgov-theme/index.html?path=/docs/components-alert--default) should be displayed on the page

This card is about creating a custom version of relay's 'useMutation' with a default `onError` callback that:
- alerts Sentry
- uses React Context API to display a single custom error message (the previous error message would be replaced)

#### Acceptance Criteria:

Given I am a CAS developer
When I implement a component that calls a mutation
Then I have access to a custom `useMutation(...)` hook that requires an error message, and sets the error and alerts sentry

Given I am a CIF user
When I execute an action that triggers a network request (edit a form, save a form...)
And the request fails for any reason
Then I can see an error message at the top of the page

#### Development Checklist:

- [ ] a `GlobalAlert` component rendered in the `DefaultLayout`, and uses the React Context API to display its content.
- [ ] a custom `useMutation(...)` hook that accepts an error message. It has the same API as relay's `useMutation` and adds custom `onError` callback that calls `Sentry.captureException` and sets the message to be rendered in the global alert
- [ ] Meets the DOD

#### Notes:

- React Context doc: https://reactjs.org/docs/hooks-reference.html#usecontext

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/309?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi

**Comment by LindsayMacfarlane** [comment]
@BCerki - Any best ways for me to test this one?

**Comment by BCerki** [comment]
I'm not sure--@matthieu-foucault, any suggestions?

**Comment by matthieu-foucault** [comment]
After creating or editing a project, use the back button to go back to the forms, and then try to edit a field. Your change should be undone and the error should appear. I will demo it during our sprint review

**Comment by LindsayMacfarlane** [comment]
Beautiful. Thank you @BCerki and @matthieu-foucault - saw in demo and was able to recreate in dev.
