### ISSUE TITLE
Review CIF 'schedule' documents

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#312]
#### Describe the task

The CIF Funding Agreement Appendix A has a series of schedules with project information. 

This ticket captures the work of reviewing documents related to CIF schedules.

#### Acceptance Criteria

- [x] Get updated spreadsheets/addition examples of Funding Agreement documents from TP
- [x] Review spreadsheets/documents in 'Appendix A Planning' Miro board
- [x] Identify commonalities and differences
- [x] Create list of all necessary fields

#### Additional context

- Additional tickets will stem from this issue (e.g., tasks, UX design, user stories, etc)

**Comment by Sriram-pc** [comment]
Most of the documents are within these folders.
![image.png](https://images.zenhubusercontent.com/6149103e0c14630f5a9c158a/b824a6b5-00b0-46cd-8037-a7d63b9b6c89)
![image.png](https://images.zenhubusercontent.com/6149103e0c14630f5a9c158a/9c5b4db9-407e-4307-97a1-b669dde3c4c7)

**Comment by LindsayMacfarlane** [comment]
What an awesome team effort on this one!
