### ISSUE TITLE
As a Project Coordinator, I want to enter the RFP number in any format, so that I can enter numbers from previous years

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#315]
#### Description:

The RFP number field needs to be more flexible to handle older formats. We have decided for now to go with a free-form input for this field. We should rename this field to Proposal Reference, since that is what it really is and there is a lot of confusion around the naming of this field.

**Exploration**: 
How best to validate the uniqueness of the Proposal Reference and when to display that error if it is not unique

#### Acceptance Criteria:

Given I am a CIF user
When I am creating a project
Then I see a 'Proposal Reference' field to enter data for the previously named "RFP Number"

Given I am a CIF user
When I am creating a project
Then I can enter an Proposal Reference in any format

Given I am a CIF user
When I enter a Proposal Reference
And I try to submit the project
When the Proposal Reference is not unique, I see an error

#### Development Checklist:

- [x] The "RFP Number" field is renamed to "Proposal Reference" on the front-end and in the database
- [x] The Proposal Reference field is a free-form text input
- [x] If a Proposal Reference is not unique, an error is shown on submit
- [x] Meets the DOD

#### Notes:

-

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/315?planning-poker) with ZenHub @matthieu-foucault @pbastia @BCerki @mikevespi @gurjmatharu

**Comment by pbastia** [comment]
Here's what I suggest:
- [ ] creating a `hasExistingFieldValue(columnName: text)` computed column on the `form_change` table
    - that retrieves the value from the json new_form_data field and returns true if that value exists in the database already on the table that the form_change targets
    - ignores `archived_at` records
- [ ] make sure we have indexes on the columns where we check for existence (here cif.project.rfpNumber)
- [ ] when rendering the `ProjectForm` the query fetches that computed column (for rfpNumber)
- [ ] a [front-end custom validation rule](https://react-jsonschema-form.readthedocs.io/en/latest/usage/validation/#custom-validation-rules) checks that the computed column returned `false` or fails the validation

We don't need server side validation for this, since the database already enforces the rule by design.

**Comment by pbastia** [comment]
we can use the [`extraErrors`](tests/unit/components/Form/ProjectForm.test.tsx) prop if we want to turn on that single error in real time

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia ! I tested in dev:

- created a new project with proposal reference #2022-RFP-1-GGXX-666, was able to enter info as expected. 
- created a second project with the same proposal reference number (2022-RFP-1-GGXX-666) - received expected error message. 

Observation:
- The error message was a bit squishy (see screenshot). Is there opportunity to simplify the error message? 
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/093e79b6-d536-46ce-a534-b64676982ce7)

FYI @suhafa
