### ISSUE TITLE
Wireframe schedule screens

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#316]
#### Describe the task

Begin to wireframe initial screens that address the Appendix A and the relevant schedules. 

#### Acceptance Criteria

- [x] Design lo-fi wireframe
- [x] Refine Appendix A board
- [x] Find answers for orphan fields + missing information in Appendix A
- [x] Elaborate on the Budget and Milestone forms (this was made into separate tickets so doesn't apply under here anymore)
- [x] Reiterate wireframes (this was made into separate tickets so doesn't apply under here anymore)
- [x] Prepare for usability testing session with Ops Team

#### Additional context

- This ticket may need to be split into several issues.

**Comment by suhafa** [comment]
Closing this, some tasks have been created into separate tickets.
