### ISSUE TITLE
Branded decks

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#319]
#### Describe the task

Design and brand reusable decks for presentations.

#### Acceptance Criteria
- [ ] Diagnose and research the problem
- [ ] Get a list of previous presentations for context (e.g., sprint reviews, product demos, other)
- [ ] Collect branding elements
- [ ] Identify best software/apps for applying the design (powerpoint/google slides?)
- [ ] Design reusable templates
- [ ] Review for feedback
- [ ] Final Iterations

#### Additional context
- Help make things consistent and pretty
- Consult with @jaimiebutton.

**Comment by nanyangpro** [comment]
#545 is relevant.

**Comment by patriciarussellCAS** [comment]
This is no longer required.
