### ISSUE TITLE
Analyze CPI Workshop Survey

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#321]
Following the CPI Workshop survey captured in [Ticket #242](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/242), this ticket documents the analysis of the results.

- [x] Send first round of responses to key stakeholders (requested in March 3 Sprint Review)
- [x] Analyze responses
- [x] Create report & disseminate

#### Notes:
- Survey close date: March 18.

**Comment by elliottSlee** [comment]
Report can be found in Scrum Team/Files/Research/CPI-Survey.html

https://bcgov.sharepoint.com/:u:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/Research/CPI-Survey.html?csf=1&web=1

**Comment by LindsayMacfarlane** [comment]
Thank you @elliottSlee ! So fascinating to see the results from the survey.
