### ISSUE TITLE
As a CIF user, I want to see names displayed consistently across the application, so I never get confused by last/first name

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#326]
#### Description:

We need consistent name display in the CIF app

#### Acceptance Criteria:

Given I am a CIF user
When I see a person's name in the system (contact, user, manager, ...)
Then I always see it in the "last name, first name" format.

Given I am a CIF user
When I see a person's name in the system (contact, user, manager, ...)
And either the first or the last name is null,
Then I always see it in the "name" format.

#### Development Checklist:

- [x] `cif_user` table columns should be renamed to `given_name` and `family_name` , to be consistent with the `contact` table
- [x] abstract existing computed column on the `contact` table into a reusable function
- [x] implement a computed column on the `cif_user` table that reuses that function
- [x] display of user names (i.e. in the header, or when displaying manager names) should always be done using the `fullName` property
- [ ] Meets the DOD

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
Question for displaying names: what is the rational for doing the 'last, first' format vs 'first last'.

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/326?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @pbastia

**Comment by pbastia** [comment]
@LindsayMacfarlane there isn't any, really (we picked it because of the "Last, First MINISTRY:EX" format the BC gov follows).
This card is about having consistency everywhere in the application and a single piece of code where this is decided so changing it later is a really easy task

**Comment by gurjmatharu** [comment]
Hi @pbastia, can we please elaborate on `display of user names` I'm not quite sure where to make these changes.

**Comment by pbastia** [comment]
@gurjmatharu There are quite a few places on the front-end that use "firstName lastName" in the query and the display logic, this is what we mean with it. I can see it in those pages (but I might have missed some):
- `app/components/Form/ProjectManagerForm.tsx`
- `app/components/Project/ProjectTableRow.tsx`
- `app/components/User/UserProfile.tsx`
- `app/pages/admin/users.tsx`
- `app/pages/cif/project/[project]/index.tsx`

**Comment by gurjmatharu** [comment]
@pbastia, ah gotcha, those should already be changed.
