### ISSUE TITLE
Add getting started instructions to the readme

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#333]
#### Describe the task

Add instructions to the readme that explain how to get the app running locally.

#### Acceptance Criteria

- [x] List of pre-reqs (install the same packages as the to-do app, set up gpg signing, etc.)
- [x] Ordered list of commands for set-up (installation, what folder to be in, etc.)
- [x] Ordered list of commands to start the db, start the app, test, what flags/env/runtime settings to include, etc.
- [x] List of how to shut down and restart the app (how daily/post-rebase start-up is different from initial set up)

#### Additional context

- From Pierre: a lot of it could be copied over from the docs in the ciip repo: https://github.com/bcgov/cas-ciip-portal/tree/develop/docs I wonder at this point if we could combine them, or if the relay,react,next etc versions have diverged too much
- Partial list of instructions/commands: 

```
    make install_dev_tools

    make deploy_dev_data

    cd app

    yarn install

    yarn dev

    cd ..

    make drop_db && make deploy_dev_data
```
- `ENABLE_DB_MOCKS='true' yarn dev ENABLE_MOCK_AUTH` (currently we use process.env.ENABLE_DB_MOCKS, but process.argv.includes("ENABLE_MOCK_AUTH"); check when that changes from https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/340)

**Comment by BCerki** [comment]
> @BCerki May I assign the current sprint to this ticket and move it to the pending PO approval column?!

I've done it, thanks for the reminder!

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki ! Is there anything in particular I should be reviewing for  this ticket?

**Comment by BCerki** [comment]
> Thank you @BCerki ! Is there anything in particular I should be reviewing for this ticket?

Nothing to review in dev, but if you'd like to read the new instructions (mainly technical), they're here:
- https://github.com/bcgov/cas-cif/blob/develop/docs/developer-environment-setup.md
- https://github.com/bcgov/cas-cif/blob/develop/docs/developer-guide.md

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki !
