### ISSUE TITLE
Craft usability testing calendar invites

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#334]
One area of feedback we've received from the CIF team is to add more clarity to calendar invites about who should be in attendance and what topics will be covered.

Let's take the opportunity to perfect our invites for usability testing and continue to use the format we develop & iterate on for future meetings.

Acceptance criteria:
- [x] Review Diana's guidance on email updates
- [x] Create draft invite structure
- [x] Create calendar invites for usability testing with the Operations team

**Comment by Sriram-pc** [comment]
https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EYQdRHMg3QBJmHwvt9p3WOMB3D5k9Hn-VTrgZYd93dhSAQ?e=bSaCOt

**Comment by jaimiebutton** [comment]
Here's a first take at a calendar invite:

**Subject:** [Screen/Epic] Usability Testing
**Invitees:** Participant [Required], GGIRCS Team [Optional]
__________

Body: Elliott’s Writeup (shortened)

**Agenda:**
- Introduction to usability testing & goals
- We’ll have you walk through the CIF app and get your feedback!

**Before the meeting:**
There is nothing you need to prepare. We look forward to our session.

**Comment by jaimiebutton** [comment]
### Updated calendar invite for review:

**Subject:** Usability Testing: Add/Create a Project 
**Invitees:** Participant [Required], GGIRCS Team [Optional]
__________

As we develop  the CIF digital system, we want to make sure it meets your needs. This is why we would like to invite you to a session to test out what we’ve built so far. The point is to get your feedback early so that we stay on the right track. 
 
**What is usability testing?** 
The session is quite simple.  You will be asked to do several short tasks using the online system while we record your experience. You will also be asked questions about your experience and perceptions of the website. 

**Agenda:**
- Introduction to usability testing & goals
- We’ll have you walk through the CIF app and get your feedback!

You don’t have to prepare anything for it. There will be a few members of our team joining to watch and, if you consent, we will record the session including your camera and your screen.

**Comment by Sriram-pc** [comment]
Looks great

**Comment by jaimiebutton** [comment]
Hey @LindsayMacfarlane, I've made changes based on the first 2 bullets. I'm not sure of the time breakdowns @elliottSlee had in mind so it may be best to add those to the invite closer-to.

**Comment by LindsayMacfarlane** [comment]
Awesome - thank you @jaimiebutton ! Much appreciated.

**Comment by LindsayMacfarlane** [comment]
Thanks Team! Usability testing emails look great. Excited for the outcomes of these sessions.
