### ISSUE TITLE
Document lessons learned from project so far

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#335]
Every project is an opportunity for learning! As we have now completed Inception, Discovery, and User Story Mapping, the team would like to take a moment to reflect on lessons learned and capture them for future reference.

**Acceptance criteria:**
- [ ] Create a place to capture lessons learned
- [ ] Gather learnings from GGIRCS team
- [ ] Record learnings for future reference

**Comment by elliottSlee** [comment]
Would it be worthwhile to include a piece about organizing research/discovery findings?

**Comment by patriciarussellCAS** [comment]
This ticket is very old. We have now done a CIF Retro for the DS team. If we want to do a full retro with the CIF team, this could be part of our future planning work that may happen in late 2024.
