### ISSUE TITLE
As a CIF user, I want to see the managers assigned to a project in the list of projects

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#337]
#### Description:

The 'assigned to' column in the list of projects page is currently hardcoded to "J. Doeloremipsum, J. Doe". Now that we have the ability to assign multiple managers, it should show the list of managers assigned to a project (via the project_manager table).

![Screenshot from 2022-03-10 09-49-27.png](https://images.zenhubusercontent.com/5fc1589bc8692570749d2bed/7bf2abe7-428b-4626-aa2d-55de5e1219bc)

The Project fragment in `components/Project/ProjectTableRow.tsx` needs to retrieve the list of project managers (`projectManagersByProjectId { ...`) and display those managers instead of J. Doeloremipsum, J. Doe"

#### Acceptance Criteria:

Given I am a CIF user
When I am viewing the list of projects
Then I can see who each project is assigned to in the 'assigned to' column

#### Development Checklist:

- [ ] The Project fragment retrieves the list of managers
- [ ] The list of managers is displayed in the 'assigned to' column
- [ ] Meets the DOD

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/337?planning-poker) with ZenHub @dleard @pbastia @gurjmatharu @BCerki

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki ! Looks great. 

General observations:
- order of project manager names don't always seem to match up. It appears that the listing of primary vs secondary names are being reversed?
1. Project Table
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/a550036b-22bb-4163-a239-49a319b54292)
2. Edit a Project
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/fc44a1bd-8a40-4348-bbd5-c4b241bdcb69)
3. Project Overview
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/9abd0a19-4e14-42f9-9647-d476f1e58c17)

**Comment by BCerki** [comment]
> Hi @BCerki - confirming, since ticket #353 has been created, can I close this one?

I only made a new PR, not a new issue, so I think this one should stay open? (unless it's better to make a new issue? haven't learned all the workflows yet)

**Comment by LindsayMacfarlane** [comment]
Thank you for the updates @BCerki ! Tested in dev and project manager names appear to be displayed in the correct order :)
