### ISSUE TITLE
Create task user flow based on wireframes 

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#354]
#### Acceptance Criteria
- [ ] Reiterate wireframes after usability sessions
- [ ] Identify all the variables for creating the user tasks(s)
- [ ] Discovery session with Taylor to learn about funding streams (IA + EP) 
- [ ] Identify what fields can/will be amended
- [ ] **Create tasks user flow**
- [ ] Decide how the flow for amendments would look like

#### Additional context

- Follows creation of wireframes

**Comment by LindsayMacfarlane** [comment]
No longer required. Closing ticket.
