### ISSUE TITLE
Custom 500 page isn't rendered when front-end routing leads to an error

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#359]
Describe the Bug:

When an error happens in the application, we should redirect to the 500 page or show the sentry fallback (same UI). Some paths lead to the generic 500 page 

Probability (1-5): 2

Effect (1-5): 3

Steps to reproduce the behaviour:

If #301 isn't implemented, then this can be easily triggered by trying to edit one of the existing projects. Once the generic page below is displayed, you can refresh the page to see the nicer 500 page

Screenshots:
![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/db0075c5-d79c-48bf-b298-2d335893c89c)

**Comment by BCerki** [comment]
Notes to self:
-Sentry fallback doesn't work for event handlers: https://github.com/getsentry/sentry-javascript/issues/3140#:~:text=Sigh.%20Just%20found%20where%20the%20docs%20for%20error%20boundaries%20explicitly%20note%20that%20they%20don%27t%20catch%20exceptions%20from%20event%20handlers.%20That%20explains%20pretty%20much%20all%20of%20the%20issues%20I%27ve%20encountered.%20%3E.%3C

**Comment by BCerki** [comment]
#301 is now implemented, so the above testing suggestion won't work. I tested it with console logs, which isn't going to work for Lindsay--any testing suggestions, @matthieu-foucault?

**Comment by matthieu-foucault** [comment]
I'm not aware of any exception throwing errors on the client during the rendering process. I don't think this can be manually tested at the moment, Lindsay will have to trust us on this one :smile:

**Comment by LindsayMacfarlane** [comment]
I see above comment :) Moving this ticket to done.
