### ISSUE TITLE
Bug: the 'Clear' button in the project manager form doesn't work

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#360]
Describe the Bug:

The "Clear" Button on the project manager form doesn't work

![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/359e41ac-7a71-42c1-8586-9d76eccbacab)

Probability (1-5): 4

Effect (1-5): 4

Steps to reproduce the behaviour:

To reproduce:
As a CIF Admin, login and head to the dashboard
Click "Create New Project" or "Resume project creation"
Add a "Tech Team Primary" project manager
Click the "Clear" button next to it

Expected:
The Tech Team Primary field is cleared

Actual
The Tech Team Primary field is not cleared
There is a console error about the delete mutation

Development checklist:
- [ ] identify and resolve the issue
- [ ] write an end to end test making sure we can clear a project manager

**Comment by dleard** [comment]
@LindsayMacfarlane to test this bugfix:
Go to create/resume a project
add a manager
click the clear button
the manager should be removed without having to refresh the page
