### ISSUE TITLE
Tech Debt: conventional commits for CIF

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#363]
The CIF pre-commit hook doesn't check for conventional commits. This is useful for consistency across the team, and should be enabled.

We can set it up with this https://github.com/compilerla/conventional-pre-commit, or with an ad-hoc hook like we do for CIIP

More info here: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki ! I also like tasks that bring consistency ;) My assumption is that there is no testing required on my end - so approving.
