### ISSUE TITLE
As a Project Coordinator, I want to enter project data in multiple pages, so that I can break down my work

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#366]
#### Description:

This is the first part in the "task list" work. To keep it as small as possible, the work should be limited to displaying the task list as shown below in a left-side navigation with a "sticky" position, and splitting the existing project-revision page into four pages: one for each form, and one for the submit/discard buttons.
Each form needs a "submit" button to ensure that the validation errors can still be seen

#### Acceptance Criteria:

Given that I clicked the button to start or edit a project
When I am redirected to the project overview form, at `/cif/project-revision/<id>/form/overview`
Then I see the task list on the left, and the project overview form on the right

Given that I am viewing the `/cif/project-revision/<id>` page
  - When I click the "Submit" button
  Then the project revision is submitted and I am redirected to the project list
  
  - When I click the "Discard Changes" button
  Then the project revision is submitted and I am redirected to the project list

Given that I am viewing the overview form
  - When I click on the "Add projects managers" link
  Then I am redirected to `/cif/project-revision/<id>/form/managers`

  - When I click on the "Add projects contacts" link
  Then I am redirected to `/cif/project-revision/<id>/form/contacts`

Given that I filled the one of the forms and it is valid
When I click the `Submit <form name>` button
Then I am redirected to `/cif/project-revision/<id>` 

#### Development Checklist:

- [x] A `TaskList` component should be created, with links to the different pages. Each of the form page and the check-answers page should render the `TaskList`
- [x] The `DefaultLayout` component should have a `leftSideNav` prop, which should be used to render the task list
- [x] A `staged` status should be added to the `change_status` table, indicating that the user clicked the submit button (or navigated away from the form, behaviour to be added in another user story)
- [x] `app/pages/cif/project-revision/[projectRevision]/index.tsx` should be split into four different pages
- [x] page-specific `updateFormChange` mutations should be created, to provide better encapsulation and reduce over-fetching
- [x] When clicking on an individual form's "Submit" button, the corresponding `form_change` records should have their status set to `staged`
- [ ] Editing a `staged` `form_data` should revert its status to `pending`
- [x] The submit and discard buttons on the `/cif/project-revision/<id>` page should remain the same
- [ ] Meets the DOD

#### Notes:

![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/f9b26ea1-ca77-4ce5-8f75-6d30d9418a21)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/366?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @pbastia

**Comment by LindsayMacfarlane** [comment]
Thank you @matthieu-foucault - the bones of the task list are looking good!

One observation: the submit contacts button is within the frame; however, for the other pages, the button is located outside the frame. Something to look at in a future iteration of the design. 
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/3847fd05-b1d1-40bf-b28a-c6b29f8f67fa)

**Comment by matthieu-foucault** [comment]
Good spot. This contacts form needs a redesign anyway
