### ISSUE TITLE
As a Project Coordinator, I want to see which task in the task list is currently opened, so that understand which task I am looking at

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#369]
#### Description:

This short user story merely adds highlighting to the `TaskList` component, based on the current route.
It simply need to use `useRouter()` to find the current route, and highlight the correct link depending on that.

#### Acceptance Criteria:

Given that I am viewing a project revision page
When I navigate to a form page, or the "check answers" page
Then the corresponding item in the task list is highlighted

#### Development Checklist:

- [ ] Meets the DOD

#### Notes:

![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/2232f898-7c36-4293-b4e7-146672823775)

**Comment by matthieu-foucault** [comment]
@suhafa I tried some colors by looking at existing menus in BC government websites, but I'm not sure if that's the best option.
The example above uses an `#e5e5e5` background for the task list, and a `#fafafc` background for highlighted element (same as our page's background color). Does this look okay to you?

**Comment by suhafa** [comment]
@matthieu-foucault  I experimented a bit with the layout of the task list with those colors and tried to find a way to incorporate them. The challenge is to keep it clean, and make the elements sit right (as opposed to looking like they are hovering). I attached a screenshot of a solution, which includes adding borders around the task list items, and spacing them out a bit more vertically. With this solution, I find it flows well with the colors, and that the 'grey-ing' out of inactive list items help visually by staying in the background. What do you think? 
<img width="460" alt="image" src="https://user-images.githubusercontent.com/99216375/159544164-c4ba55ff-b727-4f7f-9550-27083c2775da.png">

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/369?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @pbastia @mikevespi

**Comment by LindsayMacfarlane** [comment]
Looks awesome @BCerki ! Tested in dev by adding a new project and editing an existing project - confirmed that the project task list was highlighted depending on what step of the application I was on. Just confirming based on the attached wireframe - the status of each step was not part of this ticket (e.g., action required, not started, etc)?

**Comment by BCerki** [comment]
Yes, the status is in this  other ticket: https://github.com/bcgov/cas-cif/issues/439
