### ISSUE TITLE
As a Project Coordinator, I want to submit a reason for change when submitting a project revision, so that the rationale behind the change is recorded

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#372]
#### Description:

When a project revision is updating a project, the user should submit a mandatory "reason" for the changes. This `textarea` input will be located in the "Check Answers" page, and must have a value before allowing the submission of a project revision.

To keep the application behaviour consistent, the "reason" will be saved in the `project_revision` table as the user types, using a debounced mutation.

#### Acceptance Criteria:

Given I am a CIF user
When I am reviewing a revision
And I am on the "Check Answers" page of my revision
Then I have a place to enter a reason for the change.

Given I am a CIF user
When I am on the "Check Answers" page of a project revision
And I have not entered a reason for the changes
Then I can't submit the revision

Given I am a CIF user
When I am on the Check Answers page of my project revision
And I am typing the change reason
Then the my change reason is saved as I type
And I can see a saving indicator indicating whether my changes are being saved or not

#### Development Checklist:

- [x] add a `change_reason` type `varchar(10000)` to the `project_revision` table 
- [x] a `project_revision` json schema with the form_change marked as required
- [x] a frontend rjsf component to display a form for that schema
- [x] a happo screenshot and an e2e test to submit a change with a reason
- [ ] Meets the DOD

![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/f4859c50-98a2-424c-a6f1-8bebfe0fab37)

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/372?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi

**Comment by mikevespi** [comment]
@matthieu-foucault I just caught this, `a project_revision json schema with the form_change marked as required` it's `change_reason` that should be required right?

**Comment by matthieu-foucault** [comment]
Yes. I'm not sure we need a full form and json schema here, given that we have only one field.

**Comment by mikevespi** [comment]
Since the `commitProject` in `app/pages/cif/project-revision/[projectRevision]/index.tsx` is already updating the project_revision I think a simple input in that page might suffice? 

The other question I had was should we prevent changing status to `committed` without a `change_reason` in the backend too, or is preventing on the front end enough in this context?

**Comment by matthieu-foucault** [comment]
I suppose a backend validation should happen too

**Comment by mikevespi** [comment]
Sounds good

**Comment by LindsayMacfarlane** [comment]
Thank you @mikevespi ! I may have tested a early based on @matthieu-foucault 's comments at standup, but the functionality appears to be functioning as expected and meets the acceptance criteria. Do you know if there is a ticket to capture the ability to see a list of the reasons for changes?

**Comment by mikevespi** [comment]
@LindsayMacfarlane Not that I saw, but I think we need some way to look at individual revisions too (as opposed to just the latest) so I think the scope is a bit larger here.
