### ISSUE TITLE
Delete the `change_reason` column in `form_change`

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#376]
#### Describe the task

The `change reason` is going to be entered at the project revision level, not for each `form_change`

#### Acceptance Criteria

- [ ] no more `form_change.change_reason`

**Comment by matthieu-foucault** [comment]
@pbastia I think we discussed this in a previous PR. Do you agree that this column should be removed?
We currently don't have a need for this column, so I don't think we should maintain code for it. At the very least it should be nullable

**Comment by pbastia** [comment]
@matthieu-foucault it makes sense to me. This way we decouple:
- the form_change, which only describes the database operation
- the intent, which can be revising a project, or revising anything else if we need to implement it.
let's delete it!
