### ISSUE TITLE
As a Project Coordinator, I want to undo the changes of a given form page, so that I can revert changes without discarding an entire revision

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#378]
#### Description:

There should be an easy way to clear the changes to a form. We should have an `undo changes` button on each form page. This needs to be displayed in a way so that it is clearly different than `discard revision`, and only discard the changes from the current form.

Clicking the `undo changes` button should revert the current form back to the state it was in before changes were made. 
This means
- for form changes without a parent (i.e. new records), reset the `newFormData` value to `{}`
- for form changes with a parent, reset `newFormData` to the parent's `newFormData`

#### Acceptance Criteria:

Given I have made changes to a project's form
When I want to discard only the changes I've made to that form
Then I see a button to undo the form changes that is clearly distinct from the `discard revision` option

Given I have made changes to a form
When I click the `undo changes` button
Then the current form is reset to the state it was in before I made changes to it

#### Development Checklist:

- [ ] Project form pages have an `undo changes` button above the form on the left
- [ ] the `undo change` button should use the `secondary` variant
- [ ] Clicking the `undo changes` button discards the form_change records for the current page that were created by the user
- [ ] Meets the DOD

#### Notes:

-

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/378?planning-poker) with ZenHub @BCerki @gurjmatharu @matthieu-foucault @pbastia

**Comment by LindsayMacfarlane** [comment]
Thanks @BCerki ! A reminder to check-off the checklist checkboxes (helps me to understand what was done or if anything got moved to a different ticket). 

Looks great! I tested in Dev by:
1) Creating a Project
- Undo changes appears on each form page, except the review page (as expected)
- Playing around with the undo button on the project overview page

2) Editing an existing Project
- Undo changes appears on each form page, except the review page (as expected)
Observations:
- The project status drop down didn't display any data for the first couple of attempts. Eventually it did, but it is unclear to me what triggered it to start working again. Every time I started a new project, there was no data in project status. Bug? Would appreciate someone else testing it out.

**Comment by BCerki** [comment]
Hey @LindsayMacfarlane, for the status drop down on new projects, initially, for me the only option was "Select a Project Status." Once I'd entered the RFP stream and year, then I got the statuses. Is this similar to what you experienced, or was the status field completely blank for you?

**Comment by LindsayMacfarlane** [comment]
Hi @BCerki - you are correct! Although I feel I had those fields filled in yesterday and still didn't get the project status list, but I do today (probably user error on my end ;) ). Thanks for checking!

**Comment by matthieu-foucault** [comment]
Yes, the statuses are tied to a given RFP. The status selection dropdown could be updated, asking the user to select a funding stream and year if they're not defined
