### ISSUE TITLE
How can we make Sprint Review as effective as possible?

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#383]
Following reflection from the GGIRCS Team during retrospective, we have identified some steps we can take to make sprint review more effective and valuable for program areas.

Acceptance Criteria:
- [ ] TBD
- [ ] Get feedback from CIF Team
- [ ] Make changes as identified

**Comment by jaimiebutton** [comment]
Tagging @Peirist for future follow-up

**Comment by Sriram-pc** [comment]
Some of the steps discussed in Retro about Sprint Review and action taken so far.
- [ ] Send Agenda in advance.
Action Taken:  Agenda send in advance, posted in channels too.
- [ ] Are sprint reviews mandatory (stakeholders)?
Action Taken:  Informed in agenda email that it is voluntary, but encourage stakeholders to attend.
- [ ]Objective of Sprint Review
Action Taken: Added "What’s a sprint review?" definition in the agenda email.
- [ ]Can we improve our sprint review meeting invite?
Action Taken: Used the improved invite that Lindsay made. Can be further refined if required.
- [ ]Survey Again
Action Taken: Survey Sent to the Stakeholders.
- [ ]Include times of demo segments in Sprint Review recording post
Action taken: Added time Stamp to the Sprint Review recording post. 

Based on feedbacks and future follow ups more action/steps to be taken to improve the Sprint Review. Also actions already noted above can be improved/updated based on further discussion and feedback.

**Comment by Sriram-pc** [comment]
Hi @LindsayMacfarlane, Should we close this ticket for now ?

**Comment by LindsayMacfarlane** [comment]
@Sriram-pc - question for you on this one. Have you observed how long we spend speaking to a specific agenda item? For example, CIIP (5 mins); CIF (20 mins), etc.

**Comment by Sriram-pc** [comment]
Hi @LindsayMacfarlane, I think its very close to above numbers. Typically Intro & explaining the worked completed is 5-7 mins, CIF (~20 mins), CIIP (~5 mins), PR (~5mins). Overall 35-40 mins average
