### ISSUE TITLE
Explore ZenHub Charts/Reporting

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#384]
We know we can do burndown charts! Breakdowns of tech debt vs tasks! Oh my!

What else? This ticket captures exploration into ZenHub's reporting capabilities for showing team progress at future Sprint Reviews.

Acceptance Criteria:
- [ ] TBD

**Comment by LindsayMacfarlane** [comment]
Hi @Sriram-pc - do you have documented anywhere (possibly in your SM playbook) - how you have been filtering ZenHub for burndown report out?

**Comment by Sriram-pc** [comment]
I will add that to the SM playbook and let you know once I am done.

**Comment by Sriram-pc** [comment]
Hi @LindsayMacfarlane I have documented on SM playbook how to create Zenhub Burndown Charts for Sprints.

**Comment by LindsayMacfarlane** [comment]
@Dianadec - would love your insight on how we can better leverage ZenHub reporting capabilities.
