### ISSUE TITLE
CIF: BC Registry ID is missing from the Operator View page

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#385]
Describe the Bug:

Probability (1-5): 5

Effect (1-5): 1

Steps to reproduce the behaviour:
Visit the view page for any operator

Development checklist:
- [x] the `bcRegistryId` is queried in the relay fragment (`app/pages/cif/operator/[operator].tsx`)
- [x] the field is rendered on the page
- [x] the unit test for that page makes sure it is rendered

**Comment by LindsayMacfarlane** [comment]
Thanks @gurjmatharu! I tested in dev by:

- going to an operator
- selecting view
- confirming that the BC Registry ID (if available) was displayed on the screen.
