### ISSUE TITLE
Finalize Hi-Fi wireframes

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#388]
- [ ] Create finalized wireframes for different task user flows
- [ ] How would the user see all the big steps (task list)
- [ ] Set a meeting for review with team
- [ ] Have an internal review with dev team
- [ ] Make iterations on the basis of reviews

#### Additional context

- Nice to have some prototyping

**Comment by LindsayMacfarlane** [comment]
@suhafa - what's our priority on completing this task?

**Comment by suhafa** [comment]
@LindsayMacfarlane This dinosaur is outdated in light of all the epic-wise tickets we've been tackling. We could repurpose this to be about user-testing our soft launch? c:

**Comment by LindsayMacfarlane** [comment]
This is no longer required. Closing ticket.
