### ISSUE TITLE
Add Documents & Dates to Process Map

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#39]
Acceptance Critera
- [x] Ask Taylor to add reference documents to process map
- [x] Add reference documents into process map

**Comment by jaimiebutton** [comment]
Moving to closed as this ticket has been taken care of in [ticket #87 (Prepare Process Map for Co-Creation)](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/87)

**Comment by LindsayMacfarlane** [comment]
Following up to see where we are with this task.

**Comment by LindsayMacfarlane** [comment]
Hi @Peirist ! Is this a task you can help us with? We're looking at adding documents to the process map so that we can better visualize where they fit into the process.

**Comment by Peirist** [comment]
Happy to help with this.  I can likely start working on it on Monday.

**Comment by LindsayMacfarlane** [comment]
Hi @Peirist - can you provide an update on the status of this task. Thanks!

**Comment by Peirist** [comment]
Partially complete.  Didn't get it all done before going on holidays; taking much longer than anticipated.  Will continue to work on it over the next couple days.

**Comment by LindsayMacfarlane** [comment]
Process map looks amazing!
