### ISSUE TITLE
As a project coordinator, I want the "check answers" page to display errors, so that I can fix them before submitting my project revision

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#396]
#### Description:

The check answers summary page should clearly show any errors present in the revision before submitting. The errors should be shown in the same style as defined in the [fieldTemplate component](https://github.com/bcgov/cas-cif/blob/develop/app/lib/theme/FieldTemplate.tsx).

During this work, it may become apparent that we need some custom validation functions in the database to handle more complicated errors. There is an example of how this was done in CIIP. Database examples are [here](https://github.com/bcgov/cas-ciip-portal/tree/develop/schema/deploy/application_validation_functions). An example of the implementation of these custom validation functions can be found [here](https://github.com/bcgov/cas-ciip-portal/blob/develop/app/containers/Applications/ApplicationWizardConfirmation.tsx#L203).

The error messages should make sense to the user. It should be clear what is wrong with the field and how to fix it. Some of the default error messages are not very helpful and can be overridden with rjsf's customTransformErrors. Example of this is [here](https://github.com/bcgov/cas-cif/blob/develop/app/lib/theme/customTransformErrors.ts).

#### Acceptance Criteria:

Given I have errors in my project revision
When I navigate to the answers summary
Then I can clearly see what fields have errors

Given I have errors in my project revision
When I read the errors on the answers summary
Then the error messages are easily understood as to what is wrong

Given I have errors in my project revision
When I am on the answers summary
Then submission of the revision is blocked

#### Development Checklist:

- [ ] Answers summary shows error messages below the corresponding field, styled to match the [fieldTemplate component](https://github.com/bcgov/cas-cif/blob/develop/app/lib/theme/FieldTemplate.tsx).
- [ ] Any unclear error messages are overridden to contain language that the user can understand
- [ ] Custom validation functions exist for more complicated errors (if necessary)
- [ ] Errors prevent submission of the revision
- [ ] Meets the DOD

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/396?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi

**Comment by LindsayMacfarlane** [comment]
Thank you @gurjmatharu! A reminder to check-off the checklist items to help make it clear that all the steps were completed.

I tested in dev by:
1) Creating a project: Attempted to create a project with an incorrect Proposal Reference and without total funding request, project status - I received the error message "Please enter a value" on those two fields as expected. Submit button is not accessible (greyed out) as expected from acceptance criteria. 
2) Edit an existing project by removing the total funding request. When I tried to submit the project, the warning message "should be number" was displayed. 

Observations:
- I included (what should be) an incorrect proposal reference number and received no error message and I was able to submit with an incorrect format. I believe bug ticket #554 will address this issue. 
- Error message displayed seems to differ between creating a project and editing a project. For example, total funding request error on project creation is please enter a value, while on edit it is should be a number. Is this the expected messaging? 

FYI @matthieu-foucault

**Comment by pbastia** [comment]
@LindsayMacfarlane we're not constraining the format of proposal reference at this point. The decision was made because the format used by CIF evolved year after year, and is not 100% determined for the future. 
To speed up development time, we're not maintaining a list of approved RFP# formats, and we made it free form instead

**Comment by LindsayMacfarlane** [comment]
Thanks for that clarification @pbastia! Now that you've mentioned that, it rings a bell :)

**Comment by matthieu-foucault** [comment]
> I got an error message when I didn't include a primary contact...and yet that form is stated as optional

Yes, that's a different issue we need to solve
