### ISSUE TITLE
As a project coordinator, I want the answers summary to only display the differences since the last revision, so that I can focus on what did change

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#397]
#### Description:

Rather than showing the entirety of the forms, the summary page should only display the fields that were changed.
This means that a `diff` between each `form_change` and its parent needs to be performed, and only those attributes that changed should be displayed.

Given that the objects that are compared are flat JSON objects whose structure will not change between revisions, we may not need a diff library.
The cases where contacts or managers are added or removed will be easily identifiable by looking at the `form_change`'s `operation`, so this use case is easier than if we were comparing two arbitrary project revisions

#### Acceptance Criteria:

Given that I am editing a project, and that I only updated a given set of fields
When review my answers
Then only the changes of the updated fields are displayed

Given that I am editing a project, and that I did not update a given form
When review my answers
Then the page should display `<form name> not updated` for the forms that did not change.

Given that I am editing a project, and that I added a secondary contact or manager
When review my answers
Then the page should display `Added <manager name>` or `Added <contact name>`

Given that I am editing a project, and that I removed a secondary contact or manager
When review my answers
Then the page should display `Removed <manager name>` or `Removed <contact name>`

#### Development Checklist:

- [ ] Meets the DOD

#### Wireframe:

![image](https://user-images.githubusercontent.com/2684022/161814001-f5397451-d7e0-4ff4-be5f-16345f367e72.png)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/397?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @mikevespi @pbastia @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Thanks @dleard - this is fantastic!

Tested in dev by:
- Editing an existing project and making changes to total funding request and project status. I was clearly able to see what I edited and in which sections I made no changes. 
- Confirmed changes reflected in project lists
