### ISSUE TITLE
User testing of quarterly report wireframes

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#410]
#### Describe the task
Take wireframe out to ops team for testing, review and input.

#### Acceptance Criteria
- [x] identify users from ops team to test wireframe
- [x] schedule testing session(s)
- [x] conduct session(s)
- [x] document feedback
- [x] create prototype wireframes
- [x] review feedback with dev team and prioritize feedback for development
- [x] update wireframes based on feedback and priorities
- [x] upload/attach wireframe to respective user stories (create user stories if required)

#### Additional context
- Note: depending on volume of feedback, updating wireframe could be pulled into its own ticket.

**Comment by suhafa** [comment]
Completed!
