### ISSUE TITLE
Internal User Personas

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#42]
This ticket is created as a follow-up to the [external user persona](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/32) ticket.

- [x] Create a plan for the completion of internal user personas
- [x] Schedule a time with CIF internal champions
- [x] Create internal user personas
- [x] Pass personas back to CIF team for feedback
- [x] Post personas in CIF Internal Users channel with date for completion
- [x] Pass Program Advisor persona to Meghan for review
- [x] Once refined, put personas in [CIF Internal Users channel](https://bcgov.sharepoint.com/:f:/r/teams/00608-CIFInternalUsers/Shared%20Documents/CIF%20Internal%20Users/Personas?csf=1&web=1&e=B7C0ZQ)

_What makes a persona ready?_
- [x] Comments given by CIF team
- [x] Comments incorporated
- [x] GGIRCS team agrees persona is ready

**Comment by Mattzah** [comment]
General comment

**Comment by Peirist** [comment]
Hello World

**Comment by patriciajrussell** [comment]
I'm here!

**Comment by amandavolk** [comment]
Hey all!

**Comment by Meghangough** [comment]
Hi

**Comment by rajpersram** [comment]
Jamie and Raj to meet to discuss lessons learned from the CIIP persona creation review outcomes.

**Comment by jaimiebutton** [comment]
Will add Program Advisor persona to Teams once complete - but time to move this ticket along!

**Comment by LindsayMacfarlane** [comment]
Thank you for taking the lead on this @jaimiebutton ! So good to have this wrapped up. Question for you - how often would you recommend that we revisit the personas to make sure they are reflective of our users?
