### ISSUE TITLE
CIF Project View

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#425]

**Comment by LindsayMacfarlane** [comment]
I goofed again - @jaimiebutton or @Sriram-pc can someone show me how to changed this into an EPIC next week.

**Comment by Sriram-pc** [comment]
@LindsayMacfarlane converted to Epic

**Comment by LindsayMacfarlane** [comment]
Looks like we can close this EPIC. Thoughts?

**Comment by LindsayMacfarlane** [comment]
Closing as EPIC complete.
