### ISSUE TITLE
Harmonize relay component testing and provide test helper functions

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#428]
#### Describe the task

Testing of our relay components is done in a few different ways, and requires a fair amount of setup. There is an opportunity for reusable test helpers and more homogeneity on how we test things, to speed up future unit testing

**Comment by pbastia** [comment]
- a RelayHelper object
- with a `reinit()` method to be called  in the `beforeEach`
- exposes a `loadQuery()` and a `renderComponent()` method
  - `renderComponent( (data) => props )` takes a function argument that can be used to translate the result of the test query to make component props
- takes in the constructor (we can make it generic?):
  - a test query
  - the query type
  - default query variables (optional)
  - default query resolver
  - the component to test
  - default props for that component
  

`ProjectContactForm.test.tsx` is a good example of how testing setup should be done in the library

**Comment by pbastia** [comment]
The above is valid to test a component. We might need a slightly different helper for testing a page

**Comment by pbastia** [comment]
@LindsayMacfarlane this is a pure development ticket, nothing to demo

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia :)
