### ISSUE TITLE
Sessions are not automatically extended when user is active [6]

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#429]
Describe the Bug:

Our sso-express or sso-react packages may need an update, and we should review the configuration used.

Probability (1-5): 4 (any user being active for 28min)

Effect (1-5): 2

**Comment by LindsayMacfarlane** [comment]
Assuming this PR is still awaiting to be merged? I went to test and now the app opens with the extend session message.

**Comment by LindsayMacfarlane** [comment]
Tested in dev. Timeout message displayed when expected. Button to remain active worked as expected. Thanks @gurjmatharu!
