### ISSUE TITLE
Zenhub Training for CIF Internal Champions

### ISSUE THREAD

**Issue by Sriram-pc** [bcgov/cas-cif#43]
Checklist

- [x] Request Internal Champions to set up GitHub account
- [x] Request Internal Champions to setup Zenhub account
- [x] Conduct Zenhub Training Session
- [x] Ensure internal champions have the correct permissions in order to leave comments/feedback on a ticket
- [x] Ensure that GGRICS Members can tag CIF team members in Zenhub.
- [x] Address privacy concerns by providing guidelines in CIF Internal User channel

**Comment by Sriram-pc** [comment]
@Peirist @Meghangough : Hi There, This is to test whether Scrum Team can tag CIF members. Please leave a "Yes" comment below if you see this comment. Cheers

**Comment by Meghangough** [comment]
Yes

**Comment by Peirist** [comment]
Yes

**Comment by Sriram-pc** [comment]
CIF members can comment on the tickets. We tested that during the Zenhub session

**Comment by LindsayMacfarlane** [comment]
From @Sriram-pc: 

_Note: Tagged Peirist & Meghangough to the ticket. 3 more CIF members yet to accept the invite to the CAS-CIF repository._

**Comment by Meghangough** [comment]
How do I accept the invite?

Meghan

**Comment by Sriram-pc** [comment]
@Meghangough : Thanks Meghan. I believe you already accepted the invite and we are able to tag you. No further action required.

**Comment by LindsayMacfarlane** [comment]
Hi @Sriram-pc - once you've received feedback from the team on the ZenHub/GitHub privacy guidelines, please add to the Wiki. I will then close off this ticket. Thanks!

**Comment by LindsayMacfarlane** [comment]
Considering ticket closed. Thank you for all your work on this @Sriram-pc! As a next step thought - it might be good to put together a miro or powerpoint for future training that captures what you did as part of this training.

**Comment by Sriram-pc** [comment]
Thanks @LindsayMacfarlane . Good idea. I will put it together in a Miro Board.
