### ISSUE TITLE
Plan usability testing with Tech team

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#431]
This ticket captures the work to prepare for first round of usability testing and wireframe testing with the tech team.

- [x] Identify which user stories we would like to test
- [x] Identify which wireframes we would like to test
- [x] Write script
- [x] Determine who in CIF should be involved in usability testing
- [x] Design testing session(s)
- [x] Ask Taylor who we should involve (e.g., Shelby or Devan)
- [x] Schedule usability testing sessions

**Comment by elliottSlee** [comment]
See also #404 & #411

**Comment by LindsayMacfarlane** [comment]
Hi @elliottSlee - given we have started testing, is this ticket now complete? If so, can you complete the checklist and move into the PO column.

**Comment by LindsayMacfarlane** [comment]
Thanks for all your work on this one @elliottSlee!
