### ISSUE TITLE
As a Project coordinator, I want to see "Edit Project" in the task list, so that I know that I am editing a project

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#438]
#### Description:

This is about making it clear to the user that a project is being edited, not created

#### Acceptance Criteria:

Given I am a CIF administrator
When I am on the project revision form
And this project revision is for an existing project
Then I see "Edit Project" as a title on the left panel

#### Development Checklist:

- [ ] Check if the `project_revision.project_id` is null, it means this revision is about creating a project, otherwise it's an edit
- [ ] Meets the DOD

#### Notes:

-

**Comment by pbastia** [comment]
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/fdd40a7c-4d68-478d-b2c5-460c6a2fc7e0)
