### ISSUE TITLE
As a Project Coordinator, I want to view the project forms in read-only mode, so that I can view all the information

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#440]
#### Description:

To allow the user to view all the project information without requiring the team to write custom views for every form, a possible first approach is to render each form in `disabled` mode.
The form in edit or view mode would be rendered in the same page, and the mode would be chosen based on the status of the corresponding `project_revision`

#### Acceptance Criteria:

Given that a `project_revision` is committed
When I visit `/cif/project-revision/<projectRevisionId>/form/(overview|contacts|managers)` 
Then

- The form is displayed in `disabled` mode
- There is an `Edit` button in the top-right corner
- The form `submit` button is not displayed
- The `TaskList` is displayed in view mode

Given that I click the `View` button for a project in the project list
When I am redirected
Then I land on the `/cif/project-revision/<projectRevisionId>/form/overview`, where `projectRevisionId` is the latest committed project revision for the given project.

Given that I am viewing a committed project revision
When the project revision is not the latest committed project revision for the given project,
Then I am redirected to the page for the latest project revision to ensure that I am viewing up-to-date information.

Given that I am viewing a committed project revision
When I click the `Edit` button
Then a new project revision is created, and I am redirected to the form matching the one I was viewing

Given that I am viewing a committed project revision
When there is a pending project revision in progress
Then the `Edit` button should display: `Resume Edition`

#### Development Checklist:

- [x] The `TaskList` component should have a `mode` variable, where `mode` is `"view" | "create" | "update"` (may have been added in #439 , depending which issue is done first). The task list would be in `view` mode when the `TaskList_projectRevision` `changeStatus` is "committed". In `view` mode, there will be no link to the "review and submit" page, and the links the the various forms should only be the form name (i.e. no "add" or "update" prefix, see screenshot below). The title of the TaskList should be the project reference.
- [x] ~The `disabled` prop should be passed to every widget. Some widget's implementation may not pass the `disabled` prop to their component, so that should be checked (and unit tested)~ Used the read-only them instead
- [x] Meets the DOD

#### Wireframe:

![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/e32049da-acd5-4fe2-a6f9-39a4fb75d9a1)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/440?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @mikevespi @pbastia

**Comment by LindsayMacfarlane** [comment]
Thanks @mikevespi and @matthieu-foucault !

I tested in dev by:
1) Made amendment for project #001. Able to start, exit and resume an amendment/revision.  
2) Made amendment for project #002. Able to start, exit and resume an amendment/revision.  

Observation:
- I was able to have two projects in revision (001 and 002)
