### ISSUE TITLE
CIF internal usability testing with Tech team

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#444]
#### Describe the task
Complete first round of usability testing with at least one user to better understand if functionality to date meets user needs and interview them about what functionality they expect.

#### Acceptance Criteria

- [ ] make sure the testing environment has data
- [ ] print script
- [ ] prepare data collection tool (spreadsheet)
- [ ] disseminate data collection tool to attendees

**Comment by elliottSlee** [comment]
What's highest impact for them in terms of development priority and does that align with the priorities we've heard?

**Comment by elliottSlee** [comment]
@LindsayMacfarlane's suggested Qs:
1) Given what is built to date - does it meet preliminary tech team needs? My assumption is that what is built so far only provides functions that would help them search for a project in the system
2) Confirm what some of their priorities are. We have the list from Taylor, but one of the only things mentioned is a communication mechanism from Ops team to tech team, but we've also heard from Taylor the need for 'other data'. Is that tech team data? What info do they need in the system or at least want to capture? Based on some of the sensitivities around how they score projects, some of that may remain out of the system, but is there any basic info they need included?

**Comment by elliottSlee** [comment]
See #404 #411 and maybe #408 #407 
@suhafa which of these tickets should we do during our sessions with the Tech team.

**Comment by suhafa** [comment]
@elliottSlee #404 would be done and ready by the end of this sprint. As for Quarterly reports, perhaps the next sprint. So milestone reports prototype would be best perhaps given that it'll be ready.
