### ISSUE TITLE
As a project coordinator, I want to filter the statuses in the projects list with a drop down so that I don't have to memorize all potential inputs.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#460]
#### Description:

The statuses were created during discovery, so users are not familiar with them so they don't know what to search for. They would like a dropdown list of statuses to select from instead of a filter. We should use a searchable dropdown component for this since we have a lot of statuses. There is currently no [table filter](https://github.com/bcgov/cas-cif/tree/develop/app/components/Table/Filters) set up for a searchable dropdown, but we do have a [search dropdown widget](https://github.com/bcgov/cas-cif/blob/develop/app/lib/theme/widgets/SearchDropdownWidget.tsx) that could be used as a starting point for creating one.

#### Acceptance Criteria:

Given that a user is on the projects list page
When they click the filter for status
Then a drop down list of statuses will appear

Given a cif user is filtering project statuses
When they begin to type
Then the list of statuses is pared down based on the search input

#### Development Checklist:

- [ ] A table filter that provides a searchable dropdown exists
- [ ] The status filter on the project list page uses the searchable dropdown table filter instead of a text filter
- [ ] Meets the DOD

#### Notes:

-

**Comment by suhafa** [comment]
Based on insights from our usability session, our users suggested that they'd like to have a dropdown for this, so a searchable dropdown sounds perfect!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/460?planning-poker) with ZenHub @BCerki @gurjmatharu @matthieu-foucault @pbastia @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Thank you @gurjmatharu ! Tested on columns: status and project manager. Works as expected.
