### ISSUE TITLE
As a project coordinator, I want to click on the show details button when adding a contact to project so that I can be confident that the contact information of the person I selected is correct.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#462]
#### Description:

Show details button for add contact when creating a project doesn't work. People tried to use it in the usability testing but it didn't work. Someone on our team mentioned that it was put in as a place holder.

Using the `asProject` computed column created in #500, the contact details for each contact form_change record can be accessed via `contactByContactId`. These details are what will be shown in the ui when clicking on the `Show Details` button.

#### Acceptance Criteria:

Given that a user is in the contacts section of create a new project
When they click on the show details button
Then they will see the details of the contact they just added below the contact dropdown

#### Development Checklist:

- [ ] The fragment in ProjectContactForm uses the `asProject` computed column to traverse the graph and retrieve the contact details associated with the form_change record
- [ ] When clicking the `Show Details` button the contact details are displayed

**Comment by suhafa** [comment]
![image.png](https://images.zenhubusercontent.com/6201b10c9827341d8d5cbe9c/4857528a-3288-475f-bfe5-f22294458dd2)
[Figma Link](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=1775%3A2665)

**Comment by pbastia** [comment]
Looks awesome! I think the information #1 we wanted to see here was the company they are on, to make sure we have the right Bob Loblaw, so maybe we can add that there too.
This is condensed enough, and won't likely have more than a handful of contacts, so maybe we can even remove the whole show/hide details logic (I don't see any reason to ever having that info hidden)

**Comment by suhafa** [comment]
I agree, it'll be great to remove the show/hide details component. As for checking the company of the contact - do we have a plan to add such a field ('Company Name') when creating a new contact? I didn't see it in the dev environment, it would be good to have.
I can update the wireframe accordingly to accommodate adding 'company name' and removing the 'show details' component once confirmed c:

**Comment by pbastia** [comment]
You're right, we're not associating a contact to a company...maybe their email is enough as feedback, initially at least

**Comment by suhafa** [comment]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/99216375/171955546-2e54d87e-6c9c-4259-b522-7b8a41961d02.png">
'Show Details' removed completely. Adding 'Company' as a part of adding contacts for referencing.

**Comment by LindsayMacfarlane** [comment]
This issue is no longer required as it has been addressed through #694, #695, #701 and #705.

**Comment by LindsayMacfarlane** [comment]
Closing ticket as a new approach is being taken.
