### ISSUE TITLE
As a project coordinator, I want to filter the project list by who it is assigned to so that I can see all my projects or a colleague's when they need help.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#465]
#### Description:

The project list has filter options for all columns except assigned to. Ops team sees value in being able to filter by assigned to because they expect to look at a project list of their own projects and sometimes they need to look at another colleague's list of projects for instance when that other person's on vacation.

#### Acceptance Criteria:

Given I am on the project list
When I filter on the project manager column
Then I have a dropdown of all the project managers to select from

Given I am on the project list
When I filter on the project manager column
Then I can type in the name filter to narrow down the search

Given that I am on the project list
When I filter the assigned to columns by a particular name
Then I will see only projects that are assigned to that person, regardless of whether they're primary or secondary project manager.

#### Development Checklist:

- [ ] a filter component that uses the `Autocomplete` in the same way as the `SearchDropdownWidget`
- [ ] an e2e test
- [ ] Meets the DOD

#### Notes:

-

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/465?planning-poker) with ZenHub @BCerki @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani
