### ISSUE TITLE
As a project coordinator, I want to search the project list by different components of the RFP number.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#467]
#### Description:

Usability testing with the Ops team revealed they wanted to filter project list by different components of the RFP number. The test environment at the time just had the full RFP number. Since then, RFP has been split out to trade name and proposal reference (3 unique digits). What about year?

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

#### Notes:

-

**Comment by elliottSlee** [comment]
Closing this issue because newer research has revealed a more precise ticket that can be created: filter by year.

**Comment by LindsayMacfarlane** [comment]
Closing ticket based on @elliottSlee 's feedback from above.
