### ISSUE TITLE
As a project coordinator, I want to track when & why changes were made to operators so that I know if there have been changes in ownership.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#472]
#### Description:

Sometimes facilities and operators change ownership. This is currently tracked by changing the trade name of who they're dealing with but the legal name stays the same because it's who signed the contract and is now just subsumed under the new ownership.

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

#### Notes:

-

**Comment by pbastia** [comment]
Changes to operators are already tracked in the system through our `form_change` table. Maybe just a comments field on the edit form would be enough to solve that? That would allow people to change the name, and write "Formerly XYZ ltd."

**Comment by elliottSlee** [comment]
@pbastia That sounds like a great solution.

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro and @suhafa - do we need to explore design to support the implementation of this ticket?

**Comment by suhafa** [comment]
@LindsayMacfarlane need some additional context for this ticket. @pbastia did you mean to suggest something similar to tracking revisions for Operators like we do currently for projects?

**Comment by pbastia** [comment]
We do already track all changes to an operator through form_change records. Displaying a change in ownership would just mean to find these form changes and see the name history.
- Does it mean we just need to be able to display a history of changes on an operator?
- Should we add an optional "reason for change" when editing an operator?

**Comment by nanyangpro** [comment]
@pbastia - To your questions:
1. I think so, yes. It fulfills the first user goal as to know "when changes were made".
2. Including an optional "reason for change" would be ideal, as knowing "why changes were made" is the other user goal according to the user story.

**Comment by LindsayMacfarlane** [comment]
@nanyangpro - this will be captured within the revision/amendment work, correct?

**Comment by nanyangpro** [comment]
Yes, @LindsayMacfarlane - I believe this can be taken care of by revision/amendment, thus can be closed.

**Comment by LindsayMacfarlane** [comment]
Considering this ticket a duplicate that will be covered with the work on revisions/amendments. Closing.
