### ISSUE TITLE
As a CIF developer, I want the attachments to be stored on GCP, so that they have a place to be stored

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#484]
#### Description:

This is about configuring the minio instance to store the attachments on the team's GCP instance

#### Acceptance Criteria:

Given I am a CIF user
When I upload an attachment to a project 
Then that attachment is stored on the cas-ggircs GCP instance

Documentation is http://nm-muzi.com/docs/minio-gateway-for-gcs.html

#### Development Checklist:

- [ ] configuration for minio 
- [ ] pulling the gcp access tokens from the OCP secrets
- [ ] Meets the DOD

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
This ticket is currently considered low priority as it is top a priority of the program area. Priority and implementation can be reconsidered at a later date.

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/484?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Thanks @pbastia! I tested in dev by:
1) Uploaded a jpg to Test Project 001. I was able to upload, view  (although you can't actually view the uploaded document, just the metadata), and download the file
2) Uploaded a PDF to Test Project 002. I was able to up view, and download the file

Observation:
- Uploading a file currently gets appended/accessible to every project and not the specific project. We definitely need some UX/UI on this, but that will come in later iterations. 

Thanks for all your work on this Pierre.
