### ISSUE TITLE
As a CIF Project Coordinator, I want an error to tell me if the RFP # is already being used so that I know what is wrong when I can't submit a project because the # is already in use.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#489]
### Description
During usability testing with Siyue from the tech team, he was given duplicate information from the previous usability session which meant the RFP # he was asked to add was already in use. This meant he was unable to submit but no error showed up. ![Screen Shot 2022-04-11 at 11.15.11 AM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/6ba83d7f-9c1a-414a-aad4-c5ac7edac98b)

### Acceptance Criteria
Given a project coordinator is creating or editing a project,
When they enter a duplicate RFP #,
They will be notified that the # is already in use.

**Comment by matthieu-foucault** [comment]
This has been fixed since
