### ISSUE TITLE
As a CIF Project Coordinator, I want a link to contact help/IT so that I can have help when I run into trouble.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#490]
### Description
During usability testing, it was noted that when a user encounters problems with the CIF digital system, they want to know how to contact someone for help. Similarly, CIIP has the box on the main page about contacting the dev team. ![Screen Shot 2022-04-11 at 11.20.53 AM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/6d6941ff-cb74-41e8-abfb-ede4062d18b2)

### Acceptance Criteria
Given that a project coordinator is on any page of the CIF digital system,
when they need help they can find it,
then they click on it and it gets them into contact with someone who can help.

**Comment by LindsayMacfarlane** [comment]
@suhafa @nanyangpro - completed as part of the dashboard re-design, correct?

**Comment by nanyangpro** [comment]
Just checked Suha's latest design on Dashboard in Figma, as well as the DEV/TEST environments, I believe the ticket has been taken care of already. @LindsayMacfarlane

**Comment by LindsayMacfarlane** [comment]
Ticket a duplicate and was implemented as part of the dashboard re-design. Closing.
