### ISSUE TITLE
As a project coordinator, I want to see the list of all contacts when adding a contact to a project so that I can sort through them and select the one I want.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#491]
View contacts list button when adding a project doesn't work.

**Comment by LindsayMacfarlane** [comment]
Not sure if this issue is actually a bug? Perhaps a user story?

**Comment by matthieu-foucault** [comment]
We may want to rework the entire contacts form, leaving this in "New issues" for now

**Comment by elliottSlee** [comment]
> Not sure if this issue is actually a bug? Perhaps a user story?

Makes sense, we can remove the bug label. I only included it because the button's there. There's still some ux/ui design work necessary for what happens when they click the button. 
I would also suggest we have a larger discussion about contacts which may have implications for this. See #492.

**Comment by LindsayMacfarlane** [comment]
This issue is no longer required as it has been addressed through #694, #695 and #701.

**Comment by LindsayMacfarlane** [comment]
Closing issues as it will be addressed through the contact page re-design.
