### ISSUE TITLE
If only funding stream is filled out, form doesn't save and tasklist status doesn't change [3]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#493]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 1?
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
Add a project and fill out only the Funding stream field. Note that Changes Saved checkmark appears but tasklist status doesn't change. Navigate away and come back and the field will be blank again. Field is also missing on the summary page.
(Once you add a funding stream RFP, it does save.)

Screenshots:
https://www.loom.com/share/4cfb3b4a7ccc4261954ff6080c6d87fa
![Screenshot from 2022-04-12 08-23-43.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/74c1d63b-4847-4882-8ba4-a8177573e370)
![Screenshot from 2022-04-12 08-27-27.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/bbea815f-594d-4dd5-826a-effcc7fd9bde)
![Screenshot from 2022-04-12 08-27-14.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/769df273-6888-4934-842e-9e7b4d07e125)

![Screenshot from 2022-04-12 08-27-48.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/6c62ef63-522c-4f62-be79-df85a1cec235)

Additional information:

- OS: Pop OS
- Browser: Chrome
- Version: [e.g. 22]
- Additional context

**Comment by matthieu-foucault** [comment]
@BCerki for this one I would lower the probability to 1: It is very unlikely that a user only selects the funding stream (and not the year) and goes to submit the project

**Comment by BCerki** [comment]
This will probably be solved with https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1075

**Comment by Sepehr-Sobhani** [comment]
still a bug Nov 30, 2022

**Comment by BCerki** [comment]
No longer relevant since we made funding stream immutable
