### ISSUE TITLE
As a Project Coordinator, I want the project status dropdown to be in chronological order so that I can easily find the status I need.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#496]
#### Description:

In the create project page, the status dropdown is not in an order that makes sense to users. Usability testing with Ops & Tech team has shown they would like it to be in the chronological order of the normal process.

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
This seems like a nice to have and not a priority for our first prod release. We can follow up with the program area to get the list ordered chronologically.

**Comment by Peirist** [comment]
@LindsayMacfarlane Are you able to direct me to the list of project statuses that the dev team is currently using? I think the list has been pared down since I sent it back in the fall.

**Comment by LindsayMacfarlane** [comment]
@Peirist - the list:
Proposal Submitted
 Technical Review
 Review Complete
 Waitlisted
 Disqualified
 Withdrawn
 Funding Offered
 Agreement Signed
 Agreement Terminated
 Advanced Milestone Complete
 Project Underway
 TEIMP
 Performance Milestone Complete
 Summary Report Submitted
 Annual Reporting
 Complete
 Under Review

**Comment by Peirist** [comment]
@LindsayMacfarlane Thanks.  I'll check with the Ops Team to see what order they'd like these to be in, and/or if we can further reduce the list; to me it seems like it's already in roughly sequential order but they may want it a different way.

**Comment by Peirist** [comment]
@LindsayMacfarlane I met with the Ops and Tech Teams to revise and reorder the list.  The finalized list:

Proposal Submitted
Under Technical Review
Technical Review Complete
Waitlisted
Disqualified
Withdrawn
Funding Agreement Pending
Agreement Signed
In Progress
Project in TEIMP
Summary/Verification Report Complete
Project in Annual Reporting
Closed
Agreement Terminated
Not Funded

**Comment by elliottSlee** [comment]
It may be worth asking CIF team if they'd like to add "Pending Amendment" as a status. It came up during usability testing. @LindsayMacfarlane should I ask Taylor during office hours?

**Comment by LindsayMacfarlane** [comment]
Great call @elliottSlee, we can tag Taylor here. @Peirist, what are your thoughts on adding 'pending amendment' to the list of statuses? Elliott indicated that it came up during usability testing.

**Comment by Peirist** [comment]
@elliottSlee @LindsayMacfarlane When I had my session with the Ops Team I asked about a "Pending Amendment" status and they indicated they didn't need it, so I'm not sure if their thinking has evolved or whether that functionality is captured another way.  The Dev team indicated we will be able to add statuses beyond these initial one so we could potentially add the amendment status if needed.

**Comment by LindsayMacfarlane** [comment]
Note: During CIF Prioritization session this ticket was considered no longer required. However, looking through previous comments and comparing to the status list in Dev - there is still further refinement required.

**Comment by LindsayMacfarlane** [comment]
@nanyangpro - this ticket may also be relevant for our conversation today re. status difference between EP and IA.

**Comment by nanyangpro** [comment]
Thanks @LindsayMacfarlane! - This ticket can be closed since the ordering has already been reflected in the app and we have #518 addressing further investigation around the "Project Status" and the split between EP and IA.

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro - can you verify the above has been done? When I look at the list in Dev, it doesn't completely reflect the order as requested and includes statuses the team indicated could be removed.

**Comment by nanyangpro** [comment]
Thanks for the reminder, @LindsayMacfarlane - We can either keep it or close it. I'll take care of the refined (and reordered) list above in #518's mapping work.

**Comment by LindsayMacfarlane** [comment]
Thank you @nanyangpro! If addressed in #518, this one can be closed.
