### ISSUE TITLE
As a CIF developer, I want to store reporting requirements in the database, so I can build a frontend for it

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#501]
#### Description:

Building the database side for reporting requirements

#### Acceptance Criteria:

Given I am a CIF developer,
When I store reporting requirements in the database
Then I have the (reporting_requirement, report_type, budget_item, payment) tables available

#### Development Checklist:

- [ ] `reporting_requirement` table
    - `due_date` timestamptz
    - `submitted_date` timestamptz
    - `status` varchar? enum? check with @suhafa for a list of status
    - `comments` varchar(10000)
    - `certified_by` varchar? can maybe become a contact in the future
    - `certified_by_professional_designation` varchar , can probably be an enum once we know a list of accepted values
- [ ] `report_type` table
    - `name` varchar(1000)
    - `form_schema` jsonb - we'll need to confirm whether we use this or not, this is a larger discussion to be consistent with the rest of the application
- [ ] `budget_item` table
    - `amount` numeric
    - `category` enum? right now the 2 values would be "general" and "materials, supplies, equipment and other items"
    - `description` varchar(10000)
    - `is_confirmed` boolean
    - `is_tentative` boolean
- [ ] `payment` table (this is a bit of a placeholder right now)
    - `amount` numeric
    - `date_issued` timestamptz
    - `date_paid` timestamptz
    - `comment` varchar(10000)
    - `transaction_id` varchar(1000)
    - `status` varchar(1000)? enum?
- [ ] Meets the DOD

#### Notes:
Fields with question marks can be implemented either way, and changed at a later time.
The list of dependencies is attached, red dots mean that the table is subject to the `form_change` creation/update/archive process, direct writing to the tables should not be done

**Comment by pbastia** [comment]
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/8163983b-85c6-4f63-be37-f919e9cf1b18)

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/501?planning-poker) with ZenHub @BCerki @gurjmatharu @matthieu-foucault @pbastia @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
I'm assuming this is done as it is in the approved by po/dev column? I don't think there is anything I can really test on this one, so moving to closed unless there are any objections.
