### ISSUE TITLE
Tech Debt: Minio python API should use an asynchronous client

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#503]
Problem: The default python MinIO client is synchronous, which means it blocks the uvicorn worker while retrieving large files. This will cause issues when multiple people want to download files at the same time, depending on how many workers there are.

The solution is to use an asynchronous s3-compatible client like this one:
https://pypi.org/project/aiobotocore/

**Comment by matthieu-foucault** [comment]
@pbastia I assume we can close this given that we won't use minio anymore

**Comment by pbastia** [comment]
Closing this issue as Minio has deprecated their GCS wrapper
