### ISSUE TITLE
Mapping the display of forms/fields/tasklist with Funding Streams and Project Statuses

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#518]
Display of forms/fields/tasklist should be based on:
1. Selected Funding Stream
2. Selected Project Status

Display of Project Status dropdown list options should be based on:
- Selected Funding Stream

A refined list of "Project Statuses" has been captured in #496. Besides confirming on the ordering of them, mapping work of the above is also required.

**Comment by elliottSlee** [comment]
@LindsayMacfarlane with #496 in the icebox, can we icebox this as well?

**Comment by LindsayMacfarlane** [comment]
@elliottSlee Let's keep this in for now. We can even pull the ordered list from #496 into this ticket. The reason why I'd like to leave this in for now, is it might align with our onboarding conversation with CIF, specifically - with the current statuses, would CIF be able to enter all projects (not just funded projects) into the system.

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro - can you use this ticket to support mapping out project status?

**Comment by nanyangpro** [comment]
Thanks @LindsayMacfarlane, good suggestion. I will refine the ticket a bit more based on our discussion around EP vs IA.

**Comment by nanyangpro** [comment]
See #496 for the refined and re-ordered list of status.

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane, this ticket can be closed with findings visualized and validated with CIF Ops (please see the "Forms" tab in the [mapping spreadsheet](https://bcgov.sharepoint.com/:x:/t/00608-ScrumTeam/EbxB55A0pk9Kr-eCTocUvIkB6sWffF4ACkh3oQ5_89dTlg?e=dcgbof&isSPOFile=1)), and learnings delivered and discussed with the devs.

**Comment by LindsayMacfarlane** [comment]
Great work on this @nanyangpro! It is so helpful to see things clearly mapped out.
