### ISSUE TITLE
User discovery related to project budgets, expenses and payments

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#521]
#### Describe the task

User discovery to identify challenges, opportunities, and needs related to tracking of project budgets, expenses and payments in order to inform design/wireframing.

#### Acceptance Criteria

- [x] Find all existing documentation
- [x] Compile/synthesize existing documentation (Appendix A pt.2 in Miro)
- [x] Design discovery/research questions
- [x] Use office hours with Taylor to go over questions/findings

#### Additional context

- This ticket will cover discovery/research with simpler questions answered by Taylor

**Comment by elliottSlee** [comment]
Existing discovery work captured [here](https://bcgov.sharepoint.com/:w:/r/teams/00608-CIFInternalUsers/Shared%20Documents/CIF%20Internal%20Users/Meetings%20%26%20Workshops/Topic%20Chats/Topic%20Chat%20Notes.docx?d=wd9ca0dbf32f640618da6d04876f83f85&csf=1&web=1)

**Comment by LindsayMacfarlane** [comment]
Hi Team - do we consider this ticket complete now? I really enjoyed the session with AV that I was able to attend - a lot of great insight and information (cc: @elliottSlee, @nanyangpro, @suhafa)

**Comment by suhafa** [comment]
With the last session in, I would say yes, we can close this ;D

**Comment by LindsayMacfarlane** [comment]
Thanks everyone! Loved the collaborative team approach on this task :)
