### ISSUE TITLE
Wireframe project budgets, expenses and payments screens

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#522]
#### Describe the task

Based on feedback/learning during the user discovery sessions (#521), create low-fidelity wireframes.

#### Acceptance Criteria

- [x] Design lo-fi screens in Figma that capture project budgets, expenses and payments
- [x] Review lo-fi screens with team
- [x] Reiterate screens if need be

#### Additional context
This ticket covers wire-framing, reviewing with the team internally.

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro and @suhafa - checking in on the status of this ticket. Is there anything else left to do to support this ticket?

**Comment by nanyangpro** [comment]
Thanks for checking-in with us, @LindsayMacfarlane . Yes, at least one more iteration is required (incorporating additional feedback, validating the 3rd user story set and wireframes, etc.), but it shouldn't be a blocker for implementing the functionalities as discussed yesterday.

**Comment by nanyangpro** [comment]
Just noticed that we also have #544 in the design backlog to address the iteration. We should be able close this one then. @LindsayMacfarlane

**Comment by LindsayMacfarlane** [comment]
Thanks team! Excited to start implementing budgets, expenses and payments :)
