### ISSUE TITLE
As a project coordinator, I want to expand and collapse reporting requirements, so that I can focus on the upcoming reports

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#529]
#### Description:

Add a Collapse/Expand button for quarterly and annual reports

#### Acceptance Criteria:

Given I am editing reporting requirements (quarterly or annual reports)
When I click on the header of a closed requirement
Then the requirement expands open

Given I am editing reporting requirements (quarterly or annual reports)
When I click on the header of an open requirement
Then the requirements slides closed

Given I am editing reporting requirements
When I load the page
Then the first non-completed requirement is expanded
And all the others are collapsed

#### Development Checklist:

- [ ] Each requirement/report should be its own react component, managing its internal open/closed state
- [ ] e2e with snapshots for open and close state
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [ ] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/07ad2cdf-8089-44e6-97e8-47d3326b4503)
@suhafa @nanyangpro do you mind making sure we have the right wireframe here?

**Comment by suhafa** [comment]
the wireframe you've attached here is correct Pierre!

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/529?planning-poker) with ZenHub @matthieu-foucault @mikevespi @Sepehr-Sobhani @pbastia

**Comment by elliottSlee** [comment]
Can we also apply this to milestone reports or would you like me to recreate this for milestone reports?

**Comment by LindsayMacfarlane** [comment]
@matthieu-foucault: what are your thoughts - can this feature wait until after our first launch?

**Comment by LindsayMacfarlane** [comment]
Looks good @pbastia and @BCerki ! I tested in dev by:
1. Creating a new project and adding multiple milestones, annual and quarterly reports and ensuring reports were collapsible. 
2. Editing an existing project and adding/updating milestone, annual and quarterly reports and ensuring reports were collapsible.

Meets acceptance criteria.
