### ISSUE TITLE
As a Project coordinator, I want to see the number of days until the due date of a report

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#530]
#### Description:

Make a custom widget for the due date, to be used in the Quarterly reports page

#### Acceptance Criteria:

Given that I see a due date widget
When I click on it
Then I see a calendar input

Given that I see a due date widget, with a selected date (e.g. Apr. 05, 2022)
When the number of days between the current date and the selected date is less than or equal to 60 days
Then the widget displays `Due in X days (Apr. 05, 2022)`

Given that I see a due date widget, with a selected date (e.g. Apr. 05, 2022)
When the number of days between the current date and the selected date is greater than 60 days
Then the widget displays `Due in Y weeks (Apr. 05, 2022)`

![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/160cfcc3-f27b-4e19-a8e9-f9010a0f1aad)

#### Development Checklist:

- [ ] The widget should be accessible, i.e. being fillable with keyboard navigation
- [ ] https://www.npmjs.com/package/react-datepicker is a good candidate for this component
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/530?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @mikevespi @pbastia @Sepehr-Sobhani

**Comment by mikevespi** [comment]
@matthieu-foucault any opinion on what the widget should display if the due date is past?

**Comment by matthieu-foucault** [comment]
Only display the date in that case? @suhafa what do you think?

**Comment by suhafa** [comment]
Only displaying the date works for 'Report Due Date'. As for 'Received Date' we could show it as following if past due: 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/99216375/167692655-c4b8abdb-59aa-42b9-bc0e-aca7cea3b9ee.png">

**Comment by LindsayMacfarlane** [comment]
Thanks @mikevespi!

A couple of observations/questions:
- This ticket only applies to quarterly reports and I don't see a ticket that will apply this to all the reports? In particular, the due date count down.
- I can't seem to trigger the overdue feature. It simply shows 0 days.

**Comment by BCerki** [comment]
> * This ticket only applies to quarterly reports and I don't see a ticket that will apply this to all the reports? In particular, the due date count down.

I added it to the other reports in the received date PR @mikevespi

**Comment by mikevespi** [comment]
@LindsayMacfarlane The overdue function is only on the received date widget. They're one after the other so the information will be right there. That ticket is in flight right now I believe so should be in soon.

**Comment by LindsayMacfarlane** [comment]
Thanks @mikevespi ! This is a really cool feature. I'll move this ticket to closed unless you still need it open?

**Comment by mikevespi** [comment]
I think it can close, the PR adding it to the other forms due dates was just merged, so will be in dev next release
