### ISSUE TITLE
As a project coordinator, I want to see if a report is received, late or upcoming

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#531]
#### Description:

Custom widget for the Received / Late / Upcoming date of a report. This widget should use data from the `reporting_requirement` table created in #501 to determine whether it is received, late or upcoming.

#### Acceptance Criteria:

Given I am viewing the milestone reporting page
When a report has been received
Then I can see a widget showing that it has been received
And the widget shows a green check mark with the date it was received

Given I am viewing the milestone reporting page
When a report is late
Then I can see a widget showing how many days overdue the report is
And a warning icon beside the widget should be visible

Given I am viewing the milestone reporting page
When a report is not received or late
Then I can see a widget showing how many days until it is due and the due date

![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/e7b02057-09c7-4a62-8e82-3d284aef88a3)

- Figma design can be found at https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=989%3A2796 all 3 states of this widget are shown in the Quarterly Reports wireframe

#### Development Checklist:

- [x] A widget exists that can display the 3 states of  a report (received, late, pending)
- [x] The widget uses data from the `reporting_requirement` table to determine what to display
- [ ] The widget is implemented on the Milestone Reporting page
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Do we need screens for the different states for this custom control?
- received
- late
- "not yet received but not late"

**Comment by matthieu-foucault** [comment]
yes, I was going to ask about this in our planning session

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/531?planning-poker) with ZenHub @matthieu-foucault @Sepehr-Sobhani @mikevespi

**Comment by dleard** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/531?planning-poker) with ZenHub @pbastia

**Comment by LindsayMacfarlane** [comment]
Looks great @BCerki ! This widget helps make it clear when a report is received or late. I tested this is dev by creating a project and adding in various milestone, quarterly and annual reports and then playing around with date fields. I also tested by editing existing report due dates to reflect when a project has been received. Meets acceptance criteria.
