### ISSUE TITLE
As a project coordinator, I want to see a computed reporting status for quarterly and annual reports

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#532]
#### Description:

Show a reporting status, computed based on the state of the reporting requirements.
This is only about the computed status. Any manual edit will be described in another User Story.

#### Acceptance Criteria:

Given I am a CIF administrator
When I view the Quarterly or Annual milestones
Then I can see a badge with the status of the project

Given I am a CIF administrator
When I view the Quarterly or Annual milestones
And there are late reporting requirements
Then the status is "Late"

Given I am a CIF administrator
When I view the Quarterly or Annual milestones
And all the past due reporting requirements have been marked complete
Then the status is "On Track"

Given I am a CIF administrator
When I view the Quarterly or Annual milestones
And there are no upcoming reporting requirements 
Then the status is "On Track"

#### Development Checklist:

- [ ] A `reporting_requirement_status` table in the database with "On Track" and "Late" values
- [ ] two computed columns: returning the `reporting_requirement_status` type  (one for quarterly, one for annual)
- [x] A react component to show the status as a badge
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/009681df-1c90-41a7-a128-aeef16f85cee)

**Comment by pbastia** [comment]
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/c9850b9a-8424-48be-9bb5-befa09f497b0)

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/532?planning-poker) with ZenHub @Sepehr-Sobhani @gurjmatharu @matthieu-foucault @dleard @BCerki

**Comment by BCerki** [comment]
@suhafa, for the overall status of reports, should the status be for individual report types (eg status of milestone reporting, screenshot #2) or for the whole project's reports (status of project reporting, screenshot #1)?

**Comment by BCerki** [comment]
I didn't do the first two items in the developer checklist because 1) this table already exists, 2) the computed columns in [this PR](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/589) already do what I need them to

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki ! One observation, which can be fixed in another ticket is the spacing between components, which at the moment seems a bit squishy. I also noticed that some functionality seems a bit different between quarterly and annual reports (might be addressed in an existing ticket?). FYI @nanyangpro and @suhafa. 

![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/9e42744b-5b2a-4aeb-ac52-32170b651ddc)

![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/74ac530f-6ca3-4e08-a401-cb22d1611fb6)

**Comment by BCerki** [comment]
Annual and milestone report functionality is in: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/685. I'll add the spacing fix to the AC
