### ISSUE TITLE
As a project coordinator, I want to be able to undo changes on the quarterly reports page

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#538]
#### Description:

As part of this PR, the undo button should be refactored into a generic component, so that it can be added to future pages without requiring code duplication.

#### Acceptance Criteria:

Given that I am creating or editing a project, and that I have made changes to the quarterly reports form
When clicking the "undo changes" button
Then all of my changes since the project was last submitted are reverted.

#### Development Checklist:

- [x] Make a generic `UndoChangesButton` component, that is reused across every form
- [x] Consider making a `undo_form_changes(form_changes_ids integer[])` function, moving the undo logic to the server. This function might need to return the project revision, to allow the mutation to query all the form changes again
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/538?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @mikevespi @pbastia @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Thanks @Sepehr-Sobhani ! I tested in dev by creating and editing a project. Functionality meets the acceptance criteria.

**Comment by Sepehr-Sobhani** [comment]
@LindsayMacfarlane There is no ticket for those reports just yet, but we can add them since this newly created button should be generic enough to handle undoing changes for all project forms.
