### ISSUE TITLE
As a project coordinator, I want to collapse all previous reporting requirements into a single row, so that it doesn't take too much space on the screen

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#541]
#### Description:

Collapsing all previous, completed reports (quarterly or annual) into one row to save real-estate and not fill the screen with information not relevant to the user

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by matthieu-foucault** [comment]
I don't think we should have both this user story and #529. I sounds like the code written in #529 would be completely undone by this user story

**Comment by matthieu-foucault** [comment]
The issue of having too much screen real estate used by completed reports will be fixed by ensuring that collapsed elements are condensed enough, and adding a link in the "next report widget" (#589)
