### ISSUE TITLE
CIF Presentation

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#545]
#### Describe the task

Prepare a stock presentation of CIF product development and product.

#### Acceptance Criteria

- [x] Book meeting with team to discuss
- [x] Brainstorm  & determine how best to showcase our team's work and CIF product
- [x] Create pp and/or video

#### Additional context

- We will want this ready for the next branch meeting on June 28th
- Draft deck on [Scrum Team](https://bcgov.sharepoint.com/:p:/t/00608-ScrumTeam/EV6WsJ49vrxMr1ZqMUV7nMYB68gvCWgv8E7NwGkEaQYurg?e=Sge40E) channel (note: very draft...just the bones)

**Comment by LindsayMacfarlane** [comment]
@nanyangpro - the next scheduled Branch meeting is scheduled for June 28th. Unknown about length of time - assume 10-15 mins. We can do a combination of PPT, live or recorded demo. I'm curious about an animation though!

**Comment by nanyangpro** [comment]
Thanks for the clarification, @LindsayMacfarlane! Sounds good.

I can show you the animations I've done for MDT before during our check-in tmr.

Question: does this preparation has anything to do with the meeting day on Jul 12th at all?

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro - No, July 12th is more around team building, re-evaluating our branch mission/vision and change management. An agenda is still to be worked out.

**Comment by nanyangpro** [comment]
Gotcha, thanks @LindsayMacfarlane!

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - The 1st draft of the [slide deck](https://bcgov.sharepoint.com/:p:/t/00608-ScrumTeam/EV6WsJ49vrxMr1ZqMUV7nMYB68gvCWgv8E7NwGkEaQYurg?e=KdVHKc) has been completed and is ready for you to review.

**Comment by LindsayMacfarlane** [comment]
I love it @nanyangpro! I'm sure there will be tweaks here and there, but overall, it looks great. Thank you so much! Should we create a separate ticket to address the pre-recorded demo video? What are your thoughts?

**Comment by nanyangpro** [comment]
Thanks @LindsayMacfarlane! Good call, I've got some thoughts on that and hope to discuss with you during our 1:1 in an hour. :)

**Comment by nanyangpro** [comment]
Close #545. Pre-recorded demo will be addressed in #733.

Thanks @LindsayMacfarlane for your kind support and wonderful suggestions!
