### ISSUE TITLE
CAS/Clean Growth Branch Week

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#546]
#### Describe the task

Prepare content/activity that represents our team and our work for the CAS Branch Week. Clean Growth is scheduled for 2:00 - 3:00 pm on May 11, 2022. 

#### Acceptance Criteria

- [x] Identify team volunteers
- [x] Determine activity
- [x] Prepare content

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by nanyangpro** [comment]
Thanks for tagging me @LindsayMacfarlane!

Could you please confirm and update the date/time in the task description? :)

I will be on flex next Monday, thus hoping we can close this ticket by the end of tmr. I'll book a meeting for us to sync and tackle it together if it works with you.

**Comment by nanyangpro** [comment]
[Branch Week Quiz Working Doc](https://bcgov.sharepoint.com/:w:/r/teams/00608-ScrumTeam/_layouts/15/Doc.aspx?sourcedoc=%7BFFCFCAE3-8C31-4031-AB86-852B586EB556%7D&file=Branch%20Week%20Quiz.docx&action=default&mobileredirect=true)

**Comment by nanyangpro** [comment]
I had a chance to walkthrough the [quiz](https://interacty.me/projects/digital-services-team) during my touch base with Nancy Norris. She provided very positive feedback (good introduction of both our team and the programs we support) yay.

**Comment by LindsayMacfarlane** [comment]
Thank you so much for all your effort on this Nan!
