### ISSUE TITLE
Prepare for wireframe testing session

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#547]
#### Describe the task

Prepare for testing session with the Ops team (ideally at 3rd week of May)

#### Acceptance Criteria

- [x] Create research goals
- [x] Create script
- [x] Finalize script after reviewing with team
- [x] Create observation notes file
- [x] Set up meeting sessions with Ops team

**Comment by LindsayMacfarlane** [comment]
Hi @suhafa @nanyangpro and @elliottSlee - can you remind me, did we say this am that we wanted to set up sessions with the Ops Team next week for usability testing of the wireframe? Myself or @Sriram-pc can get those sessions set up for you :)

**Comment by nanyangpro** [comment]
Thanks for confirming @LindsayMacfarlane -  Yes, mid next/later week would be awesome. @Sriram-pc 

We gave the heads-up to Jesse and Amanda during our discovery session today, can also mention it again in the upcoming sprint review as discussed.

**Comment by suhafa** [comment]
Closing this ticket, we've got the foundational work for this ticket done :D
