### ISSUE TITLE
CIF Quarterly and Annual Reports (Appendix A)

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#55]
Beginning on the contract start date, and continuing until the end of the target emission intensity measurement period, subject to Schedule E, the recipient will submit a quarterly report for each of the following three month periods: January 1 to March 31, April 1 to June 30, July 1 to September 30, and October 1 to December 31. Such reports shall be submitted no later than the fifth day of the month following the specified period.

**Comment by LindsayMacfarlane** [comment]
EPIC completed - moving to closed :)
