### ISSUE TITLE
Develop plan to onboard CIF team to using the app

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#550]
#### Describe the task

We need to develop a plan in collaboration with the CIF team to work out how and when they will onboard and start using the CIF app. There is still confusion around at what stage the app is 'usable' and for what type of records. 

#### Acceptance Criteria

- [x] Draft document/deck/Miro listing potential onboarding options based on existing research/assumptions
- [x] Discuss with team, highlight values, recognize concerns, compare options, etc.
- [x] Work with Taylor to refine document/deck (ideally visualize procedures in consistent with the CIF process)
- [x] Book meeting with Ops Team and KT to propose and discuss options, ideally come to an agreement

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro - your support on this ticket would be fantastic! I love your idea of providing options for onboarding.

**Comment by nanyangpro** [comment]
Thanks @LindsayMacfarlane - more than happy to take on the task. I've updated the AC as discussed.

**Comment by LindsayMacfarlane** [comment]
Follow up email sent to meeting attendees. Thank you so much @nanyangpro for all your effort helping to craft an approach and for drafting the response.
