### ISSUE TITLE
As a Project Coordinator, I want the submit button on the create project pages to lead to the next page in the sequence so that I can complete a project without jumping around.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#559]
#### Description:

Clicking on Submit Project Overview, Submit Project Managers, and Submit Contacts all lead to the Review and submit information page. As one participant in usability testing stated, "[I] expected it to go to the next order of operations in the task list, not the very end. Next fillable part."

#### Acceptance Criteria:

Given that user is creating a project and they are on the Add project overview page
When they click on Submit Project Overview
Then they will be directed to the Add project managers page

Given that user is creating a project and they are on the Add project managers page
When they click on Submit Project Managers
Then they will be directed to the Add contacts page

Given that user is creating a project and they are on the Add contacts page
When they click on Submit Contacts
Then they will be directed to the Add quarterly reports page

Given that user is creating a project and they are on the Add quarterly reports page
When they click on Submit Quarterly Reports
Then they will be directed to the Review and submit information page

Given that user is editing a project and are on any of the pages
When they click on the page's Submit button
Then they will be directed to the Review and submit information page

Order of the AC below should match the order in the tasklist
- [x] If more pages are added to the task list before this card is implemented, please update AC.

#### Development Checklist:

- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
Hi @elliottSlee - does this ticket relate to the exploration ticket cif-#317? Or something different? They seem in conflict of each other.

**Comment by LindsayMacfarlane** [comment]
Thank you for that clarification @elliottSlee :)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/559?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @pbastia @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki ! I have tested in dev by following the acceptance criteria list above and confirm the functionality matches as expected.
