### ISSUE TITLE
CIF Project Emission Intensity  (Appendix A - TEIMP/Schedule E)

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#56]
The project emission intensity (Appendix A, Schedule E):
- includes information required in Schedule E of the Funding Agreement (FA)
- is accompanied by a verification statement by a verification body
- frequency of report: one time report out on the TEIMP, report to be submitted within 60 days of the last day of the TEIMP

Emissions intensity is the total CO2 equivalent emissions produced divided by the total output of production, or the per unit emissions from each unit of production. The emissions intensity report being the final report of the project which summarizes the project's performance in reducing the emissions intensity of the operation.

**Comment by LindsayMacfarlane** [comment]
EPIC completed - moving to closed :)
