### ISSUE TITLE
As a Project Coordinator, I want to add the sector to projects so that I can organize projects by sector.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#560]
#### Description:

Tech team wants to know the sector the projects are in. They like to filter projects by sector for when they receive requests for information by sector. Currently the sector is an open field in the spreadsheet, the sectors are not official sectors such as NAICS--just a list of sectors the team uses.

#### Acceptance Criteria:
Given that a project coordinator is logged in and creating or editing a project
when they navigate to the project overview page
then they will see a dropdown field for sector

Given that a project coordinator is logged in and creating or editing a project overview
when they click on the dropdown list
then they will be able to choose from the following options:
- Agriculture
- Cement
- Lime
- Refining Oil & Gas
- Midstream Oil & Gas
- Upstream Oil & Gas
- Mining
- Pulp & Paper
- Utility
- Other, please specify:

Given that a project coordinator is on the project overview page and selecting a sector 
when they select "Other"
then a required text input will be available for them to specify the sector
then their entry will become a part of the list of sectors.

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
Copied feedback into ticket #645
