### ISSUE TITLE
As a Project Coordinator, I want the project list assigned to names to be in order of firstname lastname, so that there are fewer commas and it’s not as confusing.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#567]
#### Description:

![Screen Shot 2022-05-05 at 8.20.42 AM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/54e5ae1a-b746-46a3-a8b4-090a901b72c7) The current format with 4 names has a comma between each name, which users found confusing during usability testing. Users would prefer to have firstname lastname, firstname lastname.

Currently: Peiris, Taylor, Volk, Amanda, LeQuesne, Bailey, Ferguson, Jesse
Desired: Taylor Peiris, Amanda Volk, Bailey LeQuesne, Jesse Ferguson

#### Acceptance Criteria:

Given that user is on the projects list page
When they see the list of project managers in the assigned to column
Then the project manager names will be written in the order of firstname1 lastname1, firstname2 lastname2, firstname3 lastname3, firstname4 lastname4

Given that I am a CIF user
When I visit the projects view page
Then I cannot sort by project manager, since it doesn't make sense with multiple managers

#### Development Checklist:

- [ ] Changing the way the full name is printed in the `fullName` computed column - or adding an alternative computed column?
- [ ] Disable the sorting on that column
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/567?planning-poker) with ZenHub @BCerki @gurjmatharu @matthieu-foucault @mikevespi @pbastia @Sepehr-Sobhani

**Comment by BCerki** [comment]
Got it, thanks!

**Comment by LindsayMacfarlane** [comment]
Thank you @mikevespi! Confirmed acceptance criteria on the following pages/forms in dev:
1. Contacts 
2. CIF Projects
3. Creating a project
All meet acceptance criteria.
