### ISSUE TITLE
As a user, I want to be able to login using my IDIR ID and password, so that I can access the CIF application

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#57]
#### Description:
Setting up keycloak with the right configuration to allow CIF staff to login, and document the procedure to add new users to the system.

#### Acceptance Criteria:
Given my IDIR is registered in the keycloak realm in the cif_admin group or in realm administrator
When I click the login button
And enter my IDIR credentials
Then I get directed to an admin landing page

Given my IDIR is registered in the keycloak realm in the cif_internal group
When I click the login button
And enter my IDIR credentials
Then I get directed to a cif_staff landing page

#### Development Checklist:
- dev :heavy_check_mark: test :heavy_check_mark: prod :heavy_check_mark: Create the cas-cif keycloak client
- dev :heavy_check_mark: test :heavy_check_mark: prod :heavy_check_mark: Create cif_admin and cif_internal groups in 
- dev :heavy_check_mark: test :heavy_check_mark: prod :heavy_check_mark: Create the groups token mapper (see screenshot below)
- dev :heavy_check_mark: test :heavy_check_mark: prod :heavy_check_mark: Create the user session token mapper (see screenshot below)

Group token mapper
![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/66263fd4-83d4-47dc-a233-1917636f9981)

User Session token mapper
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/326614de-12b4-4372-83d9-18c2a3fa9454)

keycloak
- [ ] Meets the DOD

**Comment by LindsayMacfarlane** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/57?planning-poker) with ZenHub @pbastia @AlexZorkin

**Comment by LindsayMacfarlane** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/57?planning-poker) with ZenHub @matthieu-foucault @dleard

**Comment by matthieu-foucault** [comment]
Moving this back to "in progress" while I fix the redirection issue

**Comment by LindsayMacfarlane** [comment]
Tested in dev environment. Worked as expected. I was able to login using my IDIR and password.

I did need to get granted access after my first log in attempt as I had no roles set up.
