### ISSUE TITLE
The attachments link is not visible on the project view anymore

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#575]
Describe the Bug:

When viewing a project (click the view button on the projects page) the attachments link is not visible anymore

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by LindsayMacfarlane** [comment]
Hi @pbastia - is this bug resolved in the ticket #611?

**Comment by pbastia** [comment]
Yes! Let's close this one

**Comment by LindsayMacfarlane** [comment]
Addressed in ticket #611.
