### ISSUE TITLE
All attachments are visible, not only the ones related to the project

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#576]
Describe the Bug:

The graphql query on the attachments page pulls all the attachments in the system, not only the ones relating to the viewed project

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by dleard** [comment]
I think this has been resolved somewhere. The query appears to get attachments by projectId now.

**Comment by dleard** [comment]
resolved. closing this issue
