### ISSUE TITLE
manager and contact form_change records are not staged when archived [4]

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#577]
Describe the Bug:

When editing a project, archived project_manager records never get staged because the computed column ignores archived records. There's a similar issue with contacts, but it's less apparent because we do a filter: {notEqualTo: "ARCHIVE"} in the fragment instead, so the staging of the form_change goes through, unless you refresh the page before hitting 'Submit Contacts'.

This is not a major issue at the moment as the only fallout is that it makes the statuses in the TaskList a little wonky in these scenarios.

**Suggested starting point**
I think excluding archived records is mostly so we're not showing that archived data in the forms. This should probably be done with a filter on the front-end rather than being excluded in the computed_column / relay fragment. Then the stageContactFormChanges (or manager) functions could use the unfiltered array and the display could use the filtered array.

Probability (how likely the bug is to happen, scored from 1-5): 2

Effect (how bad the bug is when it does happen, scored from 1-5): 2

Steps to reproduce the behaviour:

Edit a project with secondary contacts or project managers committed.
Archive one off those records & click submit. You can see that the status in the TaskList does not show what it should.
If you psql into the database and look at the form_change records for that revision, you'll see that the archived record is still 'pending' when it should be 'staged'

**Comment by matthieu-foucault** [comment]
I thought I would solve that with #375, but I now think it's a different issue

**Comment by BCerki** [comment]
Lindsay, this was behind-the-scenes work so I don't think you'll be able to test anything in dev, but please correct me if I'm wrong @dleard.
