### ISSUE TITLE
As a Project Coordinator, I want to reorder reporting requirements, so that I can correct mistakes when entering dates or accomodate schedule changes

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#579]
#### Description:

We need to allow users to reorder reports to support some cases:
- a schedule of quarterly reports was entered and one or more dates were missed
- schedule changes after an amendment

The issue with the current designs is that quarterly reports are numbered. Automatic reordering could be done either when the date is entered, or when the page reloads, but both of these options would be very confusing and go against best UX practices.

Options to investigate would be:
- a quarterly report sort function, similar to zenhub
- a manual "sort" button that would leave the user in control
- crafty animations to show the user when reordering takes place (this is expensive, development-wise)
- ...? @suhafa @nanyangpro to look into best practices and what the needs and context would be for such a feature

#### Checklist:

- [x] Review user story with CIF Ops team for clarity and understanding
- [x] Review technical aspects with dev team
- [x] Create design for implementation

#### Notes:

- ticket repurposed for research and design. User stories and acceptance criteria will be created based on design and research.

**Comment by suhafa** [comment]
See #604 as a possible solution to explore moving forward.

**Comment by LindsayMacfarlane** [comment]
What is our priority on this feature? How often does the Ops team need to re-order quarterly reports. Seems like this might be a nice to have?

**Comment by pbastia** [comment]
This is more of a usability issue. If I accidentally shift my 10 quarterly meetings, how do I add one at the top of the list, without changing the due date on each of them?
Having them automatically generated as in #604 would solve that issue

**Comment by dleard** [comment]
We store the `reportingRequirementIndex` in the database, but never update it (for example if we have reports with indexes 1,2,3 and remove 2, we now have reports with indexes 1 & 3. If we re-order things these indexes should be updated as well. This is just a note as it sounds like the solution in #604 doesn't require any reordering.

**Comment by suhafa** [comment]
Was referenced during our Jun 23rd Sprint Review

**Comment by nanyangpro** [comment]
Hi @pbastia, @suhafa - Shall we change the label from "low priority" to "high priority" based on the observation session with Amanda yesterday?

**Comment by pbastia** [comment]
I'd say so, especially since a "Reorder by due date" button or something like that would do the trick

**Comment by LindsayMacfarlane** [comment]
@suhafa @nanyangpro - I've updated *slightly* to reflect research and design.

**Comment by suhafa** [comment]
Wireframe for quarterly, annual and milestone reports [here](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=4091%3A2783)

**Comment by LindsayMacfarlane** [comment]
Thank you so much for all your dedication and effort on this one @suhafa!
