### ISSUE TITLE
Add CIF staff to IDIRs to the Keycloak realm

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#58]
#### Describe the task
Add CIF staff IDIRs to the KC realm.

#### Acceptance Criteria

- [x] Email TP for list of CIF staff IDIRs
- [x] Get list of IDIRs for CIF staff
- [x] CIF staff IDIRs / IDs are configured in the keycloak realm
- [x] keycloak documentation has been written (e.g., how to add user to group)

#### Additional context
This issue documents the procedure, needs to be on Gov VPN
- https://github.com/bcgov/ocp-sso/issues/118 

#### Notes
- PB will be able to complete this task most efficiently being a gov't staff member

**Comment by pbastia** [comment]
See @Peirist 's email from Feb 15 for the list of people to add.

**Comment by matthieu-foucault** [comment]
- I don't see the users in the prod realm, we probably want to add them there too
- Have we established who should be an admin? I see everyone has the cif_admin role in the test environment.
- Does the link in the issue description contain all the documentation on how to add users to the realm, of were there other steps?

**Comment by LindsayMacfarlane** [comment]
Thanks for confirming @pbastia ! Moving ticket to closed.
