### ISSUE TITLE
As a CIF administrator, I want to see the AnnualReports on the project view page, so that I can get information about them

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#586]
#### Description:

Adding the annual reports form to the project view page.
We can base the UI look based on what was already done for the other read-only forms, and add the same visual cues about reporting requirement status than in the wireframes.

#### Acceptance Criteria:

Given that a `project_revision` that includes a annual report is committed
When I visit `/cif/project-revision/<projectRevisionId>/form/annual-reports` 
Then

- The form is displayed with `readonly` theme
- There is an `Edit` button in the top-right corner
- The form `submit` button is not displayed
- The `TaskList` is displayed in view mode

Given that I am viewing a committed annual report
When I click the Edit button
Then a new project revision is created, and I am redirected to the form matching the one I was viewing

#### Development Checklist:

- [x]  The view page shows the annual report details
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/586?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki ! Meets acceptance criteria.
