### ISSUE TITLE
Create  `funding_stream` and `funding_stream_rfp` table with records

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#59]
#### Describe the task
Create `funding_stream` table with EP and IA records
Create `funding_stream_rfp` table

#### Acceptance Criteria

- [ ] there is a `stream` table with the following columns:
    - id
    - name ('EP')
    - description ('Emissions Performance stream')
- [ ] table passes the style tests

**Comment by dleard** [comment]
work moved into user story #130

**Comment by LindsayMacfarlane** [comment]
Hi @dleard - if work moved into ticket #130 - can I un-assign the sprint to this one? Or do we still want to capture the details in this ticket?

**Comment by dleard** [comment]
@LindsayMacfarlane un-assigning the sprint makes sense, we split this work out into a task and then decided it was better off written as AC in the user story
