### ISSUE TITLE
As a member of the CIF team, I want to be able to edit the project revision in flight, so that everyone can collaborate on project revisions

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#591]
#### Description:

Right now every user creates their own revision, and editing someone else's revision is not possible.
The consensus was that collaboration was important, and that the risk of having multiple people working on the same revision at the same time was very limited.

The  function that checks if a revision exists for a project needs refactoring, to not constrain it to the logged in user.

#### Acceptance Criteria:

Given I am a CIF administrator
When someone on my team starts editing a project
And I go to that project's view page
Then I can see a "Resume Edition" button

Given I am a CIF administrator 
When I edit a project
And one of my team mates is editing the project at the same time
Then I can experience an optimistic concurrency behaviour (every time a form is updated by a user, this becomes the data in the system)
And no errors are thrown

#### Development Checklist:

NOTE: This does not impact the "new project" behaviour

- [x] Refactor `computed_columns/project_pending_project_revision` to remove the current user check
- [ ] Testing to make sure that separate users still "own" their project creation revision until submitted
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [ ] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
do we also implement that behaviour for creating new projects? or is this strictly for editing existing projects?

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/591?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by mikevespi** [comment]
@pbastia Just a sanity check, `functions/pending_new_project_revision.sql` doesn't need to change, but `computed_columns/project_pending_project_revision` does, right? Creating a new project still gets the user check, but existing projects being revised can be collaborated on?

**Comment by pbastia** [comment]
ExactIy! think we'll have to be careful with explaining how that works in our training material, but a project is not available for other users to collaborate on until it is created first

**Comment by LindsayMacfarlane** [comment]
Hi @mikevespi - I'm assuming I need to test this one in conjunction with another person. Perhaps we can quickly review/test at our check-in this afternoon?

**Comment by LindsayMacfarlane** [comment]
Thank you for testing this out with me @mikevespi!
