### ISSUE TITLE
As a CIF Administrator, I want to add a new milestone, so that I can track when milestones will be due

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#595]
#### Description:

![Screen Shot 2022-05-11 at 2.41.39 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/fea08476-ef47-4ad3-9a90-76dea1c0a680)

#### Acceptance Criteria:

Given that a CIF administrator is logged in and they are at the project milestone reporting section of adding or editing a project
When they click on "add a milestone report"
Then a section will appear with the heading Milestone X [X being a # that increases by 1 each time another milestone report is added]
And they will see the input fields in that section (see #583)

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Covered by #583
