### ISSUE TITLE
As a CIF Project Coordinator, I want to input project dates, so that statuses can be automatically triggered and quarterly and annual report due dates can be automatically calculated.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#598]
#### Description:

There are several important dates for a project which, if included in the system, would enable auto-calculated due dates for quarterly and annual reports.

#### Acceptance Criteria:

Given that CIF admin is logged in,
when they are on the project details page,
then they see the following inputs.

- [x] Contract Start Date. input = datepicker, validation = nothing before 2019 or after today
- [ ] Eligible Expense Start date. input = datepicker, validation = nothing before 2019 or after today
- [ ] Project End Date. input = datepicker, auto-populated = final milestone date + 30 days
- [x] Projects Assets life end date (10 years after the Eligible Expense Start date, just for EP, not for IA). input = datepicker, validation = even greater question

#### Checklist:

- [x] Review user story with CIF Ops team for clarity and understanding
- [x] Review technical aspects with dev team
- [x] Create design for implementation

#### Notes:

- ticket repurposed for research and design. User stories and acceptance criteria will be created based on design and research.

**Comment by pbastia** [comment]
Re: BCGHGID and Sector
These are facility-level information, not operator. We currently don't track the facility an industrial reporter is applying for, but maybe this is something we'd want to consider? Or just tracking these fields as optional metadata on the application?

**Comment by elliottSlee** [comment]
#560 is about status and could be combined into this ticket. Sector was requested by CIF team.

**Comment by elliottSlee** [comment]
@LindsayMacfarlane I will break it out.

**Comment by elliottSlee** [comment]
@LindsayMacfarlane What do you think about adding facility name & BCGHGID to #578 ?

**Comment by nanyangpro** [comment]
3 Amigos meeting with Taylor and Amanda: 2019 is the only one on a different schedule, could be done manually since it's only 13 projects.

**Comment by matthieu-foucault** [comment]
@LindsayMacfarlane as per the 3 amigos discussion, the automatic creation or reports can happen after the first release. Those inputs should be available in the first release though

**Comment by dleard** [comment]
@matthieu-foucault Your comment above says these inputs should be included in the first release. Did we decide it can happen after the first release (I see the priority was lowered to medium a week ago) @LindsayMacfarlane

**Comment by suhafa** [comment]
We can tackle this after soft launch since 2019 quarterly report dates are all different.

**Comment by LindsayMacfarlane** [comment]
@suhafa @nanyangpro - I've *slightly* updated this ticket to make more relevant for research and design.

**Comment by suhafa** [comment]
As per the dev/design sync (12 August), we decided the following:
- The `Contract Start Date` and the `Project Assets Life End Date` are the two new fields to support the auto-generating functionality. They will be under `Budgets, Expenses and Payments` screen.

As for the discovery/design, the date inputs required for the report generation are as follows:
- `Contract Start Date` (Budgets) + `Measurement Period End Date` (Emissions Performance) = Quarterly Reports
-  `Report Due Date` (Emissions Performance) + `Project Assets Life End Date` (Budgets) = Annual Reports

[**Link to the wireframe**](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=3861%3A2836) capturing this ticket

@LindsayMacfarlane - this ticket can be closed after your review! c:

**Comment by LindsayMacfarlane** [comment]
Thank you so much for all your dedication and effort on this one @suhafa!  This was so much more complicated than I expected, but I know this will significantly help Amanda and the CIF team!
