### ISSUE TITLE
As a Project Coordinator, I want quarterly and annual report to be automatically generated, so that I don't have to go through the effort or make a mistake when inputting these due dates.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#599]
#### Description:

Quarterly & annual reports are always due at the same time, regardless of project, and could be calculated based upon contract date & end of Target Emissions Intensity measurement period.

Note: this end date comes from usability testing sessions with [Bailey](https://bcgov.sharepoint.com/:v:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/CIF/Usability%20Testing%20%26%20Discovery%20Recordings/Quarterly%20Report%20Test%20and%20Budget%20Wireframe%20Walkthrough%20with%20Bailey_24May22.mp4?csf=1&web=1&e=d1vuX2) and [Amanda](https://bcgov.sharepoint.com/:v:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/CIF/Usability%20Testing%20%26%20Discovery%20Recordings/Quarterly%20Report%20Test%20and%20Budget%20Wireframe%20Walkthrough%20with%20Amanda_24May22.mp4?csf=1&web=1&e=ofWyMn).

#### Acceptance Criteria:

Given that a CIF admin has created a project
When they enter start & end dates
Then quarterly reports will automatically be created on the following January 5, April 5, July 5, and October 5 until the end of the project.

Given that a CIF admin has created a project
When the contract date is within 44 days of the next quarterly report date
Then the first quarterly report will not be the most immediate quarterly date, it will be the following.

#### Checklist:

- [x] Review user story with CIF Ops team for clarity and understanding
- [x] Review technical aspects with dev team
- [x] Create design for implementation

#### Notes:

- ticket repurposed for research and design. User stories and acceptance criteria will be created based on design and research.

**Comment by nanyangpro** [comment]
3 Amigos meeting with Taylor and Amanda: The due date of the 1st annual report is tied to the TEIMP report, and can be pushed back.

**Comment by LindsayMacfarlane** [comment]
@suhafa @nanyangpro - I've *slightly* updated the ticket to reflect research and design.

**Comment by suhafa** [comment]
Design covered in [wireframe ](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=4026%3A6770)(with all possible cases such as edit, missing information, deletion etc)

**Comment by LindsayMacfarlane** [comment]
Thank you so much for all your dedication and effort on this one @suhafa!  This was so much more complicated than I expected, but I know this will significantly help Amanda and the CIF team!
