### ISSUE TITLE
As a CIF administrator, I want to describe the relationships between funding stream phases so that I can define how a project can enter each phase

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#61]
#### Description:
As a CIF administrator, I want to describe the relationships between funding stream phases

#### Acceptance Criteria:
Given
  When
  Then

#### Development Checklist:
- [Other AC]
- [Other AC]
- [Other AC]
- Meets the DOD

#### Personas:
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket
[Program Development Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by matthieu-foucault** [comment]
Let's close this until there's an actual need to add constraints for project statuses transitions

**Comment by LindsayMacfarlane** [comment]
@matthieu-foucault - should we close this or just add it to release #2?

**Comment by matthieu-foucault** [comment]
Well we haven't established that this is a need yet. We'll want users to play with the application first, to see if they need more constraints. This may be more relevant once we open the application to external users
