### ISSUE TITLE
As a CIF user, I want to see the link to add attachments when I view a project

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#611]
#### Description:

The link to the attachments page needs to be added to the task list when it is in view mode

The project view page (`app/pages/cif/project/[project]/index.tsx`) is now unused and should be removed

#### Acceptance Criteria:

Given I am a CIF user
When I visit `app/pages/cif/project/[project]/index.tsx`
Then I should see a 404 page

Given I am a CIF user
When I view a project
Then I can see an "Attachments" group with a "manage attachments" link in the tasklist

Given I am a CIF user
When I view a project
And I click the "manage attachments" link in the tasklist
Then I can see the table with the attachments for that project
And I can see an "upload attachment" link

Given I am a CIF user
When I view a project
And I click the "Upload Attachment" link
Then I am prompted with the upload file dialogue

#### Development Checklist:

- [x] remove the `app/pages/cif/project/[project]/index.tsx`
- [x] Add an extra item in the tasklist 
- [x] Refactor the existing `app/pages/cif/project/[project]/index.tsx` to be on the project revision and integrate with the current pages 
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/b283fc2a-5a4b-46de-b758-b1400881bb2f)

@matthieu-foucault did you have a more elaborate wireframe in mind for this one?

**Comment by matthieu-foucault** [comment]
looks good to me

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/611?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by suhafa** [comment]
![image.png](https://images.zenhubusercontent.com/6201b10c9827341d8d5cbe9c/1b9c3675-c697-4aa3-ba21-5612a7a869aa)
Suggest this design instead. Do we require the attachments to have a dropdown? Can the word 'Attachments' and the row it is in be clickable?

**Comment by pbastia** [comment]
I like it! And showing it without a number quite separates it from the form - since we link attachments directly to a project, and don't use the form change strategy for them yet

**Comment by LindsayMacfarlane** [comment]
Thanks @pbastia! Looks great! I tested in dev by:

1) Going to an existing project. Selecting the 'attachments' in the task list and uploading an attachment. I was able to upload multiple files. Table appeared to upload with the correct metadata. 

Observation:
- I'm =99.9% sure this is related to me doing something wrong, but when I try to navigate to the page app/pages/cif/project/[project]/index.tsx I don't get an error message - my browser just turns into into a google search? 
- Between the task list and the size of the table - not everything could be displayed on my laptop monitor without the need to scroll. 
- Is there no way to add attachments at project creation? I couldn't see a ticket in the backlog to address that (although could very well have missed it)? I would imagine as a user, that I would want to add attachments while I am creating a project?

**Comment by pbastia** [comment]
@LindsayMacfarlane 
- This is probably a browser thing that happened, the path in this card points at the `nextJS` path, not the URL. The URL would be: [http://dev.cif.gov.bc.ca/cif/project/someprojectId](http://dev.cif.gov.bc.ca/cif/project/someprojectId)
- Yes, agreed. This card was to just make the functionality available with what was already implemented, we'll have opportunities to refine the UI
- Not at this point, because attachments are (so far) not linked to a project revision, but to a project itself, which doesn't exist until it's created first. We will need revisit this behaviour at a later point to stay consistent with the rest of the app.
