### ISSUE TITLE
When creating a project, the overview and project contact forms show up as incomplete

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#612]
Describe the Bug:
untouched forms should always have `not started ` as the status.
when creating a project the project overview and project contact forms start with incomplete status (gonna be In Progress after task #540)

Probability (how likely the bug is to happen, scored from 1-5):5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
hit `create new project` button and you'll see the bug :) 

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by matthieu-foucault** [comment]
@Sepehr-Sobhani I think that we have now fixed this for the contacts. We actually might want to show the overview as "In Progress" when you first create a project, given that that form is containing required fields.

**Comment by Sepehr-Sobhani** [comment]
> @Sepehr-Sobhani I think that we have now fixed this for the contacts. We actually might want to show the overview as "In Progress" when you first create a project, given that that form is containing required fields.

@matthieu-foucault Yeah I agree. But is there a way to have it `Not Started` by default and when the user touches a single field, make it `In Progress` ? like adding this functionality when staging any change in the project overview form?!

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani ! Overall, looks to work as expected. I did notice that when creating a project, milestone reports are missing the 'Not started'. See screenshot below. Would this be a new bug ticket?
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/f0547c1a-2c61-42cc-96ff-743a1de3848c)

**Comment by Sepehr-Sobhani** [comment]
@LindsayMacfarlane Thanks for noticing that. That should be a bug. I will make that ticket.
