### ISSUE TITLE
Untouched `Quarterly Reports`, `Annual Reports` and `Contacts` forms don't trigger attention required status [5]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#613]
Describe the Bug:
When creating a brand new project when adding `QuarterlyReports` or `Contacts` and hitting submit before interacting with the form the tasklist shows `Filled` status instead of attention required.
This is due to the server-side validation never running since the `updateFormChange` mutation is never called.
Server-side validation only runs when we run the `updateFormChange` mutation.

Probability (how likely the bug is to happen, scored from 1-5):3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
Click the create new project button from dashboard -> go to project contacts form and hit submit right away

Video walkthrough: (credit: @BCerki )
https://www.loom.com/share/3396cbb076a4450192c0a55323eff38b

Screenshots:
![Screen Shot 2022-05-17 at 4.18.32 PM.png](https://images.zenhubusercontent.com/6243a3ea8726850c1675becd/39fe6375-cb0a-4b81-8693-bbe356b6c7ca)

**Comment by dleard** [comment]
I poked at this a bit in my Milestones PR before realizing there was already a bug card. I think it may originate in the `FormChangeValidationPlugin`

**Comment by Sepehr-Sobhani** [comment]
> I poked at this a bit in my Milestones PR before realizing there was already a bug card. I think it may originate in the `FormChangeValidationPlugin`

Not aware of what that plugin does 😄  gonna take a look at that.

**Comment by Sepehr-Sobhani** [comment]
@LindsayMacfarlane The issue regarding `QuarterlyReport` has already been solved and regarding the project contact form issue, we don't have this issue anymore but we have another issue which is mentioned #735 . I'm trying to cover both issues on my branch and if I can do that, will close both cards.

**Comment by LindsayMacfarlane** [comment]
Thanks @Sepehr-Sobhani !

**Comment by BCerki** [comment]
This bug may be related: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/802

**Comment by dleard** [comment]
Very nice, I tested the contacts, quarterly and annual reports forms and they all trigger `attention required` when staging incomplete forms.
