### ISSUE TITLE
Sorting projects by status [8]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#620]
Describe the Bug:
On the project list page, sorting projects by status raises an error.

Probability (how likely the bug is to happen, scored from 1-5): 5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
Visit the project list page and click the `status` table header to sort projects by their status

Screenshots:
![Screen Shot 2022-05-18 at 5.01.23 PM.png](https://images.zenhubusercontent.com/6243a3ea8726850c1675becd/794bd752-6b0a-44e7-b8fe-de85dc1eb8b4)

**Comment by LindsayMacfarlane** [comment]
Looks good to me - I can't reproduce the error :) Thank you @dleard!
