### ISSUE TITLE
Tech Debt: GitHub Actions should use the GH registry to run the workflows

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#627]
Right now, we store each version of our docker containers on GCS, which, with a larger dev team, increases the costs incurred for the cloud storage. 
We should only push to our team's GCS registry on PR merge, and use the GitHub registry in the PR builds.

Info about the GH container registry can be found [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)

External PRs need maintainer approval to run the checks, so we're protected from a potential attack there.

**Comment by matthieu-foucault** [comment]
> We should only push to our team's GCS registry on PR merge

@pbastia @gurjmatharu I'm not sure we should use GCS at all. Use of GCS instead of the GH container registry was a mitigation for a risk (bug) that has now been resolved by GitHub (the registry wasn't quite working with CRI-O runtimes, which is used by OpenShift)

**Comment by gurjmatharu** [comment]
@matthieu-foucault @pbastia there's also the artifactory that may or may not be up and running now?

**Comment by matthieu-foucault** [comment]
We are using artifactory as a local cache, which we can keep on doing with GH container registry. We don't need to use a private artifact repository though
