### ISSUE TITLE
Refactor form pages into a single page

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#632]
#### Describe the task

A PR was started during our developer workshop: https://github.com/bcgov/cas-cif/pull/630

In the spirit of keeping our PRs small, I would suggest restricting this refactor to the form pages. Changes to the task list (e.g. generating the sections and items from a configuration object) should be shipped in a second task

**Comment by LindsayMacfarlane** [comment]
Hi @matthieu-foucault are you working on this ticket? Just wondering who it should be assigned too :)
