### ISSUE TITLE
As a project coordinator, I want to be able to filter, order and paginate the list of projects, so that I can find a project of interest to review

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#64]
#### Description:
As a project coordinator, I want to be able to filter the list of projects, so that I can find a project of interest to review.

#### Acceptance Criteria:
 Given that I am a project coordinator and I want to find a specific project(s)
 When I click on the column headers of the project table
 Then the table re-orders and by the selected column

 Given that I am a project coordinator and I want to find a specific project(s)
 When I enter search text into the column filter form input
 Then the table filters by the search text using simple text search

 Given that I am a project coordinator and I want to find a specific project(s)
 When I click on the page number
 Then the table displays a paginated set of projects

#### Development Checklist:
- [ ] Enable built in column ordering, and enable for all columns if exists
- [ ] Enable built in text filtering, and enable for all columns if exists
- [ ] Use https://github.com/bcgov/cas-ciip-portal/tree/develop/app/components/FilterableTable if not implemented
- [ ]  set table to match BCGov style
- [x] Wireframe completed and linked to ticket
- [ ] Meets the DOD

#### Personas: 
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by rajpersram** [comment]
[Wireframe in Ticket 63 ](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/63) shows the project search filters.

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/64?planning-poker) with ZenHub @AlexZorkin @dleard @pbastia

**Comment by LindsayMacfarlane** [comment]
Looks great @matthieu-foucault! Tested in dev by:

- using column filters
- using text filtering
- selecting apply button or entering 'enter' when in the text filter
- clearing all filters and manually clearing text filtering

Works as expected.
