### ISSUE TITLE
As an Ops Team Member, I want to enter and track budgeting-related data on the Budgets, Expenses & Payments form

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#642]
#### Description:

As part of the funding agreement, the province will pay up to a maximum funding amount, which is based on total project value and province's share percentage.

Draft Figma design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=1878%3A3066

- total project value
- maximum funding amount
- province's share (percentage)
- performance milestone holdback percentage
- anticipated funding amount

#### Acceptance Criteria:

Given I am a CIF administrator
When I create or edit a project
Then I can see a "Budgets, Expenses and Payments" section in the tasklist

Given I am a CIF administrator
When I create or edit a project
And I click on the "Budgets, Expenses and Payments" section in the tasklist
Then I can see a budgeting section
And its title is "Funding Agreement Overview"

Given I am a CIF administor
When I am on the "Budgets, Expenses and Payments" form of a project
Then I can enter the following budgeting fields:
- maximum funding amount
- total project value
- province's share (percentage)
- anticipated funding amount
- performance milestone holdback percentage

Given I am a CIF administor
When I am on the "Budgets, Expenses and Payments" form of a project
Then the following fields have the following defaults:
- province's share (percentage): 50%
- performance milestone holdback percentage: 10%

#### Development Checklist:
- [ ] create a `funding_parameters` table with the fields:
     - fkey to project(id)
     - total project value
     - maximum funding amount
     - province's share (percentage)
     - performance milestone holdback percentage
     - anticipated funding amount
- [ ] tasklist section and new form for the budgets, expenses and payments
- [ ] new form in the form config
- [ ] manual input for now, just with defaults - default values should be a frontend concern (at least for now)
- [ ] Meets the DOD

#### Notes:

- For initial development, this field can be manual input; however, in the future, there could be opportunity to automate by calculating total project value & province's share percentage. 

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by LindsayMacfarlane** [comment]
@nanyangpro - is this user story really an update to the current terminology in the CIF app? It looks like this field is already included, but we call it 'Total Funding Request'?

**Comment by nanyangpro** [comment]
Good question, @LindsayMacfarlane - "Total Funding Request" makes more sense to the pre-FA phases/project status, while "Maximum Funding Amount" is more appropriate to the post-FA phases/project status according to CIF Ops. Ideally the field label is displayed accordingly to the project status, but can also be displayed with the alternative in brackets as indicated in the wireframe in the short term. Together with the devs, we can explore the usability of having 2 separate fields instead if it's better practice.

**Comment by pbastia** [comment]
Discussion on the province's share:

matthieu-foucault
commented 4 days ago

Should this one be calculated, instead of an input?
nanyangpro
commented 4 days ago

Good question, @matthieu-foucault - Should be an input (as defined in the FA).
nanyangpro
commented an hour ago

@matthieu-foucault - I confirmed with Taylor again, and here's his comment:
"The Province's Share should be manually entered so that the value matches the funding agreement and doesn't fluctuate due to minor differences in actual vs. budgeted expenses."
matthieu-foucault
commented 39 minutes ago

What qualifies as a "minor" difference? Or rather, when would the province's share be updated? When the difference is >1%, >5%? If there is a known threshold, we can round the value.

Having a separate input rather than a calculated value adds the risk that major differences are not reflected in this value, leading to inconsistent data.

If we decide to have a separate input, I would like to see a clear explanation of the purpose of this value, so that we can add it to our metadata, ensuring that anyone looking at our data in the future understands that the value is an approximation

**Comment by nanyangpro** [comment]
@pbastia, @LindsayMacfarlane  - The wireframe for #642 has been updated based on the 3 amigos discussion, feel free to update the ticket accordingly and ask any questions you may have.

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/642?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Hi @gurjmatharu and @Sepehr-Sobhani - looks great! Thank you for all your work on this ticket.

I tested in dev by:
1. Creating a new project
2. Editing an existing project

Meets acceptance criteria.

**Comment by LindsayMacfarlane** [comment]
@suhafa and @nanyangpro - question on design for the funding agreement - when a user first selects the funding agreement under the 'Budgets, Expenses and Payments - they have to select an additional button 'add fundng agreement. I don't believe any of our other pages have this? It seems like an extra step unless there is a reason for it?
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/6958d417-c970-4fd3-94c0-756bb11b175d)

**Comment by nanyangpro** [comment]
Good question, @LindsayMacfarlane - It's not in the design.

@gurjmatharu, @Sepehr-Sobhani - Was there a decision made among the devs to have this extra step / additional button? If so, what's the reason behind?

**Comment by dleard** [comment]
This is our only 'flat' form that has required inputs, but where the form itself cannot be required (which made the button the quickest path), so there are some things to figure out about when to create the form_change record. It shouldn't be difficult to set some logic to do this, but we didn't want to rush the exploration / solution. I will add a tech debt card to look at removing the button.

**Comment by LindsayMacfarlane** [comment]
Thank you @dleard - your clarification and explanation was super helpful. Much appreciated.
