### ISSUE TITLE
As a CIF user, I want to add an operator, so that I can assign an operator name to a project

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#66]
#### Description:
As a CIF administrator, I want to add an operator, so that I can assign an operator name to a project

#### Acceptance Criteria:
Given that a user is on the operator create screen
When they fill out the required fields and hit save
Then the new operator will be added to the database and the operator name will show up on the project create select operator dropdown menu

#### Development Checklist:
- [x] The operators list has an "Add an Operator" button
- [ ] The new operator form has the same fields as the edit form (Legal Name, Trade Name, BC Registry ID, CIF identifier
- [ ] Similar to contacts, operator creation can be resumed, and changes are saved in the `form_change` table
- [ ] Save new operator to database when the user hits the submit button
- [ ] Ensure new operator name is selectable on Project Create Page operator name form field
- [x] Wireframe completed and linked to ticket
- [ ] Meets the DOD

#### Personas:
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket
[Program Development Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by rajpersram** [comment]
![CIF Workflow Co-Design - Operator Page.jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/a743262f-75d5-4370-9bd1-a623adfa9b5d)

**Comment by rajpersram** [comment]
See [ticket 67 for Operators wireframe](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/67)

**Comment by LindsayMacfarlane** [comment]
At @Sriram-pc is this a duplicate of #128?

**Comment by Sriram-pc** [comment]
![image.png](https://images.zenhubusercontent.com/6149103e0c14630f5a9c158a/0f82c003-dbe7-4479-b11e-f87b6c7548c7)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/66?planning-poker) with ZenHub @dleard @pbastia

**Comment by LindsayMacfarlane** [comment]
Thanks @pbastia ! Tested in dev:
- able to select 'add operator button'
- able to add an operator: Legal name, trade name
- optional fields are optional: BC Registry ID, Operator code
- received expected validation errors.

Observations:
- If CIF enters an operator - how does it get linked back to swrs?
- the validation for the optional fields can updated to 
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/e9425f09-3866-4e9d-9dd3-a16bef58c995)
-
