### ISSUE TITLE
Refinement of design and behaviour of contacts page

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#666]
#### Describe the task

Review the current functionality of the contacts page to propose improved design and usability. During user testing, there was often confusion around how project contacts behaved. 

#### Acceptance Criteria

- [x] Review current functionality and feedback already received from Ops Team
- [x] Identify changes to functionality behaviour
- [x] Create new design

#### Additional context

- Some relevant tickets #462, #461
- Or here

**Comment by LindsayMacfarlane** [comment]
@suhafa and @nanyangpro - please review and refine this ticket. I'll pull it into this sprint backlog.

**Comment by nanyangpro** [comment]
Loop in @pbastia and @matthieu-foucault as well.

**Comment by suhafa** [comment]
Work for this ticket captured [here](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=1775%3A2665). We can close this @LindsayMacfarlane c:

**Comment by suhafa** [comment]
Created #694 on the basis of this ticket's work

**Comment by LindsayMacfarlane** [comment]
Thank you so much @suhafa!
