### ISSUE TITLE
As a CIF user, I want to view a list of operators

### ISSUE THREAD

**Issue by Sriram-pc** [bcgov/cas-cif#67]
#### Description:

As a CIF administrator, I want to view a searchable list of operators.
The searching / pagination functionality in the wireframe will be completed in #64.
This feature is just to show the list of operators & their details.

  Given I am logged in as a cif user
  When I navigate to the operators page
  Then I see a list of operators and their details

  Given I am on the operators page
  When I add filters
  Then the list of operators shown is pared down accordingly

Acceptance Criteria:

- [x] An 'operators' page exists
- [x] All operators are listed in a table with the following details: { legalName, tradeName, bcRegistryId, cifIdentifier }
- [x] The operators page uses the filtering/pagination work done in #64

Adding applicable Personas to the ticket
[Program Development Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

[Tech Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket
[Program Development Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

[Tech Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by rajpersram** [comment]
![CIF Workflow Co-Design - Operator Page .jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/9b26f14d-a773-4c29-bcab-aab5ad8c6907)

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/67?planning-poker) with ZenHub @AlexZorkin @matthieu-foucault @pbastia

**Comment by matthieu-foucault** [comment]
As #64 would add filtering/ordering/pagination components, this should be done after

**Comment by LindsayMacfarlane** [comment]
Thank you @AlexZorkin !

I tested in dev by:
- going to operator page
- filtering by legal name, trade name, BC Registry and code
- testing the clear, apply and using the return key on the filter function
- selecting 'view' which brought me to the operator page

Meets the acceptance criteria and development checklist.
