### ISSUE TITLE
Database restore and dev training

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#672]
#### Describe the task

The team should be familiar with the process and steps required to restore the database should something go wrong in our PROD environment

#### Acceptance Criteria

- [x] Develop training
- [x] Complete training with all developers on team
- [x] Create a playbook explaining and outlining steps required to restore the database

#### Notes
- https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/disaster-recovery/

**Comment by LindsayMacfarlane** [comment]
Would be good to have this completed prior to Dylan and Matthieu are on holidays.

**Comment by LindsayMacfarlane** [comment]
Hi @pbastia - checking in on the checklist item: "Complete training with all developers on team". Can you confirm if that was completed or is being pulled into another ticket?

**Comment by pbastia** [comment]
There was a demo done, but some team members were missing. We'll have a catch-up session when everyone's back
