### ISSUE TITLE
As a CIF user, I want to add project managers for a given project, so that I know who is responsible for each project

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#68]
#### Description:

Brief description of the work involved, including any user research context or key decisions.

#### Acceptance Criteria:

- Option - use Ghirken:
  Given
  When
  Then
- [Other AC]
- [Other AC]
- [Other AC]
- Meets the DOD

**Comment by LindsayMacfarlane** [comment]
Do we require a wireframe for this user story?

**Comment by matthieu-foucault** [comment]
This is in the wireframe for #69 , so I'm not sure if this needs to be a separate user story

**Comment by dleard** [comment]
duplicate, work to be done in #69 as part of the composite form change work
