### ISSUE TITLE
Reporting Requirement statuses should be derived

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#687]
The way statuses are implemented currently as static column data in the reporting_requirement table means that they will not update automatically. We have no mechanism to change the database data based on when a due date passes & so a status will never change to `late`.

The reporting_requirement statuses should be derived (using a computed column) rather than stored as a data column in the database so that the statuses are fetched and calculated on page load. This means removing the `status` column from the `reporting_requirement table`, removing the `reporting_requirement_status `lookup table and creating a computed column to retrieve that data on reporting_requirement form_change records.
 
Statuses should be returned by the computed column as follows:

Has future due date & no received date: `on_track`
Has past due date & no received date: `late`
Has due date & received date: `completed`

**Comment by matthieu-foucault** [comment]
Users want to be able to override the calculated value of statuses. The statuses should be derived by default, but a user should be able to override them manually

**Comment by matthieu-foucault** [comment]
This is the behaviour described in #532 (in progress) and #588 (iceboxed)
