### ISSUE TITLE
How should we allow users to set items to "In Review"

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#688]
'In Review' came up as a status the CIF team would like to manually set so that they can be aware of whether something is being looked at by the tech team/there is a delay in a decision-making but is being taken care of for now. It is more like an in-between state, and may be used for internal communication within the team.

This 'In Review' status was originally lumped in with the rest of the reporting requirement statuses (on track, late, completed). It has been split out from those as there is a clear distinction here with those statuses being derived based on dates and 'In Review' being a user-controlled status.

Questions:
Is this "In Review" status specific to reports (milestones, quarterly, annual) or are there other things that CIF users would like to be able to mark as "In Review"?

How would users mark something as "In Review"?

Is an audit trail necessary to know who was reviewing what when? Or is it enough to just see that something is currently under review?

Note:
A possible technical solution was floated when devs were talking this over of having an "In review" table that can store IDs of the item being reviewed and of the person reviewing it. Having a table instead of an "in review" column on the table of the item being reviewed allows things to move in and out of review without triggering any new project revision or amendment.

**Comment by LindsayMacfarlane** [comment]
I notice this has been given a low priority; however, does this tie into any of our discussion with AV yesterday around revisions/amendments? Is this something that should be explored sooner @nanyangpro and @suhafa?

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro - following up on this ticket. Has this been addressed in your latest research and design?

**Comment by nanyangpro** [comment]
Good question @LindsayMacfarlane, I think this ticket is a bit outdated and can be closed. Reasons below:
- **Project-wise**: We have "Under Technical Review" as one of  the options in the finalized list for the "Project Status" field. (Covered in the latest research, but not reflected in the app yet.)
- **Reporting-wise**: We have status indicators for all types of reports.
- **Amentment-wise**: We have the "Status" field along with the email notification feature yet to be implemented for internal communications.

**Comment by LindsayMacfarlane** [comment]
Closing ticket as no longer required.
