### ISSUE TITLE
As a project coordinator, I want to create a project, so that I can add high level project information into the system

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#69]
#### Description:
As a project coordinator, I want to create a project, so that I can add high level project information into the system.
At this stage, we only want to add the minimal information to identify a project. We can add more fields (e.g. project type, naics code after that)

As per the wireframe below the project overview includes attributes that will be stored in the `project` table (e.g. rfp_id, operator_id, project summary, etc) and the `project_manager` table.

As we plan on using `react-jsonschema-form` to render form on the front-end, we will need to engineer a solution to link the front-end forms to the `form_change` table, taking into account that each record of the `form_change` table should result in a single record of a table being updated:

- a `project_revision` table should be added, and an optional foreign key to that table should be added to `form_change`
- committing a `project_revision` record means committing all of the `form_change` records underneath it
- the project creation page should be made of 3+ `react-jsonschema-form` components (one for each `form_change` record), and will update the pending changes directly (see #77).
- when clicking on the submit button (the discard button will be handled in #96), a mutation on the `project_revision` is called, affecting all of the `form_change`s

 

#### Acceptance Criteria:

Given I am on the project list page
When I click the 'create project' button
Then a new `project_revision` record is created, with `form_change` records for : `project` and `project_manager` tables [only one project manager to start]

Given I entered project data
When I click the "Submit" button
Then the project gets persisted to the database [project and project_manager tables]
  and the `project_revision` and  `form_change` records are marked as "committed"

#### Development Checklist:
- `project_revision` has:
    > a state
    > a generated ID (sequential)
    > foreign key to `project` table
    > timestamp/user columns
- `form_change` table has a foreign key to `project_revision` (allow null for now)
- there is a trigger on the project_revision table that propagates the commit to the individual `form_change` rows

On the project form
- [ ] Project Name
- [ ] Project Summary
- [ ] Project Manager selection [only 1]
- [ ] Add project button
- [ ] Meets the DOD

**Comment by rajpersram** [comment]
Added a selection for Project Manager(s)

**Comment by rajpersram** [comment]
![CIF Workflow Co-Design - Create or Edit Project - Overview tab.jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/ece5f5b5-5f27-4ed1-b73e-1a503647af55)

**Comment by rajpersram** [comment]
Sidebar and revision message:
![CIF Workflow Co-Design - Copy of Create or Edit Project - Overview tab with Sidebar open.jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/5f91d909-3a63-4410-90f4-d22ac5ee4430)

**Comment by rajpersram** [comment]
![Project - Create or Edit.png](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/f6a40448-679c-4d4b-bb40-f1783e7c12dc)

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by rajpersram** [comment]
Taylor reported back that both tech and ops teams require a primary and secondary project manager stated. I've updated the wireframe above to show that.

**Comment by LindsayMacfarlane** [comment]
Tested on January 4 in Dev environment. I can't seem to submit a project. It is saved, but remains in a pending state.

**Comment by pbastia** [comment]
@LindsayMacfarlane we were missing some development data initialization that would prevent you from selecting mandatory field. You should be able to submit a project (I just saw that even though the project manager says optional, it is still required)

There is no validation enforced, just that all the fields are set

**Comment by LindsayMacfarlane** [comment]
Sweet! I works great @pbastia!
