### ISSUE TITLE
As an Ops team member, I want to have 'create a new contact' option on the primary contact dropdown itself, so that I can add a contact while creating a project

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#695]
#### Description:

[Wireframe:](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=1972%3A2663)![image.png](https://images.zenhubusercontent.com/6201b10c9827341d8d5cbe9c/3b7c9437-bde3-4009-a9d7-755a6446bf12)

This functionality allows user to select 'create a contact' in the dropdown of the 'primary' or 'secondary' contact field, thus removing the need to have a button outside of the field. It will take the user to the current 'Add new contact' screen and redirect them back to this form once they submit with all the information derived back on the Project view/project contact page 

#### Acceptance Criteria:

Given I am a Project Coordinator
And I am entering project contact details
When I select the contact drop down
Then the drop down contains an option to 'Create a new contact'

Given I am a Project Coordinator
When I select the 'Create a new contact' from the drop down list
Then I am brought to the 'Add new contact' form/screen

Given I am a Project Coordinator
When I have completed entering a new contact 
Then I am brought back to project form so I can continue entering project details
And the contact I created was added to the project

#### Development Checklist:

- [ ] Add '+ Create new contact' to contact list drop down
- [x] Create new contact should always be visible to user so that they don't need to scroll to bottom of list
- [x] If user selects the + Create new contact, then they are redirected to the contact form, and once done entering contact information, are brought back to project creation page
- [ ] Meets the DOD

#### Notes:

-

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by pbastia** [comment]
@suhafa @nanyangpro I have reservations about this design - it would be a complex development item, involving either 
- reverse-engineering or extending the `Autocomplete` control that we use ([this one](https://mui.com/material-ui/react-autocomplete/))
- implementing something different

I'm not 100% sure the benefits of this UI outweigh the amount of work involved. 
Also, what are the UX (discoverability, accessibility) implications of displaying the "+ Create New Contact" button only when the dropdown is extended?

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/695?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @pbastia @Sepehr-Sobhani @mikevespi

**Comment by suhafa** [comment]
[Wireframe updated](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2092%3A2715) on the basis of concern as to the developmental cost of having '+ Create new contact' in the dropdown, as well as its discoverability discussed during Backlog Refinement.
The 'Create new contact' button will appear under the 'Select a contact' dropdown. Once the user creates a new contact and is redirected back to this page, _it will auto-populate the field will all the info_ (name of contact, company name, email etc.) This button will be replicated for all secondary contact drop-downs as well.
![image.png](https://images.zenhubusercontent.com/6201b10c9827341d8d5cbe9c/bb891d4e-c52c-4190-9f74-13cc68fbb9d1)
![image.png](https://images.zenhubusercontent.com/6201b10c9827341d8d5cbe9c/1e587cfa-6e8f-4ab4-8271-7d0f29e2cf79)

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani ! Looks great. Tested in dev by creating a new contact by selecting the 'create new contact' button from creating a new project and editing an existing project.
