### ISSUE TITLE
As a CIF Project Coordinator, I want to be able to add contact information related to a project, so that I know who to contact if I have any questions

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#701]
#### Description:

Updates to existing 'contacts' functionality based on the updated designs from #666. During usability testing with CIF Ops Team, it became clear that the existing design and functionality of the contacts page was not intuitive, not always functional and could use a re-design to help improve usability. 

Wireframe: 
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/76451051-5c69-4a1e-a550-94a852b02a67)

![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/96fe07d1-809b-4aa6-9cb4-42e6616a48e9)

#### Acceptance Criteria:

Given I am a CIF Project Coordinator
When I have selected a contact from the drop down list
Then key contact information is displayed (email, company, position)

#### Development Checklist:

- [x] Display additional contact information under contact drop down (once selected)
- [x] Remove 'show details' button
- [x] Remove 'view contact list' button
- [x] Update secondary contact button design
- [ ] Add search icon for 'select contact'  to indicate searchability of the field
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/701?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @mikevespi @pbastia @Sepehr-Sobhani

**Comment by mikevespi** [comment]
@suhafa should we only display this contact info when the user is filling in the form? Or would we also like it displayed when in "view" mode?

**Comment by LindsayMacfarlane** [comment]
I think seeing it also in view mode would be helpful - that is something I noticed during testing yesterday of the other contact ticket, but would also like @suhafa 's feedback.

**Comment by suhafa** [comment]
@mikevespi yes! That would be a great point of reference even in view mode. Thanks Mike and @LindsayMacfarlane

**Comment by LindsayMacfarlane** [comment]
Thanks @mikevespi ! Meets acceptance criteria.

A couple of observations that can be addressed in a separate ticket(s):
1. I wonder if phone number should also be displayed? Do we have a sense if the Ops team typically communicates via email vs phone?
2. The view display on the submit page - name is displayed under the subheading, while the rest are displayed beside
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/ec86695a-2dc1-4fb8-92e0-c6c7fc46cfba)
FYI @suhafa and @nanyangpro
