### ISSUE TITLE
As a CIF Project Coordinator, I want to be able to track what company a contact relates to, so that I better understand the relationship between company and contact

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#705]
#### Description:

During user research, it was highlighted by CIP Ops team the need to track the company a particular project contact relates too. This update relates to the design updates from #666. 

Wireframe:
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/b5f26ce8-c378-4619-b5a2-cf539dad6d7f)

#### Acceptance Criteria:

Given I am a CIF Project Coordinator
And I am on the New Contact Page
When I am entering contact details
Then I am able to add Company Name

Given I am a CIF Project Coordinator
And I am on the New Contact Page
When I am editing contact details
Then I am able to edit Company Name

#### Development Checklist:

- [x] Add field for Company Name
- [x] Field to be optional
- [ ] Meets the DOD

#### Notes:

-

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by suhafa** [comment]
[Wireframe Link](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2086%3A2706)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/705?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @mikevespi @pbastia @Sepehr-Sobhani

**Comment by dleard** [comment]
@matthieu-foucault @suhafa Is this a free-form input? Or is it a select dropdown populated with the operators that exist in the database?

**Comment by matthieu-foucault** [comment]
It's a free-form input. The contact's company may not be an operator

**Comment by LindsayMacfarlane** [comment]
Awesome! Thank you @mikevespi. Tested by:
1. Updating an existing contact with company name. Confirmed saved, displayed on view page and available in drop down menu displayed in project creation/revision
2. Associating the contact to an existing project
3. Creating a new project using the contact
