### ISSUE TITLE
Test/validate calculations for Budgets, Expenses & Payments

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#706]
#### Describe the task

This ticket has been repurposed to shift the focus from usability testing towards validating the calculations under the forms below using **1. different scenarios from the [Calculations](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EcXm1DnetBZNgFOkakDR_IEBd7l2fVgU8GjCBbrmphe3Hg?e=4ttNws) document** as well as the **2. real data from CIF team's current tracking spreadsheets**.

- Budgets, Expenses & Payments
- Milestone Reports
- Emissions Intensity Reports

#### Acceptance Criteria

- [x] For each scenario, enter the manual data into TEST following the reference document
- [x] Confirm if the auto calculated/populated data is the same as the reference document
- [x] Enter the manual data into TEST following the tracking spreadsheets
- [x] Confirm if the auto calculated/populated data is the same as the tracking spreadsheets
- [x] Document and sync up the findings with the team and create follow-up tickets if necessary

#### Additional context

**Comment by pbastia** [comment]
waiting on #656 to be implemented

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro @suhafa @pbastia - following up on this ticket. The last comment above, indicates that this ticket is blocked by the implementation of ticket #656; however, that ticket is back in the backlog pipeline. During sprint planning, should we pull this ticket back into the backlog and re-prioritize #656 to be completed next sprint? What are your thoughts.

**Comment by nanyangpro** [comment]
Thanks for your question, @LindsayMacfarlane - I'd love to see it. I believe the office hour with Taylor this afternoon will be utilized by Mike to address the remaining questions for #656.

Other features for Budgets, Expenses, & Payments have been tested during our post release observation sessions FYI.

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro - is this ticket still required?

**Comment by nanyangpro** [comment]
Thanks for confirming, @LindsayMacfarlane. - Yes, we haven't conduct any user tests for Budgets, Expenses & Payments in TEST. I'd suggest doing them once the [calculations](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EcXm1DnetBZNgFOkakDR_IEB1RS8r51PTHqH2h4C5L6URw?e=YsKy83) are in place.

**Comment by nanyangpro** [comment]
Updates for @LindsayMacfarlane: 

- 2 different scenarios and a special case have been tested in TEST, referring to the [Calculations](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EcXm1DnetBZNgFOkakDR_IEBd7l2fVgU8GjCBbrmphe3Hg?e=4ttNws) doc
- Real data of a project was provided by CIF has been tested in TEST
- Overall **the implementation is mostly accurate except for the few mistakes/defects identified**. Please see [test outcome details](https://miro.com/app/board/uXjVP1NVDKE=/?moveToWidget=3458764546360062815&cot=14) here.
- Tickets required for corrections will be created by EOD. I'll pin you with the ticket number as soon as it's done. :)
- An observation session has been scheduled with Lindsay to enter real project data. (Being mindful of the holiday and flex day, it's currently scheduled next Thursday in the morning.)

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket is ready for you to review and can be closed with:

- All the [test results, findings, and reasoning for next steps](https://miro.com/app/board/uXjVP1NVDKE=/?moveToWidget=3458764546360062815&cot=14) documented in Miro.
- For the **CIF** app
    - #1472 created
- For the **Budgets, Expenses & Payments** page
    - #1448 created, re-tested, and closed with reasoning in its comments
- For the **Milestone Reports** page
    - #1471 created in Icebox as discussed with you
    - #1480 created as confirmed with Amanda, and labeled as high-priority
- For the **Emissions Intensity Report** page
    - #1442 created, implemented, and currently accepted by PO/Dev
    - #1466 created and closed (will be handled as part of #1437)
    - #1478 created as confirmed with Amanda, and labeled as high-priority

Thank you for attending the observation sessions, your input and notes helped a lot.

**Comment by LindsayMacfarlane** [comment]
Thank you @nanyangpro! It was absolutely fascinating getting to sit in and observe both how the CIF team is entering data into the system and confirming that the calculations worked (or didn't). A lot of really great insight was gathered during these sessions.
