### ISSUE TITLE
As a project coordinator, I want to be able to undo changes on the annual reports page

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#707]
#### Description:

Adding the undo changes button to the annual reports form 

#### Acceptance Criteria:

Given that I am creating or editing a project, and that I have made changes to the annual reports form
When clicking the "undo changes" button
Then all of my changes since the project was last submitted are reverted.

#### Development Checklist:

- [ ] Adding `UndoChangesButton` component to the annual reports form change
- [ ] Meets the DOD

#### Notes:
- Related to #538, which implemented same feature on quarterly reports form

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by LindsayMacfarlane** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/707?planning-poker) with ZenHub @pbastia @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! I have tested by:
1. Creating a new project and adding in annual report information. I used the undo change button to remove all annual report information, then added in 'correct' data. 
2. Updated an existing project - was able to add and then undo annual report info.

Meets acceptance criteria. Thank you!
