### ISSUE TITLE
As a project coordinator, I want to add existing contacts to a project so that I know who to contact for that project

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#71]
#### Description:

As a project coordinator, I want to add existing contacts to a project so that I know who to contact for that project

#### Acceptance Criteria:

Given I am a project coordinator
When I am on the create project view
Then I am able to enter a contact name into a search box and see a list of contacts with that name

Given I am a project coordinator
When I am on the create project view
Then I am able to click on a returned contact search result to associate it to the project

Given I am a project coordinator
When I am on the create project view and have associated contacts
Then I am able to select which contact is the primary contact

#### Development Checklist:
- [x] Contact search input that searches by contact name and returns dropdown list of results
- [x] Clickable search results that associate the contact to the project on click
- [ ] Show list of associated contacts on project view
- [x] Primary contact field that sets the primary contact
- [x] Secondary contacts field that sets any number of associated contacts (the "Add" button should always be visible at the bottom of the list)
- [x] Wireframe completed and linked to ticket
- [x] Meets the DOD

#### Personas:
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

#### Notes: 
Contact fields:
- [ ] Proponent Legal Name
- [ ] Proponent Facility Name
- [ ] Proponent Facility Address
- [ ] Primary Contact Address (street address, province, postal code)
- [ ] Primary Contact Information (first name, last name,  contact position title, email address, phone?) Note - phone is not on tracking spreadsheet.
- [ ] Secondary Contact Information (first name, last name, contact position title, email address)

#### Design

![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/0d2a1b94-e368-4776-98e8-cb8b0b4b9b12)

**Comment by LindsayMacfarlane** [comment]
Will we require a wireframe to support this user story?

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by rajpersram** [comment]
See [ticket 159](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/159) for the wireframe for adding a contact, and[ ticket 69](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/69) for the Project Details view where a contact is assigned to a project.

**Comment by rajpersram** [comment]
![CIF Workflow Co-Design - Admin - Program Settings.jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/475b512b-f2e8-4985-a611-fe4fa03fa95e)

**Comment by rajpersram** [comment]
@matthieu-foucault @LindsayMacfarlane This sounds like two tickets, one for the contacts and another for a facility, where one is related to another. No? I'm thinking we probably don't want both defined on one page. If that is the case, then [159](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/159) has the User Story for adding a contact. Perhaps this ticket should be made more Facility focused.

**Comment by matthieu-foucault** [comment]
By "Facility", do you mean "Project"? Renaming this user story, hopefully that will clear things up

**Comment by rajpersram** [comment]
@matthieu-foucault Yes, right! That was meant to be project, but I was wondering if facilities would be needed eventually.

**Comment by rajpersram** [comment]
![Contacts - list.png](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/3a047b3b-26ef-411c-b5fe-42760063c41f)

![Contacts - Edit.png](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/2144bb45-72d3-4321-b639-2f8a3d1959b6)

Existing contacts are added in the Project page, and set as Primary or Secondary there.

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/71?planning-poker) with ZenHub @AlexZorkin @dleard @pbastia

**Comment by matthieu-foucault** [comment]
@Peirist Would you ever want more that two contacts for a project?

**Comment by LindsayMacfarlane** [comment]
Hi Team, Some feedback from MZ:

- Yes. There is often a primary contact, but there can be multiple secondary/additional contacts. For example, an Operator may have a primary contact for the project, but may want to keep several individuals up-to-date as secondary contacts through communication, etc.  

- Keeping track of how contacts have changed over time is also important for the program area in order to see historical changes over time. Although not part of this ticket, this is something we should consider for edits/change history.

**Comment by matthieu-foucault** [comment]
We will keep track of every project form's history, so that will come with the project amendment feature

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia ! I tested in dev:
- Was able to select a primary contact from the drop down and clear it from the field
- Was able to add and remove multiple secondary contacts

Notes:
- For secondary contact, I can only remove a contact, but not clear it. I wonder if it should have a similar functionality to the primary contact?
-  Was unable to select the 'view contact list'
- Was unable to select the 'show details' related to the primary contact

**Comment by pbastia** [comment]
Yes, these would have to be in other cards, they're related to different views. It might not even be implemented, depending on what the UX design work yields
