### ISSUE TITLE
UX Research and discussions related to project amendments

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#712]
#### Describe the task

To get a better understanding of amendments and how they should be captured in the system.

#### Acceptance Criteria

- [x] Look up past research notes
- [x] Develop research questions
- [x] Confirm learnings and correct misunderstandings with Taylor
- [x] Book meeting to discuss with Ops Team
- [x] Document feedback

#### Additional context

- Propose and validate user stories
- Create design tickets

**Comment by LindsayMacfarlane** [comment]
Hi @suhafa - As discussed at our check-in, I have created a UX research ticket to capture amendments. Please feel free to update the checklist as appropriate.

**Comment by nanyangpro** [comment]
The Ops Team put together this [document in Mural](https://app.mural.co/t/bcparks2575/m/bcparks2575/1651006160601/761d10ec51a1bec9d133c4ebbc690ba9f6912960?sender=u5cbbacc85759c260093d1303
 ) outlining their process for handling amendments. Definitely worth checking during research.

**Comment by suhafa** [comment]
Explore UI to create revision history of 'General Comments'

**Comment by nanyangpro** [comment]
Thanks @suhafa for your comment (relevant to #677, for soft launch) above.

For this ticket, I'm hoping to accomplish discovery/research which can provide us more thorough understanding on amendment processes, and better inform design tickets/decisions for Amendments going forward. Your suggestions are highly appreciated.

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket can be closed as [findings](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2289%3A2663) are summarized in Figma and synced up with the team.

As discussed earlier, associated design tickets will be created based on the validated user stories once I hear back from the Ops team.

**Comment by LindsayMacfarlane** [comment]
Thank you @nanyangpro and @suhafa for your collaboration on revisions/amendments.
