### ISSUE TITLE
Usability testing on existing document management feature

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#713]
#### Describe the task

To review and test existing document management feature with Ops Team to better understand user needs and identify potential improvements to usability and functionality. 

#### Acceptance Criteria

- [x] Review current functionality
- [x] Meet with Dev team to figure out limits of functionality
- [x] Develop agenda for a meeting with Ops team
- [x] Book session with Ops Team members
- [x] Document feedback
- [ ] Create lofi wireframes (optional)

#### Additional context

- A ticket to address UI design still needs to be created
- Relates to ticket #509 - ability to delete an attachment

**Comment by LindsayMacfarlane** [comment]
Hi @suhafa - ticket created based on our conversation today to review and test current document upload functionality. Please feel free to update the ticket as required.

**Comment by suhafa** [comment]
Discovery work completed and [captured in Miro](https://miro.com/app/board/uXjVPWkS6Ec=/).
The Ops team decided that document management makes most sense once the application is proponent facing. For now, it may add extra work to their plate. 

@LindsayMacfarlane this ticket can be closed after your review. Thank you for your support on this ticket!

**Comment by LindsayMacfarlane** [comment]
Thank you so very much @suhafa. Your work on this and everything else has really helped drive the development of this system forward.
