### ISSUE TITLE
Review and iterate dashboard design

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#714]
#### Describe the task

Review the current content and design of the dashboard.

#### Acceptance Criteria

- [x] Review content and design
- [x] Review previous notes to see if there has been feedback
- [x] Talk to Ops Team to get feedback
- [x] Create wireframe based on design updates

#### Additional context

- Relates in part to issue #490

**Comment by LindsayMacfarlane** [comment]
Hi @suhafa - as discussed today, I've created this ticket to review the design of the CIF dashboard. Please feel free to update as needed.

**Comment by LindsayMacfarlane** [comment]
Sprint planning (June 10): Things to consider:
1) Matthieu mentioned including imbedding Metabase queries into the dashboard?
2) Calendar showing upcoming due dates to help with Ops Team planning?

**Comment by suhafa** [comment]
**Suggestions to explore**
- Embedding Metabase questions in the application
- Calendar-view to track upcoming reports

**Comment by suhafa** [comment]
[Wireframe with documentation](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2693%3A2698)

**Comment by suhafa** [comment]
@dleard Thanks Dylan! @LindsayMacfarlane I've created ticket #857 to capture the work done here. We can close this c:

**Comment by LindsayMacfarlane** [comment]
Thank you so much @suhafa!
