### ISSUE TITLE
Design, wireframe and test how to view project revisions

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#715]
#### Describe the task

Ticket #240 addresses the implementation of revisions across a project. However, before implementing, we need to understand how to display changes to a project in a meaningful way that makes sense to the CIF Ops Team.

#### Acceptance Criteria

- [x] Based on current knowledge, design a low-fi wireframe
- [x] Review proposed design with Ops Team
- [x] Iterate on design

#### Additional context

- Related to #240

**Comment by suhafa** [comment]
@dleard gave me a walkthrough CIIP and how revisions are being handled on there. We also went over some Metabase questions - so the utility in having a project revisions page is in being able to view different revisions and compare them in a more user-friendly way. Have a couple of design ideas I would love to explore: 
1) Retaining the table view as shown in previous wireframes (see #240)
2) Exploring the feasibility of having a single project 'revision view' which would be a way to see revisions visually over all

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane & @suhafa - This ticket (Design Revisions) can be closed along with #777 (Design Amendments), with the following user story tickets written up for dev refinement and implementation (see design and prototype links in each ticket): #919, #920, #922, #923, #930.

**Comment by LindsayMacfarlane** [comment]
Thank you so much @nanyangpro and @suhafa - this was such a big complicated task!
