### ISSUE TITLE
As a CIF administrator, I want to set the funding stream once before creating the project, so that I can see customized forms for each funding stream

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#718]
#### Description:

Funding streams will need separate forms, and supporting changing a project's funding stream will be:
- a nightmare programming-wise
- generating inconsistent data in the existing forms

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
Hi @pbastia - to support this ticket, do we require some user research to more clearly identify where IA differs from EP? And then some UI design?

**Comment by pbastia** [comment]
@LindsayMacfarlane  All the research! :D and a double-check with the business area, and a dev discussion on how to make this fit our database schema

**Comment by LindsayMacfarlane** [comment]
@pbastia and @nanyangpro - this ticket seems to be the same as #1075? If so I can merge any details then close/archive this ticket.

**Comment by nanyangpro** [comment]
I think so, yes (unless @pbastia suggest otherwise). Thanks @LindsayMacfarlane!
