### ISSUE TITLE
As a CIF administrator, I want to add all the attachments of a past email to a project

### ISSUE THREAD

**Issue by Sriram-pc** [bcgov/cas-cif#72]
#### Description:
As a CIF administrator, I want to add all the attachments of an *.eml file to a project

#### Acceptance Criteria:
Given
When
Then

#### Development Checklist:
- [ ]
- [ ]
- [x] Wireframe completed and linked to ticket
- [ ] Meets the DOD

#### Personas: 
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)
- [Tech Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by LindsayMacfarlane** [comment]
Will we require a wireframe for this user story? Can we use/leverage the wireframe related to the UI for document upload?

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket
[Program Development Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

[Tech Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by rajpersram** [comment]
The attachments are one in the same as the documents upload. Attaching here and will update if Thursday's presentation with CIF has any different user requirements.

**Comment by rajpersram** [comment]
![CIF Workflow Co-Design - Edit Project - Attachments (1).jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/22b38860-db75-4b33-bfe4-58314d020aae)

**Comment by LindsayMacfarlane** [comment]
Duplicate? This would be the same function as uploading a document.

**Comment by Sriram-pc** [comment]
@LindsayMacfarlane Do we want to close the ticket with a comment that it is duplicate?

**Comment by rajpersram** [comment]
Wireframes for attachments moved to [ticket 73](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/73)
