### ISSUE TITLE
Discovery on IA stream

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#720]
#### Describe the task

We need a better understanding of where and how the Innovator Accelerator (IA) stream differs from the EP stream. We know that IA doesn't have the emissions performance intensity report requirement, but where else does it differ?

#### Acceptance Criteria

- [x] Review previous notes
- [x] Discuss with Ops and Tech team
- [x] Document differences

#### Additional context/notes

- Relates to ticket #718
- Validate with CIF - if a certain funding stream is selected, should customized forms be displayed? If so, how would that look and function?

**Comment by suhafa** [comment]
IA Funding Stream typically only has Advanced Milestone + Project Summary Report Milestone. There may be reporting. Rest of the milestone types don't apply (From[ CIF Usability](https://miro.com/app/board/uXjVOB7_kC4=/) Findings)

**Comment by nanyangpro** [comment]
Updated the priority based on Jesse's suggestion from the Aug 4th Sprint Review.

**Comment by nanyangpro** [comment]
FYI @LindsayMacfarlane:

- #1051 was created addressing the envisioned changes on the **Task List**
- #1052 was created addressing the envisioned changes on the **Project Overview** page
- #1053 was created addressing the envisioned changes on the **Budgets, Expenses & Pagements** page
- #1054 was created addressing the envisioned changes on the **Milestone Reports** page
- The latest design for the "Project Summary Report" page has been validated with the whole CIF Ops team and Devin from the Tech Team. Shelby will provide her feedback tmr, once it's received and reflected, I'll create a user story ticket addressing the report page and wrap up this discovery ticket.

Feel free to let me know if you have any further questions regarding IA! :)

**Comment by LindsayMacfarlane** [comment]
Thank you @nanyangpro! This work was very insightful.

**Comment by nanyangpro** [comment]
Additional key learning: On the Project Overview page, not like the "Sector" and "Additional Sector Information", **there's no need for a freeform field for "Project Type"** to enter "Additional Project Type Information".

- Graham: Only 3 of 10 2022 IA projects would fall into the “other” category – and only 1 of 14 2021 IA projects – so it may not be necessary to add in a freeform field.
- Shelby: I’m leaning towards leaving a generic “other” category and not putting a freeform field.
- Hurrian: I’m supportive of an “other” category. Having people enter new categories for individual projects that they don’t feel fall into other types, invites extra complexity.   In future, if one project type emerges as the dominant project type within other, it can be added at that time.
- Devin: An ‘Other’ designation should suffice, and if it is warranted we can add a new category if we decide there is need.

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket can be closed with key [notes](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=4133%3A2888) summarized and synced, [design](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=4165%3A2891) validated, and the following user story tickets created:
- #1051, #1052, #1053, #1054 (see details in the comments above)
- #1061 for the **Project Summary Report** page for IA stream projects
- #518 re-purposed for the necessary mapping work (important, will work on it next sprint)

Thanks for you kind support as always. :)

**Comment by LindsayMacfarlane** [comment]
Thank you so much @nanyangpro !
