### ISSUE TITLE
Entering a due date also sets received date [7]

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-cif#721]
Describe the Bug:
When selecting a due date in the annual, quarterly or milestone reports, it also sets the received date to your selection. Selecting a received date however does not change the due date.

Probability (how likely the bug is to happen, scored from 1-5):5

Effect (how bad the bug is when it does happen, scored from 1-5):2 (possibly higher if they don't notice it happened)

Steps to reproduce the behaviour:
- Add a quarterly, annual, or milestone report to a project revision.
- Set &/or change the due date
- The received date will change as well

Screenshots:
![due-received-bug.gif](https://images.zenhubusercontent.com/61e5e470defe5556ba3d89b5/a1d13920-bf76-4c04-95bb-1b631accf29e)

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani ! Tested in dev by:
1) creating a new project
2) Updating an existing project

While creating or updating a project, the received date is no longer auto-populated based on the due date.
