### ISSUE TITLE
Refactor/create Report Due Indicator function

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#724]
This will eventually need refactoring in a separate function, so that is displays a number of months/years when appropriate

_Originally posted by @matthieu-foucault in https://github.com/bcgov/cas-cif/pull/719#discussion_r893711134_

**Comment by gurjmatharu** [comment]
@BCerki is this still applicable?  Seems like you already wrote it as a function?

**Comment by BCerki** [comment]
Yes, I think this is done

**Comment by gurjmatharu** [comment]
@LindsayMacfarlane closing as this one has already been done.
