### ISSUE TITLE
When editing milestone amount, form defaults to n/a and clears existing number if radio button clicked [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#738]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
Edit a milestone report that has an amount entered. The radio button will default to not applicable:
![Screenshot from 2022-06-14 13-50-14](https://user-images.githubusercontent.com/77306764/173686743-eefb4bc2-b4f2-496f-a2bb-fe178b5f16e7.png)
And if you change it to "enter amount", the previously entered amount is cleared:
![Screenshot from 2022-06-14 13-50-21](https://user-images.githubusercontent.com/77306764/173686798-3276bb05-03c2-4f2e-bec0-07df20d62405.png)

Screenshots:
see above

Additional information:

**Comment by dleard** [comment]
This is expected behaviour. If the value is not applicable it needs to be removed from the form_change data, otherwise it will be populated to the table data on commit..
