### ISSUE TITLE
As a CIF user, I want to upload a document to a project, so that I can easily see all relevant files related to a project

### ISSUE THREAD

**Issue by Sriram-pc** [bcgov/cas-cif#74]
#### Description
As a project coordinator, I want to upload a document to a project, so that I can easily see all relevant files related to a project.

#### Acceptance Criteria:

Given I am a CIF user
When I create or edit a project
Then I can upload multiple documents as attachments

~Given I am a CIF user~
~When I upload a document~
~Then I can set metadata properties: Title, description, project phase, received_at~

Given I am a CIF user
When I upload a document
Then my user and date/time of upload are recorded

#### Development Checklist:
- [x] Include file name
- [x] Wireframe completed and linked to ticket
- [x] Meets DOD

#### Personas:
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)
- [Tech Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

#### Notes:
- Title and Description: Can we extract appendices description from RFP form?

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket
[Program Development Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

[Tech Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by pbastia** [comment]
> (extract type from .eml?)
I think the eml parsing should be a separate card

**Comment by rajpersram** [comment]
[See ticket 72](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/72) for the wireframe associated with attachments.

**Comment by rajpersram** [comment]
Workflow for a single attachment:

Attachment List with 'Add New Attachment' button
![Project - Attachments.png](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/468d130a-e772-4553-be8d-9f8ea3de5a0f)

Upload view:
![Project - Attachments - Upload.png](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/88a1b125-e85a-4948-a227-55f31d222762)

Detail of a Single Attachment:
![Project - Attachments - Individual Detail.png](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/132541e8-ef85-47ee-a6c2-3cc7f86f5524)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/74?planning-poker) with ZenHub @AlexZorkin @dleard @pbastia

**Comment by pbastia** [comment]
@LindsayMacfarlane  @matthieu-foucault reducing the scope of this card, we'll limit the current document work to just a file (no metadata)

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia ! Closing this ticket and will test with #483, which will implement on dev.
