### ISSUE TITLE
Date Widget

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#748]
#### Describe the task

We have some complex date widgets (`DueDateWidget`, `ReceivedDateWidget`), but for simple date widget we're still using the rjsf default.

#### Acceptance Criteria

- [x] Date inputs use a simple date widget that uses `react-datepicker`

#### Additional context

- This should remove some spurious happo diffs

**Comment by LindsayMacfarlane** [comment]
Hi @matthieu-foucault - what's the priority on completing this task?

**Comment by matthieu-foucault** [comment]
We probably want to do this for our first release, the default widget doesn't look great

**Comment by LindsayMacfarlane** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/748?planning-poker) with ZenHub @dleard @matthieu-foucault @Sepehr-Sobhani @gurjmatharu

**Comment by matthieu-foucault** [comment]
This is potentially fixable with #721

**Comment by LindsayMacfarlane** [comment]
Anything specific I should be testing in relation to this ticket?

**Comment by Sepehr-Sobhani** [comment]
@LindsayMacfarlane This card and card [721](https://github.com/bcgov/cas-cif/issues/721) are somehow linked. We have replaced `ReceivedDatewidget` with a simple `DateWidget` to keep Date widgets more consistent. If card 721 is OK so this card is fine too 😃
