### ISSUE TITLE
As a Project Coordinator, I want to see a list of the uploaded files for a project so that I can easily see all relevant documentation

### ISSUE THREAD

**Issue by Sriram-pc** [bcgov/cas-cif#75]
#### Description:
As a Project Coordinator, I want to see a list of the uploaded files for a project so that I can easily see all relevant documentation

#### Acceptance Criteria:
Given I am a CIF user
When I view a project
Then I can see a list of all the attachments

Given I am a CIF user
When I list the attachments from a project
Then I can access the details of each attachment: title, description, project phase

Given I am a CIF user
When I list the attachments from a project
Then I can access metadata for each attachment: submission date & time, user, attachment category, file size

#### Development Checklist: 
- [x] Attachments table has the following columns
  - [x] Title
  - [x] Description
  - [x] Date and time submitted
  - [ ] Project state
- [x] Attachments table can be paginated, filtered and ordered
- [x] Wireframe completed and linked to this ticket
- [x] Meets the DOD

#### Personas:
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

#### Design:

![image.png](https://images.zenhubusercontent.com/575f1a78bf93871ccd9c8bcd/4a64328d-932b-49de-981d-22da627f4e11)

**Comment by LindsayMacfarlane** [comment]
Do we need a UX Design ticket to wireframe how this should look to support the development of this ticket?

**Comment by Sriram-pc** [comment]
Tagging @rajpersram

**Comment by Sriram-pc** [comment]
Tagging @rajpersram

**Comment by rajpersram** [comment]
Yes, I think a wireframe is necessary for all the main pages or tabs with co-design sessions needed for most of the busier pages. I don't think this one in particular necessarily needs a co-design with CIF but certainly input from the devs would be great.

**Comment by LindsayMacfarlane** [comment]
Thank you for the clarification @rajpersram . Could you ensure there is a ticket in the backlog for designing the wireframes that support this user story. Depending on capacity and need, this may be something we can start fleshing out in more detail next sprint.

**Comment by rajpersram** [comment]
Set 113 as a prerequisite.

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by rajpersram** [comment]
Do we want to differentiate Uploads from Attachments? Currently a subtab of a project is Attachments and the wireframe for that exists on the Co-Design Miro board.

**Comment by rajpersram** [comment]
[See ticket 72](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/72) for wireframe of the attachments screen.

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/75?planning-poker) with ZenHub @AlexZorkin @dleard @pbastia

**Comment by pbastia** [comment]
the form to upload attachment metadata still needs to be built in #478

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia ! Closing this ticket and will test with #483, which will implement on dev.
