### ISSUE TITLE
off-by-one error in reporting status [7]

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#750]
Describe the Bug:

The screenshot below, made on June 16, displays conflicting information.
The "Received date" input is correct: the report is overdue by one day. 
The other inputs are incorrect

Probability (how likely the bug is to happen, scored from 1-5): 4

Effect (how bad the bug is when it does happen, scored from 1-5): 3

Steps to reproduce the behaviour:

Define a due date on the previous day

Screenshots:

![image](https://user-images.githubusercontent.com/2684022/174190698-eac15766-baa4-48a2-81a0-b4646871d1d9.png)

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! Bug appears fixed, closing ticket.
