### ISSUE TITLE
Investigate if the anchor useEffect is still required in the tasklist

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#751]
This is an older tech debt card, we need to investigate if this is still the case:

NextJS recently fixed a bug that required us to use a combination of a query parameter and a useEffect() to make jumping to specific Milestones work properly. If we update NextJS this workaround should no longer be necessary as the fix has been deployed.

The useEffect() to be removed is here:
https://github.com/bcgov/cas-cif/blob/develop/app/components/Form/ProjectMilestoneReportForm.tsx#L119

The supporting code, where the anchor is added as a query parameter is here:
https://github.com/bcgov/cas-cif/blob/develop/app/pageRoutes.ts#L50

This can be refactored to use a URL fragment instead of adding a query parameter and relying on useEffect() to update accordingly. The update to NextJS should now allow jump link anchors to work as expected.

Notes:

The original NextJs issue is here:
https://github.com/vercel/next.js/issues/11109

The merged fix PR is here:
https://github.com/vercel/next.js/pull/36430

**Comment by tmastrom** [comment]
React seems to be moving away from useEffect where possible [docs](https://react.dev/learn/you-might-not-need-an-effect)

**Comment by pbastia** [comment]
Nothing for the PO to test either @Sepehr-Sobhani. Thank you for your hard work!
