### ISSUE TITLE
Milestone due column shows wrong status [5]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#754]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
Create or edit a project so it has a quarterly report but not a milestone report. Return to the projects view page. The "Milestone Due" status column will show the status of the quarterly report.

The same thing happens with annual reports.

Screenshots:
https://www.loom.com/share/08cd9cbf0f354708a0ba634189cdd028

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! Tested in dev by:
1) Creating a new project with only a quarterly report and no milestone report. The Milestone report displayed 'none' as expected. 

2) Editing an existing milestone - added an annual report to an existing project with no milestone. Milestone due date column in project list displayed as 'none' as expected. 

Did encounter another bug where I couldn't delete a milestone report from a project. I'll create a new bug ticket if one doesn't already exist.
