### ISSUE TITLE
Undoing primary contact change doesn't work [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#757]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
Create a new project (or go to an existing one that doesn't have a primary contact) and add a primary contact. Click undo. The form doesn't clear.
I think the issue is that `rowId` comes back undefined from the query in `ProjectContactForm.tsx` (this is why the jest test works; the mock data does have `rowId`). I think `rowId` is probably missing from a query elsewhere that the contact form relies on.

Screenshots:
https://www.loom.com/share/5f30ea0e3fd04f8ab8ea5c4c2a94b2a7

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by pbastia** [comment]
Closing, appears to be fixed.
