### ISSUE TITLE
Undoing a deleted manager doesn't work [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#758]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
Navigate to a project that has an existing manager. Clear the manager. Click undo changes. The manager doesn't come back.
I think the problem is that `formChange` is `null` when there's no manager selected, so the `rowId` is undefined. The undo changes mutation relies on `rowId` to work.

Screenshots:
https://www.loom.com/share/19b1e742dc24439db459a99330f02525

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by pbastia** [comment]
The solution is likely the same as #757

**Comment by pbastia** [comment]
Closed, appears to be fixed
