### ISSUE TITLE
As a CIF user, I can submit changes to any attribute of a project, with a reason for the change

### ISSUE THREAD

**Issue by Sriram-pc** [bcgov/cas-cif#76]
#### Description:

The `project_revision` table will allow us to draft and record revisions/amendments to a project. Storage of projects history will use a hybrid delta/snapshot approach:
 - A project revision should only contain the delta of records changed, i.e. `form_change` records should only be created for the forms that are updated within a project revision. This will prevent the creation of unnecessary "update" records, and will make summarizing revisions easier (i.e. displaying a list of the entities changed in a revision without showing the details)
 - A project revision's `form_change` records contain a snapshot of each form, facilitating insertion, validation and retrieval with jsonschema-form

Acceptance Criteria:

Given that I am viewing the "view" page for a project
When I click the "Amend Project" button
Then a new project revision is started, and I am redirected to the edit form

Given that I am viewing the "view" page for a project
When a project revision for this project is in progress,
Then 
  a message explaining that a project amendment was started 
  and a "Resume project amendment" button 
  are displayed

Given that I am viewing the "edit" form for a project
When I edit the input for any project attribute
Then the new values are saved as a "pending change"

Given that I am viewing the "edit" form for a project
When I edit the input for any project attribute
Then I can enter a "reason" for the changes

Given that I am viewing the "edit" form for a project
  and I edited the input for any project attribute
When I enter a "reason" for the changes
Then the "Submit" button is enabled

Given that I am viewing the "edit" form for a project
When I click the "Discard Project Amendment" button
Then the project_revision and its changes are deleted

#### Development Checklist:

- [ ] a required "change reason" box on the edit page
- [ ] ~computed columns for project revisions should either return the `form_change` for the current project revision, or the `form_change` for the previous project revision if it does not exist.~
- [ ] ~the forms should use an "upsert" mutation on change, that creates a form_change if it does not exist, and updates it otherwise.~
- [x] when starting a revision, form changes are created based on the current project values
- [x] deletion of records (e.g. contacts) should be handled and tested
- [x] revisions can be resumed
- [x] revisions can be discarded

- Meets the DOD

#### Personas:
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)
- [Tech Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket
[Program Development Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

[Tech Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by rajpersram** [comment]
![CIF Workflow Co-Design - Edit Project - Revision tab.jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/92f72ccd-8603-4fe9-b8e4-7455cb62fb67)

![CIF Workflow Co-Design - Edit Project - Revision tab - Details.jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/ecfbb375-30dd-4509-a905-0a27d3a07ed8)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/76?planning-poker) with ZenHub @AlexZorkin @dleard @pbastia

**Comment by Sriram-pc** [comment]
Copied the attached wireframes to ticket #240.

**Comment by LindsayMacfarlane** [comment]
I think I've tried to test to early. Has this been pushed to dev yet? 

- Operators: I was able to edit and save changes; discard changes
- Contacts: I was able to edit, save changes; discard changes
- Projects: I didn't see an edit button?

Other observations:
- Contacts: when I go to edit a contact, all the pre-populated contact info is removed and all fields are blank. I'm not sure if this is because that was our generated data or if it is a bug? As a user, I might not be updating all fields and would expect the previous information to be displayed until I edited. 
- Contacts: After I made an update, I couldn't find that contact in the contacts table. For example, I updated a contact to have the name as Bob the builder. But I couldn't find that contact using the filter.

**Comment by matthieu-foucault** [comment]
Looks like this deployed after you posted your message. #275 prevented it from deploying automatically.

Operators and Contacts edition was done earlier, so it's not part of this issue.
> Contacts: when I go to edit a contact, all the pre-populated contact info is removed and all fields are blank. I'm not sure if this is because that was our generated data or if it is a bug? As a user, I might not be updating all fields and would expect the previous information to be displayed until I edited.

Yes, this will be fixed in #301. For this reason you won't be able to edit one of the pre-made projects

> Contacts: After I made an update, I couldn't find that contact in the contacts table. For example, I updated a contact to have the name as Bob the builder. But I couldn't find that contact using the filter.

You have to refresh the page for things to update in the table, this will be fixed with #285

**Comment by LindsayMacfarlane** [comment]
Thank you @matthieu-foucault ! Looks great.

Tested in dev:
1. Entered new project, then edited by updating project status, and Tech Team primary project manager. Worked as expected.
2. Edit an existing project (i.e., one that was pre-existing, used project "test project 006), received a 500 error. 


Overall observations:
- As a user, it wasn't clear to me that I was on the 'edit' page after selecting the edit button as the page title remains as "Project Overview". It would be nice to make that more clear in the heading (or some other mechanism)
- The 'reason for change' box/field wasn't present - are we pulling that into a separate issue/ticket?
- order of project managers listed in table and on project overview page don't match order on the create/edit pages for a project

**Comment by LindsayMacfarlane** [comment]
Team provided updated at this mornings stand-up: the system wasn't designed to allow edit on the 'existing data' as it isn't true data. The comments field will be included in another ticket as opposed to this one due to some design questions and it made more sense to include it at that time.
