### ISSUE TITLE
As an Ops Team Member, I want the status of a TEIMP report for a project to be automatically populated, so that I can easily recognize whether a project needs attention or not

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#762]
#### Description:

As part of the emissions performance funding stream, funded agreements need to submit information related to project emission intensity to help show the impact to ghg reductions associated to a project. In order to support project status tracking of the emissions intensity reports, CIF Ops Team members would like to be able to see at a glance when a report is due to help with project management and alert them to when reports are late so that they can follow up with proponents.

Wireframe: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2430%3A2725

#### Acceptance Criteria:

Given I am a CIF administrator
When I am creating, editing or viewing an emissions intensity report
Then the Status of project TEIMP reporting is displayed at the top of the page

Given I am a CIF administrator
When I am creating, editing or viewing an emissions intensity report
Then I can see a badge with the status of the project

Given I am a CIF administrator
When I am creating, editing or viewing an emissions intensity report
And there are late reporting requirements
Then the status is "Late"

Given I am a CIF administrator
When I am creating, editing or viewing an emissions intensity report
And all the reporting requirements have been marked complete
Then the status is "Completed (MM DD YYYY)"

Given I am a CIF administrator
When I am creating, editing or viewing an emissions intensity report
And there are no upcoming reporting requirements
Then the status is "Not due"

Given I am a CIF administrator
When I am creating, editing or viewing an emissions intensity report
And the TEIMP end date has been reached
Then the status is either "Due in xx days" or "Due in xx weeks"

#### Development Checklist:

- [x] Project statuses include the following: Due in XX days, Due in xx weeks, Not due, Late, Completed (MM, DD, YYYY)
- [x] For Not Due - this status is only displayed until the TEIMP End Date is reached. The Report Due date would be 150 days after that. 
- [ ] Checklist item
- [ ] Meets the DOD

#### Notes:

- 

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by suhafa** [comment]
@LindsayMacfarlane - We decided on 'more than 60 days = weeks.' In addition, just for reference 'More than 52 weeks = months'

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/762?planning-poker) with ZenHub @BCerki @matthieu-foucault @mikevespi @Sepehr-Sobhani @pbastia

**Comment by suhafa** [comment]
None - When there is no information on the page (default)
Not due - If the current date is before the TEIMP Start Date
Due in xx weeks/days - When the current date is on or after the TEIMP Start Date
Late - When the current date is after the 'Report Due Date'
Complete (date) - The 'Received Date' is entered

**Comment by Sepehr-Sobhani** [comment]
> * None - When there is no information on the page (**default**)
> * Not due - If the current date is before the **TEIMP Start Date**
> * Due in xx weeks/days - When the current date is on or after the **TEIMP Start Date**
> * Late - When the current date is after the '**Report Due Date**'
> * Complete (date) - The '**Received Date**' is entered

@suhafa two more questions here:

1. What do we display if the report's due date is today?! (`0 day` or `Late`)
2. Is it possible to have no report's due date?! if so what should we display if the TEIMP end date has passed?!

**Comment by suhafa** [comment]
Hi @Sepehr-Sobhani! Thanks for your question - 
1. `0 days`, this is consistent with other statuses
2. For this screen, there is always a due date since a report is always expected if TEIMP start and end dates are inputted. In the edge case where there is no due date, let's leave it at `Not Due`

**Comment by Sepehr-Sobhani** [comment]
> Hi @Sepehr-Sobhani! Thanks for your question -
> 
> 1. `0 days`, this is consistent with other statuses
> 2. For this screen, there is always a due date since a report is always expected if TEIMP start and end dates are inputted. In the edge case where there is no due date, let's leave it at `Not Due`

Thanks @suhafa! 🙌

**Comment by LindsayMacfarlane** [comment]
- [ ] None - When there is no information on the page (default)
- [ ] Not due - If the current date is before the TEIMP Start Date
- [ ] Due in xx weeks/days - When the current date is on or after the TEIMP Start Date
- [ ] Late - When the current date is after the 'Report Due Date'
- [ ] Complete (date) - The 'Received Date' is entered

**Comment by Sepehr-Sobhani** [comment]
Thanks @LindsayMacfarlane.

Based on the AC and what we have here as clarification, the functionality of these badges is as below:
- When the current date is between the measurement start date and end date we would have `Not due`. after that, if we don't have a report due date (an edge case) we keep the same status but if we have the report due date, we will show the `Due in XX` badge. for any reason, if we have the received date, the status would be `Complete (date)` same as we have it in other reports (it's independent of any other dates)

- Also, regarding `Late` status, it is based on the report due date but if the current date is between the measurement start and end date, the status remains as `Not due`. Note that the report due date is 150 days after the measurement end date so I was assuming that we won't have a case where the report due date is passed but the measurement end date is in future.

Please let me know if that's correct or if I need to make some modifications.

**Comment by LindsayMacfarlane** [comment]
Thanks for that clarification @Sepehr-Sobhani! This will be a good one for CIF to test out :)
