### ISSUE TITLE
As an Ops Team Member/Tech Team, I want the TEIMP duration in number of months for a project to be calculated, so that I can use it in calculations of emissions

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#763]
#### Description:

As part of the emissions performance funding stream, funded agreements need to submit information related to project emission intensity to help show the impact to ghg reductions associated to a project. 

Wireframe: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2430%3A3014

#### Acceptance Criteria:

Given I am a CIF administrator
When I am creating, editing or view an emissions intensity report
Then the TEIMP duration is displayed

Given I am a CIF administrator
And I have entered TEIMP Start Date
And I have entered TEIMP End Date
Then the calculated duration is displayed next to the End Date

Given I am a CIF administrator
And I view the TEIMP duration
Then I can see a number of months + days (e.g. 5 months, 18 days)

#### Development Checklist:

- [ ] Duration to be calculated on the client side, by creating a helper function 
- [ ] Luxon's `Duration` object can be used to retrieve the number of days and months
- [ ] Meets the DOD

#### Notes:

- Start date is chosen based on suggestion of proponent; however, Tech team decides how long a reporting period will be (i.e., duration). Start date + duration = end date. 
- Duration unlikely to be less than 6 months

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by LindsayMacfarlane** [comment]
Hi @suhafa - can you review the included acceptance criteria to ensure I accurately captured the requirement? Thanks!

**Comment by suhafa** [comment]
@LindsayMacfarlane Looks good to me Lindsay! (made a very minor change added 'next to the End Date')

**Comment by pbastia** [comment]
Do we need the end date to be constrained to an entire number of months? Or do we display the value as `Duration: 6 months, 12 days` if the start + end date don't make up to an entire number of months? @suhafa

**Comment by suhafa** [comment]
@pbastia month plus days makes sense. The reason we stuck to 6/12 months is because those durations are what we heard the most from the Tech team as a point of reference. Let's go with the months + days for now and we can test out if this makes sense to the team.

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/763?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @mikevespi @Sepehr-Sobhani

**Comment by pbastia** [comment]
That is my understanding too - they set a date for the end of the measurement period and  we give them the total duration as feedback

**Comment by pbastia** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/763?planning-poker) with ZenHub @mikevespi

**Comment by LindsayMacfarlane** [comment]
Thank you @mikevespi. Meets acceptance criteria.
