### ISSUE TITLE
As an ops team member, I want to enter the relevant information on the TEIMP form

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#764]
#### Description:

As part of the emissions performance funding stream, funded agreements need to submit information related to project emission intensity to help show the impact to ghg reductions associated to a project.

Wireframe: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2293%3A2676

This does not include the fields under the **under completion** section, or the **functional unit** field

#### Acceptance Criteria:

Given I am creating or editing a project
When I am looking at the task list
Then step 6 in the task list is for the Emissions Intensity Report

Given I am a CIF administrator
When I am creating, editing, viewing the emissions intensity report
Then there are fields to capture project related dates (TEIMP Start Date, TEIMP End Date, Report Due Date, Report Received Date)

Given I am a CIF administrator
When I am creating, editing, viewing the emissions intensity report
Then I can see information related to general comments 

Given I am a CIF administrator
When I am creating, editing, viewing an emissions intensity report
Then I see data related to emissions intensity, including Baseline Emission Intensity (BEI), Target Emission Intensity (TEI), Post-Project Emission Intensity (PEI) and Total lifetime emissions reductions

#### Development Checklist:

- [x] If a project does not have an emission intensity report, a button on the page allows the user to create it
- [x] An `add_emission_intensity_report_to_revision` function provides a custom mutation
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
@suhafa - based on the wireframe, my assumption is that general comments are mandatory? Is this correct?

**Comment by suhafa** [comment]
@LindsayMacfarlane - Yes! Especially because of the tech team's increased involvement on this report, it will serve as a means of communication internally.

**Comment by matthieu-foucault** [comment]
@suhafa I think that @LindsayMacfarlane 's question was rather "my assumption is that **entering** general comments are mandatory?", instead of whether the feature itself is mandatory. General comments are probably optional (and this should be reflected in the input's label)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/764?planning-poker) with ZenHub @dleard @gurjmatharu @Sepehr-Sobhani

**Comment by pbastia** [comment]
Thanks for the hard work, this was more than anticipated!

we have one field mislabelled (maybe we'll fix it eventually, this is so low-priority #910)
