### ISSUE TITLE
As an Ops Teams Member I want to enter the functional unit of the of the emission intensity and have it auto-populate next to the emissions intensity data so that the tech team can have that information for their calculations

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#765]
#### Description:

As part of the emissions performance funding stream, funded agreements need to submit information related to project emission intensity to help show the impact to ghg reductions associated to a project.

Wireframe:  https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2430%3A3306

#### Acceptance Criteria:

Given I am a CIF administrator
When I am creating, editing or viewing emissions intensity information
Then I see the fields to capture the functional unit (nominator and denominator)

Given I am a CIF administrator
When I am creating, editing or viewing emissions intensity information
Then the numerator is defaulted to tCO2e

Given I am a CIF administrator
When I am creating, editing or viewing emissions intensity information
Then the denominator is defaulted to null

Given I am a CIF administrator
When I am creating or editing emissions intensity information
Then I am able to override default values and input other values

Given I am a CIF administrator
When I am creating, editing or viewing emissions intensity information
Then the functional unit is displayed next to:
      Baseline Emissions Intensity (BEI)
      Target Emission Intensity (TEI)
      Post--Project Emission Intensity (PEI)
      Total lifetime emissions reductions 

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [x] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/765?planning-poker) with ZenHub @dleard @gurjmatharu @mikevespi @Sepehr-Sobhani

**Comment by Sepehr-Sobhani** [comment]
Hey @suhafa / @nanyangpro . Re. displaying functional units on the project summary page and showing diffs, Do you want to display the nominator/denominator next to the number before and after the change or one per field would suffice?!
An example for the second option would be like below:

![Screen Shot 2022-08-08 at 4 46 55 PM](https://user-images.githubusercontent.com/52381975/183533305-94596218-7077-4d64-a4dd-ca8b816e4476.png)

**Comment by LindsayMacfarlane** [comment]
Looks great @Sepehr-Sobhani. 

One observation: I got a validation error on the optional GHG emission intensity performance (adjusted) field
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/ba70cc43-bc4a-4585-b422-d79f5d2b0ba9)

And on the dates. ![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/fd7006b7-5c06-4a74-9384-be552ec5e0db)

At first the dates were left blank, but once I added in dates, I couldn't clear the error message or submit the TEIMP form.

**Comment by Sepehr-Sobhani** [comment]
@LindsayMacfarlane Thanks for noticing that. 
Regarding dates, this is a similar case that we have with other date widgets, so when the user fills it, the error message is still showing up but it doesn't prevent a user from submitting. The issue with GHG emission intensity performance field is causing the report submission to fail.
I'm gonna create some bug cards regarding these issues and some others that I faced during error replication, but my suggestion is to move forward with this feature since these issues are more generic to TEIMP form and not caused by this specific feature.

**Comment by LindsayMacfarlane** [comment]
Thank you for the response and clarification @Sepehr-Sobhani! And for creating the bug tickets ;)

**Comment by Sepehr-Sobhani** [comment]
@LindsayMacfarlane related bugs: #970 , #971 and #972 
Please let me know if anything is missed.
