### ISSUE TITLE
As an Ops Team Member, I want to enter/calculate the TEIMP payment information so that I can track how much of the payment the proponent actually receives

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#767]
#### Description:

As part of the emissions performance funding stream, funded agreements need to submit information related to project emission intensity to help show the impact to ghg reductions associated to a project. 

The calculation for the payment holdback percentage is outlined in Schedule G of the EP Funding Agreement. 

Wireframe: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2430%3A3866

#### Acceptance Criteria:

Given I am a CIF administrator
When I am creating, editing, viewing an emissions intensity report 
and the "GHG Emission Intensity Performance" is defined
Then the calculated 'Payment percentage of performance milestone amount' is displayed.

Given that the "GHG Emission Intensity Performance" is defined
When It is X%
Then the calculated 'Payment percentage of performance milestone amount' is Y%, 
based on the values in the `emission_intensity_payment_percent` table.

Given I am a CIF administrator
When I am creating, editing, viewing an emissions intensity report 
and the 'Payment percentage of performance milestone amount' is defined
Then the calculated 'Holdback Payment Amount' is displayed

Given that the 'Payment percentage of performance milestone amount' is defined
When It is X%, the 
Then the calculated 'Holdback payment amount' is equal to `X% * (gross payment amount to date - net payment amount to date)`

Given I am a CIF administrator
When I am creating or editing an emissions intensity report
And the calculated 'Holdback payment amount' is defined
Then I can adjust the calculated value (i.e. use the widget created in #768)

Given I am a CIF administrator
When I am creating, editing, viewing an emissions intensity report
Then I see fields to capture project the "Date invoice sent to CSNR"

#### Development Checklist:

- [x] A `project_revision_gross_payment_amount` and `project_revision_net_payment_amount` functions are created, to be reused in #717
- [x] A `project_revision_teimp_payment_percentage` function is created
- [x] A `project_revision_teimp_payment_amount` function is created
- [ ] Meets the DOD

#### Notes:

- Note: tooltips will be addressed in a separate user story at a later date.

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by LindsayMacfarlane** [comment]
@suhafa - can you confirm, is this user story only covering the calculated holdback payment amount? Or is it covering the 3 highlighted fields in the wireframe?

**Comment by matthieu-foucault** [comment]
This should be for all three highlighted fields. The title could be improved to make that clear

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/767?planning-poker) with ZenHub @dleard @gurjmatharu @Sepehr-Sobhani @mikevespi

**Comment by pbastia** [comment]
The calculation methods for the sum of gross and net payment amounts will need to be revisited when we get clarification from the business area. (cf #853)
The calculated value for the gross or net payment should be taken in account, in case the overridden value has not been set

**Comment by LindsayMacfarlane** [comment]
Hi @pbastia - thanks for all your work on this one. One observation: I couldn't get the calculated holdback payment amount to calculate. Not sure what I'm doing wrong.
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/7f8c228d-b90d-458f-be25-73a568149216)

**Comment by pbastia** [comment]
@LindsayMacfarlane there need to be a payment made to calculate an amount here. To do that, create at least one general milestone and add a non-zero value in the "adjusted net" and "adjusted gross" amounts

**Comment by LindsayMacfarlane** [comment]
Thanks @pbastia I followed your instructions (I think anyways...), but still couldn't get it populated. Although for clarification - I didn't see an 'adjusted net' or 'adjusted gross' - just the regular net/gross payment fields.

**Comment by LindsayMacfarlane** [comment]
I'm going to approve this ticket, but I still have issues getting anything to display in the holdback. I 100% believe this is on user error, but we should definitely have the CIF team test this one out.

**Comment by LindsayMacfarlane** [comment]
Thank you @dleard for showing me that this does in fact work :)
