### ISSUE TITLE
Reusing helper functions in `DueDateWidget` and `ReceivedDateWidget`

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#773]
###Description of the Tech Debt###
Based on [this comment](https://github.com/bcgov/cas-cif/pull/770#pullrequestreview-1015883946) we need to reuse helper functions from `reportStatusHelpers.tsx` in `DueDateWidget` and `ReceivedDateWidget` to ensure consistent behaviour across the application 

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |   Low    |   1    |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |    Low   |    1   |
| System Fault Risk - Risk of system errors or application downtime                                                             |   Low    |    1   |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |   Low    |    1   |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |    Low   |    1   |
| TOTAL SCORE:                                                                                                                  |       |   5    |

**Comment by LindsayMacfarlane** [comment]
I don't believe there is anything I need to test on this one - correct me if I'm mistaken.

Thank you for your work on this one @gurjmatharu!
