### ISSUE TITLE
Discovery and design for additional data fields

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#775]
#### Describe the task

Additional data fields are suggested. Designs are needed for them.
- Proponent Cost
- Project Type
- Additional Funding Amount (and source)
- Provincial Share (per FY)
- Rank

Other fields suggested but can be handled through Metabase. _(Upon further confirmation during the Metabase walkthrough session)_
- Total Project Cost per Tonne
- BC Expenditures %
- Canada Expenditures %
- Facility Location (in Maps coordinates)
- Annual Facility Emissions
- Emission Reductions by year
- Total Emission Reductions in 2030

#### Acceptance Criteria

- [x] Propose and validate user stories
- [x] Create wireframes to visualize design
- [x] Review and validate design with devs
- [x] Review and validate design with CIF

#### Additional context

Definition of Ready
Note: If any of the points are not applicable: delete or mark N/A

- [x] Discovery work or findings are linked.

Definition of Done
Note: If any of the points are not applicable: delete or mark N/A

- [x] Proposed user stories validated by the users.
- [x] Proposed user stories validated by internal team.
- [x] Validated user stories addressed visually in the wireframe.
- [x] Follow-up tickets created if necessary.
- [x] Wireframe is created.
- [x] Design (link to wireframe/prototype) handed off to dev in associated tickets.

**Comment by LindsayMacfarlane** [comment]
Thank you so much @nanyangpro!
