### ISSUE TITLE
Design for Amendments

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#777]
#### Describe the task

From discovery on Amendments, key features were identified with draft user stories proposed and validated by CIF Ops:

- **Existing/Planned** -  As an Ops Team Member, I want to add a comment when making a change, so that I can track more details for a change.
- **Existing/Planned** - As an Ops Team Member, I want to view a change log, so that I can track who/when/what/why for a past change.
- **Planned** - As an Ops Team Member, I want to view a holistic change log, so that I can track and filter who/when/what/why for all past changes.
- **1** - As an Ops Team Member, I want to indicate (select between “Revision” and) “Amendment” when making a change, so that I can filter by the type when viewing the holistic change log.
- **2** - As an Ops Team Member, I want to log a pending Amendment, so that I can track more details (status, who is working on it, etc.) for it.
- **3** - As an Ops Team Member, I want to alert other user groups on action items for a pending Amendment.
- **4** - As an Ops Team Member, I want to have attachments linked to an Amendment (pending/settled), so that I can track associated documents for it.

#### Acceptance Criteria

- [x] Create wireframes based on the key features identified above
- [x] Break down / group user stories if necessary
- [x] Review design with devs
- [x] Review design with CIF
- [x] Iterate on design if necessary
- [x] Create tickets with links to design for implementation

#### Additional context

- Add any other context about the task here.

Definition of Ready
Note: If any of the points are not applicable: delete or mark N/A

- [x] Discovery work or findings are linked.

Definition of Done
Note: If any of the points are not applicable: delete or mark N/A

- [x] Proposed user stories validated by the users.
- [x] Proposed user stories validated by internal team.
- [x] Validated user stories addressed visually in the wireframe.
- [x] Follow-up tickets created if necessary.
- [x] Wireframe is created.
- [x] Design (link to wireframe/prototype) handed off to dev in associated tickets.

**Comment by nanyangpro** [comment]
Related to #715

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane & @suhafa - This ticket (Design Amendments) can be closed along with #715 (Design Revisions), with the following user story tickets written up for dev refinement and implementation (see design and prototype links in each ticket): #919, #920, #922, #923, #930.

**Comment by LindsayMacfarlane** [comment]
Thank you so much @nanyangpro and @suhafa - this was such a big complicated task! Thank you Nan for taking so much time to walk me through everything and answer all my questions/concerns. This was a great feature to see how design, devs and stakeholders collaborate in order to create a feature that is technically sound and meets user needs.
