### ISSUE TITLE
Architecture Prototyping

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#78]
Team to get together and design an initial data model for the CIF app.

#### Output: 
- initial architecture prototyping and how it will be represented in the database
- initial data model to be implemented, UML-like diagram

#### Notes:
- Don't need to worry about which frameworks we use to implement things

**Comment by LindsayMacfarlane** [comment]
Sprint Planning (November 12, 2021): Considering ticket complete as initial design completed and reviewed with IITD Data Architect for feedback.
