### ISSUE TITLE
Cannot add Milestone to project with existing Milestone [7]

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-cif#780]
Describe the Bug:

Adding a milestone to a project with a completed milestone throws the following error:
`Cannot return null for non-nullable field ReportingRequirement.reportingRequirementIndex.
       reportingRequirementIndex`.

Probability (how likely the bug is to happen, scored from 1-5): 4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3/4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- Start a project revision for a project with an existing milestone.
- Try to add a milestone to the project.

Screenshots:
![create-milestone-error.gif](https://images.zenhubusercontent.com/61e5e470defe5556ba3d89b5/73790eca-cd9d-4515-8fe1-ae69bdd33895)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki ! I can now add multiple milestone reports to a project if there was a pre-existing report.
