### ISSUE TITLE
Set up feature flagging controls

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#782]
#### Describe the task

As new features will be developed while the application is actively used, feature flagging is necessary to allow us to ship critical fixes to production without being restricted by unfinished features in the `develop` branch.

The CCBC team uses GrowthBook and is happy with it.

#### Acceptance criteria

- [x] A Growthbook account is setup
- [x] The Growthbook API key is added to our 1Password and the `cas-pipeline` repo in a k8s secret
- [x] Growthbook is setup for the CIF front-end
- [ ] A first feature flag, e.g. "TEIMP" is created, and a team meeting is held to demonstrate use of the feature flags
- [ ] Team agreements on the usage of feature flags (including cleanup process) are documented in the CIF Readme

**Comment by LindsayMacfarlane** [comment]
Want this ticket to be addressed asap after first release, but doesn't need to be done as part of first release.
