### ISSUE TITLE
Co-Design Project View and Edit UI Wireframes

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#79]
#### Checklist:
- [x] Decide on sync/async/hybrid approach to co-design of wireframes with CIF staff
- [x] Identify specific areas that make sense to do a co-design approach
- [x] Identify CIF team members who we'd like to participate
- [x] Plan co-design session(s)
- [x] Hold session(s)
- [x] Review results of co-design session(s) and draft 'final' presentation
- [x] Present final wireframe idea to CIF team for usability testing/comments

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - we forgot to review and pull into this sprint. Is this something we should refine and pull in together?

**Comment by jaimiebutton** [comment]
Yes, good call! Something we can discuss in our meeting today.

**Comment by rajpersram** [comment]
Co-Design Miro board located https://miro.com/app/board/o9J_lkk44vo=/. Further sessions on those user stories can happen async

**Comment by rajpersram** [comment]
Fri, Nov 12: Presented ideas of wireframes to CIF and GGIRCS team, narrowing down the most important items needed for MVP. Wireframe final captured in ticket 63.

**Comment by LindsayMacfarlane** [comment]
Thank you @rajpersram - I really enjoyed the co-design sessions we had both as an internal team and with our CIF colleagues. I look forward to more designs.
