### ISSUE TITLE
Bug: if BC Reg ID isn't given, dropdown shows (null) [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#793]
Describe the Bug:

Not 100% sure this is a bug, but I think I'd find `null` confusing if I was a user

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in Dev (OR start the app with `yarn dev --as-role CIF_ADMIN` abd clean db (`make drop_db && make deploy_db_migrations`))
- create an operator without a registry ID or code
- add a project and select the operator. The dropdown will show the name and `(null)` in parenthesis

Screenshots:
![Screenshot from 2022-06-30 11-22-27.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/84aab7b3-684e-4b33-859f-1fb125b63c4d)
![Screenshot from 2022-06-30 11-18-40.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/19719691-9da1-47c0-a90f-a2e487386ee3)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by mikevespi** [comment]
This was fixed in #870, marking as duplicate
