### ISSUE TITLE
Bug: project overview form doesn't save when starting app with `--as-role CIF_ADMIN` [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#794]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 1
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- start the server with `yarn dev --as-role CIF_ADMIN`
- clean db (`make drop_db && make deploy_db_migrations`)
- create an operator
- click "add a project" button from the projects list page
- fill out the fields (bug seemed to happen no matter which ones/how many I filled out)
- note that it says "changes saved" at the top
- navigate away
- return to the projects list
- instead of the "resume editing" button, you'll see "add a project", and if you click that, everything you filled out is gone
- even if you hit "submit" on the overview page, the form doesn't save. It only seems to save if you submit the entire project.

Screenshots:
https://www.loom.com/share/6efa6051ddfb4c3aac181737eb0a2941

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by pbastia** [comment]
This is most likely because the `sub` is null for a mock user, and the "create project revision" scopes it to the current user to make sure we only create one pending revision per user.

**Comment by pbastia** [comment]
@LindsayMacfarlane this might be a good one to tackle ahead of the keycloak gold migration, since test username / password won't be available anymore

**Comment by LindsayMacfarlane** [comment]
Thanks for flagging @pbastia - feel free to pull into this sprint if there is capacity or we can bring into next sprint.

**Comment by mikevespi** [comment]
I am unable to reproduce this, awaiting confirmation that it doesn't happen for anyone anymore before closing.

**Comment by BCerki** [comment]
Confirmed I can't reproduce it anymore either

**Comment by mikevespi** [comment]
Closing this issue as the bug no longer seems to exist.
