### ISSUE TITLE
Spacing on project summary page [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#798]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in Dev
- create a project
- arrive at the project summary page
- there's a gap between total funding request and project status
- also inconsistent spacing between contact info blocks and report info blocks

Screenshots:
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/a1f4b8d6-0535-4cfb-a4a3-aa861e73af11)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
Still a bug Nov 16, 2022

**Comment by Sepehr-Sobhani** [comment]
This has been merged but not deployed to dev yet!

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani ! Looks great and there are no more awkward spaces :)
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/dd44fa9f-e087-4bbb-8495-0fc2e3c9203f)
