### ISSUE TITLE
Filtering project list by manager throws error [5]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#799]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in Dev
- go the project list page
- click to filter by manager
- receive error

Screenshots:
https://www.loom.com/share/223d094041904c54b17c684add166f5f

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
@BCerki This is addressed by this PR: https://github.com/bcgov/cas-cif/pull/829

**Comment by Sepehr-Sobhani** [comment]
Addressed in #829
