### ISSUE TITLE
Co-Creation of Business Canvas

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#8]
Some questions to answer as we go:

- [x] Decide which canvas ([Business Model Canvas](https://learn.marsdd.com/article/building-blocks-of-the-business-model-canvas/), [Value Canvas](https://miro.com/app/board/o9J_lFm_59I=/?moveToWidget=3074457360946110169&cot=14), hybrid?)
- [x] Decide who will be included
- [x] Coordinate when it will be completed and in what cadence
- [x] Make a plan to refer back to it in the future ([see ticket #33](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/33))

**Comment by jaimiebutton** [comment]
Update: [First draft of Value Canvas](https://miro.com/app/board/o9J_luPsw4E=/?moveToWidget=3074457364826286464&cot=14) was created in the CIF Discovery Workshop.

**Comment by jaimiebutton** [comment]
This ticket will be continued in [Ticket #33](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/33) as a follow-up from the discovery workshop.

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton :)
