### ISSUE TITLE
 As a CIF user, I want to see a landing page after I login, so that I can start completing my tasks

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#80]
#### Description:
Design of the site map

#### Acceptance Criteria:

Given I am a CIF User
And I have entered my IDIR ID and Password
When I select the login button
Then I am brought to a landing page within the CIF application

#### Development Checklist: 
- [x] rough prototype / wireframes for the landing page
- [ ] CIF users see the landing page after they login 
- [ ] Landing page has links to:
  - [ ] The project list page (`/cif/projects`)
  - [ ] The "new project" page, or a page to resume creation of a project
  - [ ] The Operators management page
  - [ ] The Contacts management page
  - [ ] The Request for Projects management page
  - [ ] The Project Status Settings page
- [x] Wireframe completed and linked to ticket
- [ ] Meets the DOD

#### Personas:
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)
- [Tech Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by rajpersram** [comment]
@pbastia To make the sitemap more interesting than just a series of text links, would it be possible to show a React Flow visual sitemap that gets dynamically updated as we build more pages? I was thinking of something like https://reactflow.dev/

**Comment by matthieu-foucault** [comment]
I think there was some miscommunication regarding the site map. I don't see a need to display it to the users, at least not for MVP, but the team (dev and design) do need to discuss it prior to building pages, to set conventions now and avoid unnecessary refactoring down the line. As for the landing page design, I don't think it there is high value at the moment in coming up with anything other than links, organized into cards/sections. There are more crucial items out there, e.g. regarding project attachments management.

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket
[Program Development Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

[Tech Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/Ec2AmUecYCdDlmURctGwTbMBUMGZXlUyyt5HQZJdpjeejA?e=0axXlm)

**Comment by rajpersram** [comment]
Version 1 of the Landing Page / Dashboard
![CIF Workflow Co-Design - Landing Page - v1 - Simple Links.jpg](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/53ce9c7d-793b-4711-a64d-97b8a8e54af9)

**Comment by matthieu-foucault** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/80?planning-poker) with ZenHub @AlexZorkin @dleard @pbastia

**Comment by LindsayMacfarlane** [comment]
@matthieu-foucault - it is so nice and simple! This is awesome.
