### ISSUE TITLE
When adding project, tasklist milestone section says "Edit" [5]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#800]
Describe the Bug:

Not sure this is a bug--this case isn't shown in figma: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=1061%3A2689

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in dev
- add a project
- navigate to milestones
- note in the tasklist that it says "edit" while everywhere else says "add"

Screenshots:
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/50171f78-ba4a-43ee-ab75-568e1cdaefc1)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
@suhafa, is this a bug or are milestones supposed to say "edit" when adding a project?

**Comment by suhafa** [comment]
Good find! I think it makes sense to leave it at Edit because its already been 'added' and unlike other reports, each milestone shows up in the task list. 'Attention required' status takes care of its need to be filled. So no, wouldn't consider this a bug.

**Comment by dleard** [comment]
This was done on purpose for the reasons @suhafa described above. Since the Milestone in this case has already been 'added', it made more sense to me to have it read 'Edit'.
