### ISSUE TITLE
Summary page shows validation errors for milestones [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#804]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in dev
- create a project
- add a milestone but don't fill out the form
- go to project summary page
- it shows validation errors instead of showing "not added" for blank fields

Screenshots:
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/b9feaa20-ca25-4862-b07b-5eebfa77b9fa)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
tested on Nov 30, 2022 and couldn't reproduce it.
