### ISSUE TITLE
Project status shows as undefined on summary page [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#805]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in dev
- create a project and don't fill in project status on the overview page
- go to the summary page
- the field says "undefined" instead of "not added"

Screenshots:
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/583580f7-f2e1-4055-ba79-1e1a65cbe407)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
Still a bug Nov 16, 2022

**Comment by pbastia** [comment]
Works as intended! Thanks for the hard work @Sepehr-Sobhani !
