### ISSUE TITLE
Add sysdig alerts for CIF Prod 

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#807]
We need some sysdig alerts set up for our production CIF namespace. We already have some sysdig alerts set up for our other namespaces, and these can easily be copied over for CIF using the sysdig UI.

High priority alerts:
- No app pods running
- Single app pod running
- Storage space usage high
- CPU usage high

#### Checklist 
- Set up alerts
- Onboard new team members to sysdig
- Update mailing list for sysdig

We shouldn't have to use the persistent storage team & can just use the basic team. I think Platform Services removed the need for splitting out storage monitoring into a separate team a little while ago.

**Comment by LindsayMacfarlane** [comment]
Note: Once this ticket is complete EPIC#238 can be closed.

**Comment by dleard** [comment]
Also added alerts for no pgbouncer pods running, no database pods running and some checks that the metrics we are relying on are actually returning data.
