### ISSUE TITLE
Contacts project view page shows validation error [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#808]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in dev
- find an existing project without a primary contact
- view the contacts form
- see error

Screenshots:
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/8706fda1-1f1a-4bca-b1be-106da371ea62)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by pbastia** [comment]
Could not reproduce, it's fixed!
