### ISSUE TITLE
Wrong information on annual report summary page [5]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#810]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in dev
- go to a project
- see that the text says always says "not updated" instead either "No Annual Reports" or the reports' summary

AND
- create an empty project and go the review page
- there's no text under the Annual Reports section

Screenshots:
https://www.loom.com/share/dde9d8c11d8e43d28a9b02fe9903dccb?focus_title=1&muted=1&from_recorder=1
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/cf5be991-79cd-4bdc-ae1b-c3dafbf8b099)
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/21445bd3-fbbb-44c1-8316-25972d441252)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by pbastia** [comment]
Nice work!
