### ISSUE TITLE
Review CIF icebox items

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#811]
#### Describe the task

Review CIF tickets that are in the icebox or labelled medium and low priority to determine what needs to be implemented and their priorities. 

#### Acceptance Criteria

- [ ] book meeting for SF, NY, LM to review
- [x] book meeting with CIF team
- [x] create Miro board template for discussion
- [x] review tickets
- [x] refine tickets if required

**Comment by LindsayMacfarlane** [comment]
Added feedback and reprioritized tickets based on session with CIF team. @nanyangpro - feel free to go in and add anything if I missed any details.

**Comment by nanyangpro** [comment]
Thanks @LindsayMacfarlane! I love the session you facilitated and the collaborative effort with CIF from it.
I have reviewed all your comments in the associated tickets, look great, thank you!
