### ISSUE TITLE
As a user, I want to upload a document to cloud storage, attach it to a project and specify document versions

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#82]
#### Description:
How do we upload documents to cloud storage, attach those documents to a project, and define a version history of documents?

#### Development Checklist:
- [ ] Figure out the entire skeleton that supports the above user story
- [ ] How do we define storage?
- [ ] How do we define versioning of documents?
- [ ] Set up developers meeting/discussion
- [ ] Identify pros/cons, investigate available solutions, document what was investigated and why a certain decision was made (document in the repo)
- [ ] Meets the DOD

#### Notes:
- This is code skeleton that we can iterate on
- Code that we keep
- Look at document storage that was created for the WALLY app / GWELLS

**Comment by LindsayMacfarlane** [comment]
Hi @AlexZorkin! I tested in Dev:

- select link 'attachments'
- select button 'upload'
- file browser opened and I was able to select documents (tried a jpg and PDF). However, nothing happened after this. Should I be able to see a list of uploaded files?

**Comment by LindsayMacfarlane** [comment]
Hi @AlexZorkin ! Following up on this ticket. I'm still experiencing the same issue, where I upload a document, but then nothing happens.

**Comment by rajpersram** [comment]
@matthieu-foucault Is the ticket title accurate because it reads like attachments would first be uploaded and then associated with a project, but my understanding is a project would first be created and then attachments upload to it. Thoughts?
