### ISSUE TITLE
Milestone overall status doesn't update

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#821]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:
https://www.loom.com/share/138499759f424805908724e687d6fb8e

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by pbastia** [comment]
@BCerki this seems to be the same as #825?

**Comment by BCerki** [comment]
@pbastia, yes, duplicate

**Comment by pbastia** [comment]
Thank you! Closing
