### ISSUE TITLE
Can't delete report received dates [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#826]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in dev
- edit an existing project with a completed milestone
- delete the received date
- try to submit the form
- receive error
- also a problem for quarterly and annual reports
- incorrect status badge and report indicator bug is in another ticket

Screenshots:
https://www.loom.com/share/aab98d33fb32456681ec6d778b475f61
![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/ebf51fb0-9ae5-47bc-8100-483489df9aa2)![image.png](https://images.zenhubusercontent.com/61b280604648aa38cf25994f/215f18c2-3ec4-4e39-a4ba-1ca779ee5d33)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by pbastia** [comment]
Thank you @mikevespi !
