### ISSUE TITLE
DevOps architecture diagram

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#835]
#### Describe the task

Create a detailed DevOps architecture diagram. 

#### Deliverable
- [x] a Miro board with the diagram
- [ ] links to DevOps documentation in GitHub about the different tools and automated processes that the team uses

**Comment by pbastia** [comment]
our "GGIRCS Deployments architecture diagram" could be expanded to reflect the CIF app and its dependencies

**Comment by pbastia** [comment]
Audience: internal, and sharing with anyone interested by the technical side

**Comment by matthieu-foucault** [comment]
The Miro board containing the previous diagrams can be found here: https://miro.com/app/board/o9J_kjtHnq8=/?share_link_id=933124605694

**Comment by pbastia** [comment]
We have a miro board that we can use as a base for this

**Comment by LindsayMacfarlane** [comment]
This is a beautiful diagram. I'd love someone to walk me through it.
