### ISSUE TITLE
Unable to delete a milestone [2]

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#836]
#### Describe the Bug:

This appears to be a dev-data issue only.

Probability (how likely the bug is to happen, scored from 1-5): 1
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

#### Steps to reproduce the behaviour:
1. Select an existing project
2. Go to milestone report and select edit button
3. Try to delete the milestone report by selecting the 'remove' button
4. Get error message "An error occurred when deleting"

#### Screenshots:
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/b62507fe-791f-466a-9aca-c6302dfc4706)

#### Additional information:

- Browser: Chrome
- Version: [e.g. 22]
- Additional context

**Comment by dleard** [comment]
I'm fairly certain this is a dev data issue. I tested the 'remove' button for a project that was created by our dev data and the error occurred. When I created a project with a milestone from scratch, submitted it, created a new revision and removed the milestone in the subsequent revision, no error occurred.

**Comment by mikevespi** [comment]
Cannot reproduce. Milestones have since undergone a significant refactor, and the bug has been fixed even with dev data.
