### ISSUE TITLE
Dev data is not adding contacts to projects

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#838]
create_project() used to create a primary project_contact form_change record by default, but we made that section optional and don't create contacts and managers on project creation anymore (I can't find the exact commit that removed it, but I feel like it was quite a while ago) . So [this](https://github.com/bcgov/cas-cif/blob/develop/schema/data/dev/004_cif_project.sql#L40) update statement does nothing because we have no form_change records for the project_contact table to update. We have not really been missing that data as it took us a long time to figure out that there were no contacts attached to projects in the dev data.

Option 1: Remove the update statement that does nothing. Projects in dev will not have contacts attached by default.

Option 2: Replace the update statement with an insert to create `project_contact` form change records. Projects in dev will then have contacts attached.

**Comment by LindsayMacfarlane** [comment]
Nothing for me to test on this one. Thank you @gurjmatharu for your work on this tech debt issue.
