### ISSUE TITLE
Undoing a primary contact doesn't work the first time [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#839]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- navigate to an existing project with no contacts
- add a primary contact
- click undo
- nothing will undo
- but if you clear the contact and then try again, it will undo

Screenshots:
https://www.loom.com/share/64a1d9d1a89a46c7bda198fcf8c47618

Additional information:
- there's a cypress test for undoing contacts but it's commented out

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by dleard** [comment]
Nice job, works as expected
