### ISSUE TITLE
As a CIF Ops user, I want the 'Summary' field renamed to 'Project Description' so that I can enter the correct information

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#844]
#### Describe the task

'Project Description' best captures what the team would like to fill in for this field, as opposed to 'Summary'

![image.png](https://images.zenhubusercontent.com/6201b10c9827341d8d5cbe9c/a84e36c8-3707-49a5-acaf-57b57ac2fd93)

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Development Checklist:
 
- [ ] Checklist item
- [ ]  Checklist item
- [ ]  Checklist item
- [ ]  Meets the DOD

####  Notes:
- Added after observation of CIF team's initial exploration of the app before release.
- Derived from notes in #555

#### Definition of Ready (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ]  User role and type are identified
- [ ]  Acceptance criteria are included
- [ ]  Wireframes are included (if required)
- [ ]  Design / Solution is accepted by Product Owner
- [ ]  Dependencies are identified (technical, business, regulatory/policy)
- [ ]  Story has been estimated (under 13 pts)
- [ ] Definition of Done (Note: If any of these points are not applicable, mark N/A)

####  Acceptance criteria are tested by the CI pipeline
 
- [ ] UI meets accessibility requirements
- [ ]  Configuration changes are documented, documentation and designs are updated
- [ ]  Passes code peer-review
- [ ]  Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ]  Ticket is ready to be merged to main branch
- [ ]  Can be demoed in Sprint Review
- [ ]  Bugs or future work cards are identified and created
- [ ]  Reviewed and approved by Product Owner

**Comment by pbastia** [comment]
Covered by #858
