### ISSUE TITLE
As an Ops team member, I want to have the contact email address as a hyperlink, so that it opens up an email for me directly

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#845]
#### Description:
The user would like to have the email ID in view mode be a clickable link that would open up a new email with the contact address auto-filled. 

Wireframe of the desired outcome:
![image.png](https://images.zenhubusercontent.com/6201b10c9827341d8d5cbe9c/1c303fc0-26f7-428b-9a56-a283c0701d40
)

#### Acceptance Criteria:

Given I am a CIF project manager
When I see the contact email address in project view mode
Then that contact email address is hyperlinked

Given I am a CIF project manager
When I select the email address hyperlink
Then a new email is created in my outlook email addressed to the contact

#### Development Checklist:

- [ ] email - when present - is a `mailto:...` link
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

#### Notes:

- Based on CIF team observation prior to soft launch
- Derived from notes in #555

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/845?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @mikevespi @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Thank you @mikevespi! I tested in Dev by confirmed that email address addresses are hyperlinked and when selected opens up a new email in my outlook on the following pages:
- Contact page
- Edit, project contacts
- Create, project contacts
- Was able to update and save the contact email and have that change applied to the forms.

Meets acceptance criteria. 

Thank you!
