### ISSUE TITLE
Funding Agreement form should be rendered by default (no 'Add' button)

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#847]
The funding agreement form currently has an 'Add Funding Agreement' button. We would like to remove the button and render the form by default instead. The issue is, this form is our only 'flat' form (like project overview) that has required inputs, but where the form itself cannot be required (projects may not have a funding agreement when created, or ever if not funded). This creates a question of when to create the form_change record. We can't create it on project creation (like we do for the overview), since that would block submission of projects that do not have a funding agreement.

**Comment by pbastia** [comment]
This will only be a rework of the user control, with either different wording or a slightly different control. Design to be solidified by @suhafa @nanyangpro

**Comment by nanyangpro** [comment]
Just for the record, @gurjmatharu - We agreed to introduce "Is this a funded project? Y/N" in the last discussion with the team. :)

**Comment by nanyangpro** [comment]
Hi @gurjmatharu, @pbastia - please see the [design](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?page-id=2655%3A2669&node-id=3426%3A2678&viewport=-1133%2C1340%2C0.2&scaling=contain&starting-point-node-id=3426%3A2678&show-proto-sidebar=1) here.

**Comment by nanyangpro** [comment]
As requested, @gurjmatharu - Here's the [latest design for the Budgets, Expenses & Payments form](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2898%3A2863).

**Comment by LindsayMacfarlane** [comment]
Thank you @gurjmatharu!

Tested in Dev by creating a new project and editing an existing project. Radio buttons function as expected and if I change between Yes/No I get an appropriate warning message.

Thanks for your work on this one :)
