### ISSUE TITLE
No "Attention Required" message on the "Project overview" form when submitting a new project without project overview data [6]

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#848]
Describe the Bug:

When creating a new project, and adding any data except for "Project Overview" (including no data at all),
and then submitting the project, the user faces a non-descriptive error message instead of being directed to the "Project Overview" form with the "Attention required" status

Probability (how likely the bug is to happen, scored from 1-5): 2-3

Effect (how bad the bug is when it does happen, scored from 1-5): 3
Poor feedback and no indication on how to fix the error. Potentially quite a bit of work lost if the user doesn't figure out what is wrong

Steps to reproduce the behaviour:
- Login
- Create a new project
- Go directly to the "review and submit" page (or add any milestones, etc. just no project overview data)
- Hit 'Submit'

Issues:
- The user is the presented with a cryptic "an error occurred" message instead of being redirected to the Overview form
- The Submit button is active ( @nanyangpro @suhafa I think it should be inactive in this case)

Screenshots:
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/429f303d-289f-40e4-a811-cfceb20dbba6)

**Comment by dleard** [comment]
Looks good. Attention Required appears and the submit button is disabled when the overview is incomplete.
