### ISSUE TITLE
Provincial and holdback percentages aren't discarded [6]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#850]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in dev
- edit an existing project's payment form
- discard the revision
- view the project's payment form. Provincial share and holdback percentage weren't discarded

Screenshots:
https://www.loom.com/share/b3706f2142e54eb6ac0438f95cf07d49

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by pbastia** [comment]
Works well, thank you!
