### ISSUE TITLE
Dev data is missing sector information on the project overview [6]

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#852]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2

Steps to reproduce the behaviour:
- Edit a project created by the dev script without touching the project overview
- Save the revision

There is an error on the project overview form

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
This card was addressed as part of [this](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/832) card.
