### ISSUE TITLE
As an Ops team member, I want to have an updated version of the dashboard, so that it is better suited to my needs

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-cif#857]
#### Description:

In view of the soft launch, we've reiterated the dashboard. All updates to be implemented are covered in [**the wireframe**](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2693%3A2698) based on work done in #714

#### Acceptance Criteria:

Given I am a CIF administrator
When I am using the CIF app
And I am looking at the top navigation bar
Then I see 'Home' label that when selected will take me back to the main page

Given I am a CIF administrator
When I am on the Home page
And I am looking at the 'Projects' category
Then I see the following helpful text under the Projects heading: Create, view and manage projects

Given I am a CIF administrator
When I am on the Home page
And I am looking at the 'Reporting Operations' category
Then I see the following helpful text under the Projects heading: Create, manage and search

Given I am a CIF administrator
When I am on the Home page
And I am looking at the 'Administration' category
Then I see a link called "Data Insights (Metabase)"

Given I am a CIF administrator
When I have selected the "Data Insights (Metabase)" link
Then a new tab is opened in my browser that takes me to the correct page in Metabase (https://cas-metabase.nrs.gov.bc.ca/)

Given I am a CIF administrator
When I am on the Home page
And I am looking at the 'Administration' category
Then I see a link called "Report a Problem"

Given I am a CIF administrator
When I have selected the "Report a Problem" link
Then my email pops up pre-populated with the correct email address

Given I am a CIF administrator
When I am using the CIF app
And I am looking at the bottom navigation bar
Then I see 'Login Page' label that when selected will take me back to the CIF login page

Given I am a CIF administrator
When I am using the CIF app
And I am looking at the bottom navigation bar
Then I see the following links (with their URL):
- Login Page (https://cif.gov.bc.ca - or dev or test)
- Disclaimer (https://www2.gov.bc.ca/gov/content/home/disclaimer)
- Privacy (https://www2.gov.bc.ca/gov/content/home/privacy)
- Accessibility (https://www2.gov.bc.ca/gov/content/home/accessible-government)
- Copyright (https://www2.gov.bc.ca/gov/content/home/copyright)
- Contact Us (mailto: ggircs email, subject: CIF App: Report a problem!)

#### Development Checklist:

- [x] Update 'Dashboard' to Home in navigation bar
- [x] Add in text below sections to add in more clarity
- [x] Add in link to Metabase to help with user navigation/workflow
- [x] Update 'Home' to Login Page in bottom navigation bar
- [x] Add in additional links on bottom navigation bar
- [x] Contact us mailto: `mailto:ggircsemail?subject=CIF App: Report a problem!`, whether this needs to be manually url-encoded needs to be determined
- [ ] Meets DOD

#### Notes:

-

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [ ] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by LindsayMacfarlane** [comment]
While reviewing the wireframe and refining the ticket, additional details are required around step 5: adding additional links in bottom navigation bar. Is it possible to add in the required urls to this ticket?

**Comment by suhafa** [comment]
Thanks for your comment @LindsayMacfarlane! -

1. Calling on @dleard for this one: for 'Data Insights (Metabase)' link in the dashboard where do we link our users to in the Metabase? Would it be CIF section of Metabase? Are we ready to link them to it now?

2. Correct! It will link them to an outlook email addressed to GGRICS. I will update the text in the wireframe to capture that part.

3. Question for @dleard (last one I swear) - For CIIP, we seem to have made new pages within the application itself instead of linking to the BC gov website for the footer links. Is there any reason why we did so? Was wondering if it's better to link it to external gov links or should we be creating a separate page for CIF footer links too?

**Comment by dleard** [comment]
1. It would link to our production metabase instance (external of the CIF app). It is not currently set up to receive data from the CIF database, but I will make a note to set it up.
3. It looks like we've linked to some external gov links in our CIIP footer, and some of our own. I don't remember a reason why we would have created our own pages except maybe we wanted some customization (for example the 'contact us' page). I figure we can link to external gov sites where appropriate in CIF.

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/857?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @mikevespi @Sepehr-Sobhani

**Comment by suhafa** [comment]
`mailto:ggircsemail?subject=CIF App: Report a problem!` would be best, with the subject line also pre-populated so we have a standard way of filtering CIF app issues

**Comment by LindsayMacfarlane** [comment]
This ticket seems to be in dev already - is it ready for me to test @pbastia @Sepehr-Sobhani?

**Comment by Sepehr-Sobhani** [comment]
> This ticket seems to be in dev already - is it ready for me to test @pbastia @Sepehr-Sobhani?

@LindsayMacfarlane Yes, it is. All tickets in `Accepted by PO or Dev` are already in dev because of the release but feel free to do additional QA on those cards.

**Comment by LindsayMacfarlane** [comment]
Thanks @Sepehr-Sobhani! I curious since it is still in the Pending Dev review pipeline :)

**Comment by Sepehr-Sobhani** [comment]
> Thanks @Sepehr-Sobhani! I curious since it is still in the Pending Dev review pipeline :)

Well, actually it should be in the `Accepted by PO or Dev` column :) sorry, I missed putting that in the correct column.

**Comment by LindsayMacfarlane** [comment]
Thanks @Sepehr-Sobhani! 

Meets acceptance criteria. One observation while testing:

1) The 'Login Page' link in the bottom navigation bar. When I select this link in dev, it opens up to the PROD instance. My assumption would be that when I'm in dev, it would open the dev environment, test to test and Prod to Prod. 

Let me know if we need a bug ticket to address the above.

Thanks!

**Comment by pbastia** [comment]
Good catch @LindsayMacfarlane ! We don't want people messing with production while thinking they are on the dev instance. This is a bug indeed, completely slipped past the code review, I'd say high priority since it already affects us

**Comment by Sepehr-Sobhani** [comment]
Thanks, @LindsayMacfarlane and @pbastia. I'll make a ticket for that.

**Comment by Sepehr-Sobhani** [comment]
Ticket created: https://github.com/bcgov/cas-cif/issues/925
