### ISSUE TITLE
As a CIF Administrator, I want to capture additional data fields on the "Project Overview" form, so that all my critical project information is captured in one place

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#858]
#### Description:
Design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2898%3A2671
Please refer to the design for the new arrangement (grouping, ordering, labelling) of fields
- **Score**: freeform field (E.g. 82.333)
- **Project Type**: dropdown for selection (E.g. Methane Capture, full list is upon finalization will be provided shortly)
- **Project Description**: Relabelled from "Summary"

#### Acceptance Criteria:

Given I am a CIF project administrator
When I am creating/editing a project
Then I am able to manually enter project score

Given I am a CIF project administrator
When I am creating/editing a project
Then I see a field named "Project Type" with a drop down with values:
    - Fuel Switching
    - Waste Heat Recovery
    - Renewable Energy
    - Carbon Capture
    - Utilization and Storage
    - Methane Reduction
    - Process Improvement
    - Electrification
    - Fleet Electrification
    - Hydrogen Production/Blending
    - Other

#### Development Checklist:

- [ ] Add manual/numeric field to capture project score information
- [ ] Add calculated field for project rank. Rank is calculated by ordering highest to lowest project score across a funding stream and year 
- [ ] Add field for project type. Options include: TBC
- [ ] Re-label field called Summary to 'Project Description'
- [ ] Re-order fields as per wireframe

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [ ] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro, while reviewing and refining the ticket I had a couple of questions:
- Rank: the notes indicate it is a pre-populated field based on other projects within the same funding stream/year - for clarification, the system would rank projects 1, 2, 3, etc with highest score being #1?  
- For score and rank: are these fields available in project creation and revision or just revision? 
- Do we have the full list for project type? The notes indicate a list will be provided shortly. I see the following listed in the wireframe (are these the final ones?). Also, I see the team has requested 'other' but we don't provide a field to indicate what other is - is this ok? I feel we should get away from using other as this may lead to questions in the future - what are your thoughts?
Fuel Switching
Waste Heat Recovery
Renewable Energy
Carbon Capture
Utilization and Storage
Methane Reduction
Process Improvement
Electrification
Fleet Electrification
Hydrogen Production/Blending
Other

**Comment by LindsayMacfarlane** [comment]
Note: based on a conversation with @suhafa and @nanyangpro, it was determined that getting these additional fields into the system were a top priority before implementing amendment/revision features.

**Comment by nanyangpro** [comment]
Good questions, @LindsayMacfarlane! Hope the answers below are helpful.
1. Yes
2. Project creation and revision
3. Yes, the list in the comment is the finalized one based on the Tech team's effort. "Other" was discussed by them, and was determined to be kept in the end

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/858?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @mikevespi @Sepehr-Sobhani

**Comment by pbastia** [comment]
We might want to split the calculated "rank" feature into its own user story

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! Potentially more of a designer question: the list of project types - should those be in alphabetical order (as implemented) or in the order that CIF provided (as included in the ticket)? Mainly flag as 'Other' is middle of the list, which might get lost....normally I've seen 'other' at the bottom of drop down menus.

**Comment by nanyangpro** [comment]
Thanks @BCerki!
Good call, @LindsayMacfarlane - Preferably in the order that CIF provided.

**Comment by LindsayMacfarlane** [comment]
Thank you so much for that quick update @BCerki - much appreciated.
