### ISSUE TITLE
As a CIF Administrator, I want additional data fields on the "Budgets, Expenses & Payments" form, so that all my required information is captured in one place

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#859]
#### Description:

https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2898%3A2863
Please refer to the design for the new arrangement (grouping, ordering, labelling) of fields
- ~**Proponent Cost**: freeform field~ #945
- ~**Total Project Value**: auto-calculated field (see the formula in the design), changed from freeform field (CREATE A NEW TICKET)~ #942

- ~**Additional Funding Source**: freeform field~
- ~**Additional Funding Amount**: freeform field~
- ~**Additional Funding Status**: dropdown for selection (awaiting approval, approved, denied) (CREATE A NEW TICKET FOR FUNDING SOURCES)~ #943

- ~**Anticipated Funding Amount (Fiscal Year 1)**: calculated from input for each milestone~
- ~**Anticipated Funding Amount (Fiscal Year 2)**: calculated from input for each milestone~
- ~**Anticipated Funding Amount (Fiscal Year 3)**: calculated from input for each milestone~ #944

#### Acceptance Criteria:

Given I am a Project Administrator
When I am creating/editing a project
And I am on the Budgets, expenses and payments form
Then I am able to enter the Proponent Cost related to a project

Given I am a Project Administrator
When I am creating/editing a project
And I am on the Budgets, expenses and payments form
Then I can see the sum total for 'total project value' 

Given I am a Project Administrator
When I am creating/editing a project
And I am on the Budgets, expenses and payments form
Then I am able to add 'Additional Funding Source'

Given I am a Project Administrator
When I am creating/editing a project
And I am on the Budgets, expenses and payments form
Then I am able to add 'Additional Funding Amount'

Given I am a Project Administrator
When I am creating/editing a project
And I am on the Budgets, expenses and payments form
Then I am able to select from a drop down for Additional Funding Status (choices: awaiting approval, approved, denied)

Given I am a Project Administrator
When I am creating/editing a project
And I am on the Budgets, expenses and payments form
Then there is a button called "Add Funding Source" that I can select that allows me to add additional funding source information. 

Given I am a Project Administrator
When I am creating/editing a project
And I am on the Budgets, expenses and payments form
Then there are calculated fields available for the following:
- Anticipated Funding Amount (Fiscal Year 1)
- Anticipated Funding Amount (Fiscal Year 2)
- Anticipated Funding Amount (Fiscal Year 3)

#### Development Checklist:

- [ ] Add freeform field for Proponent Cost 
- [ ] Add auto-calculated field for total project value. Total Project Value =Maximum Funding Amount + Proponent Cost +
Additional Funding Amount(s)
- [ ] Additional Funding Source: freeform field
- [ ] Additional Funding Amount: freeform field
- [ ] Additional Funding Status: dropdown for selection (awaiting approval, approved, denied)
- [ ] Button to add multiple funding sources/additional funding amounts
- [ ] Anticipated Funding Amount (Fiscal Year 1): calculated from input for each milestone
- [ ] Anticipated Funding Amount (Fiscal Year 2): calculated from input for each milestone
- [ ] Anticipated Funding Amount (Fiscal Year 3): calculated from input for each milestone

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [ ] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
Note: based on a conversation with @suhafa and @nanyangpro, it was determined that getting these additional fields into the system were a top priority before implementing amendment/revision features.

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro - based on the wireframe, can you please confirm that as part of this ticket we require the functionality to add additional funding sources? Also, is this unlimited? For example, the CIF team could add multiple funding source's.

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - Yes, the functionality is required as part of the ticket. Technically, yes, multiple are allowed. It's unusual from past experiences.

**Comment by LindsayMacfarlane** [comment]
Thanks @nanyangpro - a couple more clarifying questions:
- For optional fields, the design current shows the 'optional' label within the field. I believe we've been putting that optional label in the title. Would you like the designs to reflect that?

**Comment by pbastia** [comment]
@LindsayMacfarlane do we know the priority for this story?

**Comment by pbastia** [comment]
closing in favour of #942, #943, #944 and #945

**Comment by nanyangpro** [comment]
Thanks @pbastia - The design suggestions you and @LindsayMacfarlane raised in ZenHub and Figma will be taken into considerations and reflected in the updated design asap. Once done, will pin you in associated tickets as created above separately.
