### ISSUE TITLE
Add Internal Personas to User Stories

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#86]
Once Internal User Personas are created in ticket [#42](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/42), add corresponding personas to user stories.

**Comment by jaimiebutton** [comment]
This has also been added to our definition of ready

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton @Sriram-pc - is this ticket complete now? Question for you - when writing new tickets/issues, who will be responsible for ensuring the appropriate personas are linked? Is that something you will take on Ram?

**Comment by Sriram-pc** [comment]
@LindsayMacfarlane When new tickets are written for CIF, I can go and add personas to it (weekly I can check and add). As for this ticket, as adding personas to user stories will be an ongoing process, I guess we can mention that in the ticket and close the ticket.

**Comment by LindsayMacfarlane** [comment]
Thanks Team! Great collaborative effort on this task :)
