### ISSUE TITLE
As a CIF administrator, I want to be able to enter contacts without a phone number, so that I can still enter incomplete contact data

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#869]
#### Description:

It happens that the CIF team doesn't have a phone # for a contact

#### Acceptance Criteria:

Given I am a CIF administrator
When I create a new contact
And I don't have a contact phone number
Then I am able to leave that information empty

#### Development Checklist:

- [x] Phone number is not enforced in the database (can be `null`)
- [x] Phone number is not marked as required in the jsonschema
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
During CIF Prioritization session on August 16, CIF team indicated that this is an easy win of high impact as they don't always have the required phone numbers.

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/869?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment]
Thanks @BCerki!  Tested in dev and meets acceptance criteria.

One observation: The country code is displayed once a user saves contact information. Bug? 
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/628ac2ed-eb96-4805-a890-b987b53ba034)

**Comment by BCerki** [comment]
Yes, bug, I'll fix it

**Comment by BCerki** [comment]
I've fixed the lingering `+1` problem but in the process discovered another bug: 
 https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1026. This bug affects all optional information on the contact form and may be affected by the ongoing refactor

**Comment by LindsayMacfarlane** [comment]
Thank you for making that update @BCerki and for creating the additional bug ticket.
