### ISSUE TITLE
Legal Operator Name shows `(null)` for BC Registry ID when the operator does not have one.

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-cif#870]
Describe the Bug:

The entries in the `Legal Operator Name and BC Registry ID` dropdown show `(null)` after the name if the operator has no BC Registry ID. Some of the applicants operate in BC but aren't registered in BC, and therefore do not have a registry ID.

Probability (how likely the bug is to happen, scored from 1-5): 5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
Navigate to the Project Overview form in Create / Edit mode.
Open the Legal Operator Name and BC Registry ID dropdown.

As null values here are intended, only render the ID for an option if it exists.

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by pbastia** [comment]
Great work @mikevespi
