### ISSUE TITLE
Add validation to contact email and phone number

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#879]
#### Description

When adding a new contact, the phone number field validates that the entered text is a number, but not that it has the correct number of digits. There's also no validation on the email field to check for `@` or `.` characters.

#### Acceptance Criteria:

Given I am a user
When I am on the Contacts page and I enter a phone number with the incorrect number of digits
Then I am given a user-friendly error message when I try to submit the form

Given I am a user
When I am on the Contacts page and I enter an incorrectly formatted email (missing the `@` and/or `.`)
Then I am given a user-friendly error message when I try to submit the form

#### Development Checklist:

- [ ] email regex (x@y.z)
- [ ] north-american phone number regex 
- [ ] json-schema documentation: https://json-schema.org/understanding-json-schema/reference/regular_expressions.html
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [x] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/879?planning-poker) with Zenhub @BCerki @Sepehr-Sobhani @gurjmatharu

**Comment by LindsayMacfarlane** [comment]
Thank you @mikevespi! Tested in dev. Received expected error message when pone number or email address were incorrectly entered into the system.
