### ISSUE TITLE
Conditional Amount widget is sometimes missing the $ prefix

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#886]
The conditional amount widget (only used in Milestones) is not showing the '$' in read-only or in the diffs. This is likely a combination of an issue in the readOnly theme and the CustomDiffFields component.

Probability (how likely the bug is to happen, scored from 1-5): 3

Effect (how bad the bug is when it does happen, scored from 1-5): 2

Steps to reproduce the behaviour:

View a milestone that has values for Maximum amount / Total eligible expenses in read only (no $)
Make a change to those values & view the diff (no $)

**Comment by pbastia** [comment]
Works as expected with the '$'. Thanks @dleard
