### ISSUE TITLE
Milestone "Enter Amount" radio button behaves poorly (ConditionalAmountWidget) [6]

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#890]
There are a couple odd behaviours with the `Enter Amount` radio button for the `Total Eligible Expenses` and `Maximum Amount` fields (managed by the ConditionalAmountWidget).
1. The filled in radio button only shows up for one of the radio buttons. Clicking the radio button for one field removes the "filled in" part of the other button (though it doesn't change the value)
2. It defaults to false in a stateful way, so even if there are values in these fields, it will default to `Not Applicable` when starting an edit of an existing milestone.

I'm beginning to think that we don't want this `ConditionalAmountWidget` at all and that using [rjsf dependencies](https://react-jsonschema-form.readthedocs.io/en/latest/usage/dependencies/) might better suit our needs here. I think the widget was created when we were not totally clear if the `Total Eligible Expenses` and `Maximum Amount` fields were 100% tied to the report type & we wanted to let the user decide whether these values were needed. Now that we know that they are tightly coupled with the report type, we should be able to conditionally render / require these fields entirely within the rsjf schema.

Probability (how likely the bug is to happen, scored from 1-5): 3

Effect (how bad the bug is when it does happen, scored from 1-5): 3

Steps to reproduce the behaviour:

Begin editing an existing milestone that has values for `Total Eligible Expenses` and `Maximum Amount`.

Screenshots:
Only 1 of the radio buttons has a selection & on render, it defaults to `Not Applicable` even though there are values in the form data.

![Screenshot from 2022-07-21 15-49-04.png](https://images.zenhubusercontent.com/5fc1589bc8692570749d2bed/ddd3cd48-1087-40a8-b711-67c333236222)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by dleard** [comment]
@LindsayMacfarlane 
To test this:
- When creating a milestone other than a reporting milestone, the maximum amoutn and total eligible expenses fields should now be regular money fields (no Enter Amount / Not Applicable radio buttons)
- When the milestone is a reporting milestone those fields should not appear on the page

**Comment by LindsayMacfarlane** [comment]
Not in dev yet? I don't see radio buttons?

**Comment by dleard** [comment]
It's in dev. If you don't see radio buttons, good! I removed them :) The fields should just be regular fields now with no radio buttons at all

**Comment by LindsayMacfarlane** [comment]
Ahhh. I understand now :) Can confirm - no radio buttons displayed for any milestone types on the Milestone page.
