### ISSUE TITLE
Task: Feature Flag for the TEIMP report

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#893]
We need a feature flag for the TEIMP report

Todo:
- [ ] the feature flag
- [ ] make sure there is a mechanism for e2e to enable all feature flags

**Comment by LindsayMacfarlane** [comment]
@pbastia - anything I need to do for this ticket?

**Comment by pbastia** [comment]
No! We'll give you a tour of Growthbook one of these days

**Comment by LindsayMacfarlane** [comment]
Dylan gave me a demo before my holidays! It was awesome!

Can we consider this ticket complete @pbastia? I'm assuming the flag has already been turned on?

**Comment by pbastia** [comment]
Oh fantastic! Yes, the feature is turned on (visible) for -dev, and turned off for -test and -prod
![image](https://user-images.githubusercontent.com/11507754/182739766-ec0e64a9-118d-42e9-8dc7-4bd1f231bde5.png)
