### ISSUE TITLE
emissions intensity: incorrect task list items

### ISSUE THREAD

**Issue by gurjmatharu** [bcgov/cas-cif#899]
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by LindsayMacfarlane** [comment]
Hi @gurjmatharu - is it possible to get a bit more description on this one?

**Comment by gurjmatharu** [comment]
> @gurjmatharu, is this the same as https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1534?

Yes, same issue.

**Comment by BCerki** [comment]
Duplicate, and fixed by emission intensity refactor
