### ISSUE TITLE
Bug: adding and removing secondary contacts causes the revision to fail submission [6]

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#904]
Describe the Bug:

When creating or editing a project that doesn't have contacts, adding secondary rows and then removing them causes the submission of the revision to fail.

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

- create a new project
- fill out the project overview
- go to the contacts page
  - click on "add a secondary contact"
  - click "delete" on that secondary contact row
  - submit the contacts form (empty primary contact at this point)
- go to the project "review and submit" and click "Submit"

=> there is an error thrown with no details provided

Screenshots:

Additional information:
The project_contact table is throwing a 'violates not-null constraint' on 'contact_id'
```
✔ 0 error(s) as cif_admin in 4.70ms :: mutation updateChangeReasonMutation($input: UpdateProjectRevisionInput!) { updateProjectRevision(input: $input) { projectRevision { id changeReason } } }        11:42:27
::ffff:127.0.0.1 - - [26/Jul/2022:18:42:27 +0000] "POST /graphql HTTP/1.1" 200 122 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0"
2022-07-26 11:42:28.794 PDT [34804] ERROR:  null value in column "contact_id" of relation "project_contact" violates not-null constraint
2022-07-26 11:42:28.794 PDT [34804] DETAIL:  Failing row contains (1, 7, null, 1, 7, 2022-07-26 11:42:28.781687-07, 7, 2022-07-26 11:42:28.781687-07, null, null).
2022-07-26 11:42:28.794 PDT [34804] CONTEXT:  SQL statement "insert into cif.project_contact (project_id,contact_index) values ('7','1') returning id"
	PL/pgSQL function cif_private.commit_form_change() line 51 at EXECUTE
	SQL statement "update cif.form_change
	    set change_status = new.change_status
	    where project_revision_id=new.id
	    and form_data_table_name not in ('project', 'reporting_requirement')"
	PL/pgSQL function cif_private.commit_project_revision() line 21 at SQL statement
2022-07-26 11:42:28.794 PDT [34804] STATEMENT:  with __local_0__ as (update "cif"."project_revision" set "change_status" = $1
	where ("id" = $2)
	returning *) select ((case when __local_0__ is null then null else __local_0__ end))::text from __local_0__

 ERROR  1 error(s) as cif_admin in 23.66ms :: mutation updateProjectRevisionMutation($input: UpdateProjectRevisionInput!) { updateProjectRevision(input: $input) { projectRevision { id projectFormChange { id newFormData } } } }
```

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
This happens because when we create a secondary contact, we actually create a form change for the primary contact too; then when we remove that secondary contact, we still have the primary contact form change and it is now required to be filled which causes issue.

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani - I was not able to replicate the issue :)
