### ISSUE TITLE
Growthbook cypress & local development issues

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#906]
Features that are flagged by growthbook will currently fail cypress and not show up in local development if growthbook is down (or turned off for dev). We should add a flag when starting the server that can override the use of growthbook. This can be done by adding an env var & creating a wrapper for growthbook that returns true if it is on, or if our env var is present.

**Comment by LindsayMacfarlane** [comment]
@pbastia - anything I need to test in regards to this ticket?

**Comment by pbastia** [comment]
Nothing at all :) @LindsayMacfarlane
