### ISSUE TITLE
CIF database and Certbot PVCs are linked to the helm chart

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#909]
Describe the Bug:

The PVCs associated to the cif database and certbot are tied to the helm chart, which means that if there was a `helm uninstall` or a configuration change, they would be deleted and recreated.
**This could cause accidental data loss**

Probability (how likely the bug is to happen, scored from 1-5): 1
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 6
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
run `helm uninstall` in prod (please don't)

**Comment by pbastia** [comment]
A little bit of exploration:
- the PostgresOperator object [does not allow us to specify annotations or labels specific to that object](https://github.com/CrunchyData/postgres-operator/blob/7ed86775af0c9b55ca129afbeef7755cb7b00187/internal/controller/postgrescluster/postgres.go#L545), so adding a `"helm.sh/resource-policy": keep` annotation is probably not feasible here
- the [official storage retention strategy](https://access.crunchydata.com/documentation/postgres-operator/v5/guides/storage-retention/) requires us to have access to the `PersistentVolume` objects, which we don't have (we can only manipulate the claims)

**Comment by LindsayMacfarlane** [comment]
Some exploration completed this sprint (#86), but requires dev discussion.

**Comment by pbastia** [comment]
The gist is, it's easy to do anything in prod without confirmation.
An option that we can explore is 
- Have a team agreement that we never use `helm` or `oc` commands without the namespace specified
- Build tools to prevent accidental use of these commands (through either local aliases, or a shared `asdf` plugin that rewrites those commands)

**Comment by matthieu-foucault** [comment]
I don't think this issue is a bug, but rather a risk. Discussing the details of this risk (probability & impact) with the PO is needed, who would then decide on whether we should accept the risk or take steps to mitigate it

**Comment by matthieu-foucault** [comment]
Will be resolved by #1011 and #1012
