### ISSUE TITLE
Create Figma Prototype of Approved Wireframes

### ISSUE THREAD

**Issue by rajpersram** [bcgov/cas-cif#91]
- [x] Create key prototypes in Figma based on approved wireframes 
- [x] Present prototypes to GGIRCS and CIF team (including Figma URLs) for feedback
- [x] Iterate on prototypes if necessary
- [x] Obtain sign-off from CIF for any updates

**Comment by rajpersram** [comment]
Figma mockup uploaded to the corresponding user story in [ticket 63](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/63).

**Comment by rajpersram** [comment]
The prototypes were created for viewing a project list and creating/editing a project. Further design sessions will inform upcoming designs for the landing page, revisions, and attachments in the next sprint.

**Comment by LindsayMacfarlane** [comment]
Thank you for your work on this @rajpersram - it has been wonderful to see the design vision come together.
