### ISSUE TITLE
Usability testing for project emissions intensity report (TEIMP)

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#917]
#### Describe the task

Complete usability testing session with CIF Ops team to review and test the functionality of the emissions intensity (TEIMP) form. Get a detailed understanding of operators screen, post 2019 project requirements, IA and anything else that hasn't been tested yet 

#### Acceptance Criteria
- [x] Check in mid-week with developers regarding status of TEIMP report screen
- [x] Review screen in dev environment and note down any design inconsistencies 
- [x] Book meeting with Ops Team (Separately)
- [x] Create script
- [x] Create Miro Board space
- [x] Document feedback
- [x] Review feedback with dev team
- [x] Update designs (if required)
- [x] Create ZenHub tickets (if required)

#### Additional context

- Now that Emissions Performance is in the system, it is time to get it tested and see if we have covered everything.
- Or here

**Comment by LindsayMacfarlane** [comment]
@suhafa - the bones of the ticket are here. Please feel free to update :)

**Comment by suhafa** [comment]
@LindsayMacfarlane thank you so much, you're the best!

**Comment by suhafa** [comment]
Update - going to create a list of design inconsistencies noticed in the dev environment and upload on Figma. The reordering of fields can happen after the refactor session the developers are working on. As for terminology differences, they can be tackled sooner. The usability session will most likely be held early next sprint in that case.

**Comment by LindsayMacfarlane** [comment]
Hi @suhafa - is this ticket ready to be wrapped up?

**Comment by suhafa** [comment]
This ticket is completed. @LindsayMacfarlane Tickets #1113, #1114, #1115, #1116, #1117, #1118 have been created. Ticket #1029 was updated as well to capture text inconsistencies. The [Miro Board](https://miro.com/app/board/uXjVOlTUwNY=/) of usability testing findings has been updated for your reference @nanyangpro

**Comment by nanyangpro** [comment]
Very helpful. Much appreciated, @suhafa!

**Comment by Dianadec** [comment]
Reviewed and looks great. Adding a note that the Epic the above referenced tickets are apart of is #56. https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/56
