### ISSUE TITLE
As a CIF user, I want to view a holistic change log, so that I can track and filter all past changes (Amendment/General Revision/Minor Revision)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#919]
#### Description:
Design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=3068%3A2675

**Amendments & Other Revisions** table columns (each row refers to a "revision record"):
- **Type**: Amendment / General Revision / Minor Revision
- **Created Date**: the date when the revision record is created
- **Effective Date**: the date when the changes are approved _(for Amendment)_ or applied _(for General Revision, Minor Revision)_ and in effect in the app, displays "Pending" otherwise
- **Last Updated**: the date when the revision record is last updated
- **Updated by**: the user who made the last update to the revision record
- **Updated**:
Schedule/Scope/Cost _(for Amendment)_
the forms where fields got updated in the revision record _(for General Revision, Minor Revision)_
- **Status**:
In Discussion / Pending Province Approval / Pending Proponent Signature / Approved _(for Amendment)_
Draft / Applied _(for General Revision, Minor Revision)_

#### Acceptance Criteria:

Given I have created a project
When I am viewing the task list for the project
Then I can see in the task list an Amendments & Other Revisions section

Given there is an Amendments & Other Revisions section in the task list
When I click on that section
I can see a page with a table containing the following information:
- Type (Amendment, General, Minor)
- Created Date
- Effective Date
- Last Updated
- Updated By
- Updated (sections that were updated)
- Status

Given there is a revision table
When I want to edit or view a specific revision
Then there is a button that allows me to do so
(The button will do nothing until we implement the single amendment/revision view)

#### Development Checklist:

- [x] A section in the tasklist is added "Amendments & Other Revisions"
- [x] A new form page is added for "Amendments & Other Revisions"
- [x] The page displays a `<FilterableTable>` component with the data described in the AC
- [ ] Meets the DOD

**In the wireframe, but out of scope for this card:**
- The New Revision button will be handled in #923
- The revision type will also be created in #923 (if that card is not complete, we can leave the type blank)
- The view or view/edit button will be handled in #920. We can create the button but it doesn't have to go anywhere
Note: The wireframe shows view/edit and 'pending' for 3 amendments. This will only be applied to 1 at a time (only one open revision/amendment at a time)

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [x] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by nanyangpro** [comment]
Amanda had expressed that they would like to not have to enter "Reason for Change" on certain processes e.g. adding a report received date.
It was also mentioned that those small changes should live somewhere other than the holistic change log table to avoid it getting cluttered.
UX/UI research and decisions are required. See more details in #960 created by @mikevespi.

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/919?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by mikevespi** [comment]
@nanyangpro @suhafa in the task list for this page, is there a subsection to show? Or does clicking the "Amendments & Other Revisions" section title just change the icon direction and bring you to the page?

**Comment by nanyangpro** [comment]
Good questions, @mikevespi.
- Yes, there should be a subsection.
[Example 1](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=3169%3A3113), [Example 2](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2765%3A3314), [Example 3](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=3811%3A3243)
- Clicking the parent section title will just bring users to the holistic change log table page.

**Comment by mikevespi** [comment]
Thank you @nanyangpro  ! I'm unclear on the "view" scenario. Is there a subsection for the page with a table of all of the revisions, and a separate one for viewing a specific revision? In the mocks, the table page is in "view" mode but has no subsection, and the page viewing a revisions summary is also in "view" mode but has a subsection of "view revision".

**Comment by Sepehr-Sobhani** [comment]
@nanyangpro @suhafa have we decided on how we want to show `Updated` column when multiple forms have been updated?! 
Also just to confirm:

- We don't filter columns with date values (Like `Milestone Due` in the project table). correct?!
- We don't sort the `Updated` column as it has multiple values, but we keep filtering functionality. correct?!

**Comment by nanyangpro** [comment]
Good questions, @Sepehr-Sobhani! As discussed over the call,

- As long as the form names aren't hidden, let's keep the current display as it is, i.e. text overflow is handled by new lines.
- Ideally we add date pickers for the filter fields. But we can leave it as future enhancements if it's too much effort. Thanks for making the column sortable.
- Yes.
- Yes.

**Comment by LindsayMacfarlane** [comment]
@mikevespi @Sepehr-Sobhani - this looks beautiful :) 
Tested in dev and confirm work meets acceptance criteria. Thank you so much to you both.

**Comment by LindsayMacfarlane** [comment]
Small observation: Amendments & Revisions are displayed in the task list when creating a project (before saving a project). When I select it I get an error message (which I would expect) - but wondering if this should not be displayed in the task list until a user saves the record? Is this a bug?

**Comment by Sepehr-Sobhani** [comment]
> Small observation: Amendments & Revisions are displayed in the task list when creating a project (before saving a project). When I select it I get an error message (which I would expect) - but wondering if this should not be displayed in the task list until a user saves the record? Is this a bug?

Thanks @LindsayMacfarlane for catching this issue. yes that is a bug and I have created the bug ticket [here](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1122)
