### ISSUE TITLE
As a CIF user, I want to view a revision record, so that I can track and view who/when/what/why for a past change (Amendment/General Revision/Minor Revision)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#920]
#### Description:
Design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2661%3A4115

Sections (Amendment-specific sections are addressed in #922):
- **Revision type**: Amendment/General Revision/Minor Revision
~- **Forms updated**: displays fields (what) and forms (where) updated in the revision record~ #994
- **General comments**: displays general comment (why)
- **Revision record history**: displays the user (who) and date (when) upon creation or update of the revision record

#### Acceptance Criteria:

Given I am a cif user
When I am viewing the task list
Then I can see a `view revision` option in the task list

Given I have created a revision
When I click `view revision` in the task list
Then I can see a page with revision details

Given I have created a revision
When I am on the `view revision` page
Then I can see what type of revision it is (Amendment, General, Minor)

Separate card: #994
~Given I have created a revision
When I am on the `view revision` page
Then I can see what sections were changed in this revision with the diffs below each section~

Given I hace created a revision
When I am on the `view revision` page
Then I can leave comments about the revision (think this should be 'see' a revision)

Given I have created a revision
When I am on the `view revision` page
Then I can see a history of who created/updated the revision with a timestamp

#### Development Checklist:

- [x] The project_revision table has a revision_type enum column (Amendment, General, Minor) (done in https://github.com/bcgov/cas-cif/issues/995)
- [x] The project_revision table has a comments varchar column (done in https://github.com/bcgov/cas-cif/issues/995)
- [x] A `view revision` section is added to the task list
- [x] A `view revision` page is created to display revision details
- [x] The `view revision` page displays the type of revision
~- [ ] The `view revision` page displays the sections changed in the revision with diffs~ #994
- [x] The `view revision` page displays comments about the revision ~(editable)~
- [x] The `view revision` page displays who made changes and when
- [x] A number would be added in front of the revision type to represent the sequential number of that specific revision type (we need this number in the tasklist, header of the revision type and in the amendments table)

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [x] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/920?planning-poker) with Zenhub @BCerki @matthieu-foucault @mikevespi @pbastia @Sepehr-Sobhani

**Comment by BCerki** [comment]
> Sections (Amendment-specific sections are addressed in #922):
#922 is closed but doesn't have AC etc.

**Comment by Sepehr-Sobhani** [comment]
> Thank you so much @Sepehr-Sobhani! This looks fantastic.
> 
> For the following acceptance criteria, I'm assuming it should be to 'see' the general comments vs to leave a comment as that would align with the other criteria for this ticket: Given I have created a revision When I am on the view revision page Then I can leave comments about the revision

Absolutely!
