### ISSUE TITLE
As a CIF user, I want to set status for an Amendment, so that I can notify other user groups on action items

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#922]
#### Description:
Design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2765%3A3314

- **Status**: In Discussion / Pending Province Approval / Pending Proponent Signature / Approved
- **Pending actions from**:  Ops Team / Tech Team / Director / Proponent
- **Amendment type**:  Schedule / Scope / Cost

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
Note: Upload attachments can be a separate user story.

**Comment by BCerki** [comment]
Replaced by #981, #982, #983

**Comment by BCerki** [comment]
@nanyangpro, when you get a chance, could you please take a look at the AC for #981 and #982? I wasn't sure what to write for the buttons

**Comment by nanyangpro** [comment]
Sounds good, @BCerki. I'll take a look at them now.

**Comment by BCerki** [comment]
Split into https://github.com/bcgov/cas-cif/issues/981, https://github.com/bcgov/cas-cif/issues/982, https://github.com/bcgov/cas-cif/issues/983
