### ISSUE TITLE
As a CIF administrator, I want to only see and interact with the forms relevant for the project funding stream and status

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#924]
#### Description:

See [the excel spreadsheet](https://bcgov.sharepoint.com/:x:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/CIF/UX/Mapping%20-%20Funding%20Streams,%20Project%20Statuses,%20and%20Forms%20%26%20Fields.xlsx?d=w90e741bca6344a4fafe7824e8714bc89&csf=1&web=1) for context. Not all forms are relevant to a project, depending on their status or funding stream.

~The relationship between forms and project statuses should be encoded in our database, so that the behaviour can be easily customized (and later controlled via an admin panel)~
The relationship between forms and project statuses is unlikely to evolve at this point, so implementing it on the front-end 

#### Acceptance Criteria:

Given I am a CIF administrator
When I create a project with a specific funding stream
Then the tasklist options should adapt depending on the project status

Given I am a CIF administrator

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
@nanyangpro :eyes:

**Comment by nanyangpro** [comment]
Thanks @pbastia, cc: @gurjmatharu  - [design](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?page-id=2655%3A2669&node-id=3426%3A2678&viewport=-1133%2C1340%2C0.2&scaling=contain&starting-point-node-id=3426%3A2678&show-proto-sidebar=1) here.

**Comment by LindsayMacfarlane** [comment]
Ticket needs reviewing - this may be a duplicate or has been broken into smaller user stories? FYI @Dianadec

**Comment by dleard** [comment]
#1052 has a side effect on this card if we allow the status to move backwards. We may potentially then have data in the form_change records and table records that shouldn't exist. Not a problem if we do not allow statuses to move backwards.

**Comment by dleard** [comment]
@nanyangpro will be bringing up the status forward -> backward issue during sprint review this week

**Comment by Dianadec** [comment]
@pbastia this is marked as a duplicate, but I am not seeing the details on that... do you have any context?

**Comment by Dianadec** [comment]
This card will likely need to be split and needs @nanyangpro and or @suhafa 's input - flagging this for the next refinement in the new year.
First, the flow needs to be defined, then from there we can decide if it needs splitting. Currently we don't have structure on how to do this. We don't want to lose data on some forms.

**Comment by tmastrom** [comment]
This card was broken out into 1061 and 1053
