### ISSUE TITLE
Happo diffs should use mocked time when required

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#929]
###Description of the Tech Debt###

E2e tests shouldn't use the current date when possible, because Happo will flag artificial diffs when the date changes.

The impacted screenshots are so far:
"Project Annual Reports > editing"
"Project milestone reports Form > editing"
"Project revision summary > no_change_reason"

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |    None   |    0   |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     | Med      |    2   |
| System Fault Risk - Risk of system errors or application downtime                                                             |    None   | 0      |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |   Low    |     1  |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |  Low     |    1   |
| TOTAL SCORE:                                                                                                                  |       |   4    |

**Comment by LindsayMacfarlane** [comment]
Nothing for me to test on this one. Thank you @Sepehr-Sobhani for your work on tackling this tech debt issue.
