### ISSUE TITLE
As a CIF user, I want to edit an Amendment record, so that I can update its status and notify other user groups on action items

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#930]
#### Description:
Prototype: https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?page-id=2289%3A2663&node-id=3190%3A4775&viewport=-573%2C1082%2C0.31&scaling=scale-down&starting-point-node-id=3190%3A4775&show-proto-sidebar=1

Note that General Revisions / Minor Revisions with status "Applied", and Amendments with status "Approved" are not editable any more.

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by Dianadec** [comment]
This card will be archived as it has been broken down into 981 and 982

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro - confirming this ticket can be closed/archived based on @Dianadec above?
