### ISSUE TITLE
Research and Design for Notification

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#931]
#### Describe the task
Current Design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2765%3A3314

The CIF users want to alert other user groups on certain action items in their process. We need to design visual components and workflows for such Notification system. There are 3 aspects to consider:
- In-App vs Email
- Amendment-Specific vs Project-Level (or even Program-Level)
- User Management (Ops Team / Tech Team / Director / Proponent)

#### Acceptance Criteria
- [x] Investigate user needs and expectations from the CIF team
- [x] Create static mock-ups for further discussion/validation
- [x] Create interactive prototypes to visualize the envisioned workflows
- [x] Validate and finalize design with CIF and the devs
- [x] Write up associated user story tickets with design/prototype links for dev refinement and implementation

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket can be closed with #982 created with link to the updated design included.

**Comment by LindsayMacfarlane** [comment]
Thank you so much @nanyangpro! I really appreciate the simplicity of this first iteration.
