### ISSUE TITLE
Map out form fields with Schedule/Scope/Cost for Amendments on the holistic change log table

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#932]
#### Describe the task
Design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=3068%3A2675

Based on the form fields being amended, the holistic change log table should indicate among Schedule/Scope/Cost for an Amendment record. We need a clearer mapping to achieve this goal.

#### Acceptance Criteria
- [x] Investigate user needs and expectations from the CIF team
- [ ] Map out form fields with Schedule/Scope/Cost for Amendments on the holistic change log table
- [x] Deliver findings to the devs for further discussion/validation
- [x] Write up associated user story tickets with design/prototype links for dev refinement and implementation

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by nanyangpro** [comment]
According to the discussion with Amanda, instead of mapping out all the fields with Schedule/Scope/Cost, we will introduce a new section for the user to manually select from the 3 categories at the Preview step when creating an Amendment record. This approach will save time for research (card sorting effort for the mapping) upfront, implementation, and maintenance (due to program change) in the future.
Refined screen and prototype reflecting the design update and envisioned workflow will be provided.

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket can be closed with #983 created with link to the updated design included.

**Comment by LindsayMacfarlane** [comment]
Thank you @nanyangpro!
