### ISSUE TITLE
As a CIF Project Administrator, I want to see a calculated value for project rank, so that I can better understand and more easily see how a particular project ranked in a given funding year

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#934]
#### Description
Design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2898%3A2671
Please refer to the design for the new arrangement (grouping, ordering, labelling) of fields

- **Rank**: auto-populated field based on the score comparing to other projects within the same stream and the same year

#### Acceptance Criteria

Given I am a CIF project administrator
When I am creating/editing a project
And I am on the project overview page
Then I see a calculated/populated field for rank

Given I am a CIF project administrator
When I am creating/editing a project
And I am on the project overview page
Then the rank is calculated amongst the projects of the same stream and year

#### Development Checklist:

- [x] Add computed column for rank: `project_revision_rank` - that retrieves the rank for all projects in the same funding stream and year as the current revision, and determines the rank (probably a count(*) where score above current)
- [x] Form element
- [ ] Meets DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/934?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by matthieu-foucault** [comment]
@pbastia this needs a description of how score equality is handled. Are multiple projects assigned the same rank if they have the same score? Is there a parameter to break down ties?

**Comment by pbastia** [comment]
@matthieu-foucault  Great points to bring to the next office hours with our SME. For now I would say we can keep the logic simple, and give projects the same rank if they have the same score. And handle breaking ties in a different cards, so we can move forward with this one if that seems reasonable to you?

**Comment by LindsayMacfarlane** [comment]
@pbastia @matthieu-foucault - looping @nanyangpro into this discussion. IIRC we have already asked the CIF team this question and they indicated that they have not experienced a tied a rank.

**Comment by nanyangpro** [comment]
Thanks @LindsayMacfarlane - You are correct, we've asked them the question, and that's what I recall as well. It won't hurt to double check again if necessary :)

**Comment by nanyangpro** [comment]
I like your suggestion, @pbastia!

**Comment by pbastia** [comment]
#954 can be used to describe the process of handling score ties

**Comment by BCerki** [comment]
@nanyangpro, if the user hasn't entered the score yet, what should the field show? Nothing? Some explanatory text?

**Comment by nanyangpro** [comment]
Good question, @BCerki - Explanatory text would be good.

"Please enter a score in the above field to see the ranking of this project comparing other ones with scores entered."

**Comment by BCerki** [comment]
Probably outside the scope of this ticket, but: Should users be allowed to enter a score if they haven't already selected a stream or year? If they do, the ranking will be out of all projects that don't have a year or stream (same as how if there is a stream and year selected, the ranking will be out of all of those).

**Comment by nanyangpro** [comment]
Good question, @BCerki. - Just so that the users don't get confused by seeing the calculated ranking against the other projects not having a year or stream (which doesn't make much sense and is not indeed necessary), they shouldn't be allowed to enter a score without having selected a stream and year for a project. Hope it's helpful.

**Comment by BCerki** [comment]
> Good question, @BCerki. - Just so that the users don't get confused by seeing the calculated ranking against the other projects not having a year or stream (which doesn't make much sense and is not indeed necessary), they shouldn't be allowed to enter a score without having selected a stream and year for a project. Hope it's helpful.

Ticket for this here: https://github.com/bcgov/cas-cif/issues/1097

**Comment by LindsayMacfarlane** [comment]
Thank you so much @BCerki! Tested in dev by:
1. Editing an existing project by updating project score - rank updated
2. Creating an existing project - entered project score and rank auto calculated.

Passes acceptance criteria.

Observation:  @nanyangpro - in our discussions with CIF, was there anything mentioned around making this calculation more transparent? Currently, a user has to have confidence that the system is calculating this value correctly based on all projects in a given year/stream - but it isn't easy to compare this easily against other projects. I'm assuming this can done in Metabase, but wondering if we had any direct feedback.

**Comment by nanyangpro** [comment]
Thanks @LindsayMacfarlane - To my understanding, there isn't such need to compare project ranking with another project with a different year/stream. But I might be wrong, would you mind reminding me with more context?

In terms of transparency, I remember the CIF mentioned that for a given year & stream, it would be nice to see a list of ranked projects with their scores instead. :)
