### ISSUE TITLE
Co-design for the calculated fields on the Budgets, Expenses & Payments form

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#935]
#### Describe the task
Based on the learnings from #656 and #717 with the CIF Ops, we need to replan the existing fields for the calculated ones. This requires a collective effort between the designers and the developers.

#### Acceptance Criteria
- [x] Revisit notes and current design for #656
- [x] Schedule and hold co-design session with the devs
- [x] Refine and validate wireframes with developers and CIF Ops
- [x] Update #656 and #717 accordingly with the new design

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by nanyangpro** [comment]
@LindsayMacfarlane, @pbastia, @mikevespi - This ticket has been created and pulled to the upcoming spring as discussed. Thanks!

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane - This ticket can be closed.
- The co-design session was held on Aug 10 with @pbastia, @mikevespi, and Amanda.
As outcome of it,
- The refined design (see links in associated tickets) has been validated by both our devs and CIF Ops.
- Descriptions have been updated accordingly for #656 and #717, which should both be ready for implementation once AC is reviewed and refined by devs.

**Comment by LindsayMacfarlane** [comment]
Thank you so much for all your effort on refining this feature @nanyangpro.
