### ISSUE TITLE
Co-Design create a project wireframe

### ISSUE THREAD

**Issue by rajpersram** [bcgov/cas-cif#94]
#### Checklist:

- [x] Identify CIF team members who we'd like to participate
- [x] Plan co-design session(s)
- [x] Hold session(s)
- [x] Review results of co-design session(s) and draft 'final' presentation
- [x] Present final wireframe idea to CIF team for usability testing/comments

**Comment by LindsayMacfarlane** [comment]
Thank you @rajpersram. As always, I've really appreciated this co-design approach. Can you confirm - has the wireframe been uploaded to the appropriate dev ticket in the backlog?

**Comment by rajpersram** [comment]
No problem, @LindsayMacfarlane. The wireframe was uploaded to the corresponding user story [ticket 69](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/69) for the devs. 

Feedback was requested last week for the second round of revisions and with none on the Miro board, I interpret that as the changes are approved and align with the need, ready for prototyping in [ticket 91](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/91).
