### ISSUE TITLE
CIF external user research

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#941]
#### Describe the task

Starting thinking/brainstorming and laying the groundwork for discussion related to external user engagement. 

#### Acceptance Criteria

- [x] Review research plan created by EL
- [x] Brainstorm best path forward
- [x] Discuss with CIF
- [x] Create required ZenHub tickets

#### Additional context

- May relate to ticket #211. 

#### Documents to refer to

- Ongoing [Miro board](https://miro.com/app/board/uXjVP8R4ai0=/) for brainstorming external user research and compiling all existing research work done

**Comment by suhafa** [comment]
@LindsayMacfarlane To capture the work for CIF external user engagement, should we pull this ticket out of the icebox? Thoughts?

**Comment by LindsayMacfarlane** [comment]
Great idea @suhafa!

**Comment by suhafa** [comment]
Ticket's work is completed. Some pointers:
- During our sprint review (9 Dec), the Scrum team had a high-level discussion with the CIF team as to what fields they would like to see in the external user facing application (*Fields* Funding Stream, Funding Year, Legal Name, Facility Name, Attachments / *Features* Handling funding requests, auto-generating RFP ; one company can have several proposals so RFPs are needed to distinguish)
- Scrum team suggested to investigate other teams' work like CCBC's applicant portal, GC Forms/GC Notify to be able to quickly create an MVP by March 2023

Some action items discussed in brainstorming session:
- Ask CIF team if they have the external User Journey mapped out. If not, create one with them. Amanda would be a good point of contact for this.
- Investigate CCBC, CHEFS(? not sure if this is the right acronym), and other teams' work to see if there are any reusable components
- Create a Roadmap for the external user facing work. Who within CIF would be our ally in doing external user engagement? Need to decide communication plan, timeline etc
- External user outreach research plan outline, and ultimately getting buy-in to be able to do that once the scope is narrowed.

**Comment by LindsayMacfarlane** [comment]
Thank you so much @suhafa! I really appreciate all your effort collating all the previous research notes and thinking through some next steps.
