### ISSUE TITLE
As a CIF administrator, I want to see the total project value as a calculated field on the "Budget, expenses and payments" form, so that I have context for all other payment amounts

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#942]
#### Description:

A "Total Project Value" calculated field needs to be added to the "Budget, expenses and payments" form.

It should be calculated with the following formula:
Total Project Value = Maximum Funding Amount + Proponent Cost + Additional Funding Amount(s)

[Formula with examples](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EcXm1DnetBZNgFOkakDR_IEB1RS8r51PTHqH2h4C5L6URw?e=RbiNV2) - Please open it with the Word app instead of browser for formatting and better readability.

[Design](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=2898%3A2863&t=0b38GJFZh0GzOQrz-1) in Figma

#### Acceptance Criteria:

Given I am a CIF administrator
When I create or edit a project
And I am on the "budget, expenses, and payments" form
Then I can see a "Total Project Value" calculated field

Given I am a CIF administrator
When I am on the "Budget, expenses and payments form" for a project revision
Then the "Total Project Value" field is auto-calculated
And the formula is: Total Project Value = Maximum Funding Amount + Proponent Cost + Additional Funding Amount(s)

#### Development Checklist:

- [x] Computed column `project_revision_total_project_value` returns the right value (numeric)
- [x] The field displaying the value should use the `MoneyWidget` and be a `ReadonlyCalculatedValueWidget`
- [x] Remove existing `total_project_value` from `funding_parameter` table and update tests
- [x] Add custom discard mutation for additional funding sources
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
@nanyangpro the formula given seems a bit odd:
Total Project Value = Maximum Funding Amount + Proponent Cost + Additional Funding Amount(s)

Isn't the Proponent cost going to be covered by the provincial funding + other sources? Or is the formula actually doubling the money on purpose?

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/942?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by nanyangpro** [comment]
Good question, @pbastia.
Maximum Funding Amount is from the CIF program
Proponent Cost is the amount that the proponent pay by themselves
Additional Funding Amount(s) is from other sources other than the CIF program
Thus the formula isn't doubling any money, hope it's helpful.

**Comment by BCerki** [comment]
I started on this before I realized it was blocked and added the dependency. Incomplete work is on `feat/total-project-value` and I'll go back to it once the additional funding sources PR is in.

**Comment by nanyangpro** [comment]
Thanks for confirming, @Sepehr-Sobhani! Correct, only the calculated one.

**Comment by Sepehr-Sobhani** [comment]
Thank you @nanyangpro! I've faced another question, do we only need to include additional funding sources that have `Approved` status?!

**Comment by nanyangpro** [comment]
Good questions, @Sepehr-Sobhani! Yes.

**Comment by nanyangpro** [comment]
Good questions, @Sepehr-Sobhani! Yes.

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani ! Overall, looks great and meets acceptance criteria.

Some small observations:
- is it possible to add in a decimal to the total project value?
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/a712d353-d52e-4660-8aee-678e5dabc814)
- Where the Total Project Value is located seems kind of strange given it is calculating values from above and below on the form. I'm sure there is rationale from the CIF team, but flagging that from a workflow it may make more sense have at the bottom of the page? @nanyangpro

**Comment by Sepehr-Sobhani** [comment]
Thanks, @LindsayMacfarlane. Good points! for the first one, I'm gonna create a tech debt card. for the second one we do have a card to capture that: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1129

**Comment by LindsayMacfarlane** [comment]
Amazing! Thank you @Sepehr-Sobhani
