### ISSUE TITLE
As a CIF administrator, I want to track additional funding sources, so that I know where project's funding comes from

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#943]
#### Description:

This feature is about managing multiple funding sources for a project.

[Formula with examples](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EcXm1DnetBZNgFOkakDR_IEB1RS8r51PTHqH2h4C5L6URw?e=RbiNV2) - Please open it with the Word app instead of browser for formatting and better readability.

[Design](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=2898%3A2863&t=0b38GJFZh0GzOQrz-1) in Figma

#### Acceptance Criteria:

Given I am a CIF administrator
When I create or edit a project
And I am on the "Budget, expenses and payments" form,
Then I can click an "Add Funding Source" button to add additional (non-gov) funding sources

Given I am a CIF administrator
When I add additional funding sources 
Then for each funding source, I can enter the following data: 
  - Additional Funding Source: freeform field
  - Additional Funding Amount: freeform field
  - Additional Funding Status: dropdown for selection (awaiting approval, approved, denied)

Given I am a CIF administrator
When I create or edit a project
And I am on the "Budget, expenses and payments" form,
Then I can remove additional (non-gov) funding sources

#### Development Checklist:

- [x] a `cif.additional_funding_source` table, with the following fields:
  - id: integer PKEY
  - project_id: integer FKEY to cif.project(id)
  - source: varchar(1000)
  - funding_amount: numeric
  - status: enum(awaiting approval, approved, denied)
- [x] Forms and mutations similar to contacts to add / remove from a revision
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/943?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by pbastia** [comment]
@nanyangpro will add the 'remove' button on the wireframe

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani ! Tested in Dev by creating a new project and editing an existing project with funding sources. Meets acceptance criteria. Cheers!
