### ISSUE TITLE
As a CIF administrator, I want to see anticipated funding amounts per year for a project, so that I can budget the year accordingly

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#944]
#### Description:

Each project should display its anticipated funding amount per year.

[Formula with examples](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/EcXm1DnetBZNgFOkakDR_IEB1RS8r51PTHqH2h4C5L6URw?e=RbiNV2) - Please open it with the Word app instead of browser for formatting and better readability.

[Updated design](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=2898%3A2863&t=0b38GJFZh0GzOQrz-1) in Figma

#### Acceptance Criteria:

Given I am a CIF administrator
When I create or edit a project
And I am on the "Budgets, expenses and payments" form
Then I can see, for each *Fiscal* year funded, a calculated "Anticipated Funding amount (fiscal year x)"

Given I am a CIF administrator
When I view the anticipated funding amount for a year
Then the value is calculated from either the amounts paid for each past milestone (including holdback), or the maximum funding amounts for the upcoming milestones

#### Development Checklist:

- [x] New entries in our `json_schema_form` 
- [x] Computed column that returns an array of `{year: 20YZ, anticipatedFundingAmount: 1234.565 }` object. This will need to coalesce the adjusted gross amount and the calculated gross amount (similar to the `cif.form_change_calculated_net_amount_this_milestone` implementation)
- [x] Matches the government way of displaying fiscal years  `First Year / Second Year` (official spec [here](https://www2.gov.bc.ca/assets/gov/government/services-for-government-and-broader-public-sector/information-technology-services/standards-files/date_and_time_standard.pdf))
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by pbastia** [comment]
Comment from @LindsayMacfarlane:
> For the anticipated funding amount per fiscal - is there a calculation for that? At the moment, we don't specifically indicate payments by fiscal year, so I'm assuming the system would calculate based on the report due date? Or by the payment to CSNR date? I'm not 100% clear on how this will be calculated.

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/944?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by dleard** [comment]
work in progress, moving back to sprint backlog in favour of the blocking #986 card

**Comment by pbastia** [comment]
Given that these "anticipated funding amounts" are here to help CIF budget, they should be calculated with the "gross" amounts for each milestone.

**Comment by LindsayMacfarlane** [comment]
Backlog refinement: team discussion and decision to use gross amount. Will be an easy change if this is an incorrect assumption.

**Comment by dleard** [comment]
There is some previous work done for this here: https://github.com/bcgov/cas-cif/pull/977
Don't base off this PR, just use it as reference material
`get_fiscal_year_from_timestamp()` in that PR will be helpful
`ignore project_revision_anticipated_funding_amount_per_fiscal_year()`. It is way more complicated than it needs to be. It was made much simpler after the refactor was completed.

Whoever takes this on: let me know if you want to chat about it

**Comment by nanyangpro** [comment]
According to Amanda, these are medium to low priority fields comparing to other ones on the Budgets, Expenses, and Payments form.

**Comment by BCerki** [comment]
@nanyangpro, which date field should we be using to determine the fiscal year? And if that date isn't filled out, or the fields to do the calculations aren't filled out, what should we show?

**Comment by BCerki** [comment]
- use these dates in this priority: sent to csnr, report received date, report due date
- show a label for consistency even if nothing is filled (message: "This field cannot be calculated due to lack of information now.")
- will need to figure out a way to show three years of labels even if no dates filled out
As discussed with @nanyangpro

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki ! Looks good and no significant bugs or issues encountered while testing. UI matches design and I was able to add milestone information that correctly populates the correct fiscal year payments. We'll definitely want the CIF program to test this feature.
