### ISSUE TITLE
Given I am a Project Administrator When I am creating/editing a project And I am on the Budgets, expenses and payments form Then I am able to enter the Proponent Cost related to a project

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#945]
#### Description:

Brief description of the work involved, including any user research context or key decisions.

Wireframe: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2898%3A2863

#### Acceptance Criteria:

Given I am a Project Administrator
When I am creating/editing a project
And I am on the Budgets, expenses and payments form
Then I am able to enter the Proponent Cost related to a project

#### Development Checklist:

- [x] a new `proponent_cost: numeric` field on the `cif.funding_parameter` table
- [x] new fields in the `app/data/fundingAgreementSchema` schema and ui schema
- [x] "Proponent Cost" should use a `MoneyWidget` 
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/945?planning-poker) with ZenHub @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani @BCerki

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! Meets acceptance criteria.
