### ISSUE TITLE
As a cif user, I want to resume creating a project that I did not submit, so that I do not lose work in progress if I close my browser

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#95]
#### Description:

The forms should already save changes as the user types (#77). What is needed here is a way to resume editing a draft that is in progress.

#### Acceptance Criteria:
Given that I am logged in, and I have an unsubmitted draft to create a project
When viewing the landing page
Then the "Create a New Project" link is not visible, and replaced by a "Resume Project Creation" link

Given that I am logged in, and I have an unsubmitted draft to create a project
When viewing the project list page
Then the "Create a New Project" button is not visible, and replaced by a "Resume Project Creation" button

#### Development Checklist:
- [ ] The project creation can be resumed
- [ ] The button should direct the user to the create project page with the relay ID as a query parameter
- [ ] Wireframe completed to support development and referenced in ticket
- [ ] Meets DOD

#### Personas:
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by Sriram-pc** [comment]
Adding applicable Personas to the ticket
[Program Development Team - CIF Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)

[Operations Team - Persona](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by matthieu-foucault** [comment]
> Do we want to only allow one draft per user at a time, or have a list of draft projects?
Are we restricting users from working on a draft at the same time?
^ Questions

For this one, I would recommend starting with a single draft per user, and only that user can edit the draft. If that's the approved way forward, those would be scenarios to add the the acceptance criteria:

Given that I am logged in, and I have an unsubmitted draft to create a project
When viewing the landing page
Then the "Create a New Project" link is not visible, and replaced by a "Resume Project Creation" link

Given that I am logged in, and I have an unsubmitted draft to create a project
When viewing the project list page
Then the "Create a New Project" button is not visible, and replaced by a "Resume Project Creation" button

**Comment by LindsayMacfarlane** [comment]
Hi @rajpersram - will this ticket require a wireframe?

**Comment by LindsayMacfarlane** [comment]
Tested in Dev and was able to start and resume project.
