### ISSUE TITLE
As a CIF administrator, I want to be alerted if the calculated province's share is different than the one entered on the "budgets, expenses and payments" form, so that I can ensure data consistency

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#950]
#### Description:

Should we have an alert / an indicator showing if the calculated province's share is different than the target one (typically 50%) ?

#### Acceptance Criteria:

Given I am on the 'budgets' page
When the calculated province's share is different (by > 1%? TBC Business area) than the funding agreement value
Then I can see an alert near the field

#### Development Checklist:

- [ ] Implement the alert component
- [ ] Display the alert component near the calculated province share field if the value exceeds the threshold
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
During CIF Prioritization session on August 16, CIF team indicated that this is an easy win of high impact and medium/high urgency.

**Comment by LindsayMacfarlane** [comment]
Do we require a wireframe for this issue? What kind of wording/messaging do we want? @nanyangpro /  @suhafa - thoughts?

**Comment by pbastia** [comment]
@nanyangpro @suhafa What would you need to design this "field alert"? Should we use something similar to the json validation - except with a yellow, warning font?

**Comment by suhafa** [comment]
![image.png](https://images.zenhubusercontent.com/6201b10c9827341d8d5cbe9c/528356a5-0404-4a07-9d6a-c355efa5c37f)
A quick design/copy suggestion (not final design suggestion) - @nanyangpro feel free to edit up as you deem fit. This component can be found in the '#598/#599' page draft in Figma

**Comment by pbastia** [comment]
Does it mean we allow the user to dismiss the warning? What are the rules to displaying / hide the message?

**Comment by nanyangpro** [comment]
This ticket isn't relevant any more thus closed.

Warning would be handled by the **Proponent's Share Percentage** field on the Budgets, Expenses, & Payments form, see details in #717.
