### ISSUE TITLE
Remove `Login Page` link from footer navigation bar

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#957]
###Description of the Tech Debt###

Based on the conversation here: https://github.com/bcgov/cas-cif/issues/925 and comment: https://github.com/bcgov/cas-cif/issues/925#issuecomment-1208615968
We need to remove the `Login Page` link from the footer and update tests accordingly.

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |    1   |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |      | 1      |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |   1    |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |   1    |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |   1   |
| TOTAL SCORE:                                                                                                                  |       |    5   |

**Comment by LindsayMacfarlane** [comment]
Still in dev, so I'm assuming I'm testing too soon :)

**Comment by LindsayMacfarlane** [comment]
Link now gone. Thank you @BCerki !
