### ISSUE TITLE
Refactor money, percentage, and decimal widgets [8]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#959]
###Description of the Tech Debt###

We now have 3 very similar widgets (money, percentage, decimal). Can these be refactored into one widget that does slightly different things based on some parameter(s)?
Came up in: https://github.com/bcgov/cas-cif/pull/938#discussion_r942798005

###Tech Debt Triage#
The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

Risk Value Scoring:

| Level  | Value |
| ------ | ----- |
| High   | 3     |
| Medium | 2     |
| Low    | 1     |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |     low  |   1    |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |   med    |   2    |
| System Fault Risk - Risk of system errors or application downtime                                                             |   low    |   1    |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |  med     |     2  |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |    med    |  2     |
| TOTAL SCORE:                                                                                                                  |    8   |   low    |

**Comment by LindsayMacfarlane** [comment]
Anything in specific that I need to test in regards to this ticket @BCerki ?

**Comment by BCerki** [comment]
The only visible change is that on the project summary page, more 0 decimal places are visible (e.g. $200 became $200.00,  score of 8 became 8.000, etc.).

**Comment by LindsayMacfarlane** [comment]
Thank you for the clarification and your work on this one @BCerki.
