### ISSUE TITLE
Errors on TEIMP form doesn't trigger `Attention Required` status on the task list[6]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#970]
Describe the Bug:

`Attention Required` status doesn't show up when TEIMP report has errors.

Probability (how likely the bug is to happen, scored from 1-5):5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
Go to an existing project => add a new Emission intensity report and submit it without entering any data

Screenshots:
https://www.loom.com/share/84dc80b2cd6c4ece96aee84155ced12d

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
I think this is caused by the same problem that's causing https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/972

**Comment by BCerki** [comment]
@Sepehr-Sobhani, I think the db refactor fixed this bug; I can't reproduce it anymore. OK to close the card?

**Comment by Sepehr-Sobhani** [comment]
> @Sepehr-Sobhani, I think the db refactor fixed this bug; I can't reproduce it anymore. OK to close the card?

@BCerki Sure, Thanks.
