### ISSUE TITLE
GHG Emission Intensity Performance Field error when left blank[7]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#971]
Describe the Bug:

GHG Emission Intensity Performance Field on the TEIMP form raises an error when filled and then cleared.

Probability (how likely the bug is to happen, scored from 1-5):3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Go to an existing project => add an emission intensity report => fill required fields as well as the GHG Emission Intensity Performance field => clear the GHG Emission Intensity Performance field and try to submit

Screenshots:
https://www.loom.com/share/1eeecc30737846c884e87c0a48cd5516

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by LindsayMacfarlane** [comment]
Could not reproduce the error as indicated in the above steps. Thank you @mikevespi! Your video was also very helpful!
