### ISSUE TITLE
Quarterly Report and Emission Intensity Report status on the task list are linked[6]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#972]
Describe the Bug:

Quarterly report status and errors on the task list are in sync with the Emission Intensity Report; So all statuses on the task list for the Quarterly report will be the same for the Emission Intensity Report. 

Probability (how likely the bug is to happen, scored from 1-5):5
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):1
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Create a new project => open task list header for the quarterly report and the emission intensity report  => add a new quarterly report and see changes on both task list statuses.
Note: raising errors on the quarterly report will show up on the emission intensity report too.

Screenshots:

https://www.loom.com/share/ef45ae5285ca402db8c4197e44a9cb96

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by LindsayMacfarlane** [comment]
Thank you @BCerki! I can't recreate the bug based on the above steps :)
