### ISSUE TITLE
As a developer, I want to have access to a reusable tooltip component, so that I can easily implement tooltips in our forms

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#979]
#### Description:

We need a tooltip component, so we can have contextual help in our rjsf forms.

wireframe: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=3713%3A2681

#### Acceptance Criteria:

Given I am a developer
When I need to implement contextual help
Then I can use a `ui:options` value to toggle it on or off

Given I am a developer
When I implement contextual help with a tooltip
Then the component implements the tooltip accessibility rules: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role

#### Development Checklist:

- [x] a `<ContextualHelp>` (question mark from fontawesome) component with a configurable tooltip
- [x] changes to our `FieldLabel` component to accept the option and render the tooltip
- [x] Make sure tooltip can handle HTML content
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Bringing attention to tooltip best practices, which are: ["Don't use tooltips"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role#best_practices)

@LindsayMacfarlane @nanyangpro @suhafa

**Comment by nanyangpro** [comment]
Thanks for the comment, @pbastia - That's for sure a key understanding before we decided to introduce the tooltip component.

We try to avoid unnecessary tooltips by clear labels and visible descriptions. But in consider of form layout, readability, and complexity of context, we would still need tooltips for certain fields.

What are your thoughts, @LindsayMacfarlane, @suhafa?

**Comment by nanyangpro** [comment]
Amanda Vovk's comment from the CIF Feature Prioritization meeting on Aug 16:
_"I really like those tooltips. They are helpful."_

Jason Kubian's message from the Sprint Review on Aug 18:
_"Nice to see those 'Tooltip' addtional notes in the Design. Hopefully those help to write column descriptions that end up int he database structure."_

**Comment by LindsayMacfarlane** [comment]
During CIF Prioritization session on August 16, CIF team indicated that this is an easy win of high impact and medium urgency.

**Comment by dleard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/979?planning-poker) with ZenHub @BCerki @matthieu-foucault @mikevespi @pbastia @Sepehr-Sobhani @gurjmatharu

**Comment by pbastia** [comment]
There is a provision for this in rjsf:  https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/uiSchema/#help

**Comment by LindsayMacfarlane** [comment]
I feel, before we implement this, we should have a discussion around tool tip best practices so we come to consensus as a team. We should also identify where things can be addressed through improved labels or through something like a tool tip.

**Comment by nanyangpro** [comment]
Hi @pbastia - This ticket #979 should be the implementation of the **generic** tooltip component. However, it can be closed if we include the work in the scope of #1573 (cleaner version of the diff section for Amendments / General Revisions using tooltips), I would recommend doing so with reasons below unless you or think otherwise.

- The the contextual help text for #1573 is handled by #1659 already.
- The major work left for #1573 would be implementing the reusable tooltip component, thus can replace the work here.

**Comment by Sepehr-Sobhani** [comment]
The development checklist mentions `question mark` as the icon, but we have an exclamation mark in the wireframe. Which one is preferable?

**Comment by nanyangpro** [comment]
Thanks for confirming, @Sepehr-Sobhani! Exclamation would be more applicable.

**Comment by nanyangpro** [comment]
Amazing tool, thanks @pbastia! All passed, let's go for it, @Sepehr-Sobhani

**Comment by Sepehr-Sobhani** [comment]
Nothing to test here @pbastia !
