### ISSUE TITLE
As a CIF user, I want to set status for an Amendment, so I can keep track of its progress

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#981]
#### Description:

Design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2765%3A3314

Add a status section (header and dropdown with button) to the Amendments & Other Revisions form. Statuses are: Draft / In Discussion / Pending Province Approval / Pending Proponent Signature / Applied

#### Acceptance Criteria:

Given I am a CIF administrator
When I am on the Amendments & Other Revisions form
Then I can see a status header

Given I am a CIF administrator
When I am on the Amendments & Other Revisions form
Then I can select the status I require from a dropdown

#### Development Checklist:

- [x] Add a dropdown widget to the amendment form for status
- [x] have a button to update the status
- [x] a text that shows the status has been updated
- [x] write tests
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

#### Notes:

- Split out from https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/922

**Comment by nanyangpro** [comment]
@BCerki - I'll remove the button (which was designed to address the scenarios similar to what's described in #960) from the design, feel free to update the AC accordingly.

**Comment by pbastia** [comment]
@nanyangpro @suhafa this card allows us to change the status of an amendment from the 'view' page, does it mean we're modifying the revision? Is this one of the 'shortcuts' we were talking about?

**Comment by nanyangpro** [comment]
Good questions, @pbastia.
- Yes. It will add one more line in the "Revision record history" section on the page too.
- Correct
We can have a quick chat if you like.

**Comment by gurjmatharu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/981?planning-poker) with Zenhub @pbastia @Sepehr-Sobhani

**Comment by pbastia** [comment]
The AC don't mention the "Update" button. Is this button still expected to be implemented? (this joins the discussion on #1166)

**Comment by Sepehr-Sobhani** [comment]
This has been merged but not deployed to dev yet!

**Comment by LindsayMacfarlane** [comment]
Thanks @Sepehr-Sobhani! Looks great. A couple of observations:

- Applied vs approved. I noticed that the description mentioned 'Approved'. but what was implemented was 'Applied'. However, I feel I remember there was a discussion around applied vs approved? 
- Probably user error, but I couldn't submit the amendment - it remained in the 'pending' for the 'effective' date, which meant I could not start a new revision.

**Comment by Sepehr-Sobhani** [comment]
Thank you @LindsayMacfarlane.

- You are right, I think it was discussed in a dev/design session and also captured in this card: https://github.com/bcgov/cas-cif/issues/1085 (Sorry for not updating the description of this card, my bad!)
- You are absolutely right, that part is not complete yet and we have a card here: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1293
