### ISSUE TITLE
As a CIF user, I want to notify other user groups when a revision requires their attention, so that they can action items

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#982]
#### Description:

[Prototype Example 1 (Notify Tech Team)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=3989%3A5985&node-id=3989%3A8493&viewport=-674%2C-451%2C0.24&scaling=scale-down&starting-point-node-id=3989%3A8493&show-proto-sidebar=1)
[Prototype Example 2 (Notify Director)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=3989%3A5985&node-id=3989%3A7927&viewport=-674%2C-451%2C0.24&scaling=scale-down&starting-point-node-id=3989%3A7927&show-proto-sidebar=1)
[Prototype Example 3 (Notify Proponent)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=3989%3A5985&node-id=3989%3A7085&viewport=-674%2C-451%2C0.24&scaling=scale-down&starting-point-node-id=3989%3A7085&show-proto-sidebar=1)

Add a pending actions section (header and dropdown with button) to the Amendments & Other Revisions form. Pending actions from: Ops Team / Tech Team / Director / Proponent

#### Acceptance Criteria:

Given I am a CIF administrator
When I am viewing a single amendment from the revisions table
Then I can see a pending actions header

Given I am a CIF administrator
When I am viewing a single amendment from the revisions table
Then I can select the notification recipient I require from a dropdown

Given I am a CIF administrator
When I am viewing a single amendment from the revisions table
Then I can see a notify button (button AC will be covered in https://github.com/bcgov/cas-cif/issues/931)

#### Development Checklist:

- [ ] on the  "View Revision" form, create a section titled "Pending actions from"  that shows the `pendingActionsFrom` field and uses the dropdown widget
- [ ] director email should be in an env variable pulled in `config.js`
- [ ] write tests
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by nanyangpro** [comment]
Hi @BCerki - The expected behaviour after clicking "Notify" will be taken care of upon completion of #931, thus can be omitted from the AC of this ticket.

**Comment by mikevespi** [comment]
@nanyangpro do we need an option here for "No pending action"?

**Comment by nanyangpro** [comment]
Good call, @mikevespi! Yes, we should have it.

**Comment by Dianadec** [comment]
Notes from refinement: Nan will review async and will involve devs as needed.

**Comment by Dianadec** [comment]
@nanyangpro I am reviewing this card in preparation for refinement tomorrow and wanted to follow up on the comment above. Did you get a chance to review this async?

**Comment by nanyangpro** [comment]
Hi Diana, thanks for confirming - I had reviewed the ticket and made sure that the design is up-to-date and ready for implementation. Thanks!

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/982?planning-poker) with Zenhub @pbastia @gurjmatharu @Sepehr-Sobhani

**Comment by pbastia** [comment]
At the moment, we don't identify the director in the application - would that something hardcoded somewhere? Do we need to record it? I would suggest keeping it out of the available options until we know what the requirements are for this one

**Comment by Sepehr-Sobhani** [comment]
Have we decided to use a modal or an alternative?!

**Comment by nanyangpro** [comment]
Good question, @pbastia - Based on the discussion with CIF, we landed at having the director email hardcoded for now. I'll double-check the person and the email address, and to the description.
We do need a ticket recording further exploration on how we want to address it for the user to change the director by themselves, but it's lower priority as for now.

**Comment by pbastia** [comment]
One other question @nanyangpro : Is this feature for amendments only? Or for all types of revisions? The AC doesn't make it explicit

**Comment by nanyangpro** [comment]
Also a great question, @pbastia - Yes, amendment only.

**Comment by pbastia** [comment]
...and another one ;) Is this card 
- just about the widget to select the "pending actions from" + button?
- about showing the modal to select from project contacts / project managers / program director?
- about opening the default email app?
- all of the above?

**Comment by nanyangpro** [comment]
Love the questions, thanks for confirming, @pbastia.
It's about point 2 and 3.
1 is part of the prototypes for the sake of showcasing the scenario, but can/should be addressed separately.

**Comment by pbastia** [comment]
This card needs to be split in 2:
- form elements to change the "pending actions from" + updating the amendment record + notify button
- modal with content depending on the selected option + mailto links

**Comment by pbastia** [comment]
@nanyangpro based on this prototype, updating the status won't save until the user clicks the "Save" button - but updating the "pending actions from" field will save immediately. Is there a reason for the different behaviour?

**Comment by pbastia** [comment]
@Dianadec thanks for reminding me of this!
This has been split between #1166 and #1167 and can be now closed.
@LindsayMacfarlane those cards are in the backlog with a refinement tag, feel free to add a priority to them.

**Comment by Dianadec** [comment]
Closed as per Pierre's comment above.
