### ISSUE TITLE
As a CIF user, I want to set type for an Amendment, so that I can keep track of changes

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#983]
#### Description:

Design: 
- https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2765%3A3314
- https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?page-id=2289%3A2663&node-id=3169%3A2715&viewport=-573%2C1082%2C0.31&scaling=scale-down&starting-point-node-id=3169%3A2715&show-proto-sidebar=1

Add a amendment type section (header and checkboxes) to the Amendments & Other Revisions form. Types are: Schedule / Scope / Cost

#### Acceptance Criteria:

Given I am a CIF administrator
When I create a new project revision
And I am on the Amendments & Other Revisions form
Then I can see a Amendment Type header

Given I am a CIF administrator
When I start a new revision of type "Amendment"
Then I am offered the possibility to set the type of that amendment (none or many of: Schedule, Scope, Cost)

Given I am a CIF administrator
When I start a new revision of type **not** "Amendment"
Then I am **not** offered the possibility to set the type of that amendment

#### Development Checklist:
- [x] Changes to the form creating a new revision:
    - Given "Amendment" is selected, a "Choose Type(s) for Amendment" field (Checkbox, `Schedule`, `Scope`, `Cost`)
- [ ] Checking or unchecking a box creates or removes a form_change for the `project_revision_amendment_type` table with the right information.
Given that these fields are only for the revision - not the project, we don't need to address the "archive" case as they will never be editable.
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/983?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by nanyangpro** [comment]
More background context in #932.

**Comment by gurjmatharu** [comment]
Should `amendment_type` in the table `project_revision_amendment_type` be changed to an array to handle selecting multiple types?

**Comment by pbastia** [comment]
for a one-to-many relationship, a join table is recommended instead

**Comment by gurjmatharu** [comment]
Removing/changing acceptance criteria to remove form changes.  Instead updating a undo function and updated create product revision mutation.

**Comment by gurjmatharu** [comment]
hi @LindsayMacfarlane I've added a new PR to address the first two points.

The weird behaviour is being addressed in issue https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1186

For the general comments reordering could we please open up a new issue if need be.

**Comment by LindsayMacfarlane** [comment]
Thank you @gurjmatharu! If there is a new PR, should I move this ticket back into In Progress? 

@nanyangpro - before I create a new ticket to address the ordering of fields, can you please confirm whether the 'amendment type' is to be place above the 'general comments' section. Thanks!

**Comment by gurjmatharu** [comment]
@LindsayMacfarlane We've merged a new PR where I updated the ordering as well.  Please take another look before creating a new ticket

**Comment by nanyangpro** [comment]
Thanks for confirming, @LindsayMacfarlane - There isn't a "General Comments" field on this page /at this step in the design. For more details, please see the envisioned workflow in [the 2nd link](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?page-id=2289%3A2663&node-id=3169%3A2715&viewport=-573%2C1082%2C0.31&scaling=scale-down&starting-point-node-id=3169%3A2715&show-proto-sidebar=1) in the ticket description above.
I believe the "General Comments" field is simply there due to the existing workflows in the system and will eventually be removed? If there's a reason from the devs to keep it on the page for now, we can leave the "Amendment Type" above it.

**Comment by LindsayMacfarlane** [comment]
Thank you @nanyangpro - can you flag that for review for you and or @suhafa? I don't think that was clear given the [first link](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?node-id=2765%3A3314) shows the general comments (see screenshot). We may need a ticket to specify the removal of the general comments given it is still within the UI? @pbastia  from a developers perspective what would you recommend?

![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/8cf768a3-ee9c-4e8a-8212-59d43c2a345b)

**Comment by LindsayMacfarlane** [comment]
Thank you @gurjmatharu! Amendment now triggers amendment type, spelling is corrected.

When I tried to save an amendment, with amendment types of scope/cost I got the following error. If not already captured I will create a bug ticket. Thank you for all your work on this! 
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/c7d390d1-3fec-4f71-8e0e-cb035f757581)

**Comment by LindsayMacfarlane** [comment]
Hi @gurjmatharu - do you have any feedback on the above? If this needs to be captured as a bug ticket, I can do so. @pbastia - thoughts?

**Comment by LindsayMacfarlane** [comment]
Based on discussion in Scrum Team Channel - I'll move this ticket to accepted and try to recreate the bug. If I can re-create the bug, I'll create a bug ticket.

**Comment by pbastia** [comment]
@LindsayMacfarlane If the bug is related to the feature that's been implemented, I'd say we can re-use this ticket and put it back to 'in progress'. Otherwise a new ticket is better?

**Comment by LindsayMacfarlane** [comment]
Thank you @pbastia @gurjmatharu. Here's what I did to trigger the error:
1. Selected amendments and other revisions
2. Started a new revision
3. Didn't 'submit' the revision, but selected a page from the task list
4. Went back to the revision page, which made me start another new revision, which when I went to submit I got the error.

**Comment by gurjmatharu** [comment]
I think this should be fixed with my latest PR. It's currently in review. Let's move this conversation there.
