### ISSUE TITLE
GHG Emission Intensity Performance doesn't show in view mode [6]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#985]
Describe the Bug:

The GHG Emission Intensity Performance calculation doesn't show in view mode.

Probability (how likely the bug is to happen, scored from 1-5): 4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- add a TEIMP report to an existing project and fill out enough values to trigger the calculation of the GHG Emission Intensity Performance
- go view the project and note that the GHG calculation value is 0.00%
- edit the project and note that the calculation is there

Screenshots:
https://www.loom.com/share/d0aaca4124d34ff7a57dd1a9460415ec

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
I can't reproduce this anymore! could be addressed in: https://github.com/bcgov/cas-cif/pull/1674

**Comment by BCerki** [comment]
Also can't reproduce, closing
