### ISSUE TITLE
Create computed columns to return the total_eligible_expenses, gross_amount, net_amount for a given milestone

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#986]
These values should be calculated cumulatively for each milestone in order of report_due_date.

total_eligible_expenses (to date) includes the total eligible expenses for all previous milestones (and itself).
gross_amount is the gross calculated payment for the milestone. It includes the holdback amount (for the performance milestone).
net_amount is the net calculated payment for the milestone. It does not include the holdback amount (for the performance milestone)

gross_amount and net_amount are bound by the maximum_amount for a milestone as well as the maximum_funding_amount for a project.

**Comment by Sepehr-Sobhani** [comment]
Related PR https://github.com/bcgov/cas-cif/pull/990

**Comment by LindsayMacfarlane** [comment]
Hi @dleard please forgive my forgetful mind...can you remind me the status of this ticket. Are we breaking it down further based on the comments above?

**Comment by dleard** [comment]
The computed columns I noted in my comment above for "Specific Milestones" are done and in dev. The Cumulative ones are done & in dev review. We have questions for Nan before they can be moved forward but can probably be merged tomorrow after I chat with her.

**Comment by LindsayMacfarlane** [comment]
Awesome! Thank you @dleard !
