### ISSUE TITLE
As a CIF user, I want to filter projects only by Primary Managers

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#987]
#### Description:
On the CIF Projects page, currently if filtered by Project Managers, the table displays all projects which have the person as either Primary Manager or Secondary Manager. Users want to see projects which have the person only as Primary Manager instead.

#### Acceptance Criteria:

Given I am a CIF Administrator
When I am on the Project List page
And I am filtering on the Project Manager column
Then only the primary manager(s) are displayed / available for filtering. 

#### Development Checklist:

- [x] The project managers column is renamed to `primary project managers`
- [x] The query in app/pages/cif/project/[project]/index.tsx filters to only include primary managers (This can probably be done with something like: ```filter: {projectManagerLabelByProjectManagerLabelId: {label: {includesInsensitive: "primary"}}}``` )
- [x] The project managers column should only show primary managers
- [ ] Meets the DOD

filter: {projectManagerLabelByProjectManagerLabelId: {label: {includesInsensitive: "primary"}}}
#### Notes:

- Do we need to update the column heading?

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by LindsayMacfarlane** [comment]
During CIF Prioritization session on August 16, CIF team indicated that this is an easy win of high impact and medium/high urgency.

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro and @suhafa - design consideration for this ticket: should the column name be updated to Primary Project Manager? I'm wondering if it would be confusing if we just say project managers, but filter only on primary without being explicit that that is what is happening? For example, if I was a new user, how would I know that that column only filtered on primary managers? And I'm assuming it is primary for both Ops and Tech team?

**Comment by dleard** [comment]
^ Agree with Lindsay here. If we only filter on primary managers then we should probably only display primary managers in this column.

**Comment by suhafa** [comment]
@LindsayMacfarlane I agree, it would be best to show the column name as 'Primary Project Manager', since there seems to be a specific need to filter by that role.

**Comment by Sepehr-Sobhani** [comment]
@suhafa @dleard Are we agreed on showing only primary managers in the column?! or does changing the header of the column suffice?!

**Comment by dleard** [comment]
only primary managers should be shown

**Comment by Sepehr-Sobhani** [comment]
> only primary managers should be shown

Thanks, Updated AC.

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani - it works like a charm :)

Tested in dev by adding/updating primary and secondary project managers. Confirmed that secondary project managers are not displayed in the column or filterable.
