### ISSUE TITLE
As a CIF user, I want to add Contract Number to a project

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#988]
#### Description:
CIF Ops assign Contract Number (i.e. Transfer Payment Number) to projects, which is used when communicating with CSNR. This field should be incorporated to the Project Overview page.

E.g. TP20JHQ8000

Design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2898%3A2671

#### Acceptance Criteria:

Given that I am a CIF user
When I am creating or editing a project
And I am on the project overview page
Then I can optionally view and fill out the contract number field

#### Development Checklist:

- [x] New columns are added to the `project` table for contract number
- [x] The  json_schemas are updated to include the contract number
- [x] The field appears on the overview form as a free form field
- [x] The field is optional
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment]
During CIF Prioritization session on August 16, CIF team indicated that this is an easy win of high impact

**Comment by BCerki** [comment]
@nanyangpro, two questions:
- is the contract number field required?
- is the field free-form and/or is there any formatting validation required?

**Comment by nanyangpro** [comment]
Good questions, @BCerki!
- Optional
- Freeform is alright
- I'll put together a qucik mock-up for it

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/988?planning-poker) with Zenhub @mikevespi @BCerki @Sepehr-Sobhani @gurjmatharu

**Comment by LindsayMacfarlane** [comment]
I think I may be testing too early? I don't currently see in dev.

**Comment by mikevespi** [comment]
Sorry @LindsayMacfarlane ! The branch had been merged, but it looks like the deployment got stuck along the way. I'll move it back over once the deploy succeeds.

**Comment by LindsayMacfarlane** [comment]
Thank you @mikevespi ! Looks great! Tested in dev by:
- confirming it is displayed on the project overview page (view)
- added a contract number to an existing project
- created a new project with a contract number
