### ISSUE TITLE
Relabel "Anticipated Funding Amount"

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#989]
#### Describe the task
Relabel the "Anticipated Funding Amount" freeform field on the "Budgets, Expenses & Payments" form to "Anticipated/Actual Funding Amount" as an optional freeform field.

Re-order and group the fields on the form to reflect the latest [design](https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=2898%3A2863).

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by LindsayMacfarlane** [comment]
During CIF Prioritization session on August 16, CIF team indicated that this is an easy win of high impact.

**Comment by mikevespi** [comment]
@nanyangpro @suhafa Are all of the field names in the mock the latest names requested by CIF? For example I see "Province's share percentage" is now "Maximum province's share percentage", should that be changed as well?

**Comment by nanyangpro** [comment]
Good question, @mikevespi. Yes, the mock is up to date.

**Comment by rdromey** [comment]
It's been taken care of in ticket 1029
