### ISSUE TITLE
Investigate situations where a General/Minor Revision is needed when an Amendment is not settled

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#991]
#### Describe the task
Currently for the holistic change log table on the "Amendments & Other Revisions" page, user can only have one record in progress. This will block the user to create a General/Minor Revision during the comparatively longer waiting time for a pending Amendment to be settled.
Investigation and solution for handling such scenarios are required.

#### Acceptance Criteria

- [x] List relevant scenarios
- [x] Propose solutions with updated design
- [x] Discuss/validate proposed solutions with CIF
- [x] Discuss Discuss/validate proposed solutions with Devs

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by nanyangpro** [comment]
Key learnings from CIF Ops so far:
- There won't be 2 "open" (i.e. "Status" field hasn't been updated to "Approved") Amendment records for a project at the same time.
- Before the Amendment is settled (i.e. "Status" field is updated to "Approved"), the changes shouldn't be applied to the database.
- Users need to be able to update a project while there is an "open" Amendment, which could potentially last a long time period.
- Further Dev/Design discussion is scheduled in hope to come up with a solution not only meets the user need but also not too expensive in terms of implementation. @pbastia

**Comment by nanyangpro** [comment]
Pierre: An Amendment doesn't amend a project, it amend a funding agreement.
Suggestion: Review what fields are part of a FA (could be amended), and what are not (won't be impacted by an Amendment).

**Comment by nanyangpro** [comment]
Pierre: An Amendment doesn't amend a project, it amend a funding agreement.
Suggestion: Review what fields are part of a FA (could be amended), and what are not (won't be impacted by an Amendment).

**Comment by nanyangpro** [comment]
Hi @LindsayMacfarlane, this ticket can be closed with findings analyzed and learnings summarized in above comments for you to review.

Additionally, as discussed with the devs (cc: @pbastia, @matthieu-foucault, and @dleard), all fields in the latest design have been revisited, categorized into groups not overlapping with each other, and validated by Amanda. Please see detailed grouping in the "Fields" tab in this [mapping spreadsheet](https://bcgov.sharepoint.com/:x:/t/00608-ScrumTeam/EbxB55A0pk9Kr-eCTocUvIkB6sWffF4ACkh3oQ5_89dTlg?e=dcgbof&isSPOFile=1).

**Comment by LindsayMacfarlane** [comment]
Thank you @nanyangpro - I love this! It is very helpful to see things mapped out this clearly. The spreadsheet really helps to show what fields are considered revisions vs amendments.
