### ISSUE TITLE
As a CIF user, I want to create a new revision (Amendment/General Revision/Minor Revision), so that I can filter, view, and update it via the holistic change log table

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#992]
#### Description:

New revision page, and setting the revision type when creating a new revision

Prototype: https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?page-id=2289%3A2663&node-id=3169%3A2715&viewport=-573%2C1082%2C0.31&scaling=scale-down&starting-point-node-id=3169%3A2715&show-proto-sidebar=1 (FYI the mocks are interactive)

#### Acceptance Criteria:

Given I am a CIF administrator,
When I click the "New Revision" button on the "Amendments and Other Revisions" page,
Then I am taken to the "New Revision" form page.

Given that I am a CIF administrator,
When I am on the "New Revision" page for a project,
Then there is a form requesting the revision type

Given I am a CIF administrator
When I select the revision type and create a new revision
Then I am directed to the edit revision page

#### Development Checklist:

- [ ] A "New Revision" button on the "Amendments and Other Revisions" page that takes users to the "New Revision" page. (The tasklist status for New Revision should be "In Progress" at this point)
- [ ] A new page with a form for creating a new revision with the following fields:
    - `revisionType` (radio buttons: "Amendment", "General Revision", "Minor Revision")
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [x] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [x] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/992?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by matthieu-foucault** [comment]
@pbastia I see a list of checkboxes to "choose forms to be updated" in the interactive prototype. Are we implementing those? What is their behaviour?

**Comment by dleard** [comment]
Those have been moved to another card to rethink if they're necessary / how they should work if we do implement them. #994

**Comment by LindsayMacfarlane** [comment]
Thank you so much @gurjmatharu! Tested in dev and meets acceptance criteria. 

A couple of observations (which are probably addressed in subsequent tickets):
- Are we still planning on removing the 'Edit' button from each screen and making the user only be able to go through amendments/revisions?
- As a "non CIF user", the different revision types aren't clear. I'm sure those are clear to the program area, but probably not to anyone else or anyone who would be onboarding in the future.
FYI @nanyangpro (and apologies if you have previously answered these questions)

**Comment by nanyangpro** [comment]
Good questions, @LindsayMacfarlane 
- Yes. Except for "Routinely Updated Fields". There's an additional shortcut workflow for updating them. Please see #1158.
- Would you mind clarifying who are the "non CIF user"?

**Comment by LindsayMacfarlane** [comment]
Just me @nanyangpro ...I'm the non CIF user :)
