### ISSUE TITLE
As a CIF user, I want to see which forms I updated when I edited on the summary of a revision, so that I get confirmation of which changes I made

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#994]
#### Description:

Allowing users to review which forms they modified when creating a revision / amendment

Prototype: https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?page-id=2289%3A2663&node-id=3169%3A2715&viewport=-573%2C1082%2C0.31&scaling=scale-down&starting-point-node-id=3169%3A2715&show-proto-sidebar=1 (FYI the mocks are interactive)

![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/0b186867-fedb-4e2c-91d4-e3dbed6804f6)

#### Acceptance Criteria:

As a CIF user
When I submit any type of project revision
Then I can see a 'Forms Updated' section

As a CIF user
When I submit any type of project revision
Then I can see a list of forms with checkboxes
Where only the updated forms are checked

As a CIF user
When I submit any type of project revision
The updated forms in the list can be expanded
And expanding them displays the diff with the previous version

As a CIF user
When I submit any type of project revision
The updated forms in the list are expanded by default

#### Development Checklist:

- [x] Reusing what was designed in #633 to access the list of forms would be ideal, but we might want to start with a static list of forms (which will evolve as we refactor)
- [x] Pattern similar to `CollapsibleReport` to hide / show the changed forms
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
@nanyangpro @LindsayMacfarlane leaving this card in 'new issues' since we're unsure about
- the benefit of collecting this data at this point in the process
- how to provide feedback to the users on what was selected on this page

**Comment by nanyangpro** [comment]
Thanks for the note, @pbastia!
You indicated that "the mocks are inactive" in the description above. I just checked, it should be fine. Would you mind checking it again and let me know if there are any issues accessing it from your end?

**Comment by pbastia** [comment]
It says "interactive" :D

**Comment by LindsayMacfarlane** [comment]
Hi @nanyangpro and @pbastia - taking a look at the labels assigned to this ticket - do we still require additional UX/UI or is this ready for backlog refinement? (It already has acceptance criteria). Also, given that it is related to the amendment/revisions my assumption is that this is a high priority item for implementation.

**Comment by pbastia** [comment]
@LindsayMacfarlane @nanyangpro I am still a little confused about which data we are collecting with this list of forms, given that we don't constrain the user on which forms are to be modified.
- If the purpose is only to redirect the user to the first form, I am not sure how much value this represents
- The list of forms modified in an amendment can be computed on the Summary page

**Comment by dleard** [comment]
^ I agree with Pierre here, I don't see a lot of value in defining the forms to be updated beforehand. Maybe we can re-work this ticket to be something like: "When viewing an amendment/revision, I can see a generated list of which forms were updated"

**Comment by pbastia** [comment]
@nanyangpro I wanted to get your confirmation about this AC:
> As a CIF user
When I submit any type of project revision
The updated forms in the list are expanded by default

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/994?planning-poker) with Zenhub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by nanyangpro** [comment]
Thanks for confirming, @pbastia! - The AC looks good.
Just a quick question, if the amended field is one that cause changes on other fields, would we check the forms/fields that's been impacted under this section as well? We can also confirm CIF Ops expectations with Taylor and Amanda tmr.

**Comment by pbastia** [comment]
I think we should reflect those changes. Otherwise the state of the application changes - without any feedback to the user

**Comment by nanyangpro** [comment]
Good call, @pbastia. - On that note, shall we visually distinguish the amended fields and the impacted fields, e.g. different colours, indicators, tooltips explaining why, etc., so that the user won't be confused?

**Comment by BCerki** [comment]
@nanyangpro, the figma link doesn't seem to have a wireframe labelled #994. Is it one of the other ones? Also the link to #633 doesn't have a wireframe or seem particularly related to this ticket?

**Comment by nanyangpro** [comment]
Thanks for the question, @BCerki - The Figma link is a prototype. You can see the part for #994 at the last step. A screen capture of the section was also provided in @pbastia's ticket description.

**Comment by mikevespi** [comment]
@nanyangpro How should we distinguish between fields a user directly updated, and fields that changed as a result?

**Comment by mikevespi** [comment]
And a follow up: the section titles line up with the tasklist sections, and some of the sections in the tasklist have more than one subsection (i.e. project details has contacts and managers). For those sections, if there are changes to both forms, should we indicate which fields are from which, or just put all of the changes in a row?

**Comment by nanyangpro** [comment]
As discussed with @mikevespi on Dec 9th:

- For now (before we have Tooltip component), we'll use text indicator (instead of different colours or icons) for distinguishing fields a user directly updated, and fields that changed as a result. **Suggested text indicator for the latter:** _"This field is updated as a result of the changes you made."_
- Yes, let's display the hierarchy.

**Comment by Sepehr-Sobhani** [comment]
Based on the discussion with @nanyangpro here is the way we want to show added fields:
![Screenshot 2023-01-04 at 11 09 34 AM](https://user-images.githubusercontent.com/52381975/210631154-5123f56f-c064-43aa-8ebb-c540386b1a47.png)

and here is the way we want to show removed field:
![Screenshot 2023-01-04 at 11 11 01 AM](https://user-images.githubusercontent.com/52381975/210631223-ac666219-55de-47e6-b4f5-37970611b3e4.png)

**Comment by LindsayMacfarlane** [comment]
I think I need someone to walk me through the workflow for this ticket. I could see the 'forms updated' section, but could never get any data changes to display. It's also still confusing having the amendments/revisions section, but then we can still go in the "old way" to edit.

**Comment by Sepehr-Sobhani** [comment]
> I think I need someone to walk me through the workflow for this ticket. I could see the 'forms updated' section, but could never get any data changes to display. It's also still confusing having the amendments/revisions section, but then we can still go in the "old way" to edit.

@LindsayMacfarlane I can walk you through the workflow.

**Comment by LindsayMacfarlane** [comment]
Thank you @Sepehr-Sobhani - looks good!

Based on your demo at Sprint Review I was able to play around with this feature. I still struggle with the overall workflow of amendments and revisions, but that will hopefully be made more clear with @nanyangpro workflow mapping this sprint. Nan - let me know if you want me to walk you through from a user perspective on what is working and/or confusing from a potential users perspective.

**Comment by nanyangpro** [comment]
Thanks for suggesting that, @LindsayMacfarlane! Appreciate it!

I share your confusion walking through the partially implemented workflow too. Hopefully it's more intuitive for the users once we have unclearness clarified for the team and the full envisioned workflows are in place.
