### ISSUE TITLE
Task: Revision Type database pre-work

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#995]
Database tasks to support #992

- [x] A `revision_type` table in the database (similar to `cif.report_type`) containing the types:
    - "Amendment"
    - "General Revision"
    - "Minor Revision"
- [x] A `revision_type` field on the `project_revision` table referencing the types from the above table
- [x] A `comments` field on the `project_revision` table (varchar)
- [x] A migration adding the "General Revision" type to all existing revision records / form changes
- [x] Making sure the migration function is tested

**Comment by pbastia** [comment]
@dleard feel free to add more to this card!

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/995?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by BCerki** [comment]
Re this checkbox: "A migration adding the "General Revision" type to all existing revision records / form changes", from Dylan:
>the `project_revision` table doesn't go through our `form_change` flow, so no need to worry about that part.

**Comment by BCerki** [comment]
@LindsayMacfarlane, there's nothing to test on the front-end for this
