### ISSUE TITLE
Task: Amendment type database pre-work

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#998]
Pre-work for #983

- [x] a new `amendment_type` table with `name : varchar(1000)` as primary key
- [x] `amendment_type` table is pre-populated with the values (Schedule, Scope, Cost)
- [x] a `project_revision_amendment_type` join table with:
    - `id` pkey
    - `project_revision_id` fkey to `project_revision(id)`
    - `amendment_type` fkey to `amendment_type(name)`
- [x] the `project_revision_amendment_type` has unique indexes to make sure that a revision only has at most one amendment_type record of each type

**Comment by pbastia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/998?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by Sepehr-Sobhani** [comment]
@LindsayMacfarlane Moved this task into `Accepted by PO or Dev` as it contains only code changes and nothing to test.
